### ISSUE TITLE
The domain.com page isn’t working , domain.com is currently unable to handle this request.HTTP ERROR 500

### ISSUE THREAD

**Issue by lolbob181** [Contentify/Contentify#100]
Soo i listend to you guys and moved to digitalocean VPS i did install a control panel called sentora i have used many times but i uploaded all files to the website all php extensions installed this time (YAY) and all the folders are 777 in chmod but getting the page isn't working after  pressing Launch installer.

**Comment by krysennn** [comment]
Hello,

Ok so, on your VPS you will using only one website (contentify) or many website ?

**Comment by lolbob181** [comment]
Its gonna be one website but then we will have another website to host files onto ;)

**Comment by krysennn** [comment]
Can you provide me your URL for install Contentify ?

**Comment by lolbob181** [comment]
zealgg.com but u get error but for contentify zealgg.com/public/

**Comment by krysennn** [comment]
I dont know how Sentora work ...
How did you create your website in Sentora ?

I'm looking on google and i found this:
https://www.snip2code.com/Snippet/1032891/Laravel-5-2-on-sentora-fix

Because for Laravel your rootdirectory must like: /var/www/website1/**public**

**Comment by lolbob181** [comment]
any way to change it?

**Comment by lolbob181** [comment]
i followed that tutorial

**Comment by lolbob181** [comment]
Soo i destroyed the droplet and remade it now i installed LAMP on to the vps and the IP Changed soo i have to wait till DNS Finishes

**Comment by krysennn** [comment]
So now i can send you virtualhost configuration for your website

**Comment by lolbob181** [comment]
yes

**Comment by lolbob181** [comment]
do u know how to fix This site can’t be reached?

**Comment by krysennn** [comment]
So i think in LAMP it's Apache2:

1. go to _**/etc/apache2/sites-available**_ 
2. create file **_vim WEBSITE.conf_**
3. Add this content and adapt with your website in your file:
`<VirtualHost *:80>
        ServerName www.**DOMAINENAME.com**

        ServerAdmin contact@**DOMAINENAME.com**
        DocumentRoot /var/www/**WEBSITE**/public

        <Directory /var/www/**WEBSITE**/public>
                Allowoverride All
        </Directory>

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/**WEBSITE**/error.log
        CustomLog ${APACHE_LOG_DIR}/**WEBSITE**/access.log combined
</VirtualHost>`
4. go to _**cd /var/log/apache2/**_
5. create folder **WEBSITE**
6. command: a2ensite **WEBSITE**
7. lets go ;)

**Comment by lolbob181** [comment]
oki :)

**Comment by lolbob181** [comment]
Done it all now am uploading the contentify files into /VAR/WWW/WEBSITE/PUBLIC

**Comment by lolbob181** [comment]
I did it now with the files uploaded going to my website i get refused to connect ;(

**Comment by lolbob181** [comment]
If i go to my website thru the ip it tells me to click the WEBSITE FOLDER then PUBLIC ;( i want it to go in public straight away

**Comment by krysennn** [comment]
Can you write: **ls /etc/apache2/sites-enabled**
Copy paste the result here please.

**Comment by krysennn** [comment]
/!\ I HELP YOU BUT I'M NOT AS YOUR SERVICE !

I try to help you but is very difficult because you cannot explain your problem !
So wait !
Thank you to stop your flood !

**Comment by lolbob181** [comment]
Okay I did it and it only shows WEBSITE.CONF i think it was 000-default.conf which i just disabled ;)

**Comment by krysennn** [comment]
**I said "copy paste the result here please" so copy paste result of these command please !**

1. **ls /etc/apache2/sites-enabled**
2. **cat /etc/apache2/sites-enabled/WEBSITE.conf**
**Copy paste result** of these command please.

**Comment by lolbob181** [comment]
root@Zealgg:/var/www/WEBSITE/public# ls /etc/apache2/sites-enabled
WEBSITE.conf
root@Zealgg:/var/www/WEBSITE/public# cat /etc/apache2/sites-enabled/WEBSITE.conf                                                                                        <VirtualHost *:80>
        ServerName www.zealgg.com
        ServerAdmin admin@zealgg.com
        DocumentRoot /var/www/WEBSITE/public

        <Directory /var/www/WEBSITE/public>
                Allowoverride All
        </Directory>

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/WEBSITE/error.log
        CustomLog ${APACHE_LOG_DIR}/WEBSITE/access.log combined
</VirtualHost>
root@Zealgg:/var/www/WEBSITE/public#

**Comment by krysennn** [comment]
Ok thank you for the information, can you write there please:

1. **ls /var/www/WEBSITE/**
2. **ls /var/www/WEBSITE/public**

**Copy paste result of these command here please.**

>

**Comment by lolbob181** [comment]
root@Zealgg:/var/www/WEBSITE/public# clear
root@Zealgg:/var/www/WEBSITE/public# ls /var/www/WEBSITE/
public
root@Zealgg:/var/www/WEBSITE/public# ls /var/www/WEBSITE/public
app      bootstrap      composer.lock  config      database      license.txt   package.json  phpunit.xml  readme.md  server.php  tests
artisan  composer.json  composer.phar  contentify  Gruntfile.js  node_modules  phpspec.yml   public       resources  storage     vendor
root@Zealgg:/var/www/WEBSITE/public#

**Comment by krysennn** [comment]
Thanks.

Error is here:
`root@Zealgg:/var/www/WEBSITE/public# ls /var/www/WEBSITE/public
app bootstrap composer.lock config database license.txt package.json phpunit.xml readme.md server.php tests
artisan composer.json composer.phar contentify Gruntfile.js node_modules phpspec.yml public resources storage vendor`

1. Remove folder public in WEBSITE, **rm -rf /var/www/WEBSITE**
2. Install unzip **apt-get install unzip**
3. Download Contentify v2,
**cd /tmp**
**wget https://github.com/Contentify/Contentify/archive/2.0-dev.zip**
4. Unzip Contentify v2, **unzip 2.0-dev.zip**
5. Move file from Contentify to WEBSITE folder,
**cd Contentify-2.0-dev**
**mv * /var/www/WEBSITE/**
6. Delete unnecessary files: 
**rm /tmp/2.0-dev.zip**
**rm -rf /tmp/Contentify-2.0-dev**

Let's go

**Comment by lolbob181** [comment]
Did that all now since domain still dsnt wrk i went thru the ip and it said : The requested URL / was not found on this server.

**Comment by krysennn** [comment]
Can you make this please:

1. **ls -la /var/www/WEBSITE/**
2. **ls -la /var/www/WEBSITE/public**

Copy paste result here

**Comment by lolbob181** [comment]
oh i was a big noob and i fucked up and command sry ;( am getting this error now this page isn't working :(

**Comment by krysennn** [comment]
Ok can you make this please:

**apache2ctl -M**

Copy paste result here

**Comment by lolbob181** [comment]
root@Zealgg:~# apache2ctl -M
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php5_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 status_module (shared)
root@Zealgg:~#
Thanks for all this help :)

**Comment by krysennn** [comment]
Can you now make this:

1. **cat /var/www/WEBSITE/public/.htaccess**

Copy paste result here please

**Comment by lolbob181** [comment]
root@Zealgg:~# cat /var/www/WEBSITE/public/.htaccess
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
root@Zealgg:~#

**Comment by krysennn** [comment]
Make this:

1. **cd /var/www/WEBSITE/**
2. **chmod 777 -vR storage**
3.** chmod 777 -vR /boostrap/cache**
4.** chmod 777 -vR /public/uploads**
5.** chmod 777 -vR /public/share**
6. ** chmod 777 -vR /public/rss**

Try again please

**Comment by lolbob181** [comment]
done now ?

**Comment by krysennn** [comment]
Are you make all commands ?

**Comment by lolbob181** [comment]
were u wrote 3,4,5 and then 3 i can't do it gives me error i get this : root@Zealgg:/var/www/WEBSITE# chmod 777 -vR storage
mode of ‘storage’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/app’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/app/database.ini’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/app/.gitignore’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/app/modules.json’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/logs’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/logs/.gitignore’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/.gitignore’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/database’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/database/.gitignore’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/framework’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/framework/cache’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/framework/cache/.gitignore’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/framework/.gitignore’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/framework/views’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/framework/views/.gitignore’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/framework/sessions’ retained as 0777 (rwxrwxrwx)
mode of ‘storage/framework/sessions/.gitignore’ retained as 0777 (rwxrwxrwx)
root@Zealgg:/var/www/WEBSITE# chmod 777 -vR /public/rss
chmod: cannot access ‘/public/rss’: No such file or directory
failed to change mode of ‘/public/rss’ from 0000 (---------) to 0000 (---------)
root@Zealgg:/var/www/WEBSITE# ** chmod 777 -vR /public/rss**
No command 'app' found, but there are 17 similar ones
app: command not found
root@Zealgg:/var/www/WEBSITE#

**Comment by krysennn** [comment]
Yes i failed my command,

re-run this without "/"

**Comment by lolbob181** [comment]
K done but got error on 3cmd

**Comment by lolbob181** [comment]
u got steam soo i can talk to you on there?

**Comment by krysennn** [comment]
I'm sorry i stopped to use steam long time ago.
Come on on discord: https://discord.gg/WDeGY

**Comment by krysennn** [comment]
You can close this issue.

1. We have re-downloaded Contentify, correctly move files in folder (/var/www/website)
2. We have set chmod 777 on different folder (look in Wiki).
3. We have run **php composer.phar install** for installing vendor component
4. We have generate key with **php artisan key:generate**
5. We have created file ".env" and set application key **APP_KEY=KEYGENERATE**

**Comment by chriskonnertz** [comment]
Ok thanks! 

Yeah sometimes it can be very stressful to install it. :(  I wish it was easier. If someone has ideas how to improve the installation please let me know!
