### ISSUE TITLE
[Request] Snow particles

### ISSUE THREAD

**Issue by ghost** [Contentify/Contentify#104]
Since its coming to X-MAS i want to know how do i add falling snow on my website thanks!

**Comment by chriskonnertz** [comment]
Hah okay I'll figure something out. :snowflake:

**Comment by krysennn** [comment]
Hi,

something like that ?
http://erixsen.free.fr/jsnow/

**Comment by lolbob181** [comment]
ye

**Comment by krysennn** [comment]
System here: https://github.com/Contentify/Contentify/pull/107

**Comment by lolbob181** [comment]
stupid question: how do you instlal it xD

**Comment by krysennn** [comment]
Sure, wait pull request was accepted by @chriskonnertz and if it's accepted reinstall it because they are modification in database.

**Comment by lolbob181** [comment]
i have 40 users on the website already i've added alot of things i don't wanna reinstall :(

**Comment by krysennn** [comment]
RE-Download (new files added) and replace all files: https://github.com/Contentify/Contentify/pull/107/commits/322ca8635d31f488b308565495a0e8b0e50cee68

Add two fields in your database.
Go to DATABASE > Config > Add this:
name => app.theme_christmas
value => 0

And this:
name => app.theme_christmas
value => #ffffff

Let's go to Admin Backend, check Christmas Mode and choose color for your Flakes, default white.

**Comment by lolbob181** [comment]
http://prntscr.com/dceu52 Getting that error on the second  edit in database

**Comment by krysennn** [comment]
I have made some changes, https://github.com/Contentify/Contentify/pull/107

On your website i see the canvas id="sky" is z-index 3 so you haven't got download new files of my commit.

Show https://github.com/Contentify/Contentify/pull/107 and get new files of each commit to fix the bug on your website.

Sorry for problems.

**Comment by lolbob181** [comment]
Works Great now!! but slightly one problem i want the snow to fall over the slide picture

**Comment by krysennn** [comment]
For this i will working on Phobus and Morpheus Theme because we must change some z-index to working with show on all body éléments...
I will trying to commit the last work this week

**Comment by sCARFACETM** [comment]
Hey I have installed the christmas snow Theme everything is working fine, but in the left corner of my Site there is a " ; " when the christmas Theme is activated. (www.german-enforcers.de/public) 
How can i remove this? Thanks for your help

**Comment by krysennn** [comment]
Hi,

Actually this mod is unofficial but working, i will trying to help you.

Can you copy/paste this file:
> resources/views/snow.blade.php

And can you look there files:
> app/Modules/MorpheusTheme/Resources/Views/layout.blade.php 
> app/Modules/PhobosTheme/Resources/Views/layout.blade.php
and confirm if you have there:
```
@if(Config::get('app.theme_christmas'))
@include('snow')
@endif
```

**Comment by sCARFACETM** [comment]
Hey,

thanks for the fast response. I think the matter has resolved itself.

In the file ` app/Modules/PhobosTheme/Resources/Views/layout.blade.php` there was the " ; " in the code after @include('snow') like this

 > @if(Config::get('app.theme_christmas'))
> @include('snow');
> @endif

 That was a mistake of me.

**Comment by krysennn** [comment]
Hi,

No problem :) i make the same mistake in my first commit and i fix it in the next commit ;)

**Comment by chriskonnertz** [comment]
The code is now in the repo so I close this issue.
