### ISSUE TITLE
[Enhancement] Installation system of Contentify

### ISSUE THREAD

**Issue by krysennn** [Contentify/Contentify#106]
Hello @chriskonnertz,

Recently some people have problem to install Contentify because it's new versions and maybe some people are not developper.
I see your message here: https://github.com/Contentify/Contentify/issues/100#issuecomment-262600599
So, i will working on ASAP.

Actually i'm looking about this solution: https://github.com/RachidLaasri/LaravelInstaller

**Comment by chriskonnertz** [comment]
Have you started to work on this task? Because if yo have not, then I will start to work on https://github.com/Contentify/Contentify/issues/102.

**Comment by krysennn** [comment]
Hi ;)

No i dont started to work on this task, Yes you can start no problem ;)

**Comment by chriskonnertz** [comment]
Ok I will start tomorrow.

**Comment by chriskonnertz** [comment]
Ok I gave up on https://github.com/Contentify/Contentify/issues/102 so you can start whenever you want to.

**Comment by krysennn** [comment]
I will trying to work on them ASAP.
I will used this: https://github.com/RachidLaasri/LaravelInstaller i'm waiting this PR (https://github.com/RachidLaasri/LaravelInstaller/pull/62) merge to start the work.

**Comment by chriskonnertz** [comment]
Great! :)

**Comment by chriskonnertz** [comment]
Hi @krysennn ,

closing this one - we can reopen it or create a new issue if you want to work on this.
