### ISSUE TITLE
Contentify 2 - blank page while installing

### ISSUE THREAD

**Issue by my-eternity** [Contentify/Contentify#109]
I tried to do a fresh install of Contentify 2 and i tried to create the ".install" file in storage\app, after that i got a white screen. After i tried it again it said "NotFoundHttpException in RouteCollection.php line 161:".

After i added ".installed" instead of ".install" i get a blank/white page.

**Comment by krysennn** [comment]
Thank you for new issue is more clearer and coherent 👍 

So, about your problem i need some information about your system to find your problem.

What type of hosting you use ? 
- dedicated server / virtual private server ? 
- shared hosting ?

What are you doing to installed Contentify 2 on your hosting ?

**Comment by my-eternity** [comment]
I am using a hosting package of strato.de
I created a folder with FileZilla, copied the whole content of the folder in it and tried to isntall it. Contentify 1.2 works without any issues. For now it is not installed anymore, i deleted it for Contentify 2.

**Comment by krysennn** [comment]
Ok, you have download this https://github.com/Contentify/Contentify/releases/download/v2.0-beta/contentify_2_beta.zip ?

**Comment by my-eternity** [comment]
Yep.

**Comment by krysennn** [comment]
I have trying to installed it on my computer and i have not problem, so it's strange, but you have right because with this link: https://github.com/Contentify/Contentify/releases/download/v2.0-beta/contentify_2_beta.zip it's not ".installed" but ".install" because they are some pull request late on this package.

So can you give me the URL of your website and delete all files of laravel, download again (https://github.com/Contentify/Contentify/releases/download/v2.0-beta/contentify_2_beta.zip) and put it in your website and tell me when it's done.

Are you configure your webroot folder on your control panel to specify "public" folder of Contentify ?

**Comment by my-eternity** [comment]
So you want me to delete all files of laravel and then download the .zip file again to upload it?
Sorry for the question but where can i find the laravel files?

dunno if i get it. on my root is a subfolder where i put all the content of contentify 2 in. and the subdomain is redirecting to this folder.

**Comment by krysennn** [comment]
Yes i want to you delete all files of laravel, and download this -> https://github.com/Contentify/Contentify/releases/download/v2.0-beta/contentify_2_beta.zip
And again upload it

So, if i understand you, you put all files in folder of your hosting and you have subdomain where link to the "public folder" ?

**Comment by my-eternity** [comment]
okay. i have to do that later this day cause i'm at work atm :D 

ehm..the subdomain is called http://ttnp.my-eternity.net
i created a folder on my root called "ttnp". the subdomain redirects to this "ttnp" folder. this folder contains all files from contentify 2.
at least it is /ttnp/public/install.php
but cus i have this redirecting subdomain it's just /public/install.php
you know what i mean? :D

**Comment by krysennn** [comment]
I'm sorry i dont speak english very well ^^ so i don't understand :( ..

But Contentify (based on Laravel) Best Practices is:
Hosting must redirecting to /contentify folder/public

To call: subdomain.domain.net/install.php and not subdomain.domain.net/public/install.php

**Comment by my-eternity** [comment]
it's ok. me neither D:
okay.
and where can i find the laravel files that i have to delete? are they in the folder vendor?

**Comment by krysennn** [comment]
oh no when i tell you "laravel files" it's "contentify files" sorry ^^ because Contentify is based on Laravel PHP Framework but it's not important to know this but sorry for this failed :P

**Comment by my-eternity** [comment]
haha okay :D good to know. no problem :)

**Comment by krysennn** [comment]
Ok good 👍 

Tell me when you are time to work on your website, but me ATM is 8PM so i will maybe reply tomorrow ^^

**Comment by my-eternity** [comment]
where are you from?
well. i just found out that i already set the redirect to the public folder, tried it again it said "already installed". renamed the ".installed" to ".install" and..ye..it works xD it is installed so far.

**Comment by my-eternity** [comment]
well. there's another issue now :(
i can visit every page without problems, i can log in with my account. but if i try to get to the admin backend i receive two errors

ErrorException in FileStore.php line 78: unserialize(): Error at offset 2 of 7593 bytes (View: /mnt/web002/d0/84/57369384/htdocs/ttnp/resources/views/backend/layout_main.blade.php)

and 

ErrorException in FileStore.php line 78: unserialize(): Error at offset 2 of 7593 bytes

**Comment by krysennn** [comment]
I think it's maybe cache problem but i'm not sure ...

With SSH Console try this: php artisan cache:clear

If you have not access to SSH Console you can try to:

1. Delete all files and folders in storage\framework\cache
2. Delete all files and folders in storage\framework\sessions
3. Delete all files and folders in storage\framework\views

**Comment by my-eternity** [comment]
it's no cache problem..tried it on 3 different devices :/
okay, i'll try to delete the files later and i'll let you know if it works. ty

**Comment by krysennn** [comment]
With Contentify (based on Laravel PHP Framework) there are two system of cache.

1. Devices cache (mobile, computer, ...)
2. Framework cache for optimize speed of your website and for delete it you must make this:

> With SSH Console try this: php artisan cache:clear
> 
> If you have not access to SSH Console you can do this:
> 
> Delete all files and folders in storage\framework\cache
> Delete all files and folders in storage\framework\sessions
> Delete all files and folders in storage\framework\views

**Comment by my-eternity** [comment]
okay, good to know.
ty for your help m8 :) howi said..i'll try t later..atm at work again :D

**Comment by krysennn** [comment]
No problem i wait your feedback ;)

**Comment by my-eternity** [comment]
fml..that worked :D i can use the admin backend without any issues it seems. ty :)

**Comment by krysennn** [comment]
Nice ;)
If you have no problem now, can you close your issue please ? 👍 

Thank you ;)

**Comment by my-eternity** [comment]
lemme have a look again later when i have more time. if there's nothing else i'll close this one :)

**Comment by chriskonnertz** [comment]
ok :)

**Comment by my-eternity** [comment]
everything seems fine. thank you again for the help :)
