### ISSUE TITLE
contentify HTTP ERROR 500

### ISSUE THREAD

**Issue by DenisKhomusyak** [Contentify/Contentify#110]
Hello my friends.
What i do not right
1. Download zip, put in the folder www/test/
2. Composer update.
3.Change storage/app/database.ini
4.Go to www.test/public/install.php
5. Set writeble directories
6. Click Launcher install
7. And redirect to 500/

Sorry for my english.
P.S.
I seen demo and i think its very better webspell :+1:

**Comment by krysennn** [comment]
Hello Denis,

Contentify is based on Laravel 5 so you need to configure your document root like that: /www/test/public 

And run installer with: www.test/install.php
If error 500 persist can you copy paste your 5 last lines of laravel.log and error.log(apache or nginx) please 

Yeah sure, i use Webspell before Contentify and now i'm Contentify fan :P

**Comment by DenisKhomusyak** [comment]
omg, i forget set permissions on storage/framework/*

**Comment by krysennn** [comment]
Oh no problem ;)
If your problem is fixed close this please :)

**Comment by krysennn** [comment]
@chriskonnertz Hey ;) I think you can close this issue 👍

**Comment by chriskonnertz** [comment]
Ok.
