### ISSUE TITLE
Broke the website ;-;

### ISSUE THREAD

**Issue by lolbob181** [Contentify/Contentify#111]
I was trying to create a virtualhost for a subdomain and i was following this tutorial online and it made me remove apache2 for a reinstall now when i go to my website i get this :`<?php
/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylorotwell@gmail.com>
 */

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels nice to relax.
|
*/

require __DIR__.'/../bootstrap/autoload.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once __DIR__.'/../bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$kernel = $app->make('Illuminate\Contracts\Http\Kernel');

$response = $kernel->handle(
	$request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);` And i still want to create that subdomain also the text inside /etc/apache2/WEBSITE.conf is here : `<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.myweb.com

        ServerAdmin admin@localhost
        DocumentRoot /var/www/WEBSITE/public/

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

`there was more below but nano didn't let me edit ;-;

**Comment by krysennn** [comment]
Hello lolbob181,

We are ok to help you about Contentify problem, but we are not as your service and we are not your  Technicien IT.
Your problem is not problem with Contentify so i'm not be able to help you for your request.

I have help you during 2/3hours for help you to install Contentify and you have broke your website...  Learn how to use Apache2 and Laravel before try some tutorial on internet... 

I'm very furious...

**Comment by lolbob181** [comment]
Okay :) how do i fix the contentify problem everything is chmodde'd to 777

**Comment by krysennn** [comment]
Your issue is unreadable.. 
Try: php artisan cache:clear 
Read the Apache2 logs and Laravel.log.

Maybe your tutorial are wrong..

**Comment by chriskonnertz** [comment]
Hello lolbob181,

to me this looks like your Apache is not configured in the right way. Your Apache does not seem to know what to do with .php files. It's hard to say why. I recomment to search for terms such as `apache opens php files as text` in yourf avorite search engine. For example this is one result that looks promising to me:  http://stackoverflow.com/questions/3555681/why-are-my-php-files-showing-as-plain-text#answer-3555711

**Comment by lolbob181** [comment]
@krysennn nothing is in both logs ;(
@chriskonnertz I tried that didn't work soo i uninstalled PHP5 and purged it reinstalled php5 and in 000-default for apache2 i just added public/ end of document root and renamed WEBSITE to html all good and works now Thanks for the help anyways!
