### ISSUE TITLE
index.php works only ;/

### ISSUE THREAD

**Issue by ghost** [Contentify/Contentify#112]
wheni click the login button it says 404 /login was not found or register or any button including the news only index page shows ;-;

**Comment by chriskonnertz** [comment]
Hi,

do you use an Apache server? If so, please make sure that mod_rewrite is installed and active.

Here are some tips how to check this: http://stackoverflow.com/questions/9021425/how-to-check-if-mod-rewrite-is-enabled-in-php

**Comment by lolbob181** [comment]
its alredy enabled ;-; and the rewrite is in .htaccess alrdy

**Comment by krysennn** [comment]
I think this issue can be closed because you make new issue here: https://github.com/Contentify/Contentify/issues/122

**Comment by chriskonnertz** [comment]
-> 122
