### ISSUE TITLE
End of installation takes you to installer again.

### ISSUE THREAD

**Issue by lolbob181** [Contentify/Contentify#114]
I reset my website and when i come to the where it says congratulations your website is done blabalalal it says go to website if i click it it goes to the installer again am very confused any tips?

**Comment by chriskonnertz** [comment]
At the end of the process, the installer tries to create a file named `.installed`. If this file exists the CMS knows it has been installed. I assume that the installer was not able to create this file. Most likely it did not have the right to write in the `storage/app` directory. So waht you can do is:

a) Set write permissons to this directory and then reinstall the CMS or 
b) create the file on your own

**Comment by lolbob181** [comment]
I chmodded 777 on folders tried toake own but doesn't work

**Comment by chriskonnertz** [comment]
I will investigate.

**Comment by chriskonnertz** [comment]
> I reset my website and when i come to the where it says congratulations your website is done blabalalal it says go to website if i click it it goes to the installer again am very confused any tips?

There was a bug with this that is fixed now: 

https://github.com/Contentify/Contentify/commit/58cf72127bb8c9b2f56fe05d7d964c90070b5b43
