### ISSUE TITLE
Difficulty changing layout

### ISSUE THREAD

**Issue by mazmol1** [Contentify/Contentify#117]
How do you change the set layout and theme because for example on the Morpheus theme i dont want forum on the navbar and on the side bar i don't want cups, because this site we be primary for a organisation

**Comment by krysennn** [comment]
Hi @mazmol1,

Actually is not possible to disabled module with Admin-Backend, but you can go in /storage/app/ and open modules.json and change there:

From:
> "Forums": true,
> "Cups": true,
To:
> "Forums": false,
> "Cups": false,

You need to edit template too:
**_if you use MorpheusTheme:_**
open **"app\Modules\MorpheusTheme\Resources\Views\layout.blade.php"**
remove lines -> 67 and 120 to 132

**_if you use PhobosTheme_**
open **"app\Modules\PhobosTheme\Resources\Views\layout.blade.php"**
remove line 60 

Make CTRL+F5 on your webpage and block disappeared.
