### ISSUE TITLE
Ges 

### ISSUE THREAD

**Issue by exelv1** [Contentify/Contentify#119]
Christmas areived cqn u join csgo games in the lobbys

**Comment by krysennn** [comment]
Hi @exelv1,

I dont understand your request

**Comment by chriskonnertz** [comment]
Closed. Please create a new ticket if you have more infos.

**Comment by exelv1** [comment]
sry I was typing via cell phone what I wanted to say is would you consider ever having a match making type implementation like faceit.com?

**Comment by chriskonnertz** [comment]
At the moment there is no plan to enhace the cup/tournament system. (At least not from my point of view. Of course, there is a chance that someone else will provide new stuff,)
