### ISSUE TITLE
(IDEA) Plugin Support Ideas 

### ISSUE THREAD

**Issue by mazmol1** [Contentify/Contentify#120]
Having paid and free plugins, for example one that allow you to buy Credit or some sort to compete in tournaments. also having community built plugins so people can show off there ideas :)

**Comment by krysennn** [comment]
Hi :)

Yes it's maybe good idea,
@chriskonnertz have make idea list here and he has same idea of you:
https://github.com/Contentify/Contentify/issues/113

If you are developper you can download Contentify and add module :)

**Comment by chriskonnertz** [comment]
Hi

I added this idea to the list of ideas for v2.1: https://github.com/Contentify/Contentify/issues/113

I do not know if it will make it in v2.1, because I believe this is a big topic, especially with a differentiation between paid and free plugins.
