### ISSUE TITLE
http error 500 after mysql database entering 

### ISSUE THREAD

**Issue by ghost** [Contentify/Contentify#122]
Getting http error 500 on installation after typing in database details ;(

**Comment by chriskonnertz** [comment]
Hi,

we need log files (or any other additional info) to provide help.

- Contentify/Laravel log file (lives in `storage/logs`)
- Apache (or whatever web server you may use) log file

**Comment by lolbob181** [comment]
Contentify : in storage/logs (its empty nothing is in there besides .gitignore 
Apache: error.log ( http://pastebin.com/q9R7hsJD ) access.log http://pastebin.com/23KezAJh

**Comment by krysennn** [comment]
Hi,

31 december it's New Year's Eve and we have a LIFE so it's normal if we dont reply at your issue right now !
so you can wait and stop flooding and **please understand we are not as your service !**  You make 1 issue per week for installation and you would fast reply, **we do the best we can**.

**I reading your log and my question is: Did you have reading YOUR log ?**

I see this: 
[Sat Dec 31 18:30:42.214722 2016] [:error] [pid 10810] [client 82.10.162.207:52510] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/contentify2_0/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/contentify2_0/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107

**According to you this error means?**
it's write here: 

>  'The stream or file "/var/www/html/contentify2_0/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied'

**Diagnosis:** 
Problem with file can't be opened: "laravel.log" in "/var/www/html/contentify2_0/storage/logs/".
Error: Permission denied 

**Result of Diagnosis:**
For me it's problem with permission !
Did you have read the docs of Contentify ?

`https://github.com/Contentify/Contentify/wiki/Installation`

> **Set CHMOD 777 to these directories and their sub directories and all files in these directories**: <contentify>/storage, <contentify>/boostrap/cache, <contentify>/public/uploads, <contentify>/public/share, and <contentify>/public/rss


I think try this:

> chmod 777 -R /var/www/html/contentify2_0/storage

**Comment by chriskonnertz** [comment]
I think the installer should be improved so that it also checks if the sub directories have the right permissions. I will add this to the list https://github.com/Contentify/Contentify/issues/113
