### ISSUE TITLE
Issue found during installation.

### ISSUE THREAD

**Issue by lolbob181** [Contentify/Contentify#123]
With contentify 2.0 i had inserted my database login and it had said Database Setup Complete the next button was not working soo i had to right click open in new tab!

**Comment by krysennn** [comment]
Hi @lolbob181,

Why you reinstall every day ? Install Contentify one time, follow our tips for fix and use your website.

Weekly you installing Contentify and weekly you making an issue it's not possible.. 

Your issue:
https://github.com/Contentify/Contentify/issues/122
https://github.com/Contentify/Contentify/issues/114
https://github.com/Contentify/Contentify/issues/112
https://github.com/Contentify/Contentify/issues/111
https://github.com/Contentify/Contentify/issues/110
https://github.com/Contentify/Contentify/issues/100
https://github.com/Contentify/Contentify/issues/82
https://github.com/Contentify/Contentify/issues/77
https://github.com/Contentify/Contentify/issues/74

So now, like @chriskonnertz:

we need log files (or any other additional info) to provide help.

Contentify/Laravel log file (lives in storage/logs)
Apache (or whatever web server you may use) log file

**Comment by lolbob181** [comment]
Havin this error : NotFoundHttpException in RouteCollection.php line 161:
larvel log ( http://pastebin.com/GN93Eenj )
apache unable to get them ;-;

**Comment by krysennn** [comment]
Ok, when you get this error what is full URL (http://..../.../) of your web browser ??

I reading your log and i get some error about user of database and some problem with steam authentification.
Database: I think your are fix with admin user and password
Steam: you haven't get developper steam key so you can't use it.
-> In config/steam-auth.php set API Key

**Comment by lolbob181** [comment]
Okay soo when i get the error the URL is http://website.com/public/admin/news or something else happens on multiple things i've noticed that the "public" comes into the url but in the apache2 config its set to /home/admin/website.com/public_html/public

**Comment by nrRudiak** [comment]
Public_html is a standard folder on all hosting, its the visible files through the domain. Anything after public html can be accessed through the url by typing website.com/public/etc try using without steam to get going properly first I think krysenn may of been suggesting

**Comment by lolbob181** [comment]
I haven't setup up the steam login right now. and i have a Web Panel on my vps soo it has public_html i can edit any file i need to and i don't need to type in example.com/public

**Comment by krysennn** [comment]
I dont understand, you need public into URL or not ??

Can you trying this command and copy paste the result or make screenshot of result please:
ls -la /home/admin/website.com/public_html/public

And trying this command and copy paste or screenshot the result please:
ls -la /home/admin/website.com/public_html

**Comment by lolbob181** [comment]
I don't need public in the URL but when it displays the error it has the public in there but here:
1st command : http://prntscr.com/dv48f7
2nd command: http://prntscr.com/dv481n

**Comment by krysennn** [comment]
It's strange, can you give me Line 51 of config/app.php it's something like 'url' =>...

**Comment by lolbob181** [comment]
http://prntscr.com/dv80w7

**Comment by lolbob181** [comment]
soo?

**Comment by krysennn** [comment]
I have no idea about your problem and i cannot reproduce same error ...

If you can reset your VPS follow this:

1. Install Debian or Ubuntu

2. Install Apache2, PHP5 and packages needed for Contentify
> apt-get install apache2 php5 php5-mcrypt php5-mysql php5-json unzip vim

3.  Install Mysql server
> apt-get install mysql-server
`Follow mysql installation and keep user/password credential you needed it to installing Contentify`
4. Let's go to /var/www
> cd /var/www

5. Download Contentify 2.0, clean and configure chmod
> wget https://github.com/Contentify/Contentify/releases/download/v2.0/contentify2_0.zip
> unzip contentify2_0.zip
> mv contentify2_0 contentify
> rm contentify2_0.zip
> chmod 777 -R /var/www/contentify/storage
> chmod 777 -R /var/www/contentify/boostrap/cache
> chmod 777 -R /var/www/contentify/public/uploads
> chmod 777 -R /var/www/contentify/public/share
> chmod 777 -R /var/www/contentify/public/rss

6. Configure Apache2
> cd /etc/apache2/sites-available
> vim contentify.conf

Copy/paste:
```
<VirtualHost *:80>
        ServerName www.site.com

        ServerAdmin contact@site.com
        DocumentRoot /var/www/contentify/public

        <Directory /var/www/contentify/public>
                Allowoverride All
        </Directory>

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

7. Disable default apache website
> a2dissite 000-default.conf

8. Activate module rewrite and contentify website
> a2enmod rewrite
> a2ensite contentify.conf

9. Open mysql
> mysql -u root -p
> Prompt will tell you to enter your password of root user.

10. Create database and quit
>  CREATE DATABASE IF NOT EXISTS contentify2;
> exit

If all is good and i have dont forgot something you can get install of contentify: http://site.com/install.php

**Comment by lolbob181** [comment]
We're unable to reset the vps we are running vestacp with multiple websites.

**Comment by chriskonnertz** [comment]
Hi lolbob181,

providing remote support can be difficult. Since Contentify is a small open-source project support is a big deal and can be a huge challenge. Unfortunately, sometimes it is not possible to reproduce every bug, especially if the server infrastructure is uncommon. For instance, I do not konw VestaCP. I am not a professional sys/server administrator so this is simply beyond my horizon. So maybe we are not able to help you with this one.
