### ISSUE TITLE
Help install

### ISSUE THREAD

**Issue by kydros** [Contentify/Contentify#126]
I need some help: https://gyazo.com/63768c01b6cf65a80685f125b50e00d8 i click launch installer https://gyazo.com/b46e56eafe3c0e2b308589fbf8655e4d

**Comment by krysennn** [comment]
Hi @kydros,

What type of hosting is it ? Dedicated server, Virtual private server, web hosting ?

You need to turn on mod rewrite and you need to configure your virtualhost to point on public folder.

**Comment by kydros** [comment]
Hi @krysennn,

Is VPS and i use LEMP.

**Comment by krysennn** [comment]
Did you have create virtual host on nginx ?
If it's no, open this: /etc/nginx/sites-available/default


You need to have something like that:
in this example your website is stored in /var/www/contentify and document root point in public folder for delete public in URL.
```
...
        root /var/www/contentify/public;
        index index.php index.html index.htm;
...
```

**Comment by kydros** [comment]
https://gyazo.com/c58d71c60d83ec1de6b66ce1c9fdfd2a

**Comment by krysennn** [comment]
Oh ok, you have put contentify files in /var/www/my_website ? it's right ?

**Comment by kydros** [comment]
yes

**Comment by krysennn** [comment]
Ok in `/etc/nginx/sites-available/default` change :
this: `/var/www/my_website`
by this: `/var/www/my_website/public`

and make this: `service nginx reload`

Go on http://URL/ and you will redirect to install make the installer and tell me if it's ok or not ;)

**Comment by kydros** [comment]
I have change https://gyazo.com/488d5ff9897c24f71833178a96d94209 but now i have this "Contentify already has been installed."   http://163.172.153.130/public/install.php

**Comment by krysennn** [comment]
Your configuration is not correct, you need configure nginx for use contentify with url like that: http://http://163.172.153.130 and no with: http://163.172.153.130/public

**public must be not writing in URL.**

**Comment by kydros** [comment]
What i need to change?

**Comment by krysennn** [comment]
It's very difficult to help you, because nginx or apache it's web servers and i'm not expert with nginx.
can you give me screenshot of your  `/etc/nginx/sites-available/default`

**Comment by kydros** [comment]
https://gyazo.com/c5ed8adecacf08b84c07cc4a527b07d8

**Comment by krysennn** [comment]
I'm not expert so i look on internet...
Can you add this in your file:

> location / {
>         try_files \$uri \$uri/ /index.php?\$query_string;
> }

and make this: `service nginx restart`
let's go to http://163.172.153.130

**Comment by kydros** [comment]
https://gyazo.com/5f0ca9cc27bf46aac84756639cbaa6bc

**Comment by krysennn** [comment]
If you can reinstall your VPS i recommend this:

https://github.com/Contentify/Contentify/wiki/Installation
part: Hosting.

You reinstall your VPS on ubuntu and you download @chriskonnertz script for install.

**Comment by kydros** [comment]
Ok, but i use https://www.online.net/en

**Comment by kydros** [comment]
https://gyazo.com/7758061fcb115b55b424079f471dd948

**Comment by krysennn** [comment]
Can you reset your VPS ?
If it's possible follow these steps:

1. Install Debian or Ubuntu

2. Install Apache2, PHP5 and packages needed for Contentify
> apt-get install apache2 php5 php5-mcrypt php5-mysql php5-json unzip vim

3.  Install Mysql server
> apt-get install mysql-server
`Follow mysql installation and keep user/password credential you needed it to installing Contentify`
4. Let's go to /var/www
> cd /var/www

5. Download Contentify 2.0, clean and configure chmod
> wget https://github.com/Contentify/Contentify/releases/download/v2.0/contentify2_0.zip
> unzip contentify2_0.zip
> mv contentify2_0 contentify
> rm contentify2_0.zip
> chmod 777 -R /var/www/contentify/storage
> chmod 777 -R /var/www/contentify/boostrap/cache
> chmod 777 -R /var/www/contentify/public/uploads
> chmod 777 -R /var/www/contentify/public/share
> chmod 777 -R /var/www/contentify/public/rss

6. Configure Apache2
> cd /etc/apache2/sites-available
> vim contentify.conf

Copy/paste:
```
<VirtualHost *:80>
        ServerName www.site.com

        ServerAdmin contact@site.com
        DocumentRoot /var/www/contentify/public

        <Directory /var/www/contentify/public>
                Allowoverride All
        </Directory>

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

7. Disable default apache website
> a2dissite 000-default.conf

8. Activate module rewrite and contentify website
> a2enmod rewrite
> a2ensite contentify.conf

If all is good and i have dont forgot something you can get install of contentify: http://site.com/install.php

**Comment by kydros** [comment]
http://163.172.189.91/install?step=4 
error PDOException in Connector.php line 55:
SQLSTATE[42000] [1049] Unknown database 'contentify2'

**Comment by krysennn** [comment]
Make this:

1. Open mysql
> mysql -u root -p
> Prompt will tell you to enter your password of root user.

2. Create database and quit
>  CREATE DATABASE IF NOT EXISTS contentify2;
> exit

Run again: http://163.172.189.91/install.php

**Comment by kydros** [comment]
Thank you so much, I have only one question,  I want to stream the theme Phobos Theme as Morpheus Theme has, and is it possible to chat?

**Comment by krysennn** [comment]
You would use module stream on Morpheus Theme ? i dont understand your question

**Comment by chriskonnertz** [comment]
> Thank you so much, I have only one question, I want to stream the theme Phobos Theme as Morpheus Theme has, and is it possible to chat?

Embedding the chat is not possible out-of-the-box. You would have to add it on you own. Maybe we should add this in the future.

However, I believe adding is not very complicated. Here is an example for the embed code: https://github.com/justintv/Twitch-API/blob/master/embed-chat.md
So basically you could open the template of the stream page ( app/Modules/Streams/Resources/Views/show.blade.php ) and then in line 6 add this code (_disclaimer: I did not test it_):

`<iframe frameborder="0" scrolling="no" id="chat_embed" src="http://www.twitch.tv/{{ $stream->permanent_id }}/chat" height="500" width="350"></iframe>`

You have to change the values of the height and width attributes and if you care about responsive design you would also have to think about how this chat is displayed on different devices (for example mobile phones).

**Comment by jcggraca** [comment]
ok thx
