### ISSUE TITLE
Digital Ocean Installation

### ISSUE THREAD

**Issue by maxbrood** [Contentify/Contentify#127]
Hi,

Bit of a newbie to this so please excuse my ignorance. I've attempted to follow the installation guide and setup a LAMP stack on digital ocean by following the video in the installation wiki but after installation the install.php page cannot be found. Is there an additional setup that I've missed outside of this or is this now out of date?

Thanks.

**Comment by krysennn** [comment]
Hi @maxbrood,

If it's possible, reset your droplet to Debian or Ubuntu and follow these steps:
1. Install Debian or Ubuntu

2. Install Apache2, PHP5 and packages needed for Contentify
> apt-get install apache2 php5 php5-mcrypt php5-mysql php5-json unzip vim

3.  Install Mysql server
> apt-get install mysql-server
`Follow mysql installation and keep user/password credential you needed it to installing Contentify`
4. Let's go to /var/www
> cd /var/www

5. Download Contentify 2.0, clean and configure chmod
> wget https://github.com/Contentify/Contentify/releases/download/v2.0/contentify2_0.zip
> unzip contentify2_0.zip
> mv contentify2_0 contentify
> rm contentify2_0.zip
> chmod 777 -R /var/www/contentify/storage
> chmod 777 -R /var/www/contentify/boostrap/cache
> chmod 777 -R /var/www/contentify/public/uploads
> chmod 777 -R /var/www/contentify/public/share
> chmod 777 -R /var/www/contentify/public/rss

6. Configure Apache2
> cd /etc/apache2/sites-available
> vim contentify.conf

Copy/paste:
```
<VirtualHost *:80>
        ServerName www.site.com

        ServerAdmin contact@site.com
        DocumentRoot /var/www/contentify/public

        <Directory /var/www/contentify/public>
                Allowoverride All
        </Directory>

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

7. Disable default apache website
> a2dissite 000-default.conf

8. Activate module rewrite and contentify website
> a2enmod rewrite
> a2ensite contentify.conf

If all is good and i have dont forgot something you can get install of contentify: http://site.com/install.php

**Comment by krysennn** [comment]
Before run install make this:

1. Open mysql
> mysql -u root -p
> Prompt will tell you to enter your password of root user.

2. Create database and quit
> CREATE DATABASE IF NOT EXISTS contentify2;
> exit

**Comment by maxbrood** [comment]
Wow, thankyou for the detailed explanation! It's all installed and seems to be working perfectly. You sir are a legend!

**Comment by krysennn** [comment]
No problem, you are welcome ;)

**Comment by chriskonnertz** [comment]
> I've attempted to follow the installation guide and setup a LAMP stack on digital ocean by following the video in the installation wiki 

The video might be a little bit outdated. Sorry for the inconvenience.

**Comment by EquanimityEu** [comment]
Sorry to ask on a closed thread. Following this guide with no issues until the "mv contentify2_0 contentify". It does not seem to do anything?

Please can you advise what my silly mistake is?
