### ISSUE TITLE
A Few Questions

### ISSUE THREAD

**Issue by maxbrood** [Contentify/Contentify#128]
Thanks so much with your help yesterday. I've got a few last questions today which I hope you can help with.

I'm experiencing a couple errors, firstly when I try and navigate to the "modules" component in the admin backend I'm getting an error 

> ErrorException in Collection.php line 1187:
> Undefined index: enabled

Also the captcha on the registration form is not displaying correctly. I've completed the suggestion here [https://github.com/Contentify/Contentify/wiki/Troubleshooting#captcha-image-not-displayed](https://github.com/Contentify/Contentify/wiki/Troubleshooting#captcha-image-not-displayed)

but no luck. When I open the image in a new tab I get the error 

> FatalErrorException in Captcha.php line 22:
> Call to undefined function Contentify\imagecreatefromjpeg()

Finally I'm looking to setup the job needed for the twitch streams but again my knowledge is lacking here, if I go to /jobs I get this error which probably means something isn't quite right

> FatalErrorException in StreamApi.php line 16:
> Call to undefined function App\Modules\Streams\curl_init()

Any guidance would be appreciated.

Thanks.

**Comment by krysennn** [comment]
Hi :)

For captcha and steam problem make this:
> apt-get install php5-gd php5-curl

**Comment by maxbrood** [comment]
Thankyou, that seems to have addressed some of the issues I was having. I can manually run the jobs now to get the twitch viewer information however I now need to set a cron job which I have no idea about! I've followed this - https://github.com/chriskonnertz/Jobs - but get losts after this.

I also need to create a couple pages with text on them in the selected template. When I go to pages in admin I can create a page but it doesn't appear, I looked at adding the link manually into the template but I can't even find a link to the page.

Appreciate your continued patience! hopefully this will be the last time I annoy you :)

**Comment by krysennn** [comment]
Hi,

I don't use chriskonnertz/jobs package, but i can maybe help you, where are you lost in documentation ?

About page, i think when you created your page in admin backend you can click on title and you will be redirect to your page ? (i use custom pages).

You don't annoy me ;)

**Comment by maxbrood** [comment]
Hi,

Thanks for the tip on the custom pages, I've managed to link to them now!

I've followed the setup in the package and can successfully run php artisan jobs to return the twitch view count however I'm not too experienced in creating cron jobs. I'm running crontab -e and adding in the line 1  * * * * php /var/www/contentify/artisan jobs - but it doesn't seem to be returning the information.

I've also noticed one other thing, I've setup my domain now and can access it through the frontend fine. However when I go into the backend the links in the admin navigation go to the IP rather than the web address and require me to login again. I'm imagining this is something that needs changing from the initial installation but I'm not sure what.

Thanks for your help!

**Comment by chriskonnertz** [comment]
> I've also managed to sort out the streaming stuff. However is it possible to hide streams that are offline?

Not with a checkbox in the backend but yes, sure. Where do you want to hide them? (Several places can be affected). For example on the streams page (`http://you-domain.com/stream`): You have to change this line: https://github.com/Contentify/Contentify/blob/2.0-dev/app/Modules/Streams/Http/Controllers/StreamsController.php#L19 To something like this (_disclaimer: I did not test it_):
` $streams = Stream::isOnline(true)->paginate($perPage)->setPath(Request::url());`

> Note: These changes might be overwritten by version updates in the future!

**Comment by Samaoneill** [comment]
Hi,

Clearing the cache files/folders did the trick, thanks!

I'm looking to hide the offline streams sidebar, I think it's the streamswidget.php. If I change this line

`$streams = Stream::orderBy('online', 'DESC')->orderBy('viewers', 'DESC')->take($limit)->get();`

to something like

`$streams = Stream::isOnline(true)->orderBy('online', 'DESC')->orderBy('viewers', 'DESC')->take($limit)->get();`

It just throws an error 

> Call to undefined method Illuminate\Database\Query\Builder::isOnline() (View: /var/www/contentify/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php)

Thanks!

**Comment by chriskonnertz** [comment]
Sorry, please try this instead:

`$streams = Stream::whereIsOnline(true)->orderBy('online', 'DESC')->orderBy('viewers', 'DESC')->take($limit)->get();`

**Comment by Samaoneill** [comment]
Sorry still no luck!

**Comment by chriskonnertz** [comment]
My bad, I had no time to test the code that I posted. Here is the correct and tested solution:

`$streams = Stream::whereOnline(true)->orderBy('online', 'DESC')->orderBy('viewers', 'DESC')->take($limit)->get();`

Sorry for the inconvenience!
