### ISSUE TITLE
News articles

### ISSUE THREAD

**Issue by nrRudiak** [Contentify/Contentify#129]
The articles seem to change date everytime opened. Running all through a standard web host, could i maybe just pay you to setup properly and make a few tweaks i require?

**Comment by chriskonnertz** [comment]
> could i maybe just pay **you**

As a team? Nope. :p Contentify is not a company so we do not do anything commerical atm. might change in the future but this is the current position.

But you could ask @krysennn (as a person) if he is interested. 

> The articles seem to change date everytime opened

Opened in the frontend or in the backend?

**Comment by krysennn** [comment]
I'm open to help you for fix problem or help you to install Contentify but im sorry atm i have no time for make some tweaks but maybe your tweaks are maybe interessant for other people and you can share it here: https://github.com/Contentify/Contentify/issues/18

**Comment by nrRudiak** [comment]
Okay thanks @krysennn .Well i think the main issue is i know nothing about linux so installed on standard hosting and its giving me heaps of bugs. The tweaks are very minor like background change but no prob can work those out once got something to play with. Are you able to install for me or just advise when I have issues?

**Comment by krysennn** [comment]
What sort of hosting have you ? It's small server with ssh access ? Or standard web hosting ??
Because i saw your last issue about installation problem and your website is this http://www.nerdrage.pro/public/ ?

You have some problem maybe because you have "public" in URL it's not best practices for use Contentify

(do you understand me ? Sorry my english is bad.. Im french ^^)

**Comment by nrRudiak** [comment]
Yes that is correct, we had to put a redirect in the name wasnt sure how to move from /public. And yes its standard webhosting without ssh. If i was to move to the recommended vps is it still posibble to have all our custom emails? As I am more then happy to move to the recommended so can use the site properly, I havent been able to disable modules in the standard hodting either so its a little laggy.

**Comment by krysennn** [comment]
Oh yes i understand, Contentify is CMS developped with Laravel Framework and Laravel recommand using hosting with SSH access.

If you can order VPS i can help(not this week-end, im not in my home) you for get database and files for migrate to VPS with all good settings and inject your database and files for no lost users and data.

**Comment by Samaoneill** [comment]
Hi, just a quick note. My website is running on digital ocean and I've also noticed the news article dates resetting to the current date/time randomly.

**Comment by acamilleri** [comment]
Ok @maxbrood i will check this ASAP.

**Comment by Samaoneill** [comment]
@krysennn 
Thanks, I believe I've found the cause of the issue, If I view a news entry in the admin backend it has the correct created date, however on the front end it displays a different date. I believe this date may be the last time it was viewed as it seems to update when I click it and go into the article itself. It is also being sorted by this date.

**Comment by chriskonnertz** [comment]
Hm I cannot see why/where the CMS tries to update the created_at timestamp (=attribute that saves the time when a news was created). Have to investigate more...

**Comment by acamilleri** [comment]
@chriskonnertz i search too and i nothing found, i will created news around 6pm and i will check tomorrow if datetime change.

**Comment by acamilleri** [comment]
I understood ^^

When you are in `/news/1/test` it's :

> $news->created_at => 2017-01-23
> line 4 of app\Modules\News\Resources\Views\show.blade.php -> <time>{{ $news->created_at }}</time>

when you are in `/` its :
> $item->updated_at => 2017-01-24
> line 22 of app\Modules\News\Resources\Views\stream_item.blade.php -> <time>{{ $item->updated_at }}</time>

So @chriskonnertz what do you prefer ? maybe updated_at it's more interessant when admin updated news and maybe in show.blade.php we can add `updated at {{ $news->updated_at }}` ?

**Comment by lolbob181** [comment]
The owner of the topic. I have my VPS setup with contentify and custom emails instal vestacp there is a tutorial on the forum of digitalocean :) Or ask me :)

**Comment by acamilleri** [comment]
@lolbob181 What is the relationship with the issue ?

**Comment by chriskonnertz** [comment]
> So @chriskonnertz what do you prefer ? maybe updated_at it's more interessant when admin updated news and maybe in show.blade.php we can add updated at {{ $news->updated_at }} ?

Haha that's a nice inconsistency! ;) I changed it: https://github.com/Contentify/Contentify/commit/a8fdce63629c5a9725df4ef37be73b68e6be9777 and https://github.com/Contentify/Contentify/commit/afea5b6e605b2debddb0bc65a039ed30d4ea446e

**Comment by Samaoneill** [comment]
I'd rather have my news order by created_by, I've updated the files and the created date is now displayed, but its still being sorted by updated_by, where can I change this?

Thanks.

**Comment by chriskonnertz** [comment]
Fast, easy, ugly way:
With a text editor that is capable of doing "search & replace" in directories, search "updated_at" and replace it with "created_at" in the directory `app/Modules/News` (and all of its sub directories).

> Note: I assume you meant created_*at* not created_*by*. "at" = time, "by" = user

---

> Note: These kind of changes will get overwritten when doing an update of Contentify in the future

**Comment by Samaoneill** [comment]
Thanks, just for note the ordering was dealt with in NewsController.php in the app/modules/news/http/controllers
