### ISSUE TITLE
Just installed - Can't access Modules

### ISSUE THREAD

**Issue by PureLoneWolf** [Contentify/Contentify#131]
#Hi there

I have just installed, from fresh and everything went great.  I was looking at the backend and getting used to everything when I clicked on the Modules option under Website.  At that point, I get an error:

`ErrorException in Collection.php line 1187:
Undefined index: enabled`

I searched, but only found one question about this but no solution.  If someone could help that would be great :D

**Comment by chriskonnertz** [comment]
Hi,

thanks for reporting his problem, because this actually is a bug. Or _was_. Because it's fixed now: https://github.com/Contentify/Contentify/commit/28cc07780ca773afd3a5f738c8abcb70f3d605f1

Thanks!

**Comment by PureLoneWolf** [comment]
Excellent - That's working now - Thank you :)

**Comment by chriskonnertz** [comment]
No problem.
