### ISSUE TITLE
Fatal Error Exception in Migrator.php line 335

### ISSUE THREAD

**Issue by EquanimityEu** [Contentify/Contentify#132]
Good afternoon

Please could anybody help me out with this code at all?

Thanks for your time. 

![16466389_1639424789685897_41921693_o](https://cloud.githubusercontent.com/assets/25538914/22620086/9dd37d9c-eafb-11e6-8ddb-12707f82efef.png)

**Comment by chriskonnertz** [comment]
Hi,

this is coumented here: https://github.com/Contentify/Contentify/wiki/Troubleshooting#installation-error-message-fatalerrorexception-in-migratorphp

Please leave a message if you have any question regarding this issue.

PS:
I got another email notficiation from you, a question about the installation, did you manage to solve that problem?

**Comment by EquanimityEu** [comment]
![16491418_1639457029682673_1851481262_o](https://cloud.githubusercontent.com/assets/25538914/22620485/f9459cba-eb04-11e6-9998-ec57ef6bd275.png)
![16492334_1639457046349338_843427323_o](https://cloud.githubusercontent.com/assets/25538914/22620489/fc8b4514-eb04-11e6-8152-62c37c75ad33.png)

Hello, thank you for taking the time to respond. We have got past that one and are now given this?

Kind regards

Ryan

(Please disregard that email from before, it was an awful mistake that was easily fixed!)

**Comment by EquanimityEu** [comment]
Hello sorry but it seems a friend has fixed it. it's now asking for us to create the super admin user. I believe this is the end of installation!

Thanks you so much :)

**Comment by chriskonnertz** [comment]
Great!
