### ISSUE TITLE
How to take out of development mode?

### ISSUE THREAD

**Issue by EquanimityEu** [Contentify/Contentify#133]
Good afternoon

Thanks so much for your assistance and making this Cms.

We are all installed however the final step is the following:

"Preparation For Production

Per default, Contentify is prepared for development. To prepare it for a production environment, disable the debug mode. Also ensure that the application key (you will find it in config/app.php) has been set to a random string. The diag module offers a convenient way to check if everything is set to proper values. Navigate to the backend dashboard and click on the diag icon to open the diag page."

Please could you assist with this? I do not fully understand it and do not want to break anything aha!

Kindest regards

**Comment by chriskonnertz** [comment]
If you have any questions about this topic just create a new issue :)
