### ISSUE TITLE
Some questions about Contentify

### ISSUE THREAD

**Issue by CaptainRafael** [Contentify/Contentify#136]
Hello , 
I changed to OVH and I was wondering how can I change the logo 
http://corse-esports.eu/v1/public 
and put more themes in there and also the footer
I also have a problem to log with steam , and I want to put psn and xbox live loggin option

**Comment by chriskonnertz** [comment]
Hello,

the logo files are these:

```
public/img/favicon_180.png (favicons for browsers)
public/img/header_logo.png (the logo in the header and the footer of the website)
public/img/logo_180.png (the general logo of your organisation)
```

Just replace them with new images.

**Comment by chriskonnertz** [comment]
> I also have a problem to log with steam

=> https://github.com/Contentify/Contentify/issues/125

> I want to put psn and xbox live loggin option

Currently these login options are not available out-of-the-box. To be honest I doubt that there are third-party solutions available that can be used with few effort. :(
