### ISSUE TITLE
Create new maps

### ISSUE THREAD

**Issue by CaptainRafael** [Contentify/Contentify#137]
When I create new maps I got this error : FatalThrowableError in ModelHandler.php line 392:
Call to undefined method Contentify\ModelHandler::getControllerName() 
How can I fix?

**Comment by chriskonnertz** [comment]
Hello,

which version of Contentifx do you use? 1 or 2?

When I create a new map in v2 this error does not occur. I tried some variations  as well: with uploading an image and without and editing an existing map. No error.

**Comment by chriskonnertz** [comment]
Closed. I cannot help you without more information. If you post more infos I will reopen this issue.
