### ISSUE TITLE
how to edit the frontend template in Contentify 2.0

### ISSUE THREAD

**Issue by pinoylancers** [Contentify/Contentify#139]
how to edit frontend Contentify 2.0?

![screen shot 2017-02-21 at 9 26 56 pm](https://cloud.githubusercontent.com/assets/7369034/23166771/db6783c2-f87c-11e6-9f92-4762bee486f2.png)

**Comment by acamilleri** [comment]
Hi,

You have two template in Contentify, (MorpheusTheme and PhobosTheme) and you can add new template with same structure.

Template are in modules folder (app/modules/xxxTheme).
You are able to edit theses template in views folder of the template and you will need to edit .less files in assets folder of template for edit the stylesheet.

When you change the theme in backend the less file are generate ;)

**Comment by pinoylancers** [comment]
Hi thank you very much for the clarification.. appreciate it.. :)

**Comment by chriskonnertz** [comment]
Hi,

there is an article in our wiki that you might find helpful: https://github.com/Contentify/Contentify/wiki/Themes

**Comment by chriskonnertz** [comment]
PS: The `resources/views` folder contains these general frontend templates that are not a) part of a module or b) part of a theme.
