### ISSUE TITLE
How can I view the advertisements on the frontend that I created on the Admin Panel?

### ISSUE THREAD

**Issue by pinoylancers** [Contentify/Contentify#140]
How can I view the advertisements on the frontend that I created on the Admin Panel?

**Comment by chriskonnertz** [comment]
Hi,

good question. To be honest, they are not implemented out-of-the box. What kind of ads (for example: image with a link) do you want to include and what size (width and height in pixels) would they have?

**Comment by pinoylancers** [comment]
Hi I noticed there is a Advertisement option on the Admin-Backend - is that the one that is not fully implemented? I cant seem to view what I add in there. Thank you

![screen shot 2017-02-27 at 2 27 38 pm](https://cloud.githubusercontent.com/assets/7369034/23350930/ef052242-fcf8-11e6-820f-001a45df1387.png)

**Comment by chriskonnertz** [comment]
Hi,

it is fully implemented from the point of coding. So there is a working widget that can display ads. However, this widget is not used in the themes.

Here is what you can do:
1. Open the main template of the active theme, for example `app/Modules/MorpheusTheme/Resources/Views/layout.blade.php`
2. Find a place where you want to display ads.  For example, if you want to display them at the top of the right sidebar, go to line 97 (right behind this code: `<aside id="sidebar" class="col-md-4"><div class="border">`)
3. Add this code: `@widget('Adverts::Advert')`
You can also choose a specific ad category: `@widget('Adverts::Advert', ['categoryId' => 2])`

_________________________________________

> Note 1: Your Ablocker might block the ad. 
> Note 2: These kind of changes might get lost if you install an update for Contentify in the future.
