### ISSUE TITLE
Stream isn't work.

### ISSUE THREAD

**Issue by Erezey** [Contentify/Contentify#142]
Hello guys. Can u help me to fix a module stream. 
I put everything, and when im going to live, on the website still saying im offline.

![stream](https://cloud.githubusercontent.com/assets/26022239/23344183/ec3ee874-fc88-11e6-9b00-ca1d8d14a4fd.png)

**Comment by chriskonnertz** [comment]
Hi,

please take a look at the "Streams" section of this wiki page: https://github.com/Contentify/Contentify/wiki/Built-In-Modules#streams

Did you follow these instructions?

**Comment by chriskonnertz** [comment]
Closed for now.
