### ISSUE TITLE
Installing on Bluehost shared hosting.

### ISSUE THREAD

**Issue by uberartist** [Contentify/Contentify#143]
I have uploaded the contentify zip , extracted and changed the permissions of directeries etc.
I have access to SSH and other stuff.
When I open the url _domain/public/install.php_ it works fine... all the requirements are green except 1: **Vendor libraries installed:	No - please run "composer install"!**
I am testing on subdomain so the folder whereI have uploaded is **public_html/contentify**
When I click Launch Installer it goes to _domain.com/public/install_ and page says The page isn't working with **http error 500**

Please Help!!

**Comment by chriskonnertz** [comment]
Hi,

well, just follow the instruction: 'please run "composer install"'

1. Connect to your server via SSH
2. Switch to the Contentify directory
3. Run: `php composer.phar install`
