### ISSUE TITLE
Dates constantly change. 

### ISSUE THREAD

**Issue by EquanimityEu** [Contentify/Contentify#146]
Good morning

We are having an issue with the published date not showing up on our articles. Instead it simply changes to the current date (From what we can tell).  Has anybody else had such issues before and know of a fix?

Kindest regards

**Comment by Samaoneill** [comment]
I had a similar problem with my page, have a look at this closed ticket. [https://github.com/Contentify/Contentify/issues/129](https://github.com/Contentify/Contentify/issues/129)

**Comment by EquanimityEu** [comment]
It does, thank you. What program did you use to search and replace it all? Loads to do manually!

**Comment by bitbot-marina** [comment]
@EquanimityEu if you use Sublime Text editor you can pretty easily search and replace across all files on your site. Alternatively, I think other text editors like Atom can do the same thing.

**Comment by EquanimityEu** [comment]
Sorry for the late reply and thanks. Struggling to figure out how I connect sublime to it? The guy who helped fix most of the issues with the site is no longer with us. Struggling aha!

**Comment by bitbot-marina** [comment]
If you've install Sublime, you can drag your entire folder for your site onto Sublime to open the entire website as a project. Then you should be able to do search and replace across all the files in the project.

**Comment by Samaoneill** [comment]
I didn't do a find/replace on the entire solution or even a subset of folders, I've had too many bad experiences when doing such on code I'm not 100% familiar with. I went through each of the news component files and find/replaced them one by one using Notepad++, there really isn't that many to change. 

I can't recall what I specifically changed but looking through the app/modules/news folder I can give you an idea where it has been specified as created_at and you can see if you files correspond with mine

1. app/modules/news/news.php > lines 118, 127
2. app/modules/news/Http/Controllers/NewsController.php > lines 23, 30, 52, 75, 76, 86 x2, 99 x2
3. app/modules/news/Http/Controllers/NewsWidget.php > line 15
4. app/modules/news/Resources/Views/show.blade.php > line 3
5. app/modules/news/Resources/Views/show_overview.blade.php > line 9
5. app/modules/news/Resources/Views/stream_item_blade.php > line 2, 22, 28 x2, 45

And thats it. I don't know if it is absolutely necessarily to change it in all of these instances but that is how mine is setup and it works perfectly.

**Comment by chriskonnertz** [comment]
Thank you!
