### ISSUE TITLE
Feature Suggestion: Alternative Contact Fields

### ISSUE THREAD

**Issue by bitbot-marina** [Contentify/Contentify#147]
Some contact fields, such as Skype, are considered outdated by the majority of the gaming community. It would be nice to have the option to easily add fields via the back-end, or disable/remove fields if they are irrelevant.

I ended up just going in and changing the user module myself to replace the "Skype" field with Discord, but it also required manually editing the database - not something that all users would feel comfortable with.

I think the "best" way to implement something like this would likely involve having toggleable custom fields, that will support any input type (text, email, ect) where the label can be modified in the CMS control panel.

**Comment by chriskonnertz** [comment]
Yeah this might be a good idea. The big question is: What would be best way to implemnt this? Where (in wich database table) and how do we store a) the structural data (_which_ fields do we have) and the content data (_what_ is the data of these fields).

**Comment by bitbot-marina** [comment]
I'm not super savvy with databases, so this is a front-end guy tackling a back-end problem but...

This is how I would go about it, if I wanted the site user to be able to set up three custom fields of their choice. I've seen this on some forums, such as GBATemp and GameBanana, where they allow users to add in their own fields to their profile:

1. Add six custom fields, under the "user" table. Three of them will will be "CustomLabel1, CustomLabel2, CustomLabel3" and three will be "CustomData1, CustomData2, CustomData3"
2. When called into the page, they would appear in the list of other user profile info and editable in the same manner. If the fields are blank (content="NULL") they are hidden.

Might that work as one approach?

A back-end managed version might actually be more tricky. I haven't taken a very thorough look at the database myself, so I'd have to do that before I could give a thoughtful approach on that...

**Comment by chriskonnertz** [comment]
To be honest I might follow your suggestion. It's really simple and implementation should be done in a few minutes. So why not...

**Comment by chriskonnertz** [comment]
Hello,

two udpates:

1. Added a discord field to the user profile: https://github.com/Contentify/Contentify/commit/97997a66a9dbeb5c1394f40b306bf313cc0a5c74

2. Defining custom user profiles definitely will be possible. I do not know when but I will implement it.
