### ISSUE TITLE
News not appearing, events not appearing, pages, advertisements

### ISSUE THREAD

**Issue by SAVAGEGG** [Contentify/Contentify#152]
Non is showing up when i create new ones. the news SOMETIMES appears but after a refresh of the page it disappears again. I may have installed an old version or installed incorrectly. I installed it on a web host anyway i can get help? Maybe a fresh reinstall of the cms on my host by you guys.

**Comment by chriskonnertz** [comment]
I think I will write a little PHP script that gathers some info about the problem and should help me to nail down the issue. The problem is that I cannot reproduce the issue (yet) so I hope this will help me. Ill try to write the code tomorrow.

**Comment by SAVAGEGG** [comment]
i saw in the 2.1 release under special the paid services. since ive found this cms ive changed minds of 4 website owners to leave the provider they all have and get this script  myself and the other 4 website owners are eager to pay someone to get things up for us all. Know when you will be offering such services? i feel like the instal i did i didnt do correctly would love for someone who actually knows what they are doing to do it for me

**Comment by chriskonnertz** [comment]
I have seen it on my own website now. That is a good thing, because now I will be able to debug it. :)

**Comment by chriskonnertz** [comment]
Bugfix: https://github.com/Contentify/Contentify/commit/6c3058f933c171b257bc7c08c7176f06d5c86af2

**Comment by chriskonnertz** [comment]
> i saw in the 2.1 release under special the paid services. since ive found this cms ive changed minds of 4 website owners to leave the provider they all have and get this script myself and the other 4 website owners are eager to pay someone to get things up for us all. Know when you will be offering such services? i feel like the instal i did i didnt do correctly would love for someone who actually knows what they are doing to do it for me

I understand that you are eager to get extended support. But to be honest I have no idea when  this is going to happen. Maybe soon, maybe not.
