### ISSUE TITLE
home page issue

### ISSUE THREAD

**Issue by amirgee007** [Contentify/Contentify#153]
hi, i have installed this app on local for my own purpose and after downloading composer installation etc I got this screen is there any problem I have 3-4 hours to configure it on my local but it gives me this error.can you define please thanks
![problem](https://cloud.githubusercontent.com/assets/16411441/24310581/461713e4-10f2-11e7-8d5c-1b600f43a5b7.JPG)

**Comment by chriskonnertz** [comment]
Hello,

are you sure there is an error? You need to add content to your website to make it look like the demo website. For example: Add an image to the slider, write a news, create teams, upload images (and  add them to a gallery)...

**Comment by amirgee007** [comment]
thanks for your help.

**Comment by amirgee007** [comment]
i have successfully added all the things that you mentioned problem solved <3 love you bro

**Comment by amirgee007** [comment]
sir more thing i have added so many nesw in backend and when i visit my home page its shows nothing here how can i fix it please help i am trying to do from 3-4 hours but have stucked...

**Comment by amirgee007** [comment]
![right widget on home page](https://cloud.githubusercontent.com/assets/16411441/24321300/e2e69a1e-116a-11e7-9d47-bcbe994f00ef.JPG)

also i want to remove these advertisements from home page left widget partner,team etc from which page i get the code of these widgets thank for your precious time

**Comment by chriskonnertz** [comment]
>  i have added so many nesw in backend and when i visit my home page its shows nothing here how can i fix it

This was bug. Here is a bugfix:

https://github.com/Contentify/Contentify/commit/9128d94247997a7f5698bd13cc76d77e91113482

**Comment by chriskonnertz** [comment]
> also i want to remove these advertisements from home page left widget partner,team etc from which page i get the code of these widgets

It depends on the theme you have chosen. Example for morpheus theme:

1. Open this file `app/Modules/MorpheusTheme/Resources/Views/layout.blade.php` with a text editor. 
2. Remove the widget that you do not like. For example to remove the matches and the gallery, remove this code:

```
                    <h3>
                        {{ trans('app.latest') }} {{ trans('app.object_matches') }}
                        <a href="{{ url('matches') }}" title="{{ trans('app.read_more') }}">{!! HTML::fontIcon('plus-square') !!}</a>
                    </h3>
                    @widget('Matches::Matches')

                    <br>
                    <h3>
                        {{ trans('app.object_gallery') }}
                        <a href="{{ url('galleries') }}" title="{{ trans('app.read_more') }}">{!! HTML::fontIcon('plus-square') !!}</a>
                    </h3>
                    @widget('Galleries::Galleries', ['limit' => 6])
```

Warning: These changes might be overwritten by updates in the future so you should backup the template with your changes!

**Comment by amirgee007** [comment]
ok thanks you very much sir you are great you saved my time a lot of time.
