### ISSUE TITLE
News pagination bug

### ISSUE THREAD

**Issue by bitbot-marina** [Contentify/Contentify#158]
It would seem that when the pagination for the news occurs (or whatever you want to call it when it loads in chunk by chunk) it duplicates the previous chunk of news. The result is that it keeps showing the same 6 news articles, in succession:

For reference of the issue, you can see it here:
http://googiegang.com/

Scroll down, and you'll notice the same 6 news items repeat.

**Comment by chriskonnertz** [comment]
Hi,

please take a look at the "Time / date problems" section on the troubleshooting page in the wiki: https://github.com/Contentify/Contentify/wiki/Troubleshooting#time--date-problems

This *might* solve this problem.

**Comment by bitbot-marina** [comment]
<img width="658" alt="screen shot 2017-04-06 at 10 13 32 am" src="https://cloud.githubusercontent.com/assets/15271348/24766862/cecf36d0-1ab1-11e7-93bd-f8f5d9742c8a.png">
I've verified that they do in-fact match, though changing this did not solve the issue.

**Comment by mix2002** [comment]
I make a issue with the same and anyone answers.... How to change the cms timezone? its default UTC...

**Comment by bitbot-marina** [comment]
@mix2002 probably should open your own issue for your question, but...

The first one (for Contentify) is here, where `%BASEPROJECTDIRECTORY%` is where you main folders for your site are located:
`%BASEPROJECTDIRECTORY%/config/app.php`
and here, in the /etc/ folder for your droplet:
`/php5/apache2/php.ini
`
Just do a search for "timezone" when you have those files open.

**Comment by mix2002** [comment]
I have done it :)
https://github.com/Contentify/Contentify/issues/157
![screenshot_2](https://cloud.githubusercontent.com/assets/8055275/24835842/b9688382-1d04-11e7-8032-f01b35dab55c.png)

**Comment by bitbot-marina** [comment]
@chriskonnertz have we made any headway on this?

**Comment by chriskonnertz** [comment]
Nope. But I will try to fix the problems mentioned in the currently open issue soon.

**Comment by EazYKevin** [comment]
i made my work by typing ETC in the app.php file
