### ISSUE TITLE
[Question] How to change amount of items displayed per page

### ISSUE THREAD

**Issue by tjoecs** [Contentify/Contentify#159]
Hi,
I am not a coder at all but I am able to manage some customization editing templates and stuff.
But of course, there is a point where I need help as I don't know where to look for the things I need. 
In this case I'm talking of the **_videos_** index page. 
By Default there are 10 videos per page. This value should be editable..shouldnt it? But where? Which file do I have to edit for this? 

URL to website: www.excinis.de/videos 

I appreciate any information leading me to my goal.. At the moment we have the 2.0 beta installed as it runs quite good and I don't know if I can update without further problems / rework to do after it.

Best Regards
Alex

**Comment by chriskonnertz** [comment]
Hi,

this line of code is responsible: https://github.com/Contentify/Contentify/blob/2.0/app/Modules/Videos/Http/Controllers/VideosController.php#L17

You can change it to something like `$perPage = 20;`.

> Note: This change might be overwritten by an update in the future.

**Comment by tjoecs** [comment]
Thanks.  Are there any plans of including a field for changing the $perpage variable in the admin backend? Just for comfort reasons... O:-)

**Comment by chriskonnertz** [comment]
Well not on a per-page-base, that would be too much.
