### ISSUE TITLE
Adding a descripion of the site in the homepage

### ISSUE THREAD

**Issue by ARYX01** [Contentify/Contentify#160]
When you are in the reset password page the captcha img is missing...

**Comment by chriskonnertz** [comment]
Hi,

which version of Contentify do you use?

Here on the demo server of version 2.0 it seems to work: http://46.101.169.158/auth/restore

**Comment by ARYX01** [comment]
i have fixed it, but how i can add some text in the homepage?

**Comment by chriskonnertz** [comment]
_Where_ do you want to add text?

**Comment by ARYX01** [comment]
In between the slider and the news

**Comment by chriskonnertz** [comment]
Well you would have to modify the template. 

If you use the Morpheus theme, you should be able to add the text here:
https://github.com/Contentify/Contentify/blob/2.0/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php#L76

If you use the Phobos theme, you should be able to add the text here: 
https://github.com/Contentify/Contentify/blob/2.0/app/Modules/PhobosTheme/Resources/Views/layout.blade.php#L104

**Comment by ARYX01** [comment]
Thank you so mutch for the help, but if I wanted the text only on the news(home) page

**Comment by chriskonnertz** [comment]
Then you have to add the text in this tempalte file: `app/Modules/News/Resources/Views/show_overview.blade.php` (Try to add it right at its top.)

**Comment by ARYX01** [comment]
I added the text there, but nothing appeared on the site so I added the text in show_stream.blade.php and worked, thanks anywhay!
