### ISSUE TITLE
User löschen

### ISSUE THREAD

**Issue by SlavenTV** [Contentify/Contentify#162]
Meine Frage konnte ich selbst beantworten :)

**Comment by chriskonnertz** [comment]
Alles klar, dennoch kurz die Info. Das Löschen von Usern ist nicht vorgesehen. Du kannst es sicherlich einbauen, würdest dir damit aber über kurz oder lang dein System zerschießen, da stets davon ausgegangen wird, dass zu einer User-ID auch ein User existiert. Rufst du einen Kommentar von einem gelöschten User auf -> es knallt. Rufst du einen Forum-Post von einem gelöschten User auf -> es knallt. Usw. ... Daher ist als Alternative das Bannen / Deaktivieren von Usern vorgesehen. 

> Disclaimer: Das Folgende ist keine Rechtsauskunft.

Damit sollten auch rechtlichen Anforderungen (Recht auf Löschung des User-Accounts) genüge getan sein.

PS: Es ist auch für die Zukunft nicht vorgesehen, das jemals zu ändern. Das war eine der ganz seltenen unumkehrbaren Grundsatzentscheidungen und an der wird auch nicht mehr gerüttelt. Der Aufwand, das CMS dahingehend umzustellen, wäre einfach exorbitant hoch.

Ein möglicher Kompromiss wäre, alle User-generierten Inhalte dem User mit der ID 1 (daemon-User) zuzuweisen. Aus diesem Grund existiert dieser User überhaupt. Wurde bis jetzt aber weder umgesetzt noch überhaupt irgendwie mal konkret geplant und steht definitiv auch nicht auf der Agenda.

**Comment by SlavenTV** [comment]
Alles klar danke für diese Info.
Ich bin leider noch neu in dieser Materie. Versuche mich aktuell an einem eigenen Theme xD Aber das klappt schon nicht beim Anlegen vom Module
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 11.05.17, 18:35, Chris Konnertz <notifications@github.com> schrieb:
Alles klar, dennoch kurz die Info. Das Löschen von Usern ist nicht vorgesehen. Du kannst es sicherlich einbauen, würdest dir damit aber über kurz oder lang dein System zerschießen, da stets davon ausgegangen wird, dass zu einer User-ID auch ein User existiert. Rufst du einen Kommentar von einem gelöschten User auf -> es knallt. Rufst du einen Forum-Post von einem gelöschten User auf -> es knallt. Usw. ... Daher ist als Alternative das Bannen / Deaktivieren von Usern vorgesehen.

Disclaimer: Das folgende ist keine Rechtsauskunft.

Damit sollten auch rechtlichen Anforderungen (Recht auf Löschung des User-Accounts) genüge getan sein.

**Comment by chriskonnertz** [comment]
Was klappt denn nicht?

**Comment by SlavenTV** [comment]
also ich kann das theme auswählen im Admincenter. Wenn ich das mache bekomm ich einen Error. 
Http://www.team-flash.eu
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 11.05.17, 18:45, Chris Konnertz <notifications@github.com> schrieb:
Was klappt denn nicht?

**Comment by SlavenTV** [comment]
Morgen
Um nochma auf das Löschen eines Users zurück zu kommen. Ich hab einfach ma den Test gemacht und in der datenbank struktur die Teile auf On cascade gesetzt. 
Dann kam zwar kein Fehler mehr beim löschen aber er hat dann den kompletten Thread mit gelöscht obwohl dieser nicht vom user angelegt wurde
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 11.05.17, 18:35, Chris Konnertz <notifications@github.com> schrieb:
Alles klar, dennoch kurz die Info. Das Löschen von Usern ist nicht vorgesehen. Du kannst es sicherlich einbauen, würdest dir damit aber über kurz oder lang dein System zerschießen, da stets davon ausgegangen wird, dass zu einer User-ID auch ein User existiert. Rufst du einen Kommentar von einem gelöschten User auf -> es knallt. Rufst du einen Forum-Post von einem gelöschten User auf -> es knallt. Usw. ... Daher ist als Alternative das Bannen / Deaktivieren von Usern vorgesehen.

Disclaimer: Das folgende ist keine Rechtsauskunft.

Damit sollten auch rechtlichen Anforderungen (Recht auf Löschung des User-Accounts) genüge getan sein.

**Comment by chriskonnertz** [comment]
> Um nochma auf das Löschen eines Users zurück zu kommen. Ich hab einfach ma den Test gemacht und in der datenbank struktur die Teile auf On cascade gesetzt.
Dann kam zwar kein Fehler mehr beim löschen aber er hat dann den kompletten Thread mit gelöscht obwohl dieser nicht vom user angelegt wurde

Wie gesagt das Löschen von Usern ist nicht vorgesehen, das kann sonst was für unvorhersehbare Konsequenzen haben.

> also ich kann das theme auswählen im Admincenter. Wenn ich das mache bekomm ich einen Error.

Was denn für einen? Eventuell ein Problem mit Schreibrechten. Eventuell mal den gesamten public-Ordner mit CHMOD 777 versehen.
