### ISSUE TITLE
Error after pressing "Launch Installer"

### ISSUE THREAD

**Issue by ESKiK** [Contentify/Contentify#164]
Hello everyone.

When I try to install Contentify, I get this error from the webpage:

`The requested URL /Contentify/public/install was not found on this server.`

All the things in the `install.php` are green, how can I fix this?

Thank You very much

**Comment by chriskonnertz** [comment]
Hello,

do you use Apache and if you do so, is mod_rewrite enabled? 

> You will also need a MySQL Database and it's recommended to activate Apache's mod_rewrite module (or Nginx' HttpRewriteModule). To activate mod_rewrite on a Debian destribution, execute sudo a2enmod rewrite. Usually you also have to allow the .htaccess file to override standard website configs.

**Comment by ESKiK** [comment]
Yes, I use Apache2, I already done `sudo a2enmod rewrite`, and I got the same problem
I have mySQL installed.

**Comment by chriskonnertz** [comment]
Okay. On your webspace, is there this file? `public/.htaccess` It should be there.

**Comment by ESKiK** [comment]
Yes, it is @chriskonnertz, sorry for the delay.

**Comment by itsomarawad** [comment]
I am having the exact same problem. For some reason it works when i try it out locally via XAMPP but not if i do the exact same steps on the webserver.

**Comment by chriskonnertz** [comment]
I do not know how I can help you guys, I have no idea what is going wrong.

**Comment by itsomarawad** [comment]
Well i was wrong for me it says : ../public/index.php was not found on this server. When i open up the index.php directly on my webbrowser it throws the following error page:

> Sorry, the page you are looking for could not be found.
> 
> 1/1
> NotFoundHttpException in RouteCollection.php line 161:
> in RouteCollection.php line 161
> at RouteCollection->match(object(Request)) in Router.php line 821
> at Router->findRoute(object(Request)) in Router.php line 691
> at Router->dispatchToRoute(object(Request)) in Router.php line 675
> at Router->dispatch(object(Request)) in Kernel.php line 246
> at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyAdminAccess.php line 37
> at VerifyAdminAccess->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(VerifyAdminAccess), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in UpdateUser.php line 108
> at UpdateUser->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(UpdateUser), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
> at ShareErrorsFromSession->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
> at StartSession->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
> at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
> at EncryptCookies->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
> at CheckForMaintenanceMode->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
> at Pipeline->Illuminate\Routing\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
> at Pipeline->then(object(Closure)) in Kernel.php line 132
> at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
> at Kernel->handle(object(Request)) in index.php line 53

I also noticed that if you try to open up the index.php directly it redirects to the install.php by appending it. So it opens up a URL like that: /public/index.php/install.php - i think this might be the reason it can't be found?
Is this maybe helping you a bit?

**Comment by chriskonnertz** [comment]
Hello, well sorry, your post did not help me. :/ Is this issue still up to date?

**Comment by itsomarawad** [comment]
Sorry for not getting back to you earlier (i was on vacation). I just did a fresh reinstall just to be sure, but the error persists. It must be a routing problem or something but i can't get the hang of it why it claims that index.php doesn't exist at this location when its clearly there,

**Comment by chriskonnertz** [comment]
Closed this issue. Please try to install the latest version of Contentify, 2.2
If this does not work as well please create a new issue.
