### ISSUE TITLE
Matches adding home team

### ISSUE THREAD

**Issue by ARYX01** [Contentify/Contentify#166]
Where is the file for changing the matches widget? I wanted to add HOME TEAM next to the visiting team in the table. Is this possible?
It would look something like this:
![matches](https://cloud.githubusercontent.com/assets/13236949/26279298/12a7cd38-3db0-11e7-9bb3-474f52c2dc87.PNG)

**Comment by chriskonnertz** [comment]
Hi,

this is possible, just copy this code to the file `MatchesController.php` (take a look at the linked page to see the full path): https://gist.github.com/chriskonnertz/8e45a2bd8d923bc34fb98b685bca8b55

> Attention: This change might be overwritten if you update to v2.1 in the future!

**Comment by ARYX01** [comment]
OK! Thanks for the help!
