### ISSUE TITLE
Error after db install (step6)

### ISSUE THREAD

**Issue by XtremeFighters** [Contentify/Contentify#167]
A have this error:
ErrorException in InstallController.php line 1171:
file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0

What can i do?

**Comment by acamilleri** [comment]
Hello,

You need to open php.ini of your webhosting and edit allow_url_fopen=0 to allow_url_fopen=1

**Comment by chriskonnertz** [comment]
Closed since this issue is very old and inactive.
