### ISSUE TITLE
ErrorException dans DatabaseManager.php ligne 167 

### ISSUE THREAD

**Issue by purwolf** [Contentify/Contentify#169]
bonjour 
je ne trouve pas comment faire pour régler ce souci  
voici l'erreur 

http://www.pur-esport.fr/public/install?step=4

ErrorException dans DatabaseManager.php ligne 167 :
Indice indéfini: pilote
Dans DatabaseManager.php ligne 167
À HandleExceptions -> handleError ('8', 'Indice indéfini: driver', '/htdocs/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php', '167', array ('name' => null , 'Config' => array ('mysql' => array ('host' => 'localhost', 'database' => 'pures850936_3vfjad', 'username' => 'pures850936_3vfjad', 'password' => 'd3z9k5A4W74' )))) Dans DatabaseManager.php ligne 167
Dans DatabaseManager -> makeConnection ( null ) dans DatabaseManager.php ligne 68
Dans DatabaseManager -> connection () dans DatabaseManager.php ligne 317
Dans DatabaseManager -> __ appel ('select', array ('SHOW TABLES LIKE' '')) dans Facade.php ligne 217
Dans DatabaseManager -> sélectionnez ('SHOW TABLES LIKE ""') dans Facade.php ligne 217
À la façade : __ callStatic ('select', array ('SHOW TABLES LIKE' '')) dans la ligne installController.php 302
À DB :: select ('SHOW TABLES LIKE ""') dans InstallController.php ligne 302
À InstallController -> createDatabase () dans la ligne InstallController.php 160
Chez InstallController -> index ()
à Call_user_func_array ( array ( objet ( InstallController ), 'index'), array ()) dans Controller.php ligne 80
Au contrôleur -> callAction ('index', array ()) dans ControllerDispatcher.php ligne 146
Chez ControllerDispatcher -> appel ( objet ( InstallController ), objet ( Route ), 'index') dans ControllerDispatcher.php ligne 94
Chez ControllerDispatcher -> Illuminate \ Routing \ {closure} ( objet ( Requête ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 52 Pipeline.php
Chez Pipeline -> Illuminate \ Routing \ {closure} ( objet ( Requête ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 103 Pipeline.php
à Pipeline -> puis ( objet ( fermeture )) dans la ligne 96 ControllerDispatcher.php
Chez ControllerDispatcher -> callWithinStack ( objet ( InstallController ), objet ( Route ), objet ( Requête ), 'index') dans ControllerDispatcher.php ligne 54
Chez ControllerDispatcher -> dispatch ( objet ( Route ), objet ( Requête ), 'InstallController', 'index') dans Route.php ligne 174
À Route -> runController ( objet ( demande )) dans Route.php ligne 140
À Route -> exécuter ( objet ( demande )) dans la ligne 724 du routeur.php
Au routeur -> Illuminate \ Routing \ {closure} ( objet ( demande ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 52 Pipeline.php
Chez Pipeline -> Illuminate \ Routing \ {closure} ( objet ( Requête ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 103 Pipeline.php
à Pipeline -> puis ( objet ( fermeture )) dans la ligne 726 router.php
Au routeur -> runRouteWithinStack ( objet ( Route ), objet ( demande )) dans la ligne Router.php 699
Au routeur -> dispatchToRoute ( objet ( demande )) dans la ligne Router.php 675
Au routeur -> dispatch ( objet ( demande )) dans la ligne 246 de Kernel.php
À Kernel -> Illuminate \ Foundation \ Http \ {closure} ( objet ( demande ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 52 Pipeline.php
Chez Pipeline -> Illuminate \ Routing \ {closure} ( objet ( Request )) dans VerifyAdminAccess.php ligne 37
À VerifyAdminAccess -> handle ( objet ( demande ), objet ( fermeture ))
à Call_user_func_array ( array ( objet ( VerifyAdminAccess ), 'handle'), array ( objet ( Request ), objet ( Closure )) dans Pipeline.php line 136
Au Pipeline -> Illuminate \ Pipeline \ {fermeture} ( objet ( Demande ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 32 Pipeline.php
Chez Pipeline -> Illuminate \ Routing \ {closure} ( objet ( Requête )) dans la ligne UpdateUser.php 108
À UpdateUser -> handle ( objet ( demande ), objet ( fermeture ))
à Call_user_func_array ( array ( objet ( UpdateUser ), 'handle'), array ( objet ( Request ), objet ( Closure )) dans Pipeline.php line 136
Au Pipeline -> Illuminate \ Pipeline \ {fermeture} ( objet ( Demande ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 32 Pipeline.php
Au Pipeline -> Illuminate \ Routing \ {closure} ( objet ( Requête )) dans ShareErrorsFromSession.php ligne 49
À ShareErrorsFromSession -> handle ( objet ( demande ), objet ( fermeture ))
à Call_user_func_array ( array ( objet ( ShareErrorsFromSession ), 'handle'), array ( objet ( Request ), objet ( Closure )) dans Pipeline.php line 136
Au Pipeline -> Illuminate \ Pipeline \ {fermeture} ( objet ( Demande ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 32 Pipeline.php
Chez Pipeline -> Illuminate \ Routing \ {closure} ( objet ( Request )) dans StartSession.php ligne 64
À StartSession -> gérer ( objet ( demande ), objet ( fermeture ))
à Call_user_func_array ( array ( objet ( StartSession ), 'handle'), array ( objet ( Request ), objet ( Closure )) dans Pipeline.php line 136
Au Pipeline -> Illuminate \ Pipeline \ {fermeture} ( objet ( Demande ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 32 Pipeline.php
Au Pipeline -> Illuminate \ Routing \ {closure} ( objet ( Requête )) dans AddQueuedCookiesToResponse.php ligne 37
À AddQueuedCookiesToResponse -> handle ( objet ( demande ), objet ( fermeture ))
à call_user_func_array ( tableau ( objet ( AddQueuedCookiesToResponse ), 'poignée'), matrice ( objet ( Demande ), objet ( fermeture ))) dans la ligne 136 Pipeline.php
Au Pipeline -> Illuminate \ Pipeline \ {fermeture} ( objet ( Demande ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 32 Pipeline.php
Au Pipeline -> Illuminate \ Routing \ {closure} ( objet ( Requête )) dans EncryptCookies.php ligne 59
Chez EncryptCookies -> handle ( objet ( demande ), objet ( fermeture ))
à Call_user_func_array ( array ( objet ( EncryptCookies ), 'handle'), array ( objet ( Request ), objet ( Closure )) dans Pipeline.php ligne 136
Au Pipeline -> Illuminate \ Pipeline \ {fermeture} ( objet ( Demande ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 32 Pipeline.php
Au Pipeline -> Illuminate \ Routing \ {closure} ( objet ( Requête )) dans CheckForMaintenanceMode.php ligne 44
À CheckForMaintenanceMode -> handle ( objet ( demande ), objet ( fermeture ))
à Call_user_func_array ( array ( objet ( CheckForMaintenanceMode ), 'handle'), array ( objet ( Request ), objet ( Closure )) dans Pipeline.php ligne 136
Au Pipeline -> Illuminate \ Pipeline \ {fermeture} ( objet ( Demande ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 32 Pipeline.php
Chez Pipeline -> Illuminate \ Routing \ {closure} ( objet ( Requête ))
à call_user_func ( objet ( fermeture ), l' objet ( appel )) dans la ligne 103 Pipeline.php
à Pipeline -> puis ( objet ( fermeture )) dans la ligne 132 Kernel.php
À Kernel -> sendRequestThroughRouter ( objet ( demande )) dans la ligne 99 de Kernel.php
Chez Kernel -> handle ( objet ( Request )) dans index.php line 53

**Comment by acamilleri** [comment]
Hi,

Can you copy paste your app/config/database.php
I think the default driver database is not set.

---------
Bonjour,

Je pense que le driver de base de données n'est pas indiqué dans le fichier database.php
Peux-tu copier coller ton fichier app/config/database.php

**Comment by purwolf** [comment]
![capture](https://cloud.githubusercontent.com/assets/29071614/26601650/f2074576-4580-11e7-8675-7d42381b6863.PNG)





<?php

return [

	/*
	|--------------------------------------------------------------------------
	| PDO Fetch Style
	|--------------------------------------------------------------------------
	|
	| By default, database results will be returned as instances of the PHP
	| stdClass object; however, you may desire to retrieve records in an
	| array format for simplicity. Here you can tweak the fetch style.
	|
	*/

	'fetch' => PDO::FETCH_CLASS,

	/*
	|--------------------------------------------------------------------------
	| Default Database Connection Name
	|--------------------------------------------------------------------------
	|
	| Here you may specify which of the database connections below you wish
	| to use as your default connection for all database work. Of course
	| you may use many connections at once using the Database library.
	|
	*/

	'default' => 'mysql',

	/*
	|--------------------------------------------------------------------------
	| Database Connections
	|--------------------------------------------------------------------------
	|
	| Here are each of the database connections setup for your application.
	| Of course, examples of configuring each database platform that is
	| supported by Laravel is shown below to make development simple.
	|
	|
	| All database work in Laravel is done through the PHP PDO facilities
	| so make sure you have the driver for your particular database of
	| choice installed on your machine before you begin development.
	|
	*/

	'connections' => [

		'mysql' => [
			'driver'    => 'mysql',
			/*
			 * These properties are set by the installer and stored in storage/app/database.php
			 */
			//'host'      => env('DB_HOST', 'localhost'),
			//'database'  => env('DB_DATABASE', 'contentify'),
			//'username'  => env('DB_USERNAME', 'root'),
			//'password'  => env('DB_PASSWORD', ''),
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
			'strict'    => false,
		],

		/*
		 * The database types listed below are currently not supported by Contentify.
		 */
		/*
		'sqlite' => [
			'driver'   => 'sqlite',
			'database' => storage_path('database.sqlite'),
			'prefix'   => '',
		],
		'pgsql' => [
			'driver'   => 'pgsql',
			'host'     => env('DB_HOST', 'localhost'),
			'database' => env('DB_DATABASE', 'contentify'),
			'username' => env('DB_USERNAME', 'root'),
			'password' => env('DB_PASSWORD', ''),
			'charset'  => 'utf8',
			'prefix'   => '',
			'schema'   => 'public',
		],

		'sqlsrv' => [
			'driver'   => 'sqlsrv',
			'host'     => env('DB_HOST', 'localhost'),
			'database' => env('DB_DATABASE', 'contentify'),
			'username' => env('DB_USERNAME', 'root'),
			'password' => env('DB_PASSWORD', ''),
			'charset'  => 'utf8',
			'prefix'   => '',
		],
		*/

	],

	/*
	|--------------------------------------------------------------------------
	| Migration Repository Table
	|--------------------------------------------------------------------------
	|
	| This table keeps track of all the migrations that have already run for
	| your application. Using this information, we can determine which of
	| the migrations on disk haven't actually been run in the database.
	|
	*/

	'migrations' => 'migrations',

	/*
	|--------------------------------------------------------------------------
	| Redis Databases
	|--------------------------------------------------------------------------
	|
	| Redis is an open source, fast, and advanced key-value store that also
	| provides a richer set of commands than a typical key-value systems
	| such as APC or Memcached. Laravel makes it easy to dig right in.
	|
	*/

	'redis' => [

		'cluster' => false,

		'default' => [
			'host'     => '127.0.0.1',
			'port'     => 6379,
			'database' => 0,
		],

	],

];

**Comment by purwolf** [comment]
<?php

return [

	/*
	|--------------------------------------------------------------------------
	| PDO Fetch Style
	|--------------------------------------------------------------------------
	|
	| By default, database results will be returned as instances of the PHP
	| stdClass object; however, you may desire to retrieve records in an
	| array format for simplicity. Here you can tweak the fetch style.
	|
	*/

	'fetch' => PDO::FETCH_CLASS,

	/*
	|--------------------------------------------------------------------------
	| Default Database Connection Name
	|--------------------------------------------------------------------------
	|
	| Here you may specify which of the database connections below you wish
	| to use as your default connection for all database work. Of course
	| you may use many connections at once using the Database library.
	|
	*/

	'default' => 'mysql',

	/*
	|--------------------------------------------------------------------------
	| Database Connections
	|--------------------------------------------------------------------------
	|
	| Here are each of the database connections setup for your application.
	| Of course, examples of configuring each database platform that is
	| supported by Laravel is shown below to make development simple.
	|
	|
	| All database work in Laravel is done through the PHP PDO facilities
	| so make sure you have the driver for your particular database of
	| choice installed on your machine before you begin development.
	|
	*/

	'connections' => [

		'mysql' => [
			'driver'    => 'mysql',
			/*
			 * These properties are set by the installer and stored in storage/app/database.php
			 */
			//'host'      => env('DB_HOST', 'localhost'),
			//'database'  => env('DB_DATABASE', 'contentify'),
			//'username'  => env('DB_USERNAME', 'root'),
			//'password'  => env('DB_PASSWORD', ''),
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
			'strict'    => false,
		],

		/*
		 * The database types listed below are currently not supported by Contentify.
		 */
		/*
		'sqlite' => [
			'driver'   => 'sqlite',
			'database' => storage_path('database.sqlite'),
			'prefix'   => '',
		],
		'pgsql' => [
			'driver'   => 'pgsql',
			'host'     => env('DB_HOST', 'localhost'),
			'database' => env('DB_DATABASE', 'contentify'),
			'username' => env('DB_USERNAME', 'root'),
			'password' => env('DB_PASSWORD', ''),
			'charset'  => 'utf8',
			'prefix'   => '',
			'schema'   => 'public',
		],

		'sqlsrv' => [
			'driver'   => 'sqlsrv',
			'host'     => env('DB_HOST', 'localhost'),
			'database' => env('DB_DATABASE', 'contentify'),
			'username' => env('DB_USERNAME', 'root'),
			'password' => env('DB_PASSWORD', ''),
			'charset'  => 'utf8',
			'prefix'   => '',
		],
		*/

	],

	/*
	|--------------------------------------------------------------------------
	| Migration Repository Table
	|--------------------------------------------------------------------------
	|
	| This table keeps track of all the migrations that have already run for
	| your application. Using this information, we can determine which of
	| the migrations on disk haven't actually been run in the database.
	|
	*/

	'migrations' => 'migrations',

	/*
	|--------------------------------------------------------------------------
	| Redis Databases
	|--------------------------------------------------------------------------
	|
	| Redis is an open source, fast, and advanced key-value store that also
	| provides a richer set of commands than a typical key-value systems
	| such as APC or Memcached. Laravel makes it easy to dig right in.
	|
	*/

	'redis' => [

		'cluster' => false,

		'default' => [
			'host'     => '127.0.0.1',
			'port'     => 6379,
			'database' => 0,
		],

	],

];

**Comment by acamilleri** [comment]
Your file looks good, maybe you haven't get installed the php mysql client ? 
-> apt-get install php-mysql

---
Le fichier à l'air correct, le client mysql php est-il installé ?
Il est possible de l'installer avec cette commande:  -> apt-get install php-mysql

**Comment by purwolf** [comment]
je doit l'installer ou  apt-get install php-mysql

**Comment by purwolf** [comment]
seriez vous me l'installez le cms ?
et peux ton le modifié le Template après

**Comment by acamilleri** [comment]
For using apt-get you need ssh access.
For using Contentify, requirement is dedicated server or vps with ssh access.
You can find it in Scaleway or Online.net.
Yes you can make everything you want if you know php and laravel.

-----
Pour l'utilisation d'apt get il faut un accès ssh.
Afin de pouvoir utiliser Contentify dans de bonne condition je vous recommande l'utilisation d'un serveur dédié ou un vps.
Vous pouvez en trouver notamment chez Scaleway (VPS), Online.net (Dédié) etc...
Oui vous pouvez tout modifier avec des connaissances en développement

**Comment by purwolf** [comment]
je suis ici .lws.fr  heberger

**Comment by acamilleri** [comment]
What type of plan you have subscribe at lws ?
I think it's hosting problem and not CMS problem :/

---
Quel plan as-tu souscrit chez lws ?
Je pense que le problème provient de ton offre et non du cms :/

**Comment by chriskonnertz** [comment]
Closed, since this issue is inactive.
