### ISSUE TITLE
Avatar/Portrait Picture not working

### ISSUE THREAD

**Issue by EazYKevin** [Contentify/Contentify#171]
i meen the little picture beside my account name

i have this little bug, ist maybe just me doing something wrong

it seems like when i have no Avatar/Portrait set to my profile, it registers like theres is one

and when i add a Avatar/Portrait it comes up whit the defualt img saying no Avatar/Portrait

**Comment by chriskonnertz** [comment]
Hi,

if you try to upload one of these images, does it appear in this directory? `public/uploads/users`
If not then it might be a problem with permissions.

**Comment by EazYKevin** [comment]
Hi Chris

Yes it dows apear in the public/uploads/users location i have 2 files called 2_avater.jpg and 2_image.jpg

ist like the code show the no avatar std image, when theres an image uploaded, an when you dont have an image uploaded it tries to load the picture that arent there

best regrads 
EazY(eShooting.dk)

**Comment by EazYKevin** [comment]
when picture is uploaded it load this 
background-image: url(http://test.eshooting.dk/public/img/default/no_user.png)

when no picture uploaded it loads this
background-image: url(http://test.eshooting.dk/public/uploads/users/80/)

**Comment by chriskonnertz** [comment]
Ok you are right, this is a bug.

1. Open `Contentify/app/Modules/PhobosTheme/Resources/Views/layout.blade.php` with a text editor.
2. Swap line 63 ( https://github.com/Contentify/Contentify/blob/2.0/app/Modules/PhobosTheme/Resources/Views/layout.blade.php#L63 ) with line 65 ( https://github.com/Contentify/Contentify/blob/2.0/app/Modules/PhobosTheme/Resources/Views/layout.blade.php#L65 )

Does it work?

**Comment by EazYKevin** [comment]
jep thats works

i thougt it was that of a little adjustment, but i couldent find out what files i should look ing :)

thanks for the help
EazY (eShooting.dk)

**Comment by Roldhave** [comment]
what if you use morpheusTheme

**Comment by chriskonnertz** [comment]
It does not have this bug, because it does not display the user picture in the frontend. :)

**Comment by chriskonnertz** [comment]
Bug fixed, issue closed.

Thank you for your feedback, @EazYKevin
