### ISSUE TITLE
Issue after signing in 

### ISSUE THREAD

**Issue by ghost** [Contentify/Contentify#175]
When typing my Email and Password i click login then it says the website refused to connect.

Any help would be great

**Comment by shoostar** [comment]
Have you managed to fix your database connection issue from https://github.com/Contentify/Contentify/issues/174? Until you can connect to your site's database, you're not going to be able to log in, register, or do anything within the backend of the site.

Also, unless you've closed it for a specific reason, I'd advise against closing your own issues before they're resolved (or at least, wait until someone has commented), as they get moved to the "Closed Issues" page, meaning most people won't ever see them :)

**Comment by ghost** [comment]
it was closed for a reason

**Comment by chriskonnertz** [comment]
A mysterious reason. ;)

Well it's okay, if you were able to solve the issue then closing it is legitimate.

**Comment by ghost** [comment]
Yeah i fixed the issue, but i have been running into a lot of problems aka Modules not working news not working so i'll make a post with all my issue
