### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Shootify** [Contentify/Contentify#179]
Hello guys, i have a vps on interservers where i got all my websites, server specs are more than the requirements for contentify needs, however how to is the install process when you storage more sites on your vps? also where can i get themes/templates for it
thank you

**Comment by acamilleri** [comment]
Hello,

You need to create virtualhost on your webserver to point on public folder of your Contentify folder.

Let's Run the installer on your ip or domain name

**Comment by Shootify** [comment]
how to do that?

**Comment by acamilleri** [comment]
1- Create folder in /var/www with name "contentify" and put all file of Contentify in this folder.
2- run "composer install" in folder of Contentify (/var/www/contentify)
3- make virtualhost on your webserver (search on Google how to do that)
4- run installer

**Comment by Shootify** [comment]
do i need to use putty? or just through the ftp?

**Comment by acamilleri** [comment]
Oh yes you need putty ;)

**Comment by Shootify** [comment]
will you please install this on my vps, i have multiples websites running on my server, so i have put all contentify content in a folder call "contentify" on my my public_html

**Comment by chriskonnertz** [comment]
I have closed this issue since it is very old and seems to be no longer active.

However, iIf it is still current you can still add posts here. Or just create a new issue.
