### ISSUE TITLE
[Official] Ideas for the Future

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#18]
> NOTE: This is not a roadmap nor a list of features that are definitely planned for the future! These are just ideas. 
- Replace `Contentify\Vendor\MySqlDump`with a newer, Composer-based package => scheduled
- ✓ Show matches etc. in the events calendar
- Replace the rudimentary image tags implementation with something more adavaned (tags model, tags database table, ...?)
- Uncouple controllers from modules (currently controllers work outside of modules but some classes, especially `Contentify\ModelHandler` expect the calling controller to be part of a module
- Sitemap. Nuff said.
- ✓ Translations for validation etc. (= third party packages)

**Comment by BornLuna** [comment]
Themes :)

**Comment by one337** [comment]
Medals for single users would be great :) especially combined with auto awards

**Comment by shoostar** [comment]
The ability to use OAuth or some similar way for users to quickly/easily register/login using their social media accounts would be awesome! Great work on this project, by the way! :)

**Comment by chriskonnertz** [comment]
Thanks for the ideas so far. 

> It'd be great if admins could publish/un-publish featured content slides (similar to how you handle drafts for news articles), as well as re-order them. That could also mean that you might want to move the slides from the "Permanent Content" menu to the "Daily Content" menu in the admin panel.

Done. https://github.com/Contentify/Contentify/commit/145e209a68605dcc2545008bdc120a7735dec07b

**Comment by chriskonnertz** [comment]
From Twitter user zEnry185:

> Suggest for Contentify2, team layout like HLTV, players, their photo, their stats, and ecc. It will be the best esport cms.GJ

**Comment by dieago** [comment]
I have a really good suggestion.

You could have a "link" accounts section where the 'newswriters' for the website can automatically post their content to facebook and twitter without having to manually do it. I know it's a "lazy" idea however it makes it so much better and quicker to fire out content.

So the idea basically is

News > Published > Link FB and Twitter Accounts > Post to FB and Twitter the newspost title.

**Comment by chriskonnertz** [comment]
Yes thanks, this is good suggestion.

**Comment by GenDorMetie** [comment]
Hi. I think tourney brackets is a good idea :)

**Comment by chriskonnertz** [comment]
But a lot of code. I work for Matcharena, basically a tourney website. So trust my experience, implementing a **simple** tourney system is easy. However if I do that a storm of "can you add this and that" will blow me away. ;) I know a tourney module would  add a lot of value to the CMS but from my present point of view it's too much work.

**Comment by chriskonnertz** [comment]
@BornLuna 

> Themes :)

Contentify 2 will have theme support. That means you can switch between themes in the admin backend. Also there will be more than one default theme to choose from.

**Comment by krysennn** [comment]
> Hi. I think tourney brackets is a good idea :)

Stay tuned, coming soon ;)

**Comment by mA1N** [comment]
Maybe add an option to the stream module to disable streams who arent online in the sidebar. Because it just dont look good. :p

**Comment by Talorifeyden** [comment]
hope theme support will come soon.

another widget/modul idea would be ts-viewer for the sidebar..

**Comment by chriskonnertz** [comment]
> hope theme support will come soon.

The new version of Contentify is almost at beta-state, however I have not much time these days to finish the new theme.

**Comment by chriskonnertz** [comment]
More ideas: https://github.com/Contentify/Contentify/issues/186

**Comment by niclasreich** [comment]
- Add a (!) or a (1) depending on the number of unread messages ontop of the messsage button (or just as a counter behind it)
- Make colours of theme configurable in the backend so they won't get reset after every update when changed in the corresponding .css-file
- in `domain.example/cups/teams/overview/user-id` an option to search through all teams and join them via team-password
- in `domain.example/friends/user-id` an option to search through all users and send a friend request to searched users

**Comment by chriskonnertz** [comment]
Good ideas.

> Make colours of theme configurable in the backend

Yep, this is going to be implemented. Maybe in v2.5.

> in domain.example/cups/teams/overview/user-id an option to search through all teams and join them via team-password - in domain.example/friends/user-id an option to search through all users and send a friend request to searched users

Possible via  `www.example.com/search` (=global search)
