### ISSUE TITLE
Dockerfile for deployments

### ISSUE THREAD

**Issue by caylorme** [Contentify/Contentify#180]
Hey,

just came across your project. Was thinking of deploying this myself and thought it would be nice to have a docker file to ensure a consistent environment across deployments.
I'll create one for you, just creating this issue for tracking progress. I'll update this ticket once I have a PR up.

**Comment by chriskonnertz** [comment]
Hey,

awesome! I habve not worked with Docker yet but I like the idea. Thanks!

**Comment by caylorme** [comment]
@chriskonnertz, does the application currently support environment variables for most configuration parameters? If I have most appropriate environment variables set, is there a way to skip the install.php script?
For schema changes, does this happen automatically?

**Comment by chriskonnertz** [comment]
>  does the application currently support environment variables for most configuration parameters?

I hink I miss the point here. So it is difficult for me to give you an appropriate answer. All I can say is that Contentify does not introduce environment variables. Only Laravel, the framework, does. Maybe this link helps you out: https://laravel.com/docs/5.4/configuration#environment-configuration

>   is there a way to skip the install.php script?

Yes, you can skip the `install.php` script and directly call for example `http://localhost/contentify/pubic/install/`The `isntall.php` script is just a "gate kepper" without any impact on the actual installation.

However, I am afraid that this is not the answer you actual target?

The acutal installation script lives in `contentify/Controllers/InstallController.php`. It is a controller, not a pure class so currently it is not possible to run the installation from the console / shell. But it should be pretty easy to make this possible. Please tell me if you need this, I guess I can implement the changes ad hoc.

**Comment by chriskonnertz** [comment]
I assume that the time has come to close this issue?

**Comment by caylorme** [comment]
If you choose.
I remember running into problems getting the application to work during local development. Long story short, I could never get it to run using your instructions on the wiki.
If you'd like for me to give it another go, and you have a way for me to contact you directly (Slack/IRC?), let me know.

**Comment by chriskonnertz** [comment]
Thank you for commiting your Docker files!
