### ISSUE TITLE
Instalerror

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#181]
Hello, i try to use this CMS, i think is best choice for me!! But i have a problem at instalation. At step 4 i have an error.

ErrorException in InstallController.php line 291:
set_time_limit() has been disabled for security reasons

https://ibb.co/e9d2ua

**Comment by chriskonnertz** [comment]
Hello,

I made a change in the code that should avoid this error: https://github.com/Contentify/Contentify/commit/60b0163ace6d2f993fa950cb3856a8b62c4ba212 Please copy the change to your code (open  contentify/Controllers/InstallController.php with a texteditor, then copy and paste the change, it is in the green line)

Please let me know if the code change solved the problem. :)

**Comment by khalifaone** [comment]
Hello, thank you for email and help, i change that line of code and now
i have new error, maybe the problem is my hosting reseller. Recomand me
a good server to ret some spate to upload Contentify files.  

So, you don't answer my if you are interesed to do something changes for
my in this platform. I need some changes at some points. 

PS: check attach. 

-- 

Cu respect,
CRISTIAN NICULAE
_FOUNDER_ 
E: dota2@d-play.ro 
W: www.d-play.ro [1]  

Links:
------
[1] http://www.d-play.ro
