### ISSUE TITLE
How to create own module?

### ISSUE THREAD

**Issue by Kazuto** [Contentify/Contentify#182]
I'm trying to create a module called "Informations" and duplicated the Partners module and changed every 
"partner" to "information"
"Partner" to "Information"
"partners" to "informations"
"Partners" to "Informations".

And i've created a new table "informations".
[https://pastebin.com/0bzHcthC](url)

But this does not seem to work.

Does someone have a proper guide on how to create a module?

**Comment by chriskonnertz** [comment]
Hi,

your pastebin link does not seem to work?

If your module is no secret, please upload it somewhere then I will test it.

**Comment by Kazuto** [comment]
I've uploaded it to my cloud. https://cloud.kazuto.de/index.php/s/N02kxyoHDfI4zuK

**Comment by chriskonnertz** [comment]
Did you delete this file at least once after you created your module? `storage/app/modules.json` This file is a cache file  with infos about the modules and it needs to be refreshed. When you delete it, it will be re-generated automatically.

Also I had to clear the cache to see the new entry in the navigation of the backend. The easiest way is to delete all files / folöders in `storage/framework/cache`.

Afterwards I was able to see the new entry in the backend navigation. But when I click on it an "permission denied" error is displayed. Accessing a backend module *always* needs privileges. They are stored in the `roles` table in the database. For default modules they are added during the installation of the CMS but of course that is not the case for a new module. One way to deal with this is to add an installer to the module. The "Example" module shows an example for such an installer: `app/Modules/Example/Installer.php` You can just copy it and change the namespace. Installation should be available then and automatically add permissions for super-admins. If you want to set more detailed permissions you can use the `protected $extraPermissions = array();` property wich is inherited from the `ModuleInstaller` class. See: https://github.com/Contentify/Contentify/blob/2.0/contentify/ModuleInstaller.php#L36

(I have also added this text to the wiki: https://github.com/Contentify/Contentify/wiki/Modules#module-permissions )

**Comment by chriskonnertz** [comment]
Btw, thank you for your feedback, I have added a new section to the wiki that describes the process of installing a new module. https://github.com/Contentify/Contentify/wiki/Modules#installing-new-modules
