### ISSUE TITLE
How to embed navigation widget with certain ID?

### ISSUE THREAD

**Issue by Kazuto** [Contentify/Contentify#183]
I've tried everything now but can't seem to get any other navigation to show than the first one created in the backend.

That's what I've tried to far:
@widget('Navigations::Navigation',(3))
@widget('Navigations::Navigation',('3'))
@widget('Navigations::Navigation',[3])
@widget('Navigations::Navigation',['3'])
@widget('Navigations::Navigation','id::3')
@widget('Navigations::Navigation','id=3')
 and so on.

Nothing seems to work.

**Comment by chriskonnertz** [comment]
Hi,

here is a general "guide":
- Try to locate the PHP script of the widget. The general module directory is `app/Modules` so in this case we have to go to `app/Modules/Navigation` . The PHP script of a widget is always in the `Http/Controllers` (sub) directory of a module. So in this case open this file (with a text editor): `app/Modules/Navigation/Http/Controllers/NavigationWidget.php`
- In the code you will find this variable: `$parameters` It contains the ... parameters. Not a real surprise ;)
- You will see that in this case there are two possible parameters: `template` and `id`
- This means you have to call the widget like this: `@widget('Navigations::Navigation', ['id' => 3'])`

**Comment by Kazuto** [comment]
Thanks for the answer but this does not seem to work.

`FatalErrorException in 16e04378815612ce66c156bc130a5f950b7a1bc4.php line 113:
syntax error, unexpected '']); ?>' (T_CONSTANT_ENCAPSED_STRING), expecting ']'`

**Comment by chriskonnertz** [comment]
Sorry, my bad. Try this one:

`@widget('Navigations::Navigation', ['id' => 3])`

I accidentally added a useless `'`.

**Comment by Kazuto** [comment]
Thanks :)
