### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by MLGBeta** [Contentify/Contentify#184]
I am running into various installation errors. Could anyone set this up on my server for me for a little bit of paypal money? if so shoot me an email mlgbetacod@gmail.com

**Comment by chriskonnertz** [comment]
Hello,

sorry for the delay. I your request still up to date?

**Comment by MLGBeta** [comment]
Yes please email me at devinthompson@me.com

**Comment by chriskonnertz** [comment]
Done.
