### ISSUE TITLE
My thoughs and feedback

### ISSUE THREAD

**Issue by Kazuto** [Contentify/Contentify#186]
I'm using Contentify for a few weeks now and as I frontend designer I had some problems with it. Here are my thoughts on making Contentify easier to use and customize to own needs:

- A seperate file for the main content/index page that extends the layout.blade.php instead of having it's content inside it.
   - Widgets would just be displayed were needed instead of extended on each page
   - Creating themes would be a breeze because each page could be the same or completely different
   - (I had to set every widget inside an if clause to be not displayed on every subpage)

- Splitting future and past games widget
- Improved teams backend for each team member **not user**
   - Image/Portrait
   - Social Media Icons (Twitter, Facebook, Twitch, YouTube etc.)
   - Display those informations frontend (member.image, member.social)
- Awards template and widget page
   - Currently no way to display them as a widget
- "About Us" module
   - This would allow for easy customizations without having to use or edit the Custom Page module.
   - Uploading images to this module and giving them a short description
   - Display frontend (e.g. about.text, about.image, about.bio)

**Comment by chriskonnertz** [comment]
Hello,

thank you for you feedback!

> A seperate file for the main content/index page that extends the layout.blade.php instead of having it's content inside it.

The current template/layout/theme implementation is not the best, for sure. It is not very flexible. I have noticed some drawbacks as well. I believe sooner or later the tempalte system will change.

> Improved teams backend for each team member not user

I am not sure if I understand what you are up to. Why does it make sense to have members of a team (on the team page) have an image that differs from their user portrait?

> Social Media Icons (Twitter, Facebook, Twitch, YouTube etc.)

I agree. Two of these are part of the v2.1 update ( https://github.com/Contentify/Contentify/blob/2.1-dev/app/Modules/Teams/Resources/Views/show.blade.php ). I guess it makes sense to also add Twitch and YouTube.

> Splitting future and past games widget

Maybe, or add an option to specify what is displayed.

> Awards template and widget page

Good idea. I guess that is something than can be realised pretty soon.

> About Us" module. This would allow for easy customizations without having to use or edit the Custom Page module.

True. So you believe having a form to customize this page would be a siginifacnt benefit? I am not that sure. You should be able to achive the same result by using the editor and editing the custom page.

**Comment by Kazuto** [comment]
> I am not sure if I understand what you are up to. Why does it make sense to have members of a team (on the team page) have an image that differs from their user portrait?

This way team members don't have to register and everything will be up to the admin. Team members can change quickly and therefore it's easier and faster to change the single team members than deleting and registering a complete new user. Especially if you want to have a team overview you don't just have rectangular images but complete portraits.

> Maybe, or add an option to specify what is displayed.

You can basically decide what to display, but both use the same widget template. Therefore you can't have the past games as a slider and the future games as a list. Both will look the same as it is now.

> True. So you believe having a form to customize this page would be a siginifacnt benefit? I am not that sure. You should be able to achive the same result by using the editor and editing the custom page.

I haven't thought about the page editor and that it can display HTML. That just leaves the `/pages/XYZ` as a small bother for me. Maybe a setting how thoses pages are displayed in the address bar just like Wordpress has.

**Comment by Kazuto** [comment]
> True. So you believe having a form to customize this page would be a siginifacnt benefit? I am not that sure. You should be able to achive the same result by using the editor and editing the custom page.

I've just tried to use the editor for custom pages and it removes every class from HTML elements. Therefore it's not practicable.

**Comment by chriskonnertz** [comment]
> This way team members don't have to register and everything will be up to the admin. Team members can change quickly and therefore it's easier and faster to change the single team members than deleting and registering a complete new user. Especially if you want to have a team overview you don't just have rectangular images but complete portraits.

Okay, got it. 

I understand your desire for this feature know. However, I believe that this feature is something that would rather be a customization for a special use case than something that should be part of the CMS in general. So, following the 80/20 rule ( https://en.wikipedia.org/wiki/Pareto_principle :D ) to me it seems to be too much afford in comparison to the value.

---

Despite of that one I think the other ideas are really inspiring. I don't know *when* they will be implemented but I hope I can realize all of them at some point in time.

**Comment by chriskonnertz** [comment]
I have added an awards widget: 89a2ee6
