### ISSUE TITLE
Coverages 

### ISSUE THREAD

**Issue by SlavenTV** [Contentify/Contentify#187]
Ich würde gerne Coverages a la 99Damage auf unserer Homepage anzeigen bzw. umsetzen.

In wie weit wäre dies momentan schon machbar bzw. wie groß wäre der Aufwand um so etwas umzusetzen?

99Damage Coverages: [https://csgo.99damage.de/de/coverages/](https://csgo.99damage.de/de/coverages/)
Natürlich mit den Unterseiten zu den einzelnen Coverages

**Comment by chriskonnertz** [comment]
Hallo,

out-of-the-box geht das derzeit nicht.

Beziehst du dich nur auf die verlinkte Seite? Wenn ja: Der Aufwand das einzubauen wäre aber relativ gering.

*Ich* könnte das wahrscheinlich in weniger als einer Stunde einbauen. Wenn ihr das selber machen wollt werdet ihr wohl länger benötigen. :P Allerdings bei Fragen würde ich euch natürlich helfen.

Von Vorgehen würde ich Coverages als "Kategorien" für Artikel anlegen und dann denCoverages noch die nötigen Attribute (den Statuts) verpassen.

**Comment by SlavenTV** [comment]
Ne es muss nicht so wie auf der 99Damage seite sein, bin für alternativen offen.

Aber diese Lösung würde mir für den Anhang genügen wenn der Aufwand nicht so hoch wäre.

-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 28.07.17, 20:40, Chris Konnertz <notifications@github.com> schrieb:
Hallo,
out-of-the-box geht das derzeit nicht.
Beziehst du dich nur auf die verlinkte Seite? Wenn ja: Der Aufwand das einzubauen wäre aber relativ gering.
Ich könnte das wahrscheinlich in weniger als einer Stunde einbauen. Wenn ihr das selber machen wollt werdet ihr wohl länger benötigen. :P Allerdings bei Fragen würde ich euch natürlich helfen.
Von Vorgehen würde ich Coverages als "Kategorien" für Artikel anlegen und dann denCoverages noch die nötigen Attribute (den Statuts) verpassen.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Contentify/Contentify","title":"Contentify/Contentify","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Contentify/Contentify"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chriskonnertz in #187: Hallo,\r\n\r\nout-of-the-box geht das derzeit nicht.\r\n\r\nBeziehst du dich nur auf die verlinkte Seite? Wenn ja: Der Aufwand das einzubauen wäre aber relativ gering.\r\n\r\n*Ich* könnte das wahrscheinlich in weniger als einer Stunde einbauen. Wenn ihr das selber machen wollt werdet ihr wohl länger benötigen. :P Allerdings bei Fragen würde ich euch natürlich helfen.\r\n\r\nVon Vorgehen würde ich Coverages als \"Kategorien\" für Artikel anlegen und dann denCoverages noch die nötigen Attribute (den Statuts) verpassen.\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Contentify/Contentify/issues/187#issuecomment-318731912"}}}

**Comment by chriskonnertz** [comment]
Ok ich denke darüber nach.

**Comment by tjoecs** [comment]
Da ich das hier gerade sehe, weiterer Gedankenansatz: Kann nicht nur für externe Coverages interessant sein, sondern auch zum begleiten der eigenen Saison (99LIGA oder sonst. Liga-Event, welches auch gecovert werden soll auf der eigenen Website). Wäre tatsächlich ein sehr geiles Feature.

**Comment by SlavenTV** [comment]
Klar was man damit dann anzeigt ist egal ob das externe oder interne Dinge sind :)
