### ISSUE TITLE
Anzeigefehler Backend News

### ISSUE THREAD

**Issue by SlavenTV** [Contentify/Contentify#190]
Hallo 

Mir ist gerade aufgefallen das ich einen Anzeigefehler im Adminbackend bei dem News Module habe. 
Ich weiß leider nicht wie ich das beheben kann.
Fehlerbild: [http://team-flash.eu/fehler.png](url)

Vll hat jemand eine Idee was das Problem ist.

**Comment by chriskonnertz** [comment]
Hallo,

sehr merkwürdig. Die Farben wurden ja offenbar angepasst, sicher, dass da nicht einfach versehentlich die Textfarbe (`color`) für `select` / `option`-Elemente auf `transparent` oder einen Grauton geändert wurde?

**Comment by chriskonnertz** [comment]
Nachtrag: Habe das nochmal nachgeschaut, also das ist mit recht hoher Wahrscheinlichkeit irgend ein Problem das dir durch Veränderung des Stylings aufgetreten ist. Insofern schwer zu sagen was da los ist, dazu müsste ich Zugang zur LESS/CSS-Datei haben.

**Comment by SlavenTV** [comment]
ich habe aber die original backend.css auch versucht. vll liegt es an der geänderten frontend.css 
Hatte die Tage wenig zeit zum nachgucken
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 28.07.17, 20:30, Chris Konnertz <notifications@github.com> schrieb:
NAchtrag: Habe das nochmal nachgeschaut, also das ist mit recht hoher Wahrscheinlichkeit irgend ein Problem das dir durch Veränderung des Stylings aufgetreten ist. Insofern schwer zu sagen was da los ist, dazu müsste ich Zugang zur LESS/CSS-Datei haben.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Contentify/Contentify","title":"Contentify/Contentify","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Contentify/Contentify"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chriskonnertz in #190: NAchtrag: Habe das nochmal nachgeschaut, also das ist mit recht hoher Wahrscheinlichkeit irgend ein Problem das dir durch Veränderung des Stylings aufgetreten ist. Insofern schwer zu sagen was da los ist, dazu müsste ich Zugang zur LESS/CSS-Datei haben."}],"action":{"name":"View Issue","url":"https://github.com/Contentify/Contentify/issues/190#issuecomment-318729432"}}}

**Comment by chriskonnertz** [comment]
Hm, die frontend.css kommt im Backend nicht zum Tragen, die wird da gar nicht eingebunden: Da gibt's eine ziemliche strenge Trennung, um genau solche Probleme zu vermeiden. Klingt so als hättest du ausschließlich die CSS-Datei(en) verändert, ansonsten hätte ich gesagt, ein Blick in die `resource/assets/less/shared.less` könnte nicht schaden aber so ist das wohl eher nicht zielführend. Von daher wäre es wohl sinnvoll wenn du die backend.css irgendwo hochlädst (oder hier als Gist bei GitHub postest: https://gist.github.com ), dann kann ich die bei mir einspielen und schauen ob ich das Problem so reproduzieren und dann was genaues dazu sagen kann.

**Comment by chriskonnertz** [comment]
PS: Welche Version von Contentify nutzt du überhaupt?

**Comment by SlavenTV** [comment]
Ich nutze die 2.1-dev Version.

Werd dir die css hochladen schnell mom

 

Gesendet: Samstag, 29. Juli 2017 um 20:13 Uhr
Von: "Chris Konnertz" <notifications@github.com>
An: Contentify/Contentify <Contentify@noreply.github.com>
Cc: Slaven27 <Hopperjr@web.de>, Author <author@noreply.github.com>
Betreff: Re: [Contentify/Contentify] Anzeigefehler Backend News (#190)


PS: Welche Version von Contentify nutzt du überhaupt?

**Comment by SlavenTV** [comment]
https://gist.github.com/anonymous/e0af114f1eab5d03edc3e4931786bee7

**Comment by chriskonnertz** [comment]
Okay, die backend.css hat bei mir keine Auswirkung (Opera, Firefox).

![screenshot_color](https://user-images.githubusercontent.com/4319323/28754680-87443448-754a-11e7-9964-ce6c1f2ce255.jpg)

Also an der liegt es nicht. Du kannst aber theoretisch auch selber nachschauen: 
![bild_devtools](https://user-images.githubusercontent.com/4319323/28754697-17415b2a-754b-11e7-9ebd-e038f844fae9.png)
Entwicklertools öffnen z. B. über F12 je nach Browser und das Autor-Dropdown-Element auswählen und dann werden in meinem Beispiel im Opera rechts die CSS-Eigenschaften angezeigt und aus welcher Datei und welcher Zeile sie kommen, also in dem Fall backend.css Zeile 14780.

**Comment by SlavenTV** [comment]
Also ich habe denke ich das Problem gefunden jetzt. Weiß aber nicht wie es beheben kann. 

Es liegt daran das der Text also der Autor nicht an die Auswahlbox übergeben wird. Es wird nur die ID als Value übergeben.  Wenn ich die Zeile über die Entwicklertools anpasse, erscheint der Text direkt in der Box. Siehe Screen

![fehler2](https://user-images.githubusercontent.com/28620056/28831325-8c841514-76d9-11e7-8f38-244135618c22.png)

**Comment by chriskonnertz** [comment]
Sehr merkwürdig.

- Hast du etwas am PHP-Code geändert, dass damit irgendwie, und sei es nur ganz entfernt, zu tun haben könnte?
- Es gibt mehr als 2 registrierte User, richtig? Haben alle User einen Usernamen?
- Du nutzt ein Standardsetup mit einer MySQL-Datenbank (kein Postgre oder so etwas) und einem Apache-Webserver (kein Nginx)?
- Haben sich User über die Steam-Login-Funktion eingeloggt?
- Hast du User gelöscht oder gebannt?
- Kannst du mal einen der namenlosen User als Autor einstellen und speichern? Geht das oder treten irgendwelche Fehler auf?
- Magst du mal einen Blick in den Fehlerlog werfen? Admin-Interface -> Website -> Einstellungen -> Log-Datei

**Comment by SlavenTV** [comment]
Eig hab ich nix bewusst entfernt
Vorallem nicht im Backend

Da hab ich nur die Farben geändert


Ja habe mehrere User die haben alle einen usernamen
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 01.08.17, 18:41, Chris Konnertz <notifications@github.com> schrieb:
Sehr merkwürdig.

Hast du etwas am PHP-Code geändert, dass damit irgendwie, und sei es nur ganz entfernt, zu tun haben könnte?
Es gibt mehr als 2 registrierte User, richtig? Haben alle User einen Usernamen?


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Contentify/Contentify","title":"Contentify/Contentify","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Contentify/Contentify"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chriskonnertz in #190: Sehr merkwürdig.\r\n\r\n- Hast du etwas am PHP-Code geändert, dass damit irgendwie, und sei es nur ganz entfernt, zu tun haben könnte?\r\n- Es gibt mehr als 2 registrierte User, richtig? Haben alle User einen Usernamen?"}],"action":{"name":"View Issue","url":"https://github.com/Contentify/Contentify/issues/190#issuecomment-319427233"}}}

**Comment by chriskonnertz** [comment]
Ist dieses Problem noch von Bedeutung?
