### ISSUE TITLE
Show cups on Homepage

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#191]
Hello, finaly i finish to set all things at this CMS. Now i want to show on homepage CUPS sections, in bottom of slider i want to put that section with incoming events. I search for this code line in all files but i didn;t find. i will attach a screen here!

And second thing is: Can i HIDE video from homepage, and it remain only articles? Now i have all video and articles in homepage, or set a limit number for show (Ex: last 4 articles )
![tesadada](https://user-images.githubusercontent.com/29990653/28662898-643dc62c-72c4-11e7-8e2b-9671973bc555.JPG)

**Comment by chriskonnertz** [comment]
Hello,

1) there are two widgets for cups. First is the "Featured Cup" widget: `App\Modules\Cups\Http\Controllers\FeaturedCupWidget` that displays short infos and a link for alll published cups that are marked as "featured". Second is the "CupsControlWidget" (in the same directory) that allows users to manage their cups. You include a widget in a template with this code (example): `@widget('Cups::FeaturedCup')`

2) Open this PHP script file with a text edior: `app/Modules/News/Http/Controllers/NewsController.php` The code is in the `showStream` method. The easiest way is to uncomment / delete lne 98: `$streamItems[] = $video;` (this is where a video is added to the news stream)

In line 66 / 67 you can change the number of columns and rows:

```
$colums = 2;
$rows = 3;
```

> Attention: This changes might be overwritten if you update to a new version of Contentify in the future!

**Comment by khalifaone** [comment]
Thank you! It works! have a nice day!

**Comment by chriskonnertz** [comment]
Great! Have a nice day as well.
