### ISSUE TITLE
Date & Time

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#194]
How can i change timezone for Bucharest, Romania? I find some topics but nothing corectly.

**Comment by chriskonnertz** [comment]
Hello,

did you change it in the `php.ini` and in `config/app.php`?

**Comment by niclasreich** [comment]
Hello, same issue here. Set the timezone in php.ini to `Europe/Berlin` (also displayed in /admin/config/info in the interface) and in config/app.php to `'timezone' => 'Europe/Berlin',` but still, Contentify hangs one hour behind.

**Edit:** Was an issue with summer-/wintertime. Did `timedatectl set-ntp true` to synchronize the time of my machine with the internet and it is not set up correctly.
