### ISSUE TITLE
Update fail

### ISSUE THREAD

**Issue by Laxeer0** [Contentify/Contentify#197]
When I try to update, the terminal comes out written: PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /var/www/vhosts/k2gaming.it/httpdocs/public/update.php on line 242

**Comment by chriskonnertz** [comment]
Hi,

what PHP version does your server use?

**Comment by chriskonnertz** [comment]
Guess naming a method "print" was not a smart move. :/

**Comment by chriskonnertz** [comment]
Does this help? https://github.com/Contentify/Contentify/commit/98187776a92ea13d8eb36caaa8d0e2f71480395e

**Comment by Laxeer0** [comment]
more error incoming

**Comment by Laxeer0** [comment]
https://pastebin.com/2LCG07U9

**Comment by Laxeer0** [comment]
@chriskonnertz some solution?

**Comment by acamilleri** [comment]
Hi,

what PHP version does your server use?

**Comment by Laxeer0** [comment]
i try with php 5.6.30 and 7.1.7

**Comment by chriskonnertz** [comment]
@Laxeer0 So the error message says that there is not file in "/var/www/vhosts/k2gaming.it/httpdocs/public/../AppBridge.php" which is the same as "/var/www/vhosts/k2gaming.it/httpdocs/AppBridge.php"

Please tell me if this file exists? If it exists, maybe there is a problem with missing permissions?

**Comment by Laxeer0** [comment]
@chriskonnertz don't exist

**Comment by chriskonnertz** [comment]
Okay that is really strange, it should exist as you can see here:
https://github.com/Contentify/Contentify/ or here: https://github.com/Contentify/Contentify/blob/2.1/AppBridge.php
I am suprised that you have the `public/update.php` file but not the `AppBridge.php` file?

**Comment by Laxeer0** [comment]
i resolve

**Comment by chriskonnertz** [comment]
Ok great!
