### ISSUE TITLE
HTTP ERROR 500 before launch install

### ISSUE THREAD

**Issue by AznoYT** [Contentify/Contentify#198]
Hello everyone, in advance sorry for my english because I am French, I come to see you today because I find myself with the following problem: when I click launch install it shows me "HTTP ERROR 500" Look at a may have had the same problem as me and I try to fix them but without success, so thank you in advance for your help

**Comment by chriskonnertz** [comment]
Hello AznoYT

- When / before you clicked on the "launch install" button, was everything green or something red?
- Are you able to take a look at the error log? It is this file: `storage/logs/laravel.log`

**Comment by AznoYT** [comment]
yes everything is green and i have this in the log https://pastebin.com/7ZwBfzHy

**Comment by chriskonnertz** [comment]
Did you download it right here from GitHub by cloning the repository / downlaoding the (pure) source code? If so, did you run the `php composer.phar install` command? If yes, can you runit again please?

The error log contains some error messages about missing files. This is the first time that I see this problem.  I do not know why the mentioned files would be missing, for example this file: `contentify/ServiceProviders/HtmlServiceProvider.php` Does it exist in your installation?
