### ISSUE TITLE
News limit and older news

### ISSUE THREAD

**Issue by ARYX01** [Contentify/Contentify#200]
1) How to increase news limit in homepage?
2) How to add a button at the end that load older news?

**Comment by ARYX01** [comment]
2.1 if is too hard to do that how to add another news page with previous news with img, description etc.
I tried to do that
![main_page1](https://user-images.githubusercontent.com/13236949/29314706-8351a164-81bf-11e7-91ee-920102ab2835.png)
and when I click the 2 nd page botton:
![page2](https://user-images.githubusercontent.com/13236949/29314727-9a55739a-81bf-11e7-87f7-1d75c0ba55f5.png)

**Comment by chriskonnertz** [comment]
Can you please post the code that you have added to display the paginator?

**Comment by chriskonnertz** [comment]
Ok I guess I know how you added it.

**Comment by ARYX01** [comment]
Its the same of the back-end i think, because i copyed the URL from there

**Comment by chriskonnertz** [comment]
Ok. Hmm... I cannot test it right now. :/

You would have to modify the `showOverview` method in the `app/Modules/News/Http/Controllers/NewsController.php` file so that it uses pagination.
This is the official documentation about pagination: https://laravel.com/docs/5.2/pagination
Maybe it is enough to add `->paginate(10)` to the query builder...

And you would have to change the `index` method to:

```
    public function index()
    {
        $this->showOverview();
    }
```

But I am not sure if that really works.

If you try it please let me know if it works.

**Comment by ARYX01** [comment]
So,  have changed the NewsController.php
And added this to Controllers.php:

> <?php

namespace App\Http\Controllers;

use DB;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Show all of the users for the application.
     *
     * @return Response
     */
    public function index()
    {
        $users = DB::table('users')->paginate(10);

        return view('user.index', ['users' => $users]);
    }
}

But when I press the button to go on page 2 load the same news as in page 1(now with image and summary...)

**Comment by chriskonnertz** [comment]
Hah sorry you got me wrong. :p 

I followed my own guide and it works with one little difference.
Here are all the steps I did:

1. I opened  `app/Modules/News/Resources/Views/show_overview.blade.php` and added this line at the end: `{{ $newsCollection->links() }}` This will render the paginator. You should replace your code with mine if your differs.

2. I opened `app/Modules/News/Http/Controllers/NewsController`. In line 51/52 there was this code:

```
$newsCollection = News::published()->where('internal', '<=', $hasAccess)->filter()
            ->orderBy('created_at', 'DESC')->take(5)->get();
```

I replaced it with:

```
$newsCollection = News::published()->where('internal', '<=', $hasAccess)->filter()
            ->orderBy('created_at', 'DESC')->paginate(5);
```

That's it. Works great. Of course you can choose different limit than 5.

But do not forget, your changes might be overwritten if you update to version 2.2.

**Comment by ARYX01** [comment]
It didn't render
![image](https://user-images.githubusercontent.com/13236949/29752000-177fc754-8b56-11e7-8cc4-5c4e668e7616.png)
I did all the steps, I deleted my <12> buttons, but it didn't render the paginator buttons

**Comment by ARYX01** [comment]
I have tryed to replace by buttons(they were in show_stream.blade.php) with {{ $newsCollection->links() }} but then it says: Undefined variable: newsCollection (View: /var/www/html/app/Modules/News/Resources/Views/show_stream.blade.php)

**Comment by chriskonnertz** [comment]
I assumed you are in show_overview.blade.php

**Comment by chriskonnertz** [comment]
In `show_stream.blade.php` it is `$streamItems` instead of `$newsCollection` but it will not work I guess. 

I suggest not to use show_stream but show_overview instead. In `app/Http/routes.php` line 22 search for "showStream" and repalce it with "searchOverview".

**Comment by ARYX01** [comment]
aaaa ok thanks searchOverview or showOverview? I guess showOverview works

**Comment by chriskonnertz** [comment]
Yep, `showOverview`.
