### ISSUE TITLE
News Articles Cause Query Errors

### ISSUE THREAD

**Issue by Shaneajm** [Contentify/Contentify#201]
Hello! I'm running Contentify 2.1 on Windows (hosted locally using XAMPP to demo it) and when I click on published news articles in the admin panel I get these two errors.

> 1/2: ModelNotFoundException in Builder.php line 303:
No query results for model [App\Modules\News\News].

> 2/2: NotFoundHttpException in Handler.php line 103:
No query results for model [App\Modules\News\News]. 

I also don't see any published articles on the home page, I'm assuming it's because of this issue.

Thanks!

**Comment by chriskonnertz** [comment]
Hello,

I have tested it and on my installation it works fine.

Is there anything "special" about your installation? Did you change or add any code? Did you upgrade from v2.0 or did you install a fresh copy of v2.1? Did you use `git clone` to download it? Do you use an Apache server with a MySQL database or maybe something else, something more exotic? May you please post your error log? It is in `storage/logs/laravel.log`

**Comment by Shaneajm** [comment]
I cloned a fresh install directly from GitKraken into my XAMPP install directory. I do use apache2 with MySQL and PhpMyAdmin. I attached my log file below.

[larvel-log.txt](https://github.com/Contentify/Contentify/files/1244095/larvel-log.txt)

**Comment by chriskonnertz** [comment]
Interesting: The exceptions are not mentioned in the log file. Instead there are a lot of issues with the database. Are you sure that Contentify can connect to the database? The last error is: `SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)`

**Comment by Bambutscha1337** [comment]
I have the same issue and I also get the same last error. how can i solve it. The install.php in the public server worked fine. 

I can also not open the impressum Site. It will give me the same issue with handler.php 103

How can i solve the Problem?

**Comment by chriskonnertz** [comment]
Probably fixed in Contentify 2.

=> https://github.com/Contentify/Contentify/releases/tag/v2.3

If the issues are still up-to-date with v2.3 please let me know.
