### ISSUE TITLE
Points system

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#205]
Hello!
Its possible to put a point system?
When a player / team win a cup earn 10 points. its posible to add this feature? Maybe an option wich i can set personal their winings. Like a deposit & withdraw points.

**Comment by chriskonnertz** [comment]
Hi,

well yes it is *possible*. Is this a feature request? Or do you want to implement this on your own?

**Comment by MohsinAhmedShaikh** [comment]
Its a nice idea, it should be in contentify next update that would be good as you can see there are other esports websites we found this function in there ... and i also think it will be good if those points make a clan ranking system from these point system from overall tournaments and cups etc, for example check www.gosugamers.net we can see the matches and on going matches live stream and i also request that we can make aaplication form from admin panel so user can fill and submit it .thanks

**Comment by chriskonnertz** [comment]
Ok. What I can do is this:

> When a player / team win a cup earn 10 points. its posible to add this feature?

Alright. This one should be easy.

**Comment by chriskonnertz** [comment]
I have added the cup points calculation.
- Users / teams get points for winning a cup
- You can set the amout of points in the admin backend in the cups section, default is 10, minimum is 1
- Points will be displayed on the user and the team profiles (if a user/team has more than 0 points)
- Currently there is no direct way to edit the points. However, you can edit them in the database via PHP or via phpMyAdmin or whatever
- I also fixed some general bugs

I commited the code to the v 2.2-dev branch: https://github.com/Contentify/Contentify/commit/ee7452176639f39b2913610ad0376a33ea442bc7

Currently this branch has a lot of bugs so you should be able to test it but other modules will have issues.

**Comment by khalifaone** [comment]
Hello, yes i want to put this on our esports website. 
Tank you for answers and help with new updates.

**Comment by chriskonnertz** [comment]
No problem.
