### ISSUE TITLE
Modules and Impressum

### ISSUE THREAD

**Issue by SN4RX** [Contentify/Contentify#210]
How to remove "forum" from homepage or Impressum? - because when I enter in Impressum this is displayed http://imgur.com/YIU3b2f

**Comment by chriskonnertz** [comment]
Hello,

where exactly do you want to remove it? I believe it would help me a lot if you upload a screenshot.

**Comment by SN4RX** [comment]
Hello,

I'm more specific about it: 

before - http://imgur.com/6rCuKHX

after - http://imgur.com/aPPPNlE

And it's at the bottom of the main page:

SEARCH, SERVERS, GALLERIES, AWARDS, EVENTS, DOWNLOADS

Is there a way to remove these Impressum?

Thank you.

**Comment by SN4RX** [comment]
Can you help?

**Comment by chriskonnertz** [comment]
Hello,

I had no time to take a closer look yet. I will try to catch up on it tomorrow.

**Comment by SN4RX** [comment]
No problem, I will be quietly waiting - besides, I sent a message on the contact email Contentify, can you reply?

**Comment by chriskonnertz** [comment]
Did you manage to solve the problem?

**Comment by SN4RX** [comment]
Yes, I did
