### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by valtro-one** [Contentify/Contentify#211]
Hello,

I've read a few other tickets here and i've tried following the setup guide but i can't fathom out how to get this installed correctly. 

I've uploaded all the contents of contentify to my directory. I've created my .htaccess file which is fine. The issue that i'm having is trying to launch the composer install. I haven't a clue how to do this via my webhost i'm not technically abled to fulfil it myself.

The installation doc is a bit vague on how to set this up. Do i need a virtualhost to do all of this because i'm not sure my hosting provider is able to do this for me. 

Any help would be much appreciated.

**Comment by chriskonnertz** [comment]
Hello,
    
I recommend that you download this archive: https://github.com/Contentify/Contentify/releases/download/v2.1/contentify_2_1.zip
It does include the vendor libraries so you do not have to run the `composer install`command.

**Comment by SN4RX** [comment]
Hello, and if we are talking about installation - why when I install version 2.1 on a website (not VPS) - is the main site after installation is in xxx.xx/public ?

**Comment by valtro-one** [comment]
Hi Chris,

thanks for that it seemed to have worked. My only issue now when i run the installer is that i have the following error: http://prntscr.com/gfbx2y

**Comment by valtro-one** [comment]
Sorry ignore the above it came down to my .htaccess file that i setup so that fixed the above error. 

however when i ran the setup this happened: http://prntscr.com/gfc09d http://prntscr.com/gfc0iu

**Comment by chriskonnertz** [comment]
@snarxcsgo 

> why (...) is the main site after installation is in xxx.xx/public

Technical answer: The idea is to totally hide all internal files from the outside. So you have to configure your web hosting environment so that only the content of the `public` directory is exposed to the outside (= to the web). 

Here is a guide how to use a `.htaccess` file if your hosting environment does not allow you to change the document root: https://github.com/Contentify/Contentify/wiki/Troubleshooting#installation-what-to-do-with-the-public-folder

This section of the installation wiki article is relevant as well: https://github.com/Contentify/Contentify/wiki/Installation#get-contentify

**Comment by chriskonnertz** [comment]
@Sphinxx-uk Most likely not a problem with the CMS bu with you server (configuration). 
You have a MySQL server up & running? You are sure you entered correct connection details?

Google has some suggestion, for example:

>  I had a similar problem and was able to solve it by addressing my mysql with 127.0.0.1 instead of localhost.

From: https://stackoverflow.com/questions/1676688/php-mysql-connection-not-working-2002-no-such-file-or-directory

It is hard to tell what exactly causes this issue.

**Comment by valtro-one** [comment]
@chriskonnertz i'll have another look through the code. 

Weirdly when i refreshed the site came live but when i went to create a custom page the same error cropped up. I'll do some more digging and let you know of my findings.

**Comment by SN4RX** [comment]
@chriskonnertz 

And if I want to https:// how do I have what I have to change?
Do I have to do it after installation or before?

**Comment by chriskonnertz** [comment]
After installation.
