### ISSUE TITLE
Spam register

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#212]
I have a problem with account registration, i think is a spam.  How can i solve this?
![34242342](https://user-images.githubusercontent.com/29990653/29921081-067edf48-8e59-11e7-984e-a011f7a55d6c.JPG)

**Comment by chriskonnertz** [comment]
Hello,

yeah, that looks a lot like a spam bot.

My suggestion is that you use Google ReCAPTCHA. Contentify is prepared for it but you have to do some changes on your own. Here is a step-by-step guide: https://github.com/Contentify/Contentify/wiki/FAQ#how-can-i-use-google-recaptcha-instead-of-the-default-captcha

**Comment by chriskonnertz** [comment]
I have created a new issue to remind me to fully integrate Google ReCAPTCHA. Unfortunately I have no idea when I will be able to implement this.

https://github.com/Contentify/Contentify/issues/217

**Comment by khalifaone** [comment]
I solve this problem :D, thank you again!

**Comment by chriskonnertz** [comment]
Great! :)
