### ISSUE TITLE
Problem after installation..

### ISSUE THREAD

**Issue by SN4RX** [Contentify/Contentify#213]
Hello, I have a purchased web page at home.pl - and when I upload Contentify via FTP, i go to: esportgo.pro/public/install.php - I install Contentify (everything is successfully installed) and redirected me to esportgo.pro/public, should not be so that the home page is located on esportgo.pro instead of esportgo.pro/public?

**Comment by chriskonnertz** [comment]
--> https://github.com/Contentify/Contentify/issues/211#issuecomment-326359575
