### ISSUE TITLE
Bug / Enhancement

### ISSUE THREAD

**Issue by valtro-one** [Contentify/Contentify#214]
Hello,
Is there anyway to increase the character space for the team name from 15 to something greater? http://prntscr.com/gffowq

**Comment by SlavenTV** [comment]
Hi,
u can edit this :)

Take a look in this file: 
../app/Modules/Cups/Team.php

at Line 18:
        **'title'  => 'required|min:3|max:15'**

Change this to:
         **'title'  => 'required|min:3|max:50'**


The Field in the Database is from Typ Varchar(70).

**Comment by chriskonnertz** [comment]
Hi,

yep @Slaven27 you are right. That's it. Fun fact: I experienced the same issue a week and decided to raise the limit to 20.

It is in the deveomplent branch of the next version, 2.2:

https://github.com/Contentify/Contentify/blob/2.2-dev/app/Modules/Cups/Team.php#L18
