### ISSUE TITLE
How to delete Steam login?

### ISSUE THREAD

**Issue by SN4RX** [Contentify/Contentify#216]
Hello, i have question. How to delete Steam login?

**Comment by SN4RX** [comment]
Can you answer this question and others? @chriskonnertz

**Comment by chriskonnertz** [comment]
Hello,

> How to delete Steam login?

What exactly do you want to achieve? Is it enough to hide the login button?

**Comment by SN4RX** [comment]
I just delete the button, can you add me on Skype? - a few days ago I wrote an email to you @chriskonnertz

**Comment by SlavenTV** [comment]
HI,

u can delete the Button on the Frontpage in the Login Section.


```
1.Go to the File: 
../app/Modules/Auth/Resources/Views/widget_login.blade.php

and delete:
    <a class="btn btn-default" href="{{ url('auth/steam') }}" title="STEAM {{ trans('auth::login') }}">{!! HTML::fontIcon('steam') !!}</a>
on Line 6
```
Next 

```
Go the File:
../app/Modules/Auth/Resources/Views/widget_login_classic.blade.php

and delete:
<a class="btn btn-default" href="{{ url('auth/steam') }}">{!! HTML::fontIcon('steam') !!} STEAM {{ trans('auth::login') }}</a>
on Line 12
```

I hope i can help u

**Comment by SN4RX** [comment]
Sorry, but the Steam login appears on the page.

**Comment by SlavenTV** [comment]
No it work fine for me.. 
Can u send me the Link

**Comment by SN4RX** [comment]
https://esportgo.pro

**Comment by chriskonnertz** [comment]
Well but what Slaven27 wrote seems to be right.

**Comment by SlavenTV** [comment]
It was a Line with the Steambutton in the Phobos Theme Layout.php :)

```
../app/Modules/PhobosTheme/Resources/Views/layout.blade.php

Line 95:
<a class="btn btn-default" href="{{ url('auth/steam') }}" title="STEAM {{ trans('auth::login') }}">{!! HTML::fontIcon('steam') !!}</a>
```

Delete and its fine :)

**Comment by chriskonnertz** [comment]
There will be an easier way in version 2.2: It only displays the STEAM login button if the STEAM API key has been set

https://github.com/Contentify/Contentify/commit/2f7379b913567659210130963ae052b9b902bdf5
