### ISSUE TITLE
Captcha does not work

### ISSUE THREAD

**Issue by SN4RX** [Contentify/Contentify#218]
A few days ago it worked, today it does not work.

Screenshot: https://imgur.com/yEAYqsg

**Comment by chriskonnertz** [comment]
Hello,

I do not know why the captcha is not displayed. This bug is new. 
If I will see the bug I will try to fix it but currently I have no idea when it appears.

**Comment by SlavenTV** [comment]
Pls add Recaptcha Captcha and its fine :) see section in wiki

**Comment by chriskonnertz** [comment]
PS This might help to fix the bug: https://github.com/Contentify/Contentify/wiki/Troubleshooting#captcha-image-not-displayed
