### ISSUE TITLE
Change Max. File Size for Download-Module

### ISSUE THREAD

**Issue by tjoecs** [Contentify/Contentify#220]
Moin,
an welcher Stelle kann ich denn die maximale Dateigröße anpassen? Aktuell scheinbar 4MB. Wenn ich eine Datei wähle, die größer ist, wird sie einfach nicht hochgeladen... kommt also kein Fehler. Aber die Datei existiert nachher einfach nicht (der Eintrag jedoch schon in der Download-Sektion).. #

Regards :)

**Comment by chriskonnertz** [comment]
Hallo,

in der `php.ini`. Wo die genau liegt hängt von dem Webserver ab, bspw. in `etc/php7/apache2/php.ini`. 

Zu ändern sind die Werte `upload_max_filesize` und `post_max_size`, die würde ich dann beide z. B. auf `20M`setzen.

**Comment by tjoecs** [comment]
danke dir! schaue ich mal nach!

**Comment by tjoecs** [comment]
Hat übrigens wunderbar geklappt, danke für den Hinweis!

**Comment by chriskonnertz** [comment]
Super, freut mich!
