### ISSUE TITLE
I can not log into my account.

### ISSUE THREAD

**Issue by SN4RX** [Contentify/Contentify#222]
For a few days I can not log in to my account, I do not know what is wrong - I add that as I type the mail and password, there is no information whether the password is incorrect.

Link website:

https://esportgo.pro/auth/login

**Comment by SlavenTV** [comment]
This seems like a bug in the Auth Controller. The Redirect after Login is broken.

**Comment by SN4RX** [comment]
May I ask you to give Skype or something like that? - I have a lot of questions and problems, Chris does not reply I do not know why: /

**Comment by SlavenTV** [comment]
u can add me in Steam and tell me your Probs. I try to helo u
Sacrifice666
--

**Comment by SlavenTV** [comment]
i think this can be closed :)

**Comment by chriskonnertz** [comment]
If there is a bug please let me know.
