### ISSUE TITLE
/public folder and https://

### ISSUE THREAD

**Issue by SN4RX** [Contentify/Contentify#223]
Hello,

I have a problem with SSL security - I would like to add to .htaccess so that after entering the page it was https://esportgo.pro/ instead of esportgo.pro

My .htaccess file looks like this:

RewriteEngine on
RewriteCond %{HTTP_HOST} ^esportgo.pro$ [NC,OR]
RewriteCond %{HTTP_HOST} ^www.esportgo.pro$
RewriteCond %{REQUEST_URI} !public/
RewriteRule (.*) /public/$1 [L]

What should I add to the file so that when it comes to the page was SSL: https://esportgo.pro - everywhere, for example when logging in too.

**Comment by SN4RX** [comment]
@chriskonnertz

**Comment by SN4RX** [comment]
@chriskonnertz refresh

**Comment by chriskonnertz** [comment]
Hi,

so basically what you is:

- Someone navigates to http://esportgo.pro
- There is an automatic redirect to https://esportgo.pro

If that is what you want then I have good news, I think its a good idea to add that and I think I have done this before for a website so I can just re-use that code.

**Comment by chriskonnertz** [comment]
Hi,

implemented these changes. If the HTTPS support is enabled and someone navigates to the landing page via HTTP there will be a redirect to the same page but with HTTPS.

Commit: https://github.com/Contentify/Contentify/commit/b834e70bd7a6c0b2bb416b04f1b8437eae93ffd8
