### ISSUE TITLE
Advertisement Error

### ISSUE THREAD

**Issue by MohsinAhmedShaikh** [Contentify/Contentify#226]
Hello,
i could not make an advertisement got website error . What to do ? 
and Advert Panel also not showing on main page side panel but advert blade is added in phobos theme please help.

another request is in admin/downloads creation can you add outer link to add file also with upload so we can link outer file url in it and  when we edit a file link in downloads its not showing which file is attached to it. 
thanks

**Comment by chriskonnertz** [comment]
Hello,

> i could not make an advertisement got website error

Please send me the error log file. You can send it via email if it does contain any confidential stuff such as passwords. The log is located at `store/logs/Laravel.log`.

I will take a look at you other points soon.

**Comment by MohsinAhmedShaikh** [comment]
somehow it made the advertisement but not showing on main page but i tried to make another advertisment so i got error making it then i read the log it says duplicate entry so i tried to delete the first advertisement then it start error again and i cant make a single advert after that , will send you logs on email

**Comment by chriskonnertz** [comment]
Hey,

thank you for the log file, I think I now understand the problem and I am working on a bug fix.

**Comment by chriskonnertz** [comment]
Fixed the bug by https://github.com/Contentify/Contentify/commit/25a8bb3ddd3b4d218cd64feed326833c73261842


The bug happens during the setup. Since you have an existing installation you either have to reinstall the CMS or you have to edit the database table "adverts" and delete the attribute "slug".
