### ISSUE TITLE
Contentify update 2.1

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#227]
Hello, i saw your update and i want to make that update for may website. How can i make this update? just replacing the old files with new files?

**Comment by chriskonnertz** [comment]
Hello,

here is a short guide: https://github.com/Contentify/Contentify#update

**Do not forget to make a backup from all the files before you update!**

**Comment by khalifaone** [comment]
I follow that guide and look what it happen.

![erorupdate](https://user-images.githubusercontent.com/29990653/30828594-d2537efc-a246-11e7-8cb1-83be9d6276cd.JPG)

**Comment by chriskonnertz** [comment]
Hey,

please open  `storage/app/databse.ini` and update the database connection details there.
