### ISSUE TITLE
News / Pages / Navigation & More Wont Populate

### ISSUE THREAD

**Issue by AbstraktGaming** [Contentify/Contentify#228]
When I create:

News
Pages
Navigations

They don't populate on the website at all.

Also, When I create a Team, I don't have the option to choose what country they are from Defaulting all of my teams to the European Union. I am however able to choose a country for Opponents?

I'm Also unsure how to edit the Footer menu & Top menu?

**Comment by AbstraktGaming** [comment]
http://www.teamabstrakt.com

**Comment by chriskonnertz** [comment]
Hello,

> When I create: News, Pages, Navigations
> They don't populate on the website at all.

So on http://www.teamabstrakt.com you have added some news, right? And you did check the "published" checkbox? ( Just asking the "welcome to our support" questions. :P )

> Also, When I create a Team, I don't have the option to choose what country they are from Defaulting 
> all of my teams to the European Union. I am however able to choose a country for Opponents?

This is not built-in. So you have teams from more than one country and you want add flags to them? I guess I can implement that.

> I'm Also unsure how to edit the Footer menu & Top menu?

You have to edit the main template of the chosen theme. For example, open this file:
`Contentify/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php`

Navigation in the header section: https://github.com/Contentify/Contentify/blob/2.1/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php#L60

Footer section: https://github.com/Contentify/Contentify/blob/2.1/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php#L142

> Note: If you modify this template your changes might be overwritten if youi update to version 2.2 in the future!

**Comment by AbstraktGaming** [comment]
News:
Yes It's published. I have also noticed that when my cache is cleared, and first visit the website, the news shows. Once it's clicked, it disappears and is no longer accessible.

Pages & Navigations:
This wasn't mentioned in your reply, but when I create pages or navigation, none of which populate at all.

Team Flags:
yes it would be nice to implement. Even if it's not implemented, it defaults teams to European Union. Which is not where we are located.

Footer: Thank you for the information. I will see how this works out.

**Comment by ryan9mm** [comment]
@AbstraktGaming  I figured out how to get to the custom pages assuming you are running LAMP stack with PHP 7.0:
 
First note the Page ID from the admin side. 
Your URL to type into your browser will be yoursite.com/pages/1 <-- the number of the page ID. These pages are generated via the Contentify script and pulled from the database. No actual file is created.

As for the navigation it does not work. You have to manually add them to the layout.blade.php files as specified above.

And as for the news: If you're using PHP 7.0 on your server you will need to install the following package as it is not by defualt:
`sudo apt-get install php7.0-xml`
Then restart your apache2 server:
`service apache2 restart`

@chriskonnertz  please correct me if I'm wrong but navigations is not working yet? Maybe add a "Pages" link and then add custom pages to a drop down? Just a suggestion...
Also, I wonder if some of these types of issues we're having has to do with PHP 7.0...?

**Comment by chriskonnertz** [comment]
> Also, When I create a Team, I don't have the option to choose what country they are from Defaulting all of my teams to the European Union. I am however able to choose a country for Opponents?

This has been included in uhm... v2.6 or earlier.
