### ISSUE TITLE
Editing/Expanding Quick-Access Flags in Text-Editor

### ISSUE THREAD

**Issue by tjoecs** [Contentify/Contentify#229]
Mahlzeit, 
gibt es eine einfache Option, dem System zu sagen, welche Flaggen es beim Klick auf das Flaggen-Icon in der Texteditor-Leiste anzeigen soll? Ich würde die Auswahl gern etwas anpassen!

![flagquickaccess](https://user-images.githubusercontent.com/28227128/30510017-e1a33a46-9abc-11e7-8334-52aac70588f1.jpg)

Gruß

**Comment by chriskonnertz** [comment]
Hallo,

ich würde sagen; Ja die gibt es. Es handelt sich dabei ja um ein Plugin für den CKEditor. Das JS-Script für dieses Plugin liegt hier: `Contentify/public/vendor/ckeditor/plugins/flags/plugin.js`

Hier werden die Flaggen definiert: https://github.com/Contentify/Contentify/blob/2.1/public/vendor/ckeditor/plugins/flags/plugin.js#L14

Das kannst du anpassen.

> Achtung: Diese Änderungen werden möglicherweise durch ein zukünftiges Update des CMS überschrieben. Du solltest daher ein Backup von deinen Anpassungen machen.

**Comment by tjoecs** [comment]
Hi, danke!
Klappt wunderbar.

Für alle, die auch Interesse haben: Im Anschluss ggf. einmal den Browser Cache leeren, dann sind die Flaggen auch aktuell!

**Comment by tjoecs** [comment]
Direkt mal noch ergänzend: Ich habe auch die styles.js gefunden und probiert, einen vordefinierten Style einzufügen. Jedoch war danach das Feld im Editor ausgegraut und nicht mehr zu öffnen.. wie kann ich denn eigene Styles oder CSS-Klassen irgendwie für eine komfortable Schnellauswahl einfügen?

Weil: Schreibe ich für eine div oder einen Absatz die class="" in den Code, und speichere den Post, verschwindet die class-Zuweisung aus dem Code. Das ist etwas schade, weil es bei Aktualisierung einer News dazu führt, dass ich die class wieder händisch reinschreiben muss (jedes mal wenn man die News aktualisiert)

![styles](https://user-images.githubusercontent.com/28227128/30523881-d9831150-9be9-11e7-9705-707263c857d4.png)

**Comment by sNakiex** [comment]
Would it be doable to also implement the WYSIWYG editor into the forum/comments?

**Comment by chriskonnertz** [comment]
Yes. Just adding it is easy. 

But the editor creates HTML code. You would also have to care about what users are or are not allowed to do. How would you prevent them from posting this: `</div></div></div></div></div></div></div></div></div></div></div></div>` This closes all HTML `<div>` tags and probably would destroy the layout of the page.

I have no real solution for these problems so I do not recommend doing this.

I believe the best way is to use an intermediate language such as BBCode or Markdown. Then you can exactly control how user input is rendered to HTML. That is why BBCode is suppoted in comments an forum posts. There is just no BBCode editor added.

One idea is to investigate if CKEditor can be used to output BBCode. Here is a plugin that tries to do that: https://ckeditor.com/addon/bbcode However I do not know it that really works.

**Comment by sNakiex** [comment]
please switch to like https://www.sceditor.com/ it's easier and can output bbcode ;-) ckeditor does have a config flag that turns `<div>` into `<p>` (  CKEDITOR.config.allowedContent = false;  )
See also https://docs.ckeditor.com/#!/guide/dev_advanced_content_filter

**Comment by chriskonnertz** [comment]
That is not an option at the moment. In generally I am open for suggestions but this one I have to reject. I think it would be a fundamental change and I do not want to make that change. 

However, there is nothing holding you back from implementing SCEditor on your website.

**Comment by chriskonnertz** [comment]
@tjoecs 

> Direkt mal noch ergänzend: Ich habe auch die styles.js gefunden und probiert, einen vordefinierten Style einzufügen. Jedoch war danach das Feld im Editor ausgegraut und nicht mehr zu öffnen.. wie kann ich denn eigene Styles oder CSS-Klassen irgendwie für eine komfortable Schnellauswahl einfügen?

Ich habe dein Vorgehen nachgespielt und bei mir klappt das.

1. Die Datei `public/vendor/ckeditor/styles.js` mit einem Texteditor geöffnet
2. Eigenen Style eingefügt der die Klasse "contentify-test" zuweisen soll:
![Image of Yaktocat](http://abload.de/img/style_js_screenshotxkjxu.png)
3. Er steht dann im Editor zur Verfügung, wenn ich Text markiere und den Style zuweise, speicher und neu lade und dann in den HTML-Modus wechsle sehe ich das hier:
`<div class="contentify-test">Hello world!</div>`

**Comment by tjoecs** [comment]
Okay, dann probiere ich es nachher nochmal. Das würde mir die Arbeit erheblich vereinfachen.

Gibt es eigentlich einen Grund dafür, dass manuell in der Code-Ansicht eingetippte Klassenzuweisungen einfach weg sind nach Klick auf speichern? Also er nimmt sie, weil die fertige News ja korrekt aussieht, aber würde ich direkt nochmal auf speichern klicken, wären die Zuweisungen weg.

**Comment by tjoecs** [comment]
perfekt! Funktioniert super. Habe ich wohl einen kleinen Fehler gemacht letztes Mal.
Top!

**Comment by chriskonnertz** [comment]
Schön zu hören!

> Gibt es eigentlich einen Grund dafür, dass manuell in der Code-Ansicht eingetippte Klassenzuweisungen einfach weg sind nach Klick auf speichern? Also er nimmt sie, weil die fertige News ja korrekt aussieht, aber würde ich direkt nochmal auf speichern klicken, wären die Zuweisungen weg.

Klingt erst mal nicht als sollte das so sein, ich schau mir das bei Gelegenheit mal an.
