### ISSUE TITLE
Suggestions / Problems

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#23]
> Problem: demo = is not the default style/theme from the CMS

It's not the default styling but the files of the project can be downlaoded here: http://www.contentify.org/share/contentify_demo.zip

However I understand that it's kind of a cold shower to see the CMS without any styling, just plain Bootstrap.

Maybe it's a good idea to add the styling of the demo website as a default example styling.

> Problem: 'app/modules' vs 'app/Modules' 

There was a bug when running Contentify on Linux servers. Fixed by https://github.com/Contentify/Contentify/commit/180dad83d35462444dc03050c2526bc33aac9435
NOTE: Only fixed in the `master` branch here on git.

> Problem: it is hard to build out from a fresh installation or to get any idea how to build your own nice theme / style.

Okay. Well there is some kind of tutorial featuring how to start: https://github.com/Contentify/Contentify/wiki/Website%20Development

Some of the articles in the wiki are not in a very good shape. If someone has idead how to improve them I'd be glad to read about them.

> Problem: The /public issue

Obviously this is a tripping hazard. The directory structure is preset by Laravel (-> https://github.com/laravel/laravel ). I know it's not very convenient. The solution is to change the webserver's document root so it directly targets the `publi`c directory. So if someone calls for instance `http://example.com/` the webserver looks for the `index.php` in `/var/www/html/public`

**Comment by OfficialJoe** [comment]
Demo Backend Error: https://github.com/OfficialJoe/Contentify-Contribution/blob/master/Demo%20Backend.log

This is caused when I open the admin backend

**Comment by DaBs** [comment]
Suggestion: Themes. See per instance https://github.com/teepluss/laravel-theme. If this was a build in feature that was documented, I think a lot of developers would start using Contentify, and that the ecosystem would grow more rapidly, as you could then have drag-and-drop, installation-independent themes with layouts etc.

**Comment by DaBs** [comment]
Suggestion: Some sort of way of handling drag-and-drop themes. This would make a lot more developers interested, as Contentify could potentially be a revenue income independent of having to create a specific gaming community's website.

**Comment by chriskonnertz** [comment]
@OfficialJoe Sorry for my late answer.

About your problem here: https://github.com/OfficialJoe/Contentify-Contribution/blob/master/Demo%20Backend.log

According to this http://stackoverflow.com/questions/16863156/laravel-4-unserialize-error-at-offset-0-of-32-bytes and that http://stackoverflow.com/questions/28248670/laravel-unserialize-error-at-offset-0-of-355-bytes , have you tried to clear the cache?

**Comment by Heisi2016** [comment]
Hello,

If i want to install the Contenify i have an error " Contentify already has been installed. "


Look at www.lol-network.de/cms/install.php

What is wrong ? 


Other question :

Is there a german language mod ?

**Comment by chriskonnertz** [comment]
Hello,

1. here are some suggestions: https://github.com/Contentify/Contentify/issues/30

2. Yes - German localisation is available.

**Comment by Heisi2016** [comment]
I must copy all folders to the FTP Server or only the public folder ?

**Comment by BornLuna** [comment]
@Heisi2016 All the files

**Comment by Heisi2016** [comment]
Okay... Now : 

I have an error 

QueryException in Connection.php line 651:
SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails (SQL: drop table `users`)


PDOException in Connection.php line 390:
SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails

**Comment by chriskonnertz** [comment]
Do you have phpMyAdmin on this server?

If yes: Mark all tables, then click on delete. In the next step uncheck "Foreign key checking" ("Fremdschlüsselüberprüfung aktivieren").

If no: Then we need to figure out a PHP script that does the work.

**Comment by noscobe** [comment]
hey 
first awesome work i like it 

i have a question 
is it possible to change the twitter youtube and facebook links on the top and the middle of the contentify_demo ?

**Comment by chriskonnertz** [comment]
Hello, 

thanks.

Yes it is. At the moment they are hard coded so you have to open `resources/views/frontend/layout_main.blade.php` and change the links (lines: 67-69 and 147-149).

**Comment by noscobe** [comment]
thanks man i searched for so long :O

**Comment by chriskonnertz** [comment]
No problem :smiley:

**Comment by Saekwer** [comment]
Hello,

If i want to install the Contenify, everything is correct , but when launched the installer, appears the following error:
 
-FatalThrowableError in FileViewFinder.php line 53:
Type error: Argument 2 passed to Illuminate\View\FileViewFinder::__construct() must be of the type array, null given, called in /customers/d/7/3/rleagues.es/httpd.www/play/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php on line 95-

I have corrected the file... but still receive the error ,
 any solution ?
thanks

**Comment by chriskonnertz** [comment]
May you post the whole error description?

**Comment by Saekwer** [comment]
![skrskr](https://cloud.githubusercontent.com/assets/18439909/14580916/b10a0c50-03de-11e6-94f9-8c1b221c21b4.png)

**Comment by Saekwer** [comment]
I changed the laravel folder, but no way , I think it should be server problem...
Thanks

**Comment by chriskonnertz** [comment]
Kinda. Because I have never seen this bug before and I do not know how to reproduce it.

**Comment by chriskonnertz** [comment]
Workaround: Skip the setup. Use this MySQL database dump instead: https://gist.github.com/chriskonnertz/1cea818c4b78a5d26fd513e67b4533b3

(Delete this file: `storage/app/.install` so Contentify think it has been installed properly)

**Comment by Cook93v** [comment]
Hello i french user and i need to add french language how to do

**Comment by chriskonnertz** [comment]
Hello,

French ist included by default.  You do not need to install or enable it. What yo u might want to do is log in and then go to your account settings and ensure that your interface language is set to French.

**Comment by Cook93v** [comment]
Thanks you i have a another question, I would like to add a radio to the
cms how can I do?

2018-03-30 12:40 GMT+02:00 Chris Konnertz <notifications@github.com>:

**Comment by Cook93v** [comment]
I would like replace the forum for xenforo how can i do ?

2018-03-30 17:59 GMT+02:00 Max Demoon <aizencook@gmail.com>:
