### ISSUE TITLE
Mapveto CS:GO

### ISSUE THREAD

**Issue by SN4RX** [Contentify/Contentify#230]
Hello, I have a suggestion - what do you want to add in the latest version of Contentify - mapveto CS:GO? I'm more specific about this: http://mapvote.16mb.com/

I would like to get it because it creates a sports league on Contentify and needs it.

**Comment by chriskonnertz** [comment]
Hello,

thank you for your proposal. To be honest this seems to be a pretty individual requirement. 
Here is the thing: The cup system of Contentify is a solid base but it is not perfect. It is very minimalistic. I have some experience with CMS made for leagues and there is almost endless space for ideas and improvements. This is why it has been decided to keep things simple at Contentify's cup system. 

If you want to build a league on top of Contentify you either have to implement the features that you misson your own or it might sense to use something more specialised as a base, for example LeagueScript: https://www.leaguescript.com/en/
