### ISSUE TITLE
No hint path defined for [THEMENAME]

### ISSUE THREAD

**Issue by sNakiex** [Contentify/Contentify#231]
I have created a copy of the Morpheus theme and put it in a new folder, changed the module.json to reflect the name.

After removing all the cache files and the modules.json 
i get the following error: 

No hint path defined for [THEMENAME]

**Comment by chriskonnertz** [comment]
Hello,

that means the CMS does not know the path (directory) of the theme where it stores its templates.

If the copy of the original code does not include any secrest stuff would mind to upload it somewhere so I can download it and test it?

**Comment by sNakiex** [comment]
Hi, i forgot to change the ThemeServiceProvider to reflect the new name.
My fault!

**Comment by chriskonnertz** [comment]
Ok :D
