### ISSUE TITLE
Non-secure Login form

### ISSUE THREAD

**Issue by LDierolf** [Contentify/Contentify#232]
First of all Gday! I really appreciate your work!

So when I installed my Lets Encrypt Certificates everything works like a charm via HTTPS. 
But I noticed that the Login Form gets flagged as unsecure. I managed to findout why:

The URL in the Login Form where it POSTs the Form to is still http. Did i miss something troughout the installation?

Any help is greatly appreciated
![bildschirmfoto-2017-09-20-um-23 30 14](https://user-images.githubusercontent.com/2833119/30668739-07861f24-9e5c-11e7-9195-86369d9aa9e4.jpg)

**Comment by LDierolf** [comment]
Okay i Found the Problem, you have to activate the HTTPS option in the Settings Panel.

**Comment by chriskonnertz** [comment]
Yes, that is true.
