### ISSUE TITLE
Discord Server in server list.

### ISSUE THREAD

**Issue by sNakiex** [Contentify/Contentify#233]
Would it not make sense to allow people to add their discord servers to the server list?
See https://blog.discordapp.com/add-the-discord-widget-to-your-site-d45ffcd718c6

**Comment by chriskonnertz** [comment]
Hi,

how would you integrate this into Contentify? I understand it is basically HTML code that is auto-generated and that you copy and paste in the HTML code of the website. So what do you think would be the best way to make it easy for website owners to add it to their websites?

**Comment by sNakiex** [comment]
Hi, you could use the discord API: https://discordapp.com/developers/docs/resources/guild#get-guild

This way you can make it seem part of the website instead of using the generic discord HTML widget.

You should the server name, amount of members and the region and that's it. 👍

**Comment by chriskonnertz** [comment]
Update (2019): Since Discord has become a very important player in the communication field, this is a very relevant suggestion.
