### ISSUE TITLE
[Old] Contentify 3

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#234]
Feature List:

- New image system (hashed paths etc.)
- Use markdown in comments and forum posts (_maybe_)
- Laravel 5.5 (requires PHP 7, has LTS)
- Bootstrap 4
- Full support of PHP 7 (type etc.)
- Color adjustment? # 32c5d2 / # 13b1cd ...
- Form builder? (Text area with/without  WYSIWYG, simple text fields, check/radioboxes, file upload)

_Note: There is no schedule. Conentify 3 will definitely not come in 2017._

**Comment by Fatal1tyOfficial** [comment]
In Contentify 3, could you add a new ladder?

Could you model this ladder? 

https://i.imgur.com/aJdKUJE.png

**Comment by chriskonnertz** [comment]
This is not a ladder. It's a tournament system. It should work the same way Contentify's cup module does.

**Comment by markovvv** [comment]
Is there a list of all the new/fixed features that will come with v3 ?

**Comment by chriskonnertz** [comment]
@markovvv Well, the initial post in this issue... is the list. :D This issue is meant as a reminder. There is not a real plan yet.

**Comment by tjoecs** [comment]
Vielleicht das Implementieren von Font Awesome Symbolen von Haus aus? Anstelle der Sonderzeiten-Funktion jetzt, oder zusätzlich.

**Comment by sNakiex** [comment]
Please make sure you check file uploads, for mime type and limit it to png,jpg,jpeg,gif for avatar/user pic upload.

An option to delete users would be great aswell, maybe a ip banning option?

**Comment by SalomanKane** [comment]
Hätte auch ein paar Vorschläge für zukünftige Versionen

- WYSIWYG Editor für Textbereiche (im Newseditor ja bereits vorhanden)
- Bei der Serverübersicht ein Optionales Textfeld für Infos oder Serverbanner.
- Integrierte TS ³ Schnittstelle für einen Viewer wie z.B. bei DZCP
- Navigationspunkte im Backend verwalten
- Lightbox-Ansicht bei den Galeriebildern
- Galerienavigation - Pfeile nach Links und recht sollten das Hauptbild UND die Vorschau bewegen
- Kompakte darstellung der Galerie( Name - Anzahl Bilder) Titel verlinkt zur Galerie
- Kategorie Bilder for Downloadkaegorien (Optional)
- Im Backend für Downloads ein Textfeld für externe Downloadlinks einfügen

**Comment by chriskonnertz** [comment]
> WYSIWYG Editor für Textbereiche (im Newseditor ja bereits vorhanden)

Wie genau meinst du das?

> Bei der Serverübersicht ein Optionales Textfeld für Infos oder Serverbanner.

Gute Idee, wird in v2.2 enthalten sein ( https://github.com/Contentify/Contentify/commit/19d1379eb3e139c96c8ee516e82fc8c749d21727 ).

**Comment by SalomanKane** [comment]
WYSIWYG nutzt du ja bereit beim Newserstellen (Müsste der CKEditor sein) Den Editor auch für z.B. das Forum. Mit BB-Codes können die meisten nicht mehr umgehen^^

PS: Hab meinen Ideen noch was hinzugefügt, weiß aber das dass nicht so einfach ist^^

**Comment by chriskonnertz** [comment]
@markovvv

> Is there a list of all the new/fixed features that will come with v3 ?

Now there is a small list. This list only contains the "big" changes that definetly will not be made in 2.x. More will be added in the next months.

The reason why there is no bigger list is that 3.0 is *not* the next version, the next version is 2.4 maybe followed by 2.5. Both of them will add new features so some ideas might be implemented in these versions, some might be scheduled for 3.0.

**Comment by chriskonnertz** [comment]
@SalomanKane 

> WYSIWYG Editor für Textbereiche

Für v2.4 geplant.

> Navigationspunkte im Backend verwalten

Ich weiß was du meinst und sehe es auch so dass in die Richtung was eingebaut werden sollte. Ich weiß aber noch nicht konkret wie das aussehen wird.

> Kategorie Bilder for Downloadkaegorien (Optional)
> Im Backend für Downloads ein Textfeld für externe Downloadlinks einfügen

Klingt sinnvoll.

> Integrierte TS ³ Schnittstelle für einen Viewer wie z.B. bei DZCP

Dazu sage ich nicht nein, das wurde außer von dir auch von einigen anderen gewünscht. Irgendwann kann das bestimmt kommen - es hat aber derzeit keine hohe Priorität. Es gibt halt eine lange Liste von Dingen die _noch_ wichtiger sind.  Eine sehr, sehr lange Liste :D Ich würde die gerne schnell abarbeiten denn darauf sind viele gute Ideen die schon teilweise inzwischen seit 1-2 Jahren auf eine Umsetzung warten - aber es geht nur eins nach dem anderen und manches ( ->  TS ) muss da leider warten.

> weiß aber das dass nicht so einfach ist^^

Was das Zeitmangagement angeht: Ja, leider stimmt das. Was die Komplexität angeht: Da ist jetzt nichts bei was sehr schwer ist. Die Navi-Sache, da muss ich noch eine gute Lösung finden aber da ist auch ein Problem, dass ich der Suche nach einer Lösung derzeit einfach keine Prio einräumen kann - vielleicht ist es auch gar nicht so schwer und ich habe mich bisher nur noch nicht genug damit beschäftigt um das einschätzen zu können.

**Comment by chriskonnertz** [comment]
Closing this one and recreating it here: https://github.com/Contentify/Contentify/issues/451
