### ISSUE TITLE
Database Issue

### ISSUE THREAD

**Issue by jwstv** [Contentify/Contentify#235]
I’m having an issue after creating my database, the error that comes up is:

FatalThrowableError in Migrator.php line 335:
Class 'MigrationCartalystSentinel' not found

I’m 99% sure the database is correct

**Comment by chriskonnertz** [comment]
Hello,

this issue is covered by a section in the troubleshooting chapter of the wiki: 
https://github.com/Contentify/Contentify/wiki/Troubleshooting#installation-error-message-fatalerrorexception-in-migratorphp

**Comment by jwstv** [comment]
Thanks for the quick response. I have tried deleting migrations, then databases. Neither had worked, still continue to get the same error.

**Comment by jwstv** [comment]
@chriskonnertz So I have redone it and now get this error:

PDOException in Connector.php line 55:
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

The migration error happens when I go back and try to redo the database.

**Comment by ryan9mm** [comment]
@jwstv Where you running your install at? Digital Ocean? Linode?

**Comment by jwstv** [comment]
@ryan9mm I'm running it on a web host.. Currently I'm just using ElHostingServices since I had a free chance too. Later, once I got to mess around with Contentify I was going to upgrade to a better host.

**Comment by chriskonnertz** [comment]
So basically you are just testing it? If this really is just a test you might post the URL of your website here so we can take a look.

> PDOException in Connector.php line 55:
> SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

This means Contentify tries to connect to the database with invalid credentials. They are saved in this file: `storage/app/database.ini`

**Comment by jwstv** [comment]
TrueRespect.gg
