### ISSUE TITLE
MatchScore Colors in Filter View

### ISSUE THREAD

**Issue by tjoecs** [Contentify/Contentify#236]
Mahlzeit,

gibt es eine Möglichkeit, in der Filteransicht der Matches das Ergebnis auch in der definierten Farbe anzeigen zu lassen? Standardmäßig sind die Ergebnisse ja einfach in Standard-Schriftfarbe, und ignorieren die Colorcodes. Ich fände es schöner, wenn die Ansicht auch auf die Farben zugreifen würde.

Weiterhin: In der Team-Detail Ansicht werden ja die zugehören Awards und Matches aufgelistet. Leider chronologisch falsch, es beginnt also immer mit dem ältesten. Das führt dazu, dass nach (standardmäßig) 5 Spielen die aktuellen Ergebnisse nicht dort stehen, sondern eben immer die ältesten 5. Das finde ich schade, habe aber nirgends die Sortierung gefunden (nehme an wäre einfach ein desc oder asc Wert).

Wäre schön, wenn zu den zwei Sachen noch ein Tipp kommt, wie ich das hinbiegen kann :)

**Comment by tjoecs** [comment]
Da du es als Bug geflagged hast, nehme ich mal an, meinst du die Sortierung der Items in der Team Detail Ansicht? Kann ich das irgendwie per Workaround beheben bis es mal gefixt wird? :) dann kann ich nämlich die Anzahl der angezeigten Matches wieder reduzieren, hab die aktuell auf 20 bzw 30 damit ich alle sehe...

**Comment by chriskonnertz** [comment]
Hallo, @tjoecs ,

leider ist dieses Ticket 2017 offenbar komplett untergegangen.

Dafür möchte ich mich entschuldigen.

Die Punkte, die du ansprichst, sind sehr relevant. Vermutlich hat das Ticket jetzt für dich keine Bedeutung mehr aber ich flagge es jetzt als dringend sodass es mit hoher Priorität behandelt wird.
So nützen deine Vorschlägen dann wenigstens noch anderen. :+1:

**Comment by DrCha0z** [comment]
Moinsen,

Interessiert mich tatsächlich auch ein wenig. Zumindest die Scores im Archiv das sie Farbig sind. Werde mich da mal dann versuchen und Teile dann gerne mein Ergebnis.

**Comment by chriskonnertz** [comment]
Alles kalr, wäre super, dann kann ich das übernehmen :)

**Comment by DrCha0z** [comment]
Also fals du die Tage vor hast 3.0 zu releasen, dann warte bitte nicht auf den Code hier. Denn den schaffe ich glaub ich doch nicht so schnell wie ich erwartet habe.
