### ISSUE TITLE
Replaced all Images but Header is still not changing

### ISSUE THREAD

**Issue by CardiactV** [Contentify/Contentify#238]
I replaced all images such as favicon and header_logo.png in public/img
but there is still the default contentify header and footer.
How can I change this?
I'm using the Morpheus Theme currently if this is helping.

**Comment by CardiactV** [comment]
Oh grade gesehen das du ja Deutscher bist :)

**Comment by chriskonnertz** [comment]
Hallo,

ja das stimmt. :) 

Bist du zu 100% sicher, dass dein Browser da nichts altes mehr im Cache hat? Drück mal Shift (Umschalt) + F5 um echten Fresh zu erzwingen.

Ansonsten mal Rechtsklick auf ein Bild und dort müsste was stehen wie ungefähr "Bild in neuem Tab öffnen" oder "Bild-Adresse kopieren". Damit kommst du an die URL des Bildes, die einem echten Dateipfad entspricht und somit kannst du das Bild auf der Festplatte anschauen und überprüfen, ob es zu denen gehört, die du geändert hast.

**Comment by CardiactV** [comment]
oh danke umschalt f5 hat geholfen vielen dank! hatte bisher immer nur f5 versucht ^^
Auf jeden Fall Probs für Contentify! Ist ein wirklich gelungenes CMS :)

**Comment by chriskonnertz** [comment]
Danke dir! :)
