### ISSUE TITLE
BUG IN UPLOAD IMAGES MEMBER

### ISSUE THREAD

**Issue by khunerable** [Contentify/Contentify#242]
I found bug in upload images member..

please reply.. thnks

**Comment by chriskonnertz** [comment]
Hello,

I need more information.

**Comment by ARYX01** [comment]
http://zone-h.org/archive/notifier=mirav
firewallgaming.eu/a.html and dotexe.eu/a.html

**Comment by Gicminos** [comment]
In my website somebody ran a PHP file (_edited_).

**Comment by sNakiex** [comment]
Can confirm.. (_edited_)

**Comment by chriskonnertz** [comment]
Thank you for pointing this out, I will try to create a fix for this security issue asap.

**Comment by chriskonnertz** [comment]
Quick and dirty solution: https://github.com/Contentify/Contentify/commit/2be90ae029be878fb010a981b29ef473cbba5c18

I will take a closer look soon.
