### ISSUE TITLE
User verification

### ISSUE THREAD

**Issue by Mrciller** [Contentify/Contentify#243]
How can i make a bot who sends a Email to the User to verificate his Account

**Comment by Mrciller** [comment]
+how can i put adsense on the site

**Comment by chriskonnertz** [comment]
Hello,

> How can i make a bot who sends a Email to the User to verificate his Account

have you tried setting the constant value here https://github.com/Contentify/Contentify/blob/2.1/app/Modules/Auth/Http/Controllers/RegistrationController.php#L13 to false?

> how can i put adsense on the site

I have never used Google AdSense so far. Does it provide you codes for each banner integration? If this is true, you can create new advertisement items and copy+paste that code to the "code" field.

**Comment by Mrciller** [comment]
ok i did it to false but now an admin must aktivate them manually. i asked if there is a bot what send an email with an activation code/link

**Comment by Mrciller** [comment]
+ how do i make the cup start? (set matches and so on)

**Comment by chriskonnertz** [comment]
> ok i did it to false but now an admin must aktivate them manually. i asked if there is a bot what send an email with an activation code/link

No, that is not possible out-of-the-box.

> how do i make the cup start? (set matches and so on)

The cup will start automatically at the start time. (You do not have to press a "start" button.)
