### ISSUE TITLE
reinstalled the server and cant use contentify

### ISSUE THREAD

**Issue by Mrciller** [Contentify/Contentify#244]
wie kann ich einstellen dass ein user wenn er sich registrirt eine email mit einen bestätigungslink bekommt

**Comment by chriskonnertz** [comment]
Hallo,

> i get this error SQLSTATE[42S02]: Base table or view not found: 1146 Table 'contentify2.migrations' doesn't exist
Das hat sich wohl erledigt?

> wie kann ich einstellen dass ein user wenn er sich registrirt eine email mit einen bestätigungslink bekommt

Derzeit ist das so wohl nicht möglich, das müsste programmiert werden. Ist kein Hexenwerk, aber man muss es halt machen:
- User bei Registrierung nicht automatisch aktivieren
- Mail raus mit Aktivierungslink in dem die User-ID sowie ein Aktivierungs-Token enthalten ist, den man halt irgendwo speichern muss (z. B. in der `users` Tabelle in der Datenbank
- Wird der Link aufgerufen, muss es halt einen Controller geben der ihn bearbeiten kann, den übermittelten Token mit Token aus der Datenbank für den User mit der übermittelten User-ID vergleicht und wenn sie übereinstimmen den User aktivert
