### ISSUE TITLE
Cup Undefined variable: firstMatch

### ISSUE THREAD

**Issue by Mrciler** [Contentify/Contentify#246]
Ich bekomme den fehler wenn ich bei einen cup eingeben möchte wer gegen wen spielt oder wird das automatisch nach ner zeit gemacht?

**Comment by chriskonnertz** [comment]
Hallo, 

vorab: Hier ist eine Mini-Dokumentation des Cup-Systems, falls du die noch nicht kennst: https://github.com/Contentify/Contentify/blob/2.1/app/Modules/Cups/Readme.md

Also wenn du einen neuen Cup angelegt hast und es Teilnehmer gibt dann musst du manuell auf den Seeding-Button klicken (in der Hauptübersicht der Cups im Admin-Bereich der dritte Button von links). Dann werden die Teilnehmer zufällig in Slots für die erste Runde gesetzt. D. h. du musst nicht manuell Teilnehmer in Slots setzen. Du kannst allerdings nach dem zufälligen Seeding noch korrigierend eingreifen und das Seeding ändern.

**Comment by chriskonnertz** [comment]
Die Meldung "Undefined variable: firstMatch" sollte nicht erscheinen. Wie genau hast du die erzeugt?

**Comment by Mrciler** [comment]
Wird nacher auch der gameserver angezeigt

Am 30.10.2017 17:18 schrieb "Chris Konnertz" <notifications@github.com>:

**Comment by chriskonnertz** [comment]
Hallo,

wie meinst du das? Das Cup-System hat keine explizite Unterstützung von Gameservern.

**Comment by Mrciler** [comment]
ich meine dass wenn ich einen cup starte dass da ein mapvoting oder die
serverip dasteht

Am 31.10.2017 15:09 schrieb "Chris Konnertz" <notifications@github.com>:

**Comment by chriskonnertz** [comment]
Nein, das ist nicht der Fall. Das ist zu spezifisch für Spiele bei denen Mapvoting gängig ist, außerdem ist mir kein System bekannt mit dem man Server den Matches zuordnen könnte ohne dass es da irgendeine API-Anbindung für gibt. Für Runde 1 mag das ja gehen in dem man einfach einen festen Pool an Servern hat, die zufällig auf die Matches verteilt werden.  Aber ab Runde 2 geht das nicht mehr, Passwörter müssten ja irgendwie automatisch neu generiert werden. 

Ganz klar, das ist viel zu aufwendig. Contentify ist kein Turniersystem, sondern ein CMS mit einem einfachen, integrierten Turniersystem. Es ist weder Ziel noch möglich mit einem reinem Turniersystem mitzuhalten. Wenn du so etwas benötigst, empfehle ich, mal einen Blick auf Premium League Script zu werfen: https://www.leaguescript.com/de/ Oder halt selber Contentify entsprechen anzupassen (umzucoden).
