### ISSUE TITLE
News not showing on Homepage

### ISSUE THREAD

**Issue by Ariuw** [Contentify/Contentify#247]
Hello, 

I've created a new post but it doesn't show on the Main page, what can I do to fix it?

**Comment by Mrciller** [comment]
you must klick at the intern button and featured button

**Comment by Ariuw** [comment]
I did already, it doesn't work @Mrciller

**Comment by chriskonnertz** [comment]
Hello,

please check the "https://github.com/Contentify/Contentify/wiki/Troubleshooting#time--date-problems" section here: https://github.com/Contentify/Contentify/wiki/Troubleshooting#time--date-problems
