### ISSUE TITLE
Updating Website!

### ISSUE THREAD

**Issue by LincePlays** [Contentify/Contentify#249]
Hi!

I change theme color, and favicons, but i dont see any change on the website!

What i need to do to make the changes visual?

And how i can change to spanish?

**Comment by SN4RX** [comment]
ctrl + f5

**Comment by chriskonnertz** [comment]
@LincePlays 

 > I change theme color, and favicons, but i dont see any change on the website! What i need to do to make the changes visual?

That depends on the browser that you use. Your browser caches some data form the website, so you have to tell it that it is time to refresh the cache. 

http://refreshyourcache.com/en/cache/

> And how i can change to spanish?

Spanish is not available.
