### ISSUE TITLE
Comments counter

### ISSUE THREAD

**Issue by romkej** [Contentify/Contentify#25]
Thanks for fix the bug of friends approve! I really like this cms! Now i want to ask u, how can i show comments counter in news widget? :) Thanks for replying!

**Comment by chriskonnertz** [comment]
Hello,

1. Open the widget template `app/Modules/News/Resources/Views/widget.blade.php`
2. Change this line

    <a href="{{ url('news/'.$news->id.'/'.$news->slug) }}">{{ $news->title }}</a>

to

    <a href="{{ url('news/'.$news->id.'/'.$news->slug) }}">{{ $news->title }}</a> ({{ $news->countComments() }} {{ trans('app.comments') }})

**Comment by romkej** [comment]
Thanks for answer! I love this CMS!
