### ISSUE TITLE
Opponent Shorthandle

### ISSUE THREAD

**Issue by tjoecs** [Contentify/Contentify#250]
Hallo,
ich wollte gestern das Limit des Gegner-Shorthandles von 6 auf 10 erhöhen. Die Stelle in der opponents.php habe ich auch gefunden, Er schmeisst auch korrekte Fehler wenn ich z.B. 11 Zeichen setze, dass das Limit 10 sei.

Allerdings kürzt das Eingabefeld im Admin Panel den Wert weiterhin bei 6 Zeichen, wenn ich 7-10 Zeichen eintippe. Muss ich irgendwo noch einen Wert anpassen? Ist die Feldlänge ggf. begrenzt? Oder woran liegt es?

**Comment by chriskonnertz** [comment]
Hallo,

das ist soweit richtig, zusätzlich musst du noch (z. B. mit phpMyAdmin) in der MySQL-Datenbank in der Tabelle "opponents" für das Attribut / die Spalte "short" die Länge des Datentyps VARCHAR von 6 auf 10 erhöhen.

Wenn du kein phpMyAdmin o. ä. hast gehst das auch anders aber das besprechen wir dann.

**Comment by tjoecs** [comment]
phpmyadmin ist mir bestens bekannt, werde ich morgen umsetzen - danke dir!

**Comment by tjoecs** [comment]
So, Änderung vorgenommen.
Funktioniert leider noch nicht, Cache der Website in  storage/framework/cache hatte ich einmal geleert, Browsercache auch. Kürzt immernoch von 10 auf 6.

Nehme an muss den MySQL Server neustarten, oder? Wenn nicht an anderen Stellen noch Änderungen nötig sind, bleibt fast nichts anderes mehr übrig.

**Comment by chriskonnertz** [comment]
Hallo, 

leider habe ich das hier aus den Augen verloren.

Die Lösung ist, dass es doch noch eine Stelle gibt die geändert werden muss:
https://github.com/Contentify/Contentify/blob/2.3/app/Modules/Opponents/Opponent.php#L22

Dort wird die Maximallänge festgelegt.
