### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by Mrciller** [Contentify/Contentify#251]
I need help with the mail funktion every time someone wants to reset´s hi´s passwort there is an error (time out)

**Comment by Mrciller** [comment]
kannst auch gerne in deutsch antworten

**Comment by chriskonnertz** [comment]
Hallo,

bist du sicher, dass die Mail-Einstellungen stimmen? Ich würde erst mal auf ein Probleme mit dem Server bzw. dessen Konfiguration tippen. Der Server muss logischerweise in der Lage sein Mails aus PHP heraus verschicken zu können. Ist _sendmail_ installiert?

Ggf. wäre noch interessant welche Contentify-Version du nutzt, 2.1?

**Comment by Mrciller** [comment]
ja ist. Kann es sein dass das Problem daran liegt dass ich den mailserver auf einen anderen server habe?

**Comment by chriskonnertz** [comment]
Achso, ja das kann sein. Öffne bitte mal diese Datei: `config/mail.php` 
Dort befinden sich die Einstellungen für den Email-Versand. Hier musst du die Daten deines Mailservers angeben, also wahrscheinlich so etwas wie "host", "port", "username" und "password". Ggf. hilft auch die Doku von Laravel (Contentify baut auf dem Framework Laravel auf) weiter: https://laravel.com/docs/5.5/mail
