### ISSUE TITLE
Error Message übersetzen / Problem mit Links im Admininterface

### ISSUE THREAD

**Issue by digloz** [Contentify/Contentify#252]
Hallo,

ich würde gerne wissen, in welcher Datei ich die Fehler Message "ERROR
Sorry, something bad happened. Our website has crashed. Don't worry, we will handle this. In the meantime, make a cup of coffee. And stop crushing our website!" auf Deutsch übersetzen kann.

Außerdem habe ich noch folgendes Problem. Ich habe die Seite zuerst auf einer Subdomain laufen lassen, habe Sie dann verschoben auf die Hauptdomain. Wenn ich im Admininterface bin sind die Links auf der linken Seite alle noch mit der Subdomain davor, die mittigen Icons hingegen laufen normal.

Woran kann das liegen? Muss ich noch irgendwo in einer Datei was umschreiben?
Ebenso finde ich nirgends den Punkt, wo ich die Variabel "validation.required" übersetzen bzw. überhaupt eintragen kann, denn ich sehe diese nur als Rohtext, quasi.

Danke für Deine Hilfe!
@chriskonnertz

**Comment by chriskonnertz** [comment]
Hallo,

> Ich würde gerne wissen, in welcher Datei ich die Fehler Message "ERROR
> Sorry, something bad happened. Our website has crashed. Don't worry, we will handle this. In the > meantime, make a cup of coffee. And stop crushing our website!" auf Deutsch übersetzen kann.

Ja, das ist in der Tat nicht übersetzt. Der Text steht in dieser Datei: `resources/views/error.blade.php` ( https://github.com/Contentify/Contentify/blob/2.1/resources/views/error.blade.php )
Das einfachste ist, wenn du ihn dort einfach änderst. Bei einem Update auf eine neuere Version von Contentify würde diese Datei allerdings möglicherweise überschrieben und du müsstest sie erneut ändern.

> Wenn ich im Admininterface bin sind die Links auf der linken Seite alle noch mit der Subdomain davor, die mittigen Icons hingegen laufen normal.

Zwei Dinge:
1: Öffne mal diese Datei:  `config/app.php ` und gehe zu Zeile 63 ( https://github.com/Contentify/Contentify/blob/2.1/config/app.php#L63 ) Schau ob die URL dort der Domain entspricht, wenn nicht ändere sie mal.
2. Es hat (außerdem) mit caching zu tun,  die URLs werden einmalig generiert und dann im Cache gespeichert, d. h. du musst den Cache leeren, bspw. in dem du alle Ordner/Dateien in `storage/framework/views/` ( https://github.com/Contentify/Contentify/tree/2.1/storage/framework/views ) löschst.

> Ebenso finde ich nirgends den Punkt, wo ich die Variabel "validation.required" übersetzen bzw. überhaupt eintragen kann, denn ich sehe diese nur als Rohtext, quasi.

`resources/lang/en/validation.php` ( https://github.com/Contentify/Contentify/blob/2.1/resources/lang/en/validation.php#L60 )
Hier hat jemand die gesamte Datei übersetzt: https://github.com/caouecs/Laravel-lang/tree/master/src/de

**Comment by digloz** [comment]
Hat super geklappt. Übrigens noch ein Punkt wo es nicht übersetzt ist: Die Fehlermeldung, dass man nicht angemeldet ist ;-)

**Comment by chriskonnertz** [comment]
Danke für den Hinweis! Wurde aufgenommen.
