### ISSUE TITLE
Fehler beim News Datum

### ISSUE THREAD

**Issue by digloz** [Contentify/Contentify#253]
Wenn man eine News anschaut aktualisiert sich (zumindest bei uns) das Datum auf das aktuelle - d.h. das Erstellungsdatum wird täglich angepasst und ist somit nicht dem Ursprung entsprechend.

@chriskonnertz

**Comment by chriskonnertz** [comment]
Von diesem Problem habe ich schon gehört, habe aber Probleme es zu reproduzieren. Derzeit ist mir daher auch keine Lösung bekannt.

**Comment by SalomanKane** [comment]
Den Fehler habe ich ebenfalls, mit einer ganz frischen Contentify installation

**Comment by chriskonnertz** [comment]
Läuft bei euch vermutlich auf einem Linux?

**Comment by SalomanKane** [comment]
Jup, Ubuntu 16.04
Auf deiner Demoseite ist das Datum auch immer tagesaktuell^^

**Comment by marcelkuhla** [comment]
Auf dem Demoseite liegt es aber, daran dass sich die Datenbank alle 30min neu baut, denke ich.

**Comment by marcelkuhla** [comment]
Habe gerade erst bemerkt, dass es auf meiner Seite das selbe ist :)

Ich denke fast, dass es irgendwie mit dieser Funktion zu tun hat:

https://github.com/Contentify/Contentify/blob/d30507ef9be9289e7b43650e552fa30737c1b2de/app/Modules/News/News.php#L62-L71

Weil ich habe mir das News Module mal genauer angesehen und das ist in diesem Fall eig. die einzige Frontend Datei, die auf die News zugreift und gleichzeitig einen aktuellen Timestamp verlangt.

**Comment by kamohy** [comment]
geht mal in die config/app.php

dort könnt ihr UTC suchen
Zeile: 89

Setzt da mal stattdessen CET ein

UTC ist der Nullpunkt *quasi*
CET steht für europe-berlin

Dann sollten die zeiten eigentlich stimmen.

**Comment by kamohy** [comment]
also in der version 2.5 (beta) die ich habe, hab ich es gefixt bekommen.
ist halt auf updatet_at eingestellt, das problem ist aber, das er scheinbar beim auslesen der db, einen neuen timestamp setzt.
Ich hab das updatet_ im News-modul gegen published_at ausgetauscht, nun wird es richtig angezeigt.
Dauert goth sei dank nicht all zu lang, das zu fixxen.
