### ISSUE TITLE
/public/install not found [GER]

### ISSUE THREAD

**Issue by LikeLuc** [Contentify/Contentify#255]
![404](https://user-images.githubusercontent.com/31854058/32910087-9b4ae5ea-cb08-11e7-95ad-2bacd4b3d26b.PNG)

Hey,
after the install script has finished I opend my hompage goes to /public/install.php
clicked next and got the Error 404, what can I do.

best regards
LikeLuc

**Comment by LikeLuc** [comment]
Okay, it was my bad... sorry

**Comment by chriskonnertz** [comment]
No problem. :)
