### ISSUE TITLE
More Brackets

### ISSUE THREAD

**Issue by Mrciller** [Contentify/Contentify#256]
Könntest du vielleicht eine Brackett Auswahl machen wie zum beispiel Schweizersystem oder ein System wie 99Damage hat?

**Comment by chriskonnertz** [comment]
Hallo,

ehrlich gesagt, im Moment nicht. So ein Turnier/Liga/Ladder-System ist eine ziemlich große Nummer, daher wollte ich es erst gar nicht einbauen weil klar war, man damit nicht die Wünsche aller erfüllen ohne dass man permanent daran arbeitet und es immer mehr und mehr erweitert, was aber den Rahmen eines CMS sprengen würde. Daher gilt für diesen Bereich, dass ich dort keine neuen Features einbaue.
