### ISSUE TITLE
Vendor folder and .installed script missing

### ISSUE THREAD

**Issue by daZiton** [Contentify/Contentify#257]
Hey chriskonnertz,

in my opinion the vendor folder is missing in the main directrory and also
the .installed script in the /storage/app directory?

I fixed the problem with the vendor folder but when i try to launch the install, it bring me to /puplic/install.
This directory doesn't exist?!

Thanks in advanced!

Kannst mir natürlich auch in deutsch antworten :-D

**Comment by Mrciller** [comment]
hast du es über den Installer oder über Zip download geholt?

**Comment by daZiton** [comment]
Ich hab das Repository per zip heruntergeladen, direkt ausm git.

Das die .installed fehlt ist korrekt habe ich mittlerweile auch verstanden, weil über die wird geprüft ob bereits installiert wurde. 

Dennoch lande ich über den Button "Launch installer" bei public/install. Das Verzeichnis gibt es einfach nicht.

**Comment by chriskonnertz** [comment]
Hallo,

Kurzantwort: Es gibt einmal das was von GitHub kommt, das ist (absichtlich) ohne den vendor-Ordner - der muss dann mit Composer  https://getcomposer.org/ herunter geladen werden - und einmal das, was als "fertiger" Download über die Website heruntergeladen werden kann.
