### ISSUE TITLE
Installation Webhosting ohne vollen Server Zugriff

### ISSUE THREAD

**Issue by SalomanKane** [Contentify/Contentify#258]
Vor Weg ein Klasse System Hut ab.

Auf meinem Webhosting Vertrag scheitere ich immer an der Installation. Kann ich irgendwo nachprüfen ob mein Webhosting Provider alle Voraussetzung erfüllt? Bzw. Gibt es direkt bei der Contentify-Installation eine genauere Prüfung als die Abfrage am Anfang der Installation?

**Comment by chriskonnertz** [comment]
Hallo,

> Vor Weg ein Klasse System Hut ab.

Danke für das Lob. :)

>  Kann ich irgendwo nachprüfen ob mein Webhosting Provider alle Voraussetzung erfüllt?

Du könntest einen Link zu dem Webhosting-Paket, das du nutzt, posten, sofern du das öffentlich bekanntmachen kannst. Dann schaue ich mir das mal an, vielleicht kann ich dann direkt was dazu sagen.

> Bzw. Gibt es direkt bei der Contentify-Installation eine genauere Prüfung als die Abfrage am Anfang der Installation?

Nein, gibt es nicht. Die Überprüfungen können/sollen noch etwas ausgebaut werden, aber leider sind dem in der Praxis Grenzen gesetzt. Einfach weil es verschiedene mögliche Umgebungen gibt. Meistens dürfte es ein Apache unter Linux, vielleicht einem Ubuntu, mit MySQL sein. Kann aber auch MariaDB sein. Oder eine andere Linux-Distri. Oder Windows. Oder nginx statt Apache. Und selbst wenn es erstgenanntes Szenario ist, ist unvorhersehbar, wie es konfiguriert ist, welche Rechte die PHP-Skripte haben usw. Letztlich gibt es zu viele Variablen als dass alle Voraussetzungen geprüft werden können.

Ansonsten, um dem konkreten Problem auf die Spur zu kommen: Hast du dir den Error-Log von Apache und Contentify (in `storage/logs/laravel.txt`) angeschaut? Da könnte was hilfreiches drin stehen.

**Comment by SalomanKane** [comment]
Die Idee mit dem Error Log im Storage Verzeichnis ist gut, hatte ich garnicht aufm Schirm. 

Hosting-Produkt wäre dieses: https://www.netcup.de/bestellen/produkt.php?produkt=1288

**Comment by chriskonnertz** [comment]
Ich habe mir die Infos zu dem Hosting-Paket angeschaut. Ich habe nichts gefunden das ein Problem wäre, aber leider heißt das ja nicht, dass es dennoch - dort nicht dokumentierte - Einschränkungen gibt.

Du könntest bei deinem Hoster nachfragen ob das Hosting-Paket das PHP-Framework Laravel unterstützt. Wenn das der Fall ist, funktioniert Contentify, da Contentify auf Laravel aufbaut.

**Comment by chriskonnertz** [comment]
> Bzw. Gibt es direkt bei der Contentify-Installation eine genauere Prüfung als die Abfrage am Anfang der Installation?

Hab noch mal was ergänzt. Um das zu übernehmen, die Datei `public/install.php` auf diesen Stand aktualisieren: https://github.com/Contentify/Contentify/blob/2.2-dev/public/install.php

(Sollte es eine zuvor nicht dagewesene Meldung bezüglich der PHP-Version geben, so kann sie ignoriert werden.)

**Comment by SalomanKane** [comment]
Habe die install.php wie angegeben geändert und sah auf den ersten Blick gut aus
https://prnt.sc/hk5miq

Danach kam aber der Fehler **PDOException in Connector.php line 55: SQLSTATE[HY000] [2002] No such file or directory** https://prnt.sc/hk5o8mIch bin mir nicht ganz Sicher, aber könnte es damit zusammmenhängen das der mySQL Server und Webspace auf unterschiedlichen Servern liegen. Mit localhost klappt es damit nicht sondern ich muss eine ander IP und einen anderen Port angben. Nur scheint in der database.ini garkeine abfrage des Ports vorhanden zu sein.

**Comment by chriskonnertz** [comment]
> bin mir nicht ganz Sicher, aber könnte es damit zusammmenhängen das der mySQL Server und Webspace auf unterschiedlichen Servern liegen

Kurz und knapp: Ja. Da du ja "localhost" nutzt und nicht die IP des DB-Servers.

> Nur scheint in der database.ini garkeine abfrage des Ports vorhanden zu sein.

Ja, das ist richtig, da die Angabe in den meisten Fällen nicht notwendig ist. 
Lösung: Bitte die Datei `config/database.ini` mit einem Texteditor öffnen. In Zeile 58 müsste stehen: `'port'      => env('DB_PORT', '3306'),` Das bitte ändern in `'port'      => 12345,`, nur statt 12345 dann den passenden Port.

**Comment by SalomanKane** [comment]
Das ich localhost genutzt hätte ist niht ganz korrekt Chris, ich hatte im Install die Felder mit IP, Name, User und PW gefüllt. In der Fehlermeldung stehen aber die Default Werte. Ist das normal?

in der `config/database.php` ist kein Eintrag `env('DB_PORT', '3306'),` 
Die existierenden env Einträge sind im Code auch alle ausgeklammert

Lediglich am ende bei den Einträgen für Redis DB ist eine Port angabe

Edit: Nachdem die ich mal auf die `databse.php` von deiner dev 2.2 genommen habe ist in der Fehlermeldung zwar der richtige Port aber trotz korrekter Eingaben laut Fehlermeldung falscher Host, falscher DB Name und falsche Username .
Unter `storage/app/database.ini` sind allerdings die richtigen werte Eingetragen werden aber anscheinend nicht übermittelt http://prntscr.com/hkfqjb

**Comment by SalomanKane** [comment]
Kann geschlossen werden. Habs mit dem Webspace aufgegeben und jetzt mit nem eigenen Server für Contentify^^

**Comment by chriskonnertz** [comment]
Okay. Hast du schon einen angemietet? Ansonsten teste ich gerade einen sehr günstigen VServer. Schaut bislang sehr gut aus damit und ich denke den werde ich zukünftig als allgemeine Empfehlung angeben.

**Comment by SalomanKane** [comment]
Ich hatte noch einen VServer der mich 1,99€ im Monat kostet. der lief leer und jetzt eben mit contentify. Wollte aber erst wissen ob es beim Webhosting von netcup geht. Beim Server onhne Probleme wie es aussieht

**Comment by chriskonnertz** [comment]
Ok, verstehe.
