### ISSUE TITLE
steam login

### ISSUE THREAD

**Issue by Mrciller** [Contentify/Contentify#259]
der Steam login funktioniert zurzeit nicht. Wenn ein user Beim Steam Login sich registrieren will und er nach der Steamsseite zurückgeleitet wird  kommt eine fehlermeldung dass der User nicht erstellt werden konnte. Bitte um hilfe :smile: :+1:

**Comment by chriskonnertz** [comment]
Hallo,

danke für den Hinweis. Schaue ich mir umgehend an.

Einen API-Key hast du eingetragen? https://github.com/Contentify/Contentify/blob/2.1/config/steam-auth.php#L12

Ansonsten kannst du die STEAM-API-Library die Contentify nutzt aktualisieren:
- `composer.json` mit einem Texteditor öffnen -> https://github.com/Contentify/Contentify/blob/2.1/composer.json#L18
- ` "invisnik/laravel-steam-auth": "2.*"` ändern in ` "invisnik/laravel-steam-auth": "3.*"`
- `composer update invisnik/laravel-steam-auth` auf der Konsole ausführen. Das geht entweder direkt, wenn Composer global installiert ist. Ansonsten `composer.phar` downloaden https://getcomposer.org/download/1.5.5/composer.phar und ins Contentify-Verzeichnis legen und dann per Konsole ausführen: `php composer.phar update invisnik/laravel-steam-auth` (ggf. `php` ersetzen durch Pfad zur ausführbaren PHP-Datei)

**Comment by chriskonnertz** [comment]
Ich kann heute leider nichts weiter dazu herausfinden, da ich mich erst um ein paar andere Probleme kümmern muss.

**Comment by chriskonnertz** [comment]
Bei mir funktioniert der STEAM-Login einwandfrei.

**Comment by Mrciller** [comment]
bei mir funktioniert es leider immer noch nicht D:

**Comment by chriskonnertz** [comment]
Einen API-Key hast du eingetragen? https://github.com/Contentify/Contentify/blob/2.1/config/steam-auth.php#L12

**Comment by Mrciller** [comment]
Ja

Am 11.12.2017 18:16 schrieb "Chris Konnertz" <notifications@github.com>:

**Comment by chriskonnertz** [comment]
Besteht die Möglichkeit, dass ich direkten Zugang zu dem Server bekomme? Anders fällt mir kein effizienter Weg ein wie ich das Problem weiter untersuchen könnte da es bei mir nicht auftritt. 

Falls ja, bitte ich um eine Email an contact@contentify.org dann können wir auf diesem Weg alles weitere besprechen.

**Comment by Mrciller** [comment]
habe dir eine email geschickt
