### ISSUE TITLE
Cant delete News

### ISSUE THREAD

**Issue by SalomanKane** [Contentify/Contentify#260]
Beim löschen von News kommt die Fehlermeldung 
```
Exception in ModelHandler.php line 599:
Error: Model App\Modules\News\News is not modifiable.
```
Die News ansich werden trotzdem gelöscht, die Frage ist nur wo die Fehlermeldung ihren Ursprung hat
https://prnt.sc/hmeusk

**Comment by chriskonnertz** [comment]
Hallo,

welche Version von Contentify hast du dabei verwendet?

**Comment by SalomanKane** [comment]
Die Version 2.1 die Zum Download angeboten wird

**Comment by chriskonnertz** [comment]
Derzeit kann ich den Fehler nicht reproduzieren. Da die 2.2er-Version bald erscheinen wird werde ich das Problem bis dahin erst mal ruhen lassen da es dort vielleicht schon behoben wurde.

**Comment by SalomanKane** [comment]
Alles klar^^
