### ISSUE TITLE
install no found??

### ISSUE THREAD

**Issue by nowahhh** [Contentify/Contentify#261]
Hi everyone, I have an unusual problem.

I unpacked everything in my host, put the folder permissions at 7777

launching

http://provaproleague.altervista.org/public/install.php

all green

I press launches and can not find the page !!

How do I solve?

**Comment by SalomanKane** [comment]
check for missing files. Maybe some Background libs are not supportet by altervista. I Got this message only when files are missing.

**Comment by nowahhh** [comment]
in the zip folder there is no "install" folder! just install.php in folder PUBBLIC
maybe it's my host that is not good .. do you know a free host to try this cms?

I also have a paid host, where my site is now hosted, it's called OVH, do you know if it works on this HOST?

**Comment by chriskonnertz** [comment]
Hello nowahhh,

this is a routing problem. "install" is not a real folder, it is a route (a virtual folder). Do you have Apache? Then you have to enable the mod_rewrite module.

> You will also need a MySQL Database and it's recommended to activate Apache's mod_rewrite module (or Nginx' HttpRewriteModule). To activate mod_rewrite on a Debian destribution, execute sudo a2enmod rewrite. Usually you also have to allow the .htaccess file to override standard website configs.

https://github.com/Contentify/Contentify/wiki/Installation

**Comment by nowahhh** [comment]
i have Apache and the module active.

this is my htaccess

**<IfModule mod_rewrite.c>
<IfModule mod_negotiation.c>
Options -MultiViews
</IfModule>

RewriteEngine On
RewriteBase /pubblic/

# Redirect Trailing Slashes...
RewriteRule ^(.*)/$ /$1 [L,R=301]

# Handle Front Controller...
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
</IfModule>

# # av:PHP-RG
php_flag register_globals on**


is rounting problem? lol when do you plan to fix this problem?

**Comment by chriskonnertz** [comment]
Maybe my post was ambiguous: This is most likely not a bug of the CMS but an issue with your Apache configuration. Therefore it is not a bug we can fix.

In general I consider configuration issues "beyond the border" of our support. It is impossible to support all the possible hosting environments so this is more or less a problem that you have to solve on your own or with the help of your server / webspace hoster. So one idea is that you ask your hoster for support or Apache. Here is a link to an Apache board: https://community.apachefriends.org/f/

Also note that this most likely is not an issue with the CMS but with the underlying PHP framework, Laravel. So you also might read the documentation of Laravel ( https://laravel.com/docs/5.5#installation ) or ask for help in the semi-offical Laravel board: https://laracasts.com/discuss

Also make sure that you have checked the documentation of Contentify ( https://github.com/Contentify/Contentify/wiki ) including the troubleshooting section ( https://github.com/Contentify/Contentify/wiki/Troubleshooting ). You may also check other issues ( https://github.com/Contentify/Contentify/issues ) - maybe someone else had this problem as well.

I know that this answer is not very satisfactory but Contentify is a small open source software that does not have enough capacity to provide unlimited support. We are working on one or even multiple solutions for this problem. But currently we cannot fix your Apache issues.

Sorry if we lose you at this point - but please remember that Contentify is not a commercial software created by a rich company that earns millions of dollars with this software.

**Comment by nowahhh** [comment]
I saw the demo and if it works well I could also pay for this CMS, I thank you for your reply!

Only one question my host is OVH, do you know if it works there?

Do you know a free host where are you sure it works?

**Comment by nowahhh** [comment]
another question and I swear then I will pay someone to do it! the .htaccess file what should it contain? do you have a test .htaccess to show me?

**Comment by SalomanKane** [comment]
For Example my htaccess file
`<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
`
I dont think Contentify will run on a freehost. The most dosnt Support the PHP extensions. If you want to know if OVH works ask the Support of OVH about the requirements. With an VPS/Root you can be sure it will works with the right coniguration of the server

**Comment by chriskonnertz** [comment]
> I saw the demo and if it works well I could also pay for this CMS, I thank you for your reply!

I plan to create a solution that offers web hosting for a very low price. This is one of the solutions that I mentioned in my previous comment. I am aware that the hosting / installtion thing is too difficult. But I do not know any way to make it more accessible.

> Only one question my host is OVH, do you know if it works there?

I you men a **vs** / **vps** (viirtual [private] server) / **cloud** server hosted by OVH? Then yes, that should work: https://github.com/Contentify/Contentify/issues/58#issuecomment-218265994

> Do you know a free host where are you sure it works?

No. I don'T know if there is any free hoster that supports Laravel.

>  If you want to know if OVH works ask the Support of OVH about the requirements. With an VPS/Root you can be sure it will works with the right coniguration of the server

Exactly.
