### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Shootify** [Contentify/Contentify#263]
Hello, what are the requirements to install this cms?
i have a VPS 

CPU | Common KVM processor \| Cores: 1
-- | --
Operating system | Ubuntu 16.04 (64-Bit)
Web server | Apache/2.4.18 (Ubuntu)
PHP version | 7.0.22-0ubuntu0.16.04.1
MySQL version | 5.5.5-10.0.31-MariaDB-0ubuntu0.16.04.2
FTP server | ProFTPD 1.3.5a
Database administration | phpMyAdmin 4.7.5

should be ok?

**Comment by chriskonnertz** [comment]
Hello,

yes, these specifications that you have listed fullfil the requirements of Contentify.

However, there are more requirements, for example PHP extensions: https://github.com/Contentify/Contentify/wiki/Installation#server-requirements

Since you have a VPS this is not a big thing, because if one of these extensions is missing you are able to install it.

**Comment by Shootify** [comment]
How to install on vps when it got websites running already? mean, on the publichtml folder, how to redirect the installation to the contentify folder, i have vps running ubuntu. sorry noob question
PS:  I sent you  an email!

**Comment by chriskonnertz** [comment]
So you want to have two websites running on your Apache? (It's possible :) )

**Comment by Shootify** [comment]
Well i have a Vps that i use to run my websites (2 joomla cms), so each
website has its own folder, so wondering how to install it, would you
install it for me?

**Comment by chriskonnertz** [comment]
> would you install it for me?

Kinda, but not these days. I want to create a general solution, not an individual.

> Well i have a Vps that i use to run my websites (2 joomla cms), so each website has its own folder, so wondering how to install it

Well, first thing, this is not a question of installation I believe but of the server configuration. 
So just upload it somewhere to your server and then you have to create a new vhost entry in your Apache config file for the new website.

https://www.digitalocean.com/community/questions/is-it-possible-to-install-laravel-alongside-other-websites-on-localhost

**Comment by Shootify** [comment]
im not a servers savy, i know how to install regular websites cms and
stuff, but this one is kinda confusing, also i dont have digital ocean... i
would like to use contentify... would be cool if you can make the
installation kinda user friendly or something that will help a lot... thank
you for replying

**Comment by chriskonnertz** [comment]
I work on a solution.

**Comment by Shootify** [comment]
any new solution chris? thanks

**Comment by chriskonnertz** [comment]
Unfortunately I am not able to give you an update on this topic. I feel like GabeN talking about Half Life 3. :/

**Comment by Shootify** [comment]
haha, would you help me installing it?

**Comment by Shootify** [comment]
hey chris help me installing contentify on my vps plz,... i just dont wanna
mess my current websites, my vps is using Ubuntu with latest PHP. Let me
know if you can. thanks

**Comment by chriskonnertz** [comment]
Closing this ticket since it is quite old.

> I work on a solution.

This is still a valid statement. However, no update yet.
