### ISSUE TITLE
Ein paar Fragen / A few Questions

### ISSUE THREAD

**Issue by SalomanKane** [Contentify/Contentify#265]
DE:
- Im Backend gibt es die Möglichkeit eine Navigation zu erstellen, mit welchem Code lässt sie sich im Layout nutzen? Das selbe bei erstelltem Custom Content
- Gibt es eine Funktion Blockeinträge im Layout als Liste auszugeben?
- ist es Möglich den Editor von den News ins Forum zu übernehmen für etwas mehr Komfort?

ENG: (Sry, iam not a nativ Speaker/writer)
- At the Backend can i see the possibility to create a Navigation, wich Code is needed to include it to the Layout? The same question for Customcontent
- is there a function to get blog entry a a list?
- is i possible to geet the Edior from News inside the Forum to get a bit more comfy?

Wünsche schonmal ein frohes neues Jahr
Wish a happy new year

**Comment by chriskonnertz** [comment]
Hallo,

> Im Backend gibt es die Möglichkeit eine Navigation zu erstellen, mit welchem Code lässt sie sich im Layout nutzen?

Habe dazu kurz eben geschrieben: https://github.com/Contentify/Contentify/wiki/Built-In-Modules#navigations

>  Das selbe bei erstelltem Custom Content

Probier mal das selbe wie oben aber als Code das hier: `@widget('Pages::Fragment', ['id' => 123])`

> Gibt es eine Funktion Blockeinträge im Layout als Liste auszugeben?

Bin mir nicht ganz sicher was du meinst, denke aber die Antwort lautet: Nein, nicht nativ. Lässt sich eventuell aber einfach machen.

> ist es Möglich den Editor von den News ins Forum zu übernehmen für etwas mehr Komfort?

Theoretisch ja, definitiv. Praktisch ist das "von offizieller Seite" nicht vorgesehen.
Hier findest du mehr dazu: https://github.com/Contentify/Contentify/issues/229#issuecomment-331404817

> Sry, iam not a nativ Speaker/writer 

Kein Problem. :)

> Wünsche schonmal ein frohes neues Jahr

Danke, dir auch!

**Comment by SalomanKane** [comment]
Auch wenn die Frage etwas blöd ist, wieso ist im Forum so ein Altbackender Editor verbaut wenn für News, Blogs und Custom Content ein Editor verbaut ist der modernsten Ansprüchen gerecht wird.

Auf die schnelle fällt mir selbst nur ein CMS ein das ebenfalls einen alten BBCode Editor nutzt und das ist Webspell. Da reden wir aber auch von einem gut 10 Jahre altem Sourcecode. Mit "von offizieller Seite" meinst du die Entwickler des Editors oder?

Deine Bedenken bezüglich der HTML ausgabe kann ich verstehen, bin auch verwirrt das CKeditor das nicht als Optionale Möglichkeit bietet eie z.B. TinymCE wird aber wohl sein gründe haben. 
Dann wird Contentify wohl erstmal als reines Versuchsobjekt bei mir online bleiben. 
Meine Member haben sie alle massiv wegen dem Forum beschwert. Sind halt nicht so Dinos wie wir die mit BBCodes groß geworden sind^^

**Comment by SalomanKane** [comment]
Ist es normal das bei der Benutzerverwaltung im Backend keine Möglichkeit zum löschen sondern nur zum editieren gegeben ist?

**Comment by SlavenTV** [comment]
Das ist so gewollt.
Durch löschen von benutzern kann es zu Salat kommen
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 29.12.17, 15:45, SalomanKane <notifications@github.com> schrieb:
Ist es normal das bei der Benutzerverwaltung im Backend keine Möglichkeit zum löschen sondern nur zum editieren gegeben ist?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Contentify/Contentify","title":"Contentify/Contentify","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Contentify/Contentify"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SalomanKane in #265: Ist es normal das bei der Benutzerverwaltung im Backend keine Möglichkeit zum löschen sondern nur zum editieren gegeben ist?"}],"action":{"name":"View Issue","url":"https://github.com/Contentify/Contentify/issues/265#issuecomment-354454660"}}}

**Comment by chriskonnertz** [comment]
> Auch wenn die Frage etwas blöd ist, wieso ist im Forum so ein Altbackender Editor verbaut wenn für News, Blogs und Custom Content ein Editor verbaut ist der modernsten Ansprüchen gerecht wird.

Also kurz gesagt du hast recht, das ist nicht optimal derzeit. Ich hab das mal in die neue ToDo-Liste aufgenommen: https://github.com/Contentify/Contentify/issues/264

> Auf die schnelle fällt mir selbst nur ein CMS ein das ebenfalls einen alten BBCode Editor nutzt und das ist Webspell. 
Vor ein paar Jahren gab es nicht so wirkliche Alternativen zu BBCode. Erst seit relativ kurzem hat sich Markdown https://de.wikipedia.org/wiki/Markdown ja ansatzwesie durchgesetzt. Was halt wichtig war (und immer noch nicht ganz unwichtig ist), das man den Editor auch ohne JavaScript bzw. nur bei eingeschränktem JavaScript (auf mobilen Geräten) benutzen kann und am besten ohne HTML-Tags. Also wird eine "Zwischensprache" wie BBCode oder Markdown benötigt. Denn so eine Zwischensprache garantiert zu 100%, dass User keinen (unerwünschten) HTML/JavaScript-Code einschleusen können.

> Mit "von offizieller Seite" meinst du die Entwickler des Editors oder?

Nein, schon Contentify. Soll heißen du kannst dir (in Eigenregie)  den Editor grundsätzlich bei Kommentaren und Forum-Posts einbauen, das ist möglich. Aber Contentify ist dafür nicht vorbereitet und ich würde es auch nicht empfehlen.

> Meine Member haben sie alle massiv wegen dem Forum beschwert. Sind halt nicht so Dinos wie wir die mit BBCodes groß geworden sind^^

Nachvollziehbar. Sagen sie denn, dass sie einen Editor zum Klicken haben wollen? Oder reicht ihnen sowas wie Markdown, also sowas wie:

`*Kursiv*, **Fett**` usw.?

**Comment by SalomanKane** [comment]
Als ich nach Beispielen gefragt hatte wie sie es den gut finden haben sie einfach auf unsere aktuelle Gildenseite verwiesen.
Dort läuft TinyMCE, ergo wollen die Leute was zum klicken^^ Von 130 Rückmeldung waren nur 2 für BB Codes zu begeistern. ist ein etwas magerer schnitt. Die Menschen sind halt sehr verwöhnt da es nahezu überall vollwertige WYSIWYG Editoren gibt. Der CKeditor den du nutzt haben auch diverse große Firmen in Foren verbaut. Sofern sie nicht vbulletin als Forum nutzen XD

**Comment by chriskonnertz** [comment]
> Ist es normal das bei der Benutzerverwaltung im Backend keine Möglichkeit zum löschen sondern nur zum editieren gegeben ist?

Habe das mal eingebaut. https://github.com/Contentify/Contentify/commit/b6e0fdbd8de362faf601e9021969a0b6da223096

Das löscht den User-Account nicht aber vielleicht verhindert es, dass immer wieder diese Frage auftaucht. Wenn man darauf klickt wird der User deaktiviert & gebannt und sein Profil geleert sowie seine Bilder gelöscht, außerdem sein Passwort geändert und noch ein paar Dinge zurückgesetzt. Email & Username bleiben gleich. Teams bleiben und Gruppen aber daraus kann man den User manuell entfernen.

**Comment by chriskonnertz** [comment]
> Als ich nach Beispielen gefragt hatte wie sie es den gut finden haben sie einfach auf unsere aktuelle Gildenseite verwiesen. Dort läuft TinyMCE, ergo wollen die Leute was zum klicken^^ Von 130 Rückmeldung waren nur 2 für BB Codes zu begeistern. ist ein etwas magerer schnitt. Die Menschen sind halt sehr verwöhnt da es nahezu überall vollwertige WYSIWYG Editoren gibt. Der CKeditor den du nutzt haben auch diverse große Firmen in Foren verbaut. Sofern sie nicht vbulletin als Forum nutzen XD

Ok danke für das Feedback. Es ist schon möglich so was einzubauen.

**Comment by kamohy** [comment]
wo bau ich den editor und vor allem: wie baue ich ihn ein ?
*re-open*

**Comment by chriskonnertz** [comment]
Der CKEditor unterstützt auch BBCode daher wäre es wohl möglich den zu verwenden und nach wie vor BBCode zu unterstützen. Das wäre meiner Einschätzung nach der einfachste Ansatz, weil  dann muss man im Wesentlichen einfach nur den CKEditor auf das Texteingabefeld loslassen und er nistet sich dann da ein.

Generell wie man den einbindet wird hier beschrieben: https://ckeditor.com/docs/ckeditor4/latest/guide/dev_installation.html#adding-ckeditor-to-your-page

Für den BBCode-Support kann man sich dieses Plugin einbinden:
https://ckeditor.com/cke4/addon/bbcode

Mehr kann ich dazu auch nicht sagen ohne es selber auszuprobieren.
