### ISSUE TITLE
Error beim updaten 

### ISSUE THREAD

**Issue by Mrciller** [Contentify/Contentify#266]
php update.php

Contentify Update

Welcome to the new version 2.1 of Contentify.
We recommend to make a database update before you continue.

Update now?
Please confirm: Update [y/n]y
Updating the database...PHP Notice:  Undefined variable: result in /var/www/html/public/update.php on line 147
Could not execute the database query: Duplicate entry 'app.theme_christmas' for key 'PRIMARY'Error: Code 23000

**Comment by Mrciller** [comment]
ich bitte um hilfe

**Comment by Mrciller** [comment]
bin draufgekommen das mein Programm beim uploud die Dateien falsch hochgeladen hat

**Comment by Mrciller** [comment]
so neuer error 
![unbenannt](https://user-images.githubusercontent.com/30408715/34404886-7a983870-ebb0-11e7-8ff0-b640fd20ca32.PNG)
![ednnt](https://user-images.githubusercontent.com/30408715/34404888-7ab41f4a-ebb0-11e7-88fb-5ee698cad658.PNG)
![hgannt](https://user-images.githubusercontent.com/30408715/34404889-7acaac92-ebb0-11e7-8bc5-11629034a1bb.PNG)
![llt](https://user-images.githubusercontent.com/30408715/34404890-7ae50ea2-ebb0-11e7-8004-5f58bb30e49c.PNG)

**Comment by Mrciller** [comment]
das php update geht doch noch nicht

**Comment by Mrciller** [comment]
root@5825c732c828f5 public $ php update.php y


Contentify Update

Welcome to the new version 2.2 of Contentify.
We recommend to make a database update before you continue.


Update now?
Please confirm: Update [y/n]y
Updating the database...Could not execute the database query: Duplicate column name 'cup_points'Error: Code 42S21

**Comment by SlavenTV** [comment]
Das Datenbankfeld ist schon da, deswegen meckert er das an.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 28.12.17, 13:01, Mrciller <notifications@github.com> schrieb:
root@5825c732c828f5 public $ php update.php y
Contentify Update
Welcome to the new version 2.2 of Contentify.
We recommend to make a database update before you continue.
Update now?
Please confirm: Update [y/n]y
Updating the database...Could not execute the database query: Duplicate column name 'cup_points'Error: Code 42S21

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Contentify/Contentify","title":"Contentify/Contentify","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Contentify/Contentify"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Mrciller in #266: root@5825c732c828f5 public $ php update.php y\r\n\r\n\r\nContentify Update\r\n\r\nWelcome to the new version 2.2 of Contentify.\r\nWe recommend to make a database update before you continue.\r\n\r\n\r\nUpdate now?\r\nPlease confirm: Update [y/n]y\r\nUpdating the database...Could not execute the database query: Duplicate column name 'cup_points'Error: Code 42S21\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Contentify/Contentify/issues/266#issuecomment-354277985"}}}

**Comment by Mrciller** [comment]
icons wurden von selbst gefixed nach ein paar versuchen kann aber noch immer nicht auf pages und dashboard zugreifen und forum melden

**Comment by Mrciller** [comment]
ok aber das war nur bei cup_points und bei den anderen?

**Comment by SlavenTV** [comment]
Kommen noch mehr fehler?

Ansonsten müsste er die dir auch anzeigen normal

 

Gesendet: Donnerstag, 28. Dezember 2017 um 13:10 Uhr
Von: Mrciller <notifications@github.com>
An: Contentify/Contentify <Contentify@noreply.github.com>
Cc: Slaven27 <Hopperjr@web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [Contentify/Contentify] Error beim updaten (#266)


ok aber das war nur bei cup_points und bei den anderen?

**Comment by Mrciller** [comment]
Ich hab cup auskommentiert und am ende kommt dann

PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/public/update.php on line 171
Contentify updated

Done! Welcome to version 2.2 of Contentify!
For security reasons, delete this file:
/var/www/html/public/update.php

**Comment by SlavenTV** [comment]
Dann ist wohl alles gut :)
 

Gesendet: Donnerstag, 28. Dezember 2017 um 13:13 Uhr
Von: Mrciller <notifications@github.com>
An: Contentify/Contentify <Contentify@noreply.github.com>
Cc: Slaven27 <Hopperjr@web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [Contentify/Contentify] Error beim updaten (#266)


Ich hab cup auskommentiert und am ende kommt dann

PHP Warning: Invalid argument supplied for foreach() in /var/www/html/public/update.php on line 171
Contentify updated

Done! Welcome to version 2.2 of Contentify!
For security reasons, delete this file:
/var/www/html/public/update.php

**Comment by Mrciller** [comment]
kann aber nicht die pages editieren forum meldungen sehen und auf dem dashboard auf dashboard klicken XD

**Comment by chriskonnertz** [comment]
> PHP Notice: Undefined variable: result in /var/www/html/public/update.php on line 147

Sieht nach einem älteren Stand aus, weil in Zeile 147 ist nichts: https://github.com/Contentify/Contentify/blob/2.2/public/update.php#L147 Und da ist auch keine $result-Variable in unmittelbarer Nähe, nur etwas weiter weg aber die kann es eigentlich nicht sein.

> bin draufgekommen das mein Programm beim uploud die Dateien falsch hochgeladen hat

Das könnte das von oben erklären. Damit könnte deine Installation natürlich korrumpiert oder auf Gutdeutsch kaputt sein. Ich hoffe, du hast ein Backup gemacht. :P 

> Updating the database...Could not execute the database query: Duplicate column name 'cup_points'Error: Code 42S21

Das passiert wenn es vorher beim Update ein Fehler gab. Wenn du ein Backup der Datenbank von vor dem ersten Update-Versuch hast, kannst du dieses einspielen, dann sollte das nicht mehr auftreten.

> Das Datenbankfeld ist schon da, deswegen meckert er das an.

Genau, ja. Weil das Update vorher schon mal teilweise durchgelaufen ist.

> icons wurden von selbst gefixed nach ein paar versuchen

Wahrscheinlich hatte dein Browser noch die alten im Cache oder die neuen noch nicht oder du hattest den Cache von Contentify nicht geleert. Wie auch immer, klingt sehr nach irgend einem Cache-Problem.

> kann aber nicht die pages editieren forum meldungen sehen und auf dem dashboard auf dashboard klicken XD

Schau ich mir an.

**Comment by chriskonnertz** [comment]
> kann aber nicht [...] auf dem dashboard auf dashboard klicken XD

Behoben: https://github.com/Contentify/Contentify/commit/3857e668be074bcbebec1678fb87b8eef65c7778

Danke für den Hinweis!

**Comment by chriskonnertz** [comment]
>  kann aber noch immer nicht auf pages [...] zugreifen

Bei mir klappt's. Wie genau / was genau rufst du auf?

**Comment by chriskonnertz** [comment]
> kann aber nicht [...] forum meldungen sehen

Ja, das habe ich auch. Scheint ein Problem zu sein durch den Umstieg auf Laravel 5.3. https://github.com/laravel/framework/issues/14997

**Comment by chriskonnertz** [comment]
Hässlicher Workaround: `config/database.php` öffnen und in Zeile 62 den striken Modus für SQL deaktivieren durch ersetzen von "true" mit "false" ( https://github.com/Contentify/Contentify/blob/2.2/config/database.php#L62 ).

Bei mir gibt es danach einen anderen Fehler. Ist das nur bei mir so?

**Comment by Mrciller** [comment]
bei mir ist dann Pagecat not found

**Comment by Mrciller** [comment]
nachdem kann ich aber wieder in Forum meldungen

**Comment by chriskonnertz** [comment]
> bei mir ist dann Pagecat not found

Das sollte helfen: 
https://github.com/Contentify/Contentify/commit/4e8198290123f5f7ee5ca25efbc9fb59a1adcb32

**Comment by Mrciller** [comment]
Register funktioniert nicht mehr XD

**Comment by Mrciller** [comment]
Sorry, the page you are looking for could not be found.
1/1
NotFoundHttpException in RouteCollection.php line 161:
in RouteCollection.php line 161
at RouteCollection->match(object(Request)) in Router.php line 766
at Router->findRoute(object(Request)) in Router.php line 621
at Router->dispatchToRoute(object(Request)) in Router.php line 607
at Router->dispatch(object(Request)) in Kernel.php line 268
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Kernel.php line 150
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
at Kernel->handle(object(Request)) in index.php line 52

**Comment by chriskonnertz** [comment]
Dieser Bug wurde mit Version 2.3 behoben.

=> https://github.com/Contentify/Contentify/releases/tag/v2.3
