### ISSUE TITLE
Error: Code 42000

### ISSUE THREAD

**Issue by SalomanKane** [Contentify/Contentify#267]
Bekomme beim Update den Fehlercode
https://prnt.sc/htuayy

Muss in der Datenbank was von Hand geändert werden?

**Comment by chriskonnertz** [comment]
Beim Update von Version 2.1 auf 2.2?

> Muss in der Datenbank was von Hand geändert werden?

Nein.

Probier bitte mal das hier https://github.com/Contentify/Contentify/commit/d82a1c78967d96c7aa1ff23fe6e6b81791dbe7d1 und lass mich wissen ob es geholfen hat.

**Comment by SalomanKane** [comment]
Soweit hat es geholfen, jetzt meckert er natürlich wegen den bereits erstellten Datenbankeinträgen. Wird mich morgen mal genauer ransetzen

**Comment by chriskonnertz** [comment]
Ok, hoffe es klappt!

**Comment by SalomanKane** [comment]
Kann ich bisher nicht sagen, habs Zeitlich noch nicht geschafft die schon aktualisierten Datenbankeinträge zu entfernen.
