### ISSUE TITLE
Admin pages modul

### ISSUE THREAD

**Issue by eodclan** [Contentify/Contentify#268]
See here the error: 

`FatalErrorException in BaseModel.php line 395:
Class 'App\Modules\Pages\Pagecat' not found`

**Comment by eodclan** [comment]
the next error:

`NotFoundHttpException in Handler.php line 113:
No query results for model [App\Modules\Pages\CustomPage].`

**Comment by chriskonnertz** [comment]
This commit should solve the problem: https://github.com/Contentify/Contentify/commit/4e8198290123f5f7ee5ca25efbc9fb59a1adcb32

**Comment by chriskonnertz** [comment]
Schau mal bitte  in die Datei `app\Modules\Pages\Pagecat.php`. 
1. Schreibt die sich genau so? (Groß-/Kleinschreibung)
2. In der Datei steht: `class Pagecat extends BaseModel` Passt auch hier die Groß-/Kleinschreibung?
