### ISSUE TITLE
NotFoundHttpException in RouteCollection.php line 161

### ISSUE THREAD

**Issue by itsomarawad** [Contentify/Contentify#269]
Hello! This is a continuation of #164 . I tried it out with 2.2 now as well, but the error still persists. At least the error message has become smaller :). I installed all vendor libraries and the web server should support mod rewrite and everything else. When i open up the install.php everything is green but when i click on launch install it says /public/index.php was not found on this server. But it is definitely there, and even has its access permissions set to 777.  When i open up the index.php directly in the browser it throws the following error:

> Sorry, the page you are looking for could not be found.
> 1/1
> NotFoundHttpException in RouteCollection.php line 161:
> in RouteCollection.php line 161
> at RouteCollection->match(object(Request)) in Router.php line 766
> at Router->findRoute(object(Request)) in Router.php line 621
> at Router->dispatchToRoute(object(Request)) in Router.php line 607
> at Router->dispatch(object(Request)) in Kernel.php line 268
> at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
> at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
> at Pipeline->then(object(Closure)) in Kernel.php line 150
> at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
> at Kernel->handle(object(Request)) in index.php line 52

I already used the 

> php composer.phar dumpautoload

command as described [here](https://github.com/Contentify/Contentify/wiki/Troubleshooting) but the error still persists :/

Thanks for your help!

**Comment by Mrciller** [comment]
i got the same Error but when someone wants to register himself

**Comment by chriskonnertz** [comment]
> i got the same Error but when someone wants to register himself

Thank you! Please try out this bugfix: 
https://github.com/Contentify/Contentify/commit/35c138a58bb87502cbe37427356e042983d3b625

**Comment by chriskonnertz** [comment]
> command as described here but the error still persists :/

Okay I will try to install it on  a fresh Linux server, maybe I will be able to see the error message then.

**Comment by Nordrir** [comment]
I'm getting the same issue from trying to use the Dashboard in the admin-page. I didn't have it with the clean install of 2.1, but after update to 2.2 I'm getting the exact same error. If I go to /admin, no issue, but /admin/dashboard and it has an aneurysm.

> in RouteCollection.php line 161
> at RouteCollection->match(object(Request)) in Router.php line 766
> at Router->findRoute(object(Request)) in Router.php line 621
> at Router->dispatchToRoute(object(Request)) in Router.php line 607
> at Router->dispatch(object(Request)) in Kernel.php line 268
> at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
> at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
> at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
> at Pipeline->then(object(Closure)) in Kernel.php line 150
> at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
> at Kernel->handle(object(Request)) in index.php line 52

**Comment by itsomarawad** [comment]
Hey! I wanted to inform you that i finally was able to circumvent this issue by adjusting the RewriteBase in the .htaccess from `RewriteBase /` to `RewriteBase /public`

EDIT: War etwas voreilig, Installation geht, aber hab jetzt das gleiche Problem wie Nordrir




------
Randnotiz: 
Erstmal sorry, dass ich dich solange mit nem Problem beschäftigt hab, wo du dir vermutlich eh die ganze Zeit gedacht hast (und auch Recht gehabt hast), dass die blöde Apachekonfiguration dran Schuld ist. Möchte mich herzlich mal für das Projekt an sich und den wirklich tollen und schnellen Support bedanken ( den du trotz der ganzen blinden Hühner wie mich :see_no_evil:  weiterhin so aufrecht erhältst). Dachte mir ich hätte schon alles durchprobiert, aber dann lags halt doch wieder an der RewriteRule. Naja jetzt gehts mal - vielleicht hilft das Issue wenigstens jemandem anderem der dann genauso blind war wie ich.

**Comment by chriskonnertz** [comment]
Kein Problem und danke für das Feedback. Ich mache hier erst mal zu um etwas aufzuräumen, das Issue ist über die Suche nach wie vor zu finden.
