### ISSUE TITLE
Registration allowed for logged in user

### ISSUE THREAD

**Issue by romkej** [Contentify/Contentify#27]
Hi. Today i found little bug. Then user has logged in he can go in /auth/registration/create and create another account! Please fix that! Thanks. Any news about next versions? :)

**Comment by chriskonnertz** [comment]
Hi,

we cannot completely prevent users from registering twice. The could log off, destroy the session and there is no way to recognize this.

Waht we can do is to display a message if a user navigtes to the registration page ( auth/registration/create ) while being logged in.

**Comment by romkej** [comment]
Thanks for fast answer! Can we do like that: If user is logged in and he go in registration page he cannot see registration page and he got a notification like that: "U cannot register another account becouse u are already logged in?" It wil be perfect!

**Comment by romkej** [comment]
Sorry if my english so bad :)

**Comment by chriskonnertz** [comment]
Yes, I am going to implement that.

**Comment by romkej** [comment]
Nice, tanks! I'm so happy with this CMS, support respond are really fast. :+1:

**Comment by chriskonnertz** [comment]
I'm glad you enjoy it. :)

**Comment by chriskonnertz** [comment]
Solved by https://github.com/Contentify/Contentify/commit/bb84708ce9e0b60137c2e720bbccde085fddadef (and a bugfix, https://github.com/Contentify/Contentify/commit/96abff8be6f5cdbe1f75c794a4761e0b07dc7f99 )
