### ISSUE TITLE
after Launch installer error page not found

### ISSUE THREAD

**Issue by wuast94** [Contentify/Contentify#270]
Hey :) 

wenn ich die Install.php auf mache ist alles grün und wenn ich dann auf Launch Installer klicke kommt folgende page: 

The requested URL /public/install was not found on this server.

verstehe nicht warum der button auf /public/install gelinked ist obwohl es das nicht gibt .. habe dann mal in der php nachgeguckt und dort ist das aber auch gelinked: 

echo '</table><a **href="./install**" style="display: inline-block; padding: 20px; text-decoration: none; 
        background-color: #00afff; color: white; font-size: 18px; border-radius: 5px">Launch Installer</a>';

**Comment by chriskonnertz** [comment]
Hello,

I just added a section to the wiki that covers this issue: https://github.com/Contentify/Contentify/wiki/FAQ#i-cannot-find-the-publicinstall-directory
