### ISSUE TITLE
Pages not working 

### ISSUE THREAD

**Issue by wuast94** [Contentify/Contentify#271]
when i click on "Seiten" in backend it return this:

1/2:
PDOException in Connection.php line 333:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test1.page_cats' doesn't exist

2/2: 
QueryException in Connection.php line 770:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test1.page_cats' doesn't exist (SQL: select * from `page_cats` where `page_cats`.`id` = 2 and `page_cats`.`deleted_at` is null limit 1)

**Comment by wuast94** [comment]
Aus der Log datei
[2018-01-07 09:15:09] production.ERROR: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test1.page_cats' doesn't exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333

**Comment by chriskonnertz** [comment]
Hallo,

bitte das hier übernehmen: https://github.com/Contentify/Contentify/commit/6bf1694f6c35a5dc881a77d45be9b09473d71b48
