### ISSUE TITLE
can´t create Forum

### ISSUE THREAD

**Issue by wuast94** [Contentify/Contentify#272]
wenn ich im backend versuche ein neues forum zu erstellen kommt die ganze zeit folgende meldung: 
forum id muss eine ganze Zahl sein.

im anhang was ich eingetragen habe 
<img width="717" alt="unbenannt" src="https://user-images.githubusercontent.com/16965460/34648138-3481473c-f394-11e7-8635-e95e8f863989.PNG">

**Comment by DennioWhite** [comment]
i have the same issue. What can we do?

**Comment by DennioWhite** [comment]
gibbet schon ein update?

**Comment by kamohy** [comment]
Also ich hab auch schon nachgesehen, nichts gefunden....
bin die phpdatein durch gegangen und find den fehler nicht, ich denke mal 
das er die ID's automatisch setzen sollte, aber aus irgendeinem grund geht das nicht....
also wär möglichkeit zwei, es hardcodet einzufügen im modul, das er eine ID eintragen lassen kann vom user (admin) würde bedeuten neue spalte mit dem wert forumsid
aber was weiss ich schon....

**Comment by chriskonnertz** [comment]
Bug fixed: https://github.com/Contentify/Contentify/commit/cd28397f4bbf8fa449972e590bb02e7d90bb9ca6#diff-6f79ee731fc813e57f81d0c58b66c142
