### ISSUE TITLE
Edit Cup settings

### ISSUE THREAD

**Issue by Mrciller** [Contentify/Contentify#273]
Wie kann ich den Code umändern dass es zu einen Schweizersystem wird?
Für die  die nicht Wissen:
Schweizersystem ist jeder spielt gegen jeden einmal und der mit den Meisten Wins am Ende gewinnt :D

**Comment by Mrciller** [comment]
entweder dass oder double elimination beides würde für mich sehr Hilfreich seien ;D

**Comment by chriskonnertz** [comment]
Hallo,

ich will dich nicht demotivieren, fürchte aber, das ist nicht mal eben so getan. Das klingt für mich im ersten Moment schon nach ziemlich großen Umbaumaßnahmen. Ich kann dir da derzeit nicht wirklich weiter helfen, das würde meiner Einschätzung nach den Rahmen sprengen.

Mir ist klar, das ist keine schöne Antwort. Aber das Cup-System war immer nur als einfaches, minimalistisches System gedacht. Contentify ist in dem Sinne keine richtige Ligen/Turniere-Software. So etwas zu bauen würde eine Spezialisierung auf genau dieses Thema bedeuten und Contentify ist halt nun Mal ein CMS. Darauf liegt der Fokus und _das wird auch so bleiben_. 

Klar könnte man - hypothetisch gesprochen - versuchen mehr in Richtung Turnieren und Co. zu gehen um mehr Nutzer anzusprechen, aber das Problem ist, das führt zu einem Ansatz "Masse statt Klasse". Einfach weil, wenn zu viel Masse da ist, das nicht mehr handlebar ist und man die einzelnen Komponenten nicht mehr wirklich gut gestalten kann. Dieses Problem ist jetzt schon da, Contentify ist eigentlich viel zu "fett" geworden. Es jetzt noch mal ernsthaft auf einen weiteren Bereich auszudehnen wäre too much.

Contentify ist nicht mehr ganz jung ( >3 Jahre) und jetzt wo es zu altern beginnt und man eigentlich einige Dinge mal grundlegend erneuern müsste zeigt sich, dass das sehr viel Aufwand bedeutet, weil das CMS inzwischen ziemlich groß geworden ist. In diese Falle sind ja schon andere CMS geraten. Plötzlich waren sie so groß, dass ernsthafte, umfangreiche Überarbeitungen nicht mehr realisierbar waren. Dann kamen Versuche diese CMS von Grund auf neu zu schreiben und Stand heute hat das weder bei WebSPELL noch ClanSphere geklappt. Diesen Weg muss man ja nicht auch und vor allem nicht sehenden Auges gehen.
