### ISSUE TITLE
Modal box then using STEAM auth

### ISSUE THREAD

**Issue by jonatant** [Contentify/Contentify#274]
Hello. Nice CMS! But i have 1 problem, i try todo if user registering via STEAM he need set username first after saving profile to db.

Example: I press login with steam, i come back from steam website, and in my website has popup window: Choose your username:

Can u do that? THANKS!

**Comment by jonatant** [comment]
Why this need? Becouse if steam user has nickname like: $#%^$%GDSSDF$#^ % $#. Its not verry good... Thanks!

**Comment by jonatant** [comment]
This is really important and useful! Can somebody make this thing? I'm not good coder..

**Comment by chriskonnertz** [comment]
Hello,

I will consider implementing this feature. It seems to be a legit feature.

**Comment by jonatant** [comment]
Any news? :)

**Comment by chriskonnertz** [comment]
@jonatant 

Sorry for the delay.

This feature is scheduled for the next version of Contentify, v2.3 ( https://github.com/Contentify/Contentify/issues/264 )

**Comment by chriskonnertz** [comment]
Hello @jonatant ,

please excuse the delay (again). You requested an important change that did deserve a higher priority than it actually got.

Here it is, finally: 
https://github.com/Contentify/Contentify/commit/1248ee9cdc902e5b2f2c4a648a5125494521840b

After leaving the Steam website behind, users will land on a new page where they have to confirm or adjust their username and their email address.

Some notes:

>  he need set username first after saving profile to db.

Actually creating the user account will happen _after_ setting the username, not before.

>  in my website has popup window

Actually there will not be a pop-up (modal), just a simple page with a form.
