### ISSUE TITLE
Can't save a Custom Site

### ISSUE THREAD

**Issue by marcelkuhla** [Contentify/Contentify#275]
Hey Guys, it looks like Contentify can't save Custom Pages with the german translation activated, because if I want the save the Site, it will crash with an QueryException 

LOG:
https://gist.github.com/TechPandaIT/0150408c852cd752615c38405d6091f0

To replicate:

- Change the Interface Language to German
- Create a new page at the backend
- save it 

I also found 2 Major Bugs on the setup, but i want to do more testing what triggers the errors there.

**Comment by chriskonnertz** [comment]
Hello,

thank you for reporting this bug. It has been fixed in Version 2.3.
