### ISSUE TITLE
News Module is igonoring "Publish at"

### ISSUE THREAD

**Issue by marcelkuhla** [Contentify/Contentify#276]
Error:

The News Module is ignoring the "Publish at" set in the Backend. It gets save because if you edit the news afterward it will show it, but both the front- & backend don't show it right.

To replicate:
- Create a new news or edit an old one
- change the "Publish at"
- save the news
- check the front- or backend afterward

**Comment by chriskonnertz** [comment]
Hello,

I will follow your guide and try to reproduce this bug.

**Comment by chriskonnertz** [comment]
Bitte hier das hier mal probieren /
Please thy this proposal:

https://github.com/Contentify/Contentify/issues/253#issuecomment-371585147
