### ISSUE TITLE
Can't find a install.php ?!

### ISSUE THREAD

**Issue by nobi13** [Contentify/Contentify#278]
Why i cant find install.php ?

**Comment by marcelkuhla** [comment]
https://github.com/Contentify/Contentify/wiki/Installation#installation

Please watch that Part of the Installation Process again. As Contentify is based on Laravel, everything needs to go over the /public folder, so if you don't adjust your apache.conf or folder on a shared web space, you always need to navigate to your page like that: http://example.com/public/

**Comment by chriskonnertz** [comment]
Yes. Most likely this is a problem with the configuration of the server or to be more precise with the URL / URL rewriting.
