### ISSUE TITLE
Digital Ocean Installer doesn't work

### ISSUE THREAD

**Issue by ghost** [Contentify/Contentify#280]
Hey, recently I purchased a digital ocean droplet and trying to use the installer for digital ocean doesn't work. I have tried multiple times and I am running the Ubuntu 16.04 LAMP install, so idk why it wouldn't work.

**Comment by chriskonnertz** [comment]
Hello,

there has to be some kind of an error message, right?

Just a guess - take a look at this file: `storage/app/database.ini` 
It should look like this but with you database credentials: https://github.com/Contentify/Contentify/blob/2.2/storage/app/database.ini

**Comment by ghost** [comment]
Well um there is no error, nothing even installs? I go to the ip and nothing is there at all, just "The requested URL / was not found on this server." so I am not sure what is going on.

**Comment by ghost** [comment]
There is no database.ini file to edit....

**Comment by Mrciller** [comment]
you must go to your.domain/public/install

**Comment by ghost** [comment]
Doesnt work

**Comment by Mrciller** [comment]
do your folder have permission 777? i mean the public folder?

**Comment by ghost** [comment]
Yeah

**Comment by Mrciller** [comment]
go toetc apache2 and look in the sites avalible config is there you html folder linked?

**Comment by chriskonnertz** [comment]
I assume this issue is out of date and can be closed.
