### ISSUE TITLE
URL /install wurde nicht gefunden | requested URL /install was not found

### ISSUE THREAD

**Issue by 1Tobi** [Contentify/Contentify#281]
Hallo erstmal!

Ich habe da ein Problem mit der Weiterleitung beim Installer
Ich habe jetzt schon vieles Ausprobiert um den Fehler zu finden ich habe auch rewrite aktiviert wie es im FAQ steht
Nun steh ich auf dem Schlauch und weiß nicht mehr weiter wäre Cool wenn man eine Lösung findet

**Comment by marcelkuhla** [comment]
Scheint mir das gleiche "Problem" wie hier zu sein:

#278 

Sollte es nicht so sein, dann wäre die Apache/Nginx oder Laravel Logs interessant. #

**Comment by 1Tobi** [comment]
Ich finde den Install.php ich habe in der Apache Config DocumentRoot /var/www/html/public eingetragen nur ich werde nicht Weitergeleitet

IP: Tactical-Fighters.de
Ich gehe auf Launch Install und dann kommt halt The requested URL /install was not found on this server.

**Comment by chriskonnertz** [comment]
Den Apache hast du nach den Änderungen mal neu gestartet?

**Comment by 1Tobi** [comment]
Ja, habe ich

**Comment by marcelkuhla** [comment]
Dann sende uns doch mal deine apache log, bzw. aktiviere sie und versuche es erneut

**Comment by chriskonnertz** [comment]
Hab mal noch die Überprüfung ob - wenn man Apache nutzt - mod_rewrite aktiviert wurde in den Pre-Installer eingebaut: https://github.com/Contentify/Contentify/commit/d30507ef9be9289e7b43650e552fa30737c1b2de

**Comment by 1Tobi** [comment]
Error Log: https://hastebin.com/sayoyenute.sql

**Comment by chriskonnertz** [comment]
Das ganze ist merkwürdig, wenn du sagst du hast mod_rewrite aktiviert dann sollte das eigentlich funktionieren. Was man noch schauen könnte wäre aus dem FAQ das hier:

> Sometimes you also have to allow the .htaccess file to override standard website configs.

Hast du deine Apache-Einstellungen dahingehend überprüft? 
Dieser .htaccess https://github.com/Contentify/Contentify/blob/2.2/public/.htaccess muss erlaubt sein ihren Voodoo-Zauber durchzuführen. ;)

https://askubuntu.com/questions/429869/is-this-a-correct-way-to-enable-htaccess-in-apache-2-4-7-on-ubuntu-12-04

**Comment by 1Tobi** [comment]
Jetzt kommt Diese Seite funktioniert nicht
tactical-fighters.de kann diese Anfrage momentan nicht verarbeiten.

**Comment by marcelkuhla** [comment]
> Error Log: https://hastebin.com/sayoyenute.sql

`[Tue Jan 23 19:24:26.137541 2018] [:error] [pid 17989] [client 176.199.67.32:60072] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\Logger->addRecord(400, Object(ErrorException), Array)\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Writer.php(202): Monolog\\Logger->error(Object(ErrorException), Array)\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Writer.php(113): Illuminate\\Log\\Writer->writeLog('error', Object(ErrorException), Array)\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107`

Hast du composer auf dem Server und hast es durchlaufen lassen?

**Comment by 1Tobi** [comment]
Ja, Composer ist drauf nur wie meinst du das mit durchlaufen lassen ?

Ich habe Composer install gemacht und es wurde am Ende kein Fehler angezeigt

**Comment by marcelkuhla** [comment]
Also:

ich gehe anhand der Error Logs davon aus, dass du zwar Apache/PHP mässig alle Anforderungen erfüllst, aber composer beim autoload etwas falsch oder garnicht gemacht hat und es daher ein Problem mit  Laravel selber gibt. 

Dieses bekommen wir aber nicht ausgegeben, weil Monolog wie oben im Errorlog zu sehen ist nicht richtig initialisiert werden konnte. 

Versuch also mal bitte den vendor Ordner neu hochzuladen und per `composer update` dass ganze Manuell nochmal zu triggern.

**Comment by 1Tobi** [comment]
So hab es nun Hochgeladen und composer update eingegeben jetzt sagt er aber immernoch 

Diese Seite funktioniert nicht
tactical-fighters.de kann diese Anfrage momentan nicht verarbeiten.
HTTP ERROR 500

**Comment by 1Tobi** [comment]
Ich habe mal im Error Log nachgeschaut und dies hier Gefunden :  https://hastebin.com/ecopawekuj.tex

**Comment by 1Tobi** [comment]
Ich habe auch nochmal nach dem Fehler Google benutzt und es wurde gesagt das ich Rechte geben soll, nur die Datei garnicht Existiert (/var/www/html/storage/logs/laravel.log')
Was kann ich tun ?

**Comment by 1Tobi** [comment]
Ich habs Geschafft, hab folgenden Command eingegeben: chmod -R 777 storage (REchte an den Storage ordner xd)

**Comment by chriskonnertz** [comment]
Freut mich, dass es geklappt hat!

Frage an dich: Das steht so auch in der Doku: https://github.com/Contentify/Contentify/wiki/Installation#installation
Offensichtlich hast du das (zumindest zunächst) nicht gesehen.
Woran könnte das liegen?
Wäre für mich interessant zu wissen um herauszufinden, wie man in Zukunft verhindern kann, das andere das Problem auch haben. :)

**Comment by chriskonnertz** [comment]
Leider kein Feedback erhalten -> Ticket nun geschlossen.
