### ISSUE TITLE
Lost access to Admin

### ISSUE THREAD

**Issue by PureLoneWolf** [Contentify/Contentify#283]
Hi all

I just installed and was messing around with some settings to see how things worked, I added myself to a Team and instantly lost access to the Admin Backend.

Presumably I can fix this in MySQL - The question is what and where?

Many thanks :)

**Comment by chriskonnertz** [comment]
Hello,

yes, you can fix this via MySQL.

The table is "role_users". Example query:

```
INSERT INTO `role_users` (`user_id`, `role_id`, `created_at`, `updated_at`) VALUES
(2, 5, '2017-12-06 20:14:51', '2017-12-06 20:14:51');
```

**Comment by PureLoneWolf** [comment]
That sorted it - Many thanks
