### ISSUE TITLE
Error on vendor/autoload.php German

### ISSUE THREAD

**Issue by 1Tobi** [Contentify/Contentify#285]
Hallo ich habe einen Fehler gefunden und weiß nicht wie ich diesen beheben kann
Fehler: https://hastebin.com/bujamonudo.rb

Bitte um Hilfe

**Comment by chriskonnertz** [comment]
Hallo,

bitte entschuldige, dass ich erst jetzt antworte.

Kurz gesagt, dir fehlen Fremdbibliotheken. Du musst diese installieren. Das musst du nicht von Hand tun, dafür gibt es ein Tool, das sich darum kümmert: Composer.

Das kannst du hier herunterladen: https://getcomposer.org/composer.phar
Die Datei dann bitte direkt in den Contentify-Ordner legen.
Dann per Konsole dieses Kommando ausführen: `php composer.phar install`
(Falls das nicht klappt statt `php` den korrekten Pfad zur `php.exe` o. ä. angeben)
