### ISSUE TITLE
Error with links

### ISSUE THREAD

**Issue by imanolGOMI** [Contentify/Contentify#287]
HI!

After install all works but now the links fails... 

(the link point to public/admin/news for example and this route don't work but if change to admin/news all work.)

I think that is apache configuration but i don't known...

Thanks

**Comment by chriskonnertz** [comment]
Hello,

sorry for not responding earlier. Could you solve the issue?

**Comment by imanolGOMI** [comment]
i have been away and i couldnt see this

**Comment by chriskonnertz** [comment]
Hm, I do not understand.

**Comment by kamohy** [comment]
have you flaged our side to public?
Normal: url/public/news..
Flaged: url/news...

please use ure FTP: /storage/framework/chache/ -clean it-

**Comment by imanolGOMI** [comment]
fix with last version.
