### ISSUE TITLE
NotFoundHttpException in RouteCollection.php line 161:

### ISSUE THREAD

**Issue by Bensilver86** [Contentify/Contentify#290]
Hallo,

ich habe folgendes problem. Kann dort jemand helfen?

<img width="963" alt="bildschirmfoto 2018-02-08 um 03 12 23" src="https://user-images.githubusercontent.com/36249643/35951973-0ca07258-0c7e-11e8-86e8-7ebb98f6e83c.png">

Mit freundlichen Grüßen

**Comment by Mrciller** [comment]
welche Seite probierst du zu öffnen?

**Comment by Bensilver86** [comment]
Hi das Dashboard

Von meinem iPhone gesendet

**Comment by Mrciller** [comment]
i had the problem too but i fixed it on its own so i cant rly helP D:

**Comment by chriskonnertz** [comment]
> ich habe folgendes problem. Kann dort jemand helfen?

Du kannst mal den Cache löschen, dazu alle Order & Dateien in `storage/framework` entfernen.
Außerdem schau mal ob in `config/app.php`  der Pfad zur Website richtig gesetzt ist ( https://github.com/Contentify/Contentify/blob/2.2/config/app.php#L63 )

**Comment by kamohy** [comment]
haben wir 

> Du kannst mal den Cache löschen, dazu alle Order & Dateien in storage/framework entfernen.
Außerdem schau mal ob in config/app.php der Pfad zur Website richtig gesetzt ist ( https://github.com/Contentify/Contentify/blob/2.2/config/app.php#L63 )

hatten wir auch gemacht brachte nichts... problem bestand weiterhin...

die idee: adminnavigation überarbeiten und statt admin/dashboard
einfach den link auf admin/ setzen...

wir suchen noch nach dem menü...

**Comment by chriskonnertz** [comment]
Hm, das ist eine mögliche, aber keine optimale Lösung... Besser wäre dem Problem an sich auf die Spur zu kommen. Leider weiß ich nicht wie ich das tun kann, da ich das Problem derzeit nirgendwo habe.

**Comment by chriskonnertz** [comment]
Ich mache hier aufgrund des Alters des Tickets zu. Sollte das Problem bei irgendwem erneut auftauchen, bitte Bescheid sagen! :)
