### ISSUE TITLE
DigitalOcean install.sh Problem

### ISSUE THREAD

**Issue by TheHotz** [Contentify/Contentify#291]
Mooin,
Habe ein Problem wenn den Installer für DigitalOcean nutzen möchte.
Funktioniert alles bis zur Datenbank wenn ich es richtig sehe. Dort muss ich dann ein ewig langes Passwort eingeben, woraufhin diese Meldungen kommen:

`mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
`

```
`Resolving www.contentify.org (www.contentify.org)... 178.33.36.104
Reusing existing connection to contentify.org:80.
HTTP request sent, awaiting response... 404 Not Found
2018-02-14 15:46:22 ERROR 404: Not Found.

unzip:  cannot find or open contentify_2_2.zip, contentify_2_2.zip.zip or contentify_2_2.zip.ZIP.
rm: cannot remove 'contentify_2_2.zip': No such file or directory
mv: cannot stat 'contentify_2_2': No such file or directory
install.sh: line 79: cd: html: No such file or directory
chmod: cannot access 'storage': No such file or directory
chmod: cannot access 'bootstrap/cache': No such file or directory
chmod: cannot access 'public': No such file or directory
sed: can't read storage/app/database.ini: No such file or directory
`
```

Freue mich über Hilfe ^^
PS: Würde mich noch nicht als Profi bezeichnen, wäre also nett wenn die Hilfestellung eher genauer ausfällt ;)

**Comment by chriskonnertz** [comment]
Hallo,

ja, das ist wahrscheinlich ein Bug im Skript. Die MySQL-Verbindungsdaten werden nicht korrekt in der Datei `storage/app/database.ini` gespeichert. Öffne die bitte mal mit einem Texteditor. bearbeite sie, sodass sie so aussieht nur mit deinen Daten: https://github.com/Contentify/Contentify/blob/2.2/storage/app/database.ini

Danach sollte es klappen. Das `install.sh` Skript musst du übrigens normalerweise **nicht** nochmal ausführen.

**Comment by TheHotz** [comment]
Erstmal Danke für die schnelle Antwort!

Wenn ich die Datei mit dem Command `sudo nano storage/app/database.ini` die Textdatei aufrufen möchte, um diese wie angewiesen zu bearbeiten, dann ist das Verzeichnis nicht verfügbar. Abspeichern ist somit natürlich auch nicht möglich.

Mir wird beim ausführen der install.sh ebenfalls das hier angezeigt:
`--2018-02-15 10:57:09--  http://contentify.org/share/releases/contentify_2_2.zip
Resolving contentify.org (contentify.org)... 178.33.36.104, 2001:41d0:d:f62::c:3001
Connecting to contentify.org (contentify.org)|178.33.36.104|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.contentify.org/share/releases/contentify_2_2.zip [following]
--2018-02-15 10:57:09--  http://www.contentify.org/share/releases/contentify_2_2.zip
Resolving www.contentify.org (www.contentify.org)... 178.33.36.104
Reusing existing connection to contentify.org:80.
HTTP request sent, awaiting response... 404 Not Found
2018-02-15 10:57:09 ERROR 404: Not Found.`

PS: Ich glaub ich stelle mich gerade sehr dämlich an, Sorry! 🤦‍♂️

**Comment by chriskonnertz** [comment]
Da ist leider ein Fehler unterlaufen beim Veröffentlichen von Version 2.2. Das ist ein nicht gerade trivialer Prozess und dabei ist ein Schritt übersehen worden. Daher war der Download der Version 2.2 nicht direkt von contentify.org möglich, was das Skript aber voraussetzt. 

Jetzt sollte es funktionieren. Bitte versuche es nochmal von vorne.
