### ISSUE TITLE
Register error

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#292]
Hello, i updated at v2.2 and i gave this error
![reg22](https://user-images.githubusercontent.com/29990653/36681800-47e0dee0-1b22-11e8-94cd-216661784b7c.JPG)

**Comment by chriskonnertz** [comment]
Hi,

do you know how to use git? My recommendation is to update your installation to the latest state of Contentify by using git -> https://github.com/Contentify/Contentify

**Comment by chriskonnertz** [comment]
Hello,

yes this was a bug but the bug is fixed in v2.3. (I think it is this commit: https://github.com/Contentify/Contentify/commit/afed108a334638013112ac0365f99f4ac47bf578 )
