### ISSUE TITLE
FontIcon

### ISSUE THREAD

**Issue by lukasmk87** [Contentify/Contentify#293]
Hi,

erstmal meinen Dank für das tolle CMS.

Habe vor drei Tagen ein Update von 2.1 auf 2.2 durchgeführt.
Seit dem fehlen mir die FontIcon's.

Habe schon hier und da geschaut aber nicht gefunden, was mir helfen würden.

Würde mich auf Hilfe freuen.

Danke.

P.S.: https://bastnerds.de

**Comment by lukasmk87** [comment]
Hab das Layout.blade editiert und gespeicht. 

Geht wieder.

**Comment by chriskonnertz** [comment]
Hallo,

sehr schön :)

Allerdings, war das jetzt ein Fehler des CMS? Wenn ja, magst du die Lösung teilen?
