### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#296]
Sorry for post again, but i have big problems after update at 2.2. I search all github first after post this as you tell me.

I update at 2.2 from 2.0 and i have register step errors after this i found more erros in admin panel ( pages, modules and categories from news) i decide to put my old backup 2.0 back on server because i really need to work this website.

After succefully transfer my 2.0 backup.

This page isn’t working
94.130.74.198 is currently unable to handle this request.
HTTP ERROR 500

This Backup is 90% working have a problem only at modules page didn;t open but work well. but now.. doesen't work anymore. I didn't change anythink in files or somethink... Just send from mypc to filezilla.

I will attach error.log here.

Thank you!
[error.log](https://github.com/Contentify/Contentify/files/1784683/error.log)

**Comment by khalifaone** [comment]
I solved this problem with fresh install and same database, it works. But now i have another problem at user register in first step i solved with https://github.com/Contentify/Contentify/commit/35c138a58bb87502cbe37427356e042983d3b625

But now i have another error at registration step.

SQLSTATE[HY000]: General error: 1364 Field 'slug' doesn't have a default value (SQL: insert into `users` (`email`, `username`, `language_id`, `password`, `updated_at`, `created_at`) values (testfortest@mail.com, testuser22, 1, $2y$10$ztWeanxRW.Vl6AhoYY4BxukIJb8jxKh.2w4eKHGP7G9fLE2srjVsi, 2018-03-06 18:10:00, 2018-03-06 18:10:00))

**Comment by khalifaone** [comment]
Problem solved. Create an new slug alter table and import in phpmyadmin

**Comment by chriskonnertz** [comment]
Hello,

sorry for the inconvenience. I am glad to here that you were able to solve the problems.

> I update at 2.2 from 2.0 and i have register step errors after this

A new release is going to come very soon and will fix some bugs.
