### ISSUE TITLE
Update 2.2 to 2.3

### ISSUE THREAD

**Issue by lukasmk87** [Contentify/Contentify#298]
Moin,

trotz der vielen händischen Bugfixes am Wochenende, dachte ich mir ich mache einfach ein Update auf die 2.3

Nach dem kopieren, habe ich dann das Update Skript ausgeführt. Folgende Fehler Meldung habe ich bekommen:

Updating the database...Could not execute the database query: Duplicate column name 'cup_points'Error: Code 42S21

**Comment by lukasmk87** [comment]
Update.php muss noch ersetzt werden.

**Comment by chriskonnertz** [comment]
Ja klingt als hättest du den Updater von 2.1 auf 2.2 ausgeführt.

**Comment by lukasmk87** [comment]
Bei der update Datei war die alte oder keine dabei. Hab sie direkt aus dem Git

**Comment by chriskonnertz** [comment]
Ok danke für die Info, die Datei fehlte tatsächlich in der .zip, habe sie ergänzt.
