### ISSUE TITLE
League Feature

### ISSUE THREAD

**Issue by nikeddy** [Contentify/Contentify#299]
it would be a great function enter the management of a league, where inserted players automatically creates the game calendar, where users can enter the result and automatically update the statistics.

**Comment by chriskonnertz** [comment]
Hello,

> where inserted players automatically creates the game calendar

I do not understand that one :P 

> where users can enter the result and automatically update the statistics

This is covered by the current implementation.

**Comment by Mrciller** [comment]
I think he means that the Players can make a date when the match ist.

Ich glaube dass er meint dass die Spieler selber ein Datum aussuchen können wann sie ihr match spielen wollen und es dann angezeigt wir.


So habe ich es verstanden

**Comment by chriskonnertz** [comment]
**(DE)** Das kann sein. Ist aber derzeit nicht sinnvoll, weil es hier um Cups geht die quasi an einem Stück herunter gespielt werden. Kenne das auch nur so. Ok vllt. hat man das Finale mal gesondert aber da ist das Datum dann sicher von den Veranstaltern festgelegt und nicht von den Spielern.

Datum festlegen ist ja eher etwas das man mit Ligen / Laddern verbindet und das hier ist definitiv keins von beidem.

**(EN)** Maybe. But I do not think that is a good idea, becuase this is about a cup system. Cups usually do not last longer than one day.

Choosing a date seems to be a feature of  a ladder or league system but the cup module is not one of these.
