### ISSUE TITLE
Forum "Bug"

### ISSUE THREAD

**Issue by Longshotpro2** [Contentify/Contentify#3]
I am going to try to keep all the different issues separated into there own issue so that you can keep everything organized and can mark what is done and what isn't, unlike the other issue I posted that has 25 messages :stuck_out_tongue_winking_eye: 

I was messing around on the site and if you go to forums and then click the eSports thread for example it throws a blade error.

"Trying to get property of non-object (View: /var/www/html/app/modules/forums/views/show_forum.blade.php)"

**Comment by chriskonnertz** [comment]
Fixed: https://github.com/Contentify/Contentify/commit/b385e5e1b10438f4eff642fdafe58d2c126f67b7

**Comment by chriskonnertz** [comment]
> I am going to try to keep all the different issues separated into there own issue so that you can keep everything organized

Yes it's more convenient for me.
