### ISSUE TITLE
Reinstall Issue

### ISSUE THREAD

**Issue by stazza** [Contentify/Contentify#30]
Hi I Installed Contenify and want to reinstall it again but it wont let me and comes up with "Contentify already has been installed". I was wondering whether you could help me.

**Comment by BornLuna** [comment]
How did you try to reinstall it? You can delete the database and all the files and install it all over again! Just make sure to backup everything before you delete it

**Comment by stazza** [comment]
Yes I have tried this way.

**Comment by BornLuna** [comment]
Did you try to install a fresh version from git? And what version did you try?

I'll install it now on my dedi server and see if I get the same error.

**Comment by stazza** [comment]
Ill try that tomorrow.

**Comment by chriskonnertz** [comment]
Hello,

stazza did you try to "install the git repo" (= clone the repo then try to install the CMS)?

Most likely the problem is a missing file: `storage/app/.install` This is just an empty file that indicates the CMS is *not yet* installed.

To slove the issue you may create the file by your own or download the deployment-ready version ( https://github.com/Contentify/Contentify/releases/download/v1.1.0/contentify_1_1_0.zip ). It contains the file, so you can copy it to `storage/apps`

PS: Thanks @BornLuna for helping!

**Comment by stazza** [comment]
I didn't install the git repo and I have done a fresh upload

**Comment by chriskonnertz** [comment]
And you did verify that `storage/app/.install` exists?

**Comment by stazza** [comment]
Yes downloaded the other version and tried that.

**Comment by chriskonnertz** [comment]
Please try to call the installer directly: `/install` (for example `http://localhost:8080/contentify/install`)

**Comment by stazza** [comment]
I got it to work with the demo version but it wont let me go to the admin-backend

**Comment by stazza** [comment]
I got the demo version to work but it wont let me into the Admin-Backend and keeps coming up with a error msg 
ErrorException in FileStore.php line 78:
unserialize(): Error at offset 2 of 7593 bytes (View: .com/resources/views/backend/layout_main.blade.php)

**Comment by chriskonnertz** [comment]
Probably a session/cookie error. Delete all files in `storage/framework/sessions` If this does not help delete the cookies of your browser for the website (you may have old cookies from your previous Contentify installation that cause this error)

**Comment by stazza** [comment]
ok so i got everything to work but why does the website have go to /public to actually load?

**Comment by chriskonnertz** [comment]
I wrote a long answer with my iPad, then opned a new tab and when I switched back to the first tab it reloaded. Sometimes Safari on iPad is a nightmare... So, long story told short: The idea id to increase security. Only the public directory should be accessible from the outside so configure your production server that the public dir is the web root.

**Comment by stazza** [comment]
Ah, thank you for your help.

**Comment by chriskonnertz** [comment]
No problem.
