### ISSUE TITLE
Admin broken after change domain

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#301]
Hello, i change domain for my contentify, frontend work great but i have a problem in the backend. The dashboard horizontal widgets works, but if i acces from left menu for example: Esports Content -> Cups redirect me to old website address, this is the problem for all links admin menus. Maybe i miss to change some links somewhere?

**Comment by chriskonnertz** [comment]
Hello,

the menu is not always created dynamically but it is kept in the cache for increased performance. So what you have to do is to clear the cache. Delete the files in the app/storage/framework directory or run the artisan cache clear console command.

**Comment by chriskonnertz** [comment]
PS Here is a guide how to move a Contentify website to another location (server): https://github.com/Contentify/Contentify/wiki/FAQ#how-can-i-move-the-website-to-another-location
