### ISSUE TITLE
Add clear cache command via backend

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#302]

**Comment by kamohy** [comment]
Darf ich noch ein zwei sachen hizufügen ?
so als Anreiz: Clankasse, Teamspeak-plugin, picture watermark (für bilder die hochgeladen wurden mit dem watermark quasi versehen wenn der admin es aktiviert, so is der diebstahl an bilder nicht ganz so hoch) letzteres kann man allerdings auch via grafikprogramme selber machen

**Comment by chriskonnertz** [comment]
Done / fertig:
https://github.com/Contentify/Contentify/commit/7b01e3a1551f8ec4cb612585d3ebd1c414a8cddb

**Comment by kamohy** [comment]
wow das ging fix :o
