### ISSUE TITLE
tipps und tricks

### ISSUE THREAD

**Issue by kamohy** [Contentify/Contentify#303]
Wir basteln ja fleißig auch und probieren rum...
Nun wollten wir unserer Shoubox, etwas gutes tun und ein Avatar der user mit einsetzen...
Schwierig aber nicht unlösbar.
erstma bild mit einfügen das zeitgleich mit als Link für das profil fungiert:
öffnet: app/Modules/Shouts/Resources/Views/widget.blade.php
ersetzt Zeile 6 mit:
`<a class="user" href="{{ url('users/'.$shout->creator->id) }}"><img class="user" src="{{ url('uploads/users/'.$shout->creator->avatar) }}" height="35" style="border-radius:12px;" alt="" title="{!! $shout->creator->username !!}">  {!! $shout->creator->username !!}: </a><span class="text">{!! $shout->text !!}</span>
`
Macht Sinn soweit :-D
Wir haben den originalcode genommen und experimentiert ergebniss man sieht einen Avatar in der shoutbox :) 
Was aber wenn user keinen haben ?

Ab in euren FTP -> uploads -> user: no_avatar.png hochladen

jetzt fehlt aber noch das einbinden, das ist nen ganz einfaches Javascript (keine weiteren angaben nötig)
erweitert euren bildcode nach dem einfügen des bildpfades mit: 
`onerror="this.src='{{ url('uploads/users/no_avatar.png') }}';"`

Euer Code sollte nun so aussehen:

`<a class="user" href="{{ url('users/'.$shout->creator->id) }}"><img class="user" src="{{ url('uploads/users/'.$shout->creator->avatar) }}" onerror="this.src='{{ url('uploads/users/no_avatar.png') }}';" height="35" style="border-radius:12px;" alt="" title="{!! $shout->creator->username !!}">  {!! $shout->creator->username !!}: </a><span class="text">{!! $shout->text !!}</span>`

dieser kleine zusatz im code zeigt alternativ ein bild an, wodurch die shoutbox nicht ganz so komisch aussieht.

![shoutbox](https://user-images.githubusercontent.com/37085865/37782908-66394a6e-2df4-11e8-8c2e-823fe08f910d.PNG)

MFG: Kamohy

**Comment by chriskonnertz** [comment]
Sehr schön, danke fürs Teilen! :)

**Comment by kamohy** [comment]
immer wieder gern

**Comment by kamohy** [comment]
**Kurzlinks erstellen.**

Ihr müsst 2 Datein erweitern.
Nummer 1:
app/Modules/Pages/Http/web.php
sucht zeile 18:
`ModuleRoute::get('impressum', ['as' => 'pages.showImpressum', 'uses' => 'CustomPagesController@showImpressum']);`
dadrunter setzt ihr als bsp.: 
`ModuleRoute::get('gamingstats', ['as' => 'pages.showGamingstats', 'uses' => 'CustomPagesController@showGamingstats']);`
hier sagt ihr schon, wie der kurzlink heißen soll, nehmt euch einfach ein beispiel am impressum.

Datei nummer 2:
app/Modules/Pages/Http/controller/CustomPageController.php

scrollt ganz runter bis ihr das findet:
```
    public function showImpressum()
    {
        $this->show(1, null, true);
    }
```
Jetzt nehmt ihr euch wiede ein beispiel daran kopiert es fügt das darunter wieder ein, dann ändert das nach euren wünschen ab. Hier ein bsp:
```
    public function showGamingstats()
    {
        $this->show(3, null, true);
    }
```

die dateil sollte am ende so aussehen unten:

```
    public function showImpressum()
    {
        $this->show(1, null, true);
    }
	    public function showGamingstats()
    {
        $this->show(3, null, true);
    }
}
```

wenn ihr jetzt eure url im browser eintippt könnt ihr statt sowas hier:
http://domain.usw/pages/3 einfach das eintippen 
(bezug ist jetzt das beispiel)
http://domain.usw/gamingstats

wenn ihr das innerhalb der seite verlinken wollt ist das möglich einfach:
/gamingstats (bzw. euren erschaffenen link)
