### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by johanbosman** [Contentify/Contentify#305]
Hi Im desprettly trying to install contentify and are very close to giving up. 

I first installed 2.2 after lots of things broken and again fixed on my whm server with 60 client domains. 
I managed to get it installed. I logged in and it is just error on error. 

I deleted everything and downloaded 2.3, now I just can't install it at all, first when I go to the public folder it gave green on everything but there was an error for line 69 : Call to undefined function apache_get_modules . 

So I tried to fix this and now when I go to domain/public/   it just downloads something if I go to domain/public/install.php then it just downloads the install.php file. 

Im lost I don't know how to fix or install this any more, not at all sure what to install what mod what php etc. 

Any help will be appreciated. 

Ok so after doing lots of mod installs and fixes I managed to pass this point. 

Now when I click on launch the installer, it says the following: Please enable the debug mode to start the installer.

got it installed when I changed in app.php the false to true for debug.

**Comment by chriskonnertz** [comment]
Hello,

the setup + configuration can be a real challenge. A lot of persons have trouble to setup Contentify. Therefore we plan to create a service that helps with the hosting part.

Did you manage to setup it?

**Comment by johanbosman** [comment]
Hi Chris, 

Yeah at long last I did manage to set it up. I must tell you I really battled. But I also learned a lot. haha

**Comment by chriskonnertz** [comment]
Okay fine, I'm glad you made it!

**Comment by kodxana** [comment]
@johanbosman Can you tell me how did you solved '''Call to undefined function apache_get_modules() in''' problem?

**Comment by chriskonnertz** [comment]
Hello,

maybe it helps to open `public/install.php` with a text editor and remove line 69-74 ( https://github.com/Contentify/Contentify/blob/v2.5/public/install.php#L69 ).
