### ISSUE TITLE
Pubg tournaments

### ISSUE THREAD

**Issue by johanbosman** [Contentify/Contentify#306]
Is there a way to setup a pubg tournament. 

100 players in either solo, duo or teams of 4 players. 

1 match, for instance, will then either have 100 solo players or 50 duo teams or 25 x 4 player squads. 

Points are normally calculated per player for solos or per team for duos and squads. 

Points will be awarded for your position that you or your team is eliminated. as well as points awarded for the amount of kills you, or your team gets per game. so 10 points per kill and then depending on your position a number of points. 

a tournament like this should be able to run for any amount of matches 1 match per week or more.

**Comment by chriskonnertz** [comment]
Hello,

> 1 match, for instance, will then either have 100 solo players or 50 duo teams or 25 x 4 player squads.

A match has two participantss (usually two players _or_ two teams). That's it. More than two is not possible.

**Comment by johanbosman** [comment]
Do you think a plugin like this is possible? If I hire someone to make it?

**Comment by chriskonnertz** [comment]
Yes, definetly. :)
