### ISSUE TITLE
Icons lost

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#307]
Hello! I lost my all icons from website. After update from 2.0 at 2.2. I attach some screens. I search in widget_cups_control.blade.php for example and there are for cups a "crosshair" icon but on front is not displayed.
 Social links from header & footer, Add friend, PM and Events Crosshair
![events](https://user-images.githubusercontent.com/29990653/37854158-6345ff24-2ef2-11e8-8db0-5bb647a9fab7.JPG)
![social links](https://user-images.githubusercontent.com/29990653/37854160-6364d638-2ef2-11e8-89c4-07fab0102e86.JPG)
![user links](https://user-images.githubusercontent.com/29990653/37854161-6381af10-2ef2-11e8-99cd-5fb5b0b5fd17.JPG)

I think i do something wrong?

Late edit: I saw a problem with Forgor password, if i hit the button don't make anything.

**Comment by chriskonnertz** [comment]
Hello,

please take a look at the HTML code of the page (in your borwser, go to the main brwoser menu, then go to "page" or "developer", then go to "sho source" or something similar).  Starting in line 21 (or close to this line) there should be code similar to this:

```
<link media="all" type="text/css" rel="stylesheet" href="http://localhost/contentify2/public/vendor/font-awesome/css/fontawesome-all.min.css">

  
<link media="all" type="text/css" rel="stylesheet" href="http://localhost/contentify2/public/css/backend.css">
  
<link media="all" type="text/css" rel="stylesheet" href="http://localhost/contentify2/public/vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.css">
  
<link media="all" type="text/css" rel="stylesheet" href="http://localhost/contentify2/public/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css">
```

Then click on This URL (it should be higlighted): `http://localhost/contentify2/public/vendor/font-awesome/css/fontawesome-all.min.css`

Is your browser able to open this file? If not make sure the file exists. If it does not  exist, you can get it here: https://github.com/Contentify/Contentify/blob/v2.2/public/vendor/font-awesome/css/fontawesome-all.min.css

**Comment by chriskonnertz** [comment]
> I saw a problem with Forgor password, if i hit the button don't make anything.

Thank you for reporting this bug! Bugfix: https://github.com/Contentify/Contentify/commit/5902aa418253f2e9f6c865a28c6e8b376b2b0298

(I assume the easy way for you to apply this bug fix is by just copy + paste the change manually. But pay attention, your file might look a bit different - only apply the change, do not change something else!)

**Comment by khalifaone** [comment]
Thank you @chriskonnertz i solved problem with Reset Password. Im working at FontAwesome Icons to fix.

**Comment by chriskonnertz** [comment]
Nice!

PS: You are still using FontAwesome 4 right? FontAwesome 5 has removed and renamed a lot of icons so this could be a problem but in this case not all of the icons should appear, only some of them... So I guess this is not the problem. However, I want to mention it, just in case.

**Comment by khalifaone** [comment]
Hello! Sorry for posting again.. But problem is still there.. I check my font-awesome css from vendor. File are there and i updated with your last version 5.0.1. I attach some screens from Chrome Console..
![nowshow](https://user-images.githubusercontent.com/29990653/37896582-c878972a-30ec-11e8-8e67-2067a92c6f2e.JPG)
![snip11](https://user-images.githubusercontent.com/29990653/37896583-c8991e0a-30ec-11e8-86ee-b9400c722b68.JPG)
If i put css code in console its works..

**Comment by chriskonnertz** [comment]
When I go to your website, I can see all the icons:

![screenshot_website](https://user-images.githubusercontent.com/4319323/37925180-3d2bf426-3134-11e8-91f2-18945662cea1.jpg)

(I did hide some parts of the website since I do not know if this website is ready for launch.)

Are you sure it is not a caching problem of your browser? Please visit the website with Microsoft Internet Explorer / Edge to validate my theory.

**Comment by khalifaone** [comment]
Sorry. i forgot to annouce you! I made an update at v2.3 and are all good now!Thank you and one again sorry for not posting new updates!

**Comment by chriskonnertz** [comment]
Okay, great!
