### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by MrcillerYT** [Contentify/Contentify#309]
Ich kann mich nicht auf der Website einloggen seit dem update

**Comment by chriskonnertz** [comment]
Hallo,

Update auf 2.3? Eigentlich sollte es seitdem wieder gehen :)

Schau mal bitte ob die Datei `Contentify/app/Modules/Auth/Http/web.php` diesem Stand hier entspricht:
https://github.com/Contentify/Contentify/blob/2.4-dev/app/Modules/Auth/Http/web.php

**Comment by MrcillerYT** [comment]
ok bei 2.3 kann ich install.php nicht ausführen D: da es mich zu install immer umleitet

**Comment by MrcillerYT** [comment]
so gefixed nur jetzt kommt dass 
(1/1) ErrorException
is_executable(): open_basedir restriction in effect. File(/opt/plesk/php/7.0/bin/php) is not within the allowed path(s): (/var/www/vhosts/esportcillerian.eu/:/tmp/)

**Comment by MrcillerYT** [comment]
so jetzt habe ich einen neuen error beim installieren 
ErrorException in Migrator.php line 252:
Undefined index: 2014_07_02_230147_migration_cartalyst_sentinel

**Comment by chriskonnertz** [comment]
Das hier gesehen / probiert? https://github.com/Contentify/Contentify/wiki/Troubleshooting#installation-error-message-fatalerrorexception-in-migratorphp

**Comment by MrcillerYT** [comment]
ok ich habe es jetzt auf einen neuen Server installiert da es beim alten Server zu viel Probleme gibt ich bekomme diesen Fehler 

Please enable the debug mode

**Comment by chriskonnertz** [comment]
Ok, öffne bitte die Datei `config/app.php` mit einem Texteditor: https://github.com/Contentify/Contentify/blob/2.3/config/app.php#L39
In Zeile 39 kannst du den Debug-Modus anschalten in dem du `false` durch `true` ersetzt.

**Comment by MrcillerYT** [comment]
so auf meinen VServer gehts aber auf meinen Webspace nicht XD danke für die Hilfe

**Comment by MrcillerYT** [comment]
ok mir ist auch noch aufgefallen hin und wieder werde ich auf meine Server ip geleitet und nicht auf die Domain

**Comment by chriskonnertz** [comment]
Hm, hat das jetzt eher was mit der Server-Config zu tun oder mit dem CMS?

**Comment by MrcillerYT** [comment]
Weiß es nicht .-.

Chris Konnertz <notifications@github.com> schrieb am So., 1. Apr. 2018,
15:48:

**Comment by chriskonnertz** [comment]
Hast du denn Beispiele wann du auf die IP umgeleitet wirst? (Zum Beispiel sowas wie beim Login)

**Comment by MrcillerYT** [comment]
Wenn ich ihm adminmenü bin oder wenn ich ca 10 min immer auf verschiedene
seiten gehe

Chris Konnertz <notifications@github.com> schrieb am So., 1. Apr. 2018,
15:51:

**Comment by chriskonnertz** [comment]
Hast du mal den Cache gelöscht? Das Admin-Menü wird nich bei jedem Aufruf neu erzeugt sondern es wird gecacht, du könntest daher einen alten Stand haben. Lösch mal die (Unter-)Ordner in `app/storage/framework/cache`.
