### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Nighteyess** [Contentify/Contentify#31]
When i want to install the Page i got an error on page 5 (User Data):

PDOException in Connector.php line 55:
SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

By the Database selection i dont get an Error...

**Comment by BornLuna** [comment]
You need to change the database user and password so they are correct

**Comment by Nighteyess** [comment]
Hey, thank you for your replay. I looked the video step by step and the developer from this cms dont changed the user and password. He just got the notice "The current Database is contentify". Thats by page 3. But i must fill in my data why?

**Comment by BornLuna** [comment]
I'm currently out at a business dinner, when I get home I'll check it out again :)

**Comment by Nighteyess** [comment]
Oh ok in germany its now 11pm 
Thank you Sir.

**Comment by chriskonnertz** [comment]
Hello, 

as @BornLuna says: check the database connection setting in `storage/app/database.ini`.

The video is not 100% up-to-date. When it was created the form that let you fill in the database credentials missed.

However thjis might be odd. I'll go through the installation the way the video discribes it tomorrow to see if it's confusing.

Thanks for your feedback. It will help to make the installation easier.

PS: Ich komme auch aus Deutschland. :)

**Comment by Nighteyess** [comment]
Thank you Chris,

2 minutes ago the installation was successfull :+1:  :)

P.S. Ich weiß habe dir bereits ne Mail geschrieben ;)

**Comment by sarkye** [comment]
could you please clarify the solution ?

**Comment by Nighteyess** [comment]
I dont know why the installation was successfull. i try to reproduce the failure and write down the solution.

**Comment by sarkye** [comment]
that would be great thank you

**Comment by Nighteyess** [comment]
Ok now i reproduce the failure. The autoinstaller doesnt fill the line 57 and 78 in the config/database.php
when you fill it manually the installation goes trough without any issues.

**Comment by sarkye** [comment]
weird it seems to get connected to my droplet, but just doesn't know my database.

PDOException in Connector.php line 55:
SQLSTATE[42000] [1049] Unknown database 'contentify'

**Comment by sarkye** [comment]
installed phpmyadmin to add the database, this worked!

**Comment by Nighteyess** [comment]
Yeah i had the same issue at the beginning. But after a new droplet reinstallation fixed that issue

**Comment by chriskonnertz** [comment]
Added a note to the YouTube video.

Issue closed.
