### ISSUE TITLE
Rank / Level user ribbon

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#310]
Is possible to make an options for users to have an ribbon? Me as admin i want to give an "CUP" for players how win my events. Is possbile to improve this? I need to select and attrib manualy this option only for event winners.

Thank you!

**Comment by chriskonnertz** [comment]
Hello,

well yes it is possible to code this. I will try to keep it in mind. However, to be honest, it does not have a very high priority right now.
