### ISSUE TITLE
Show streams only if they are live [enhancement]

### ISSUE THREAD

**Issue by Gicminos** [Contentify/Contentify#311]
Do you have in project to code a feature for show particular streams only if they are live?

Reagards

**Comment by chriskonnertz** [comment]
Hello,

I do not understand. :/

Please tell me in more detail what change you are suggesting?

The streams widget already prioritises streams that are online over those that are offline.

**Comment by Gicminos** [comment]
Yes, I'm propousing to totally hide the offline streams from the widget, or make an option to do that.

**Comment by chriskonnertz** [comment]
Okay, got it. For now, you can use CSS to hide the offline streams:

```
.widget-streams li.offline { display: none }
```
