### ISSUE TITLE
Custom Page

### ISSUE THREAD

**Issue by kamohy** [Contentify/Contentify#312]
Hallo Chris, deine anleitungen sind leider nicht immer aufschlussreich.
Das ist schade, denn du bietest in einigen fällen unterschiedliche dinge an.
genauer gemeint sind Pages/Seiten
okay normale Seite -> pages/(id)
Blogs -> article
Custom Content -> ???? folgendes ergebniss habe ich nun
bei Custom Content, sind wohl direckt die überschriften, allerdings sehe ich dann nur eine Weiße Seite 
(auch kein Quelltext)
(bsp.: https://kamohy.de/test ) test ist in diesem fall die überschrift der custom content.
Muss ich die custom content speziell aufbauen?
Ich habe unter module nachgesehen, und finde dort irgendwie auch keine lösung.

Ich weiss nun nicht ob es ein Bug ist deswegen ersteinmal hier.

Lass dir Zeit geniesse Ostern. :-)

**Comment by chriskonnertz** [comment]
Hallo,

eine Page vom Typ "Custom Content" hast du ja erstellt, dann geh mal in den Editor und klick auf "Insert Template":

![editor_templates](https://user-images.githubusercontent.com/4319323/38173678-ddcf96a2-35c2-11e8-8219-6894e66cc37b.png)

"Custom Content" sind Snippets die man als Editor-Vorlagen nutzen kann.

Womit du leider recht hast ist, dass solche an sich nützlichen Infos nirgendwo klar dokumentiert sind. Das ist wirklich ein Nachteil den man irgendwann mal beheben müsste. Nachdem zahlreiche noch drängendere Probleme gelöst wurden. ;)

**Comment by kamohy** [comment]
sehr gut ich danke.

**Comment by kamohy** [comment]
gemacht, dann steht da die überschrift als auswahl und die seite bleibt weiß... was nun ?

**Comment by chriskonnertz** [comment]
Drauf klicken :D Dann wird der Inhalt in den Editor eingefügt. Dazu muss natürlich Inhalt zum Einfügen vorhanden sein, 

Wobei ich gerade sehe, das ist etwas ungünstig, es dauert bei mir recht lang mit dem Einfügen und dann klickt man doppelt... und hat es doppelt drin... denke das werde ich mir mal anschauen.

> Womit du leider recht hast ist, dass solche an sich nützlichen Infos nirgendwo klar dokumentiert sind. Das ist wirklich ein Nachteil den man irgendwann mal beheben müsste

Halbe Lösung dafür: Habe es ins Wiki mit aufgenommen. Weiß nicht ob das da irgend jemand findet aber zumindest besteht die Chance. https://github.com/Contentify/Contentify/wiki/Built-In-Modules#pages

**Comment by chriskonnertz** [comment]
> Wobei ich gerade sehe, das ist etwas ungünstig, es dauert bei mir recht lang mit dem Einfügen und dann klickt man doppelt... und hat es doppelt drin... denke das werde ich mir mal anschauen.

https://github.com/Contentify/Contentify/commit/ad8e005719603c68798a8cd62233b433670ee541#diff-a0e32cc903087aaddef1b9444fdd06d1
