### ISSUE TITLE
Reset Password Error

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#313]
Hi, i found another error, i fix first error at Reset Password after you who me the bug fix. But now i found this. After i enter the email and confirm code it show me this.
![error-reset](https://user-images.githubusercontent.com/29990653/38316060-81e4dbaa-3832-11e8-829d-5a54e4ffe843.JPG)

**Comment by chriskonnertz** [comment]
Hello,

Thank you for reporting this bug. I assume I can fix it tomorrow.

**Comment by khalifaone** [comment]
Any news? :D

**Comment by chriskonnertz** [comment]
Hello,

I totally forgot this issue. :/

Well, here is the bug fix: https://github.com/Contentify/Contentify/commit/e1a7201d0aea8bb7a032185c8636ee070e0d3183

**Comment by khalifaone** [comment]
Sorry for re-open this post, but now all works, but that form dont send the email with password reset link.. I try 3 times but i didn't revice anything.

Thank you!

**Comment by niclasreich** [comment]
Hi @khalifaone - open up `<Contentify>/config/mail.php` and in line 19, set `'driver' => env('MAIL_DRIVER', 'mail'),`, so Conentitfy will send via the php-function. (by the way, would recommend that as a default setting @chriskonnertz)

**Comment by chriskonnertz** [comment]
Is it not the default setting? Which version do you use?

https://github.com/Contentify/Contentify/blob/v2.3/config/mail.php#L19 (v2.3 release tag)
