### ISSUE TITLE
I can not install ,help

### ISSUE THREAD

**Issue by okonstantinyuk** [Contentify/Contentify#314]
Not Found
The requested URL /install.php was not found on this server.

Apache/2.4.7 (Ubuntu) Server at 185.43.7.4 Port 80

**Comment by okonstantinyuk** [comment]
Wed Apr 04 19:35:06.975463 2018] [:error] [pid 8441] [client 188.120.252.89:36644] PHP Fatal error: require(): Failed opening required '/var/www/html/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/bootstrap/autoload.php on line 17, referer: http://185.43.7.4/public/install.php  
Error in logs

**Comment by chriskonnertz** [comment]
Hello,

it seems you do not have the vendor libraries in `<contentify-path>/vendor` installed.

a) Install them via console: `php composer.phar install`
b) Download the production package and use it or copy the vendor directory https://github.com/Contentify/Contentify/releases/download/v2.3/contentify_2_3.zip

**Comment by okonstantinyuk** [comment]
how much does it cost to install this product from you ?

**Comment by chriskonnertz** [comment]
Currently we do not offer this service. :/
