### ISSUE TITLE
CSS wird nicht übernommen

### ISSUE THREAD

**Issue by kamohy** [Contentify/Contentify#315]
Ich habe sämtliche grunddaten aus dem Template übernommen.
Jedoch, ist es egal ob ich etwas in die .css oder .less schreibe (auch beides),
sie werden nicht übernommen.
Die ordnerstrucktur wurde genauestens übernommen.
Ich habe das Template in die .json eingetragen, auch den cache unter storage, habe ich gelöscht.
Hast du da nen Tipp für mich ? ich würd gerne aus meinem Rohling ein Template machen. :D

**Comment by chriskonnertz** [comment]
Hallo,

- also du hast ein eigenes Theme gebaut in einem eigenen Unter-Ordner in `app/Modules`?
- bist du auf v2.3 oder auf 2.4? Hier unterscheidet sich wie CSS-Dateien gebaut werden.

Also der "Königsweg" ist eine .LESS-Datei zu schreiben. Muss man natürlich nicht aber LESS bringt eine Menge Vorteile mit sich und es ist insofern leicht damit einzusteigen, weil jede CSS-Datei auch eine LESS-Datei ist, also kann man mit purem CSS anfangen und dann das von LESS ergänzen was einem gefällt.

Die LESS-Datei muss dann natürlich zu einer CSS-Datei kompiliert werden.Hier gibt es keinen fest vorgeschriebenen Weg, sondern im Wesentlichen diese drei Optionen:
- Mit einem völlig externen Programm kompilieren, ich habe dazu Koala benutzt ( http://koala-app.com/ ) Man muss dann manuell den Kompilierungsprozess anstoßen oder das Programm erkennt Änderungen an der LESS-Datei und kompiliert automatisch
- Mit Gulp. Auch ein externes "Programm" (eher Skript), wird aber von Contentify über mitgelieferte Dateien ( vor allem https://github.com/Contentify/Contentify/blob/2.3/Gruntfile.js ) direkt unterstützt. Muss aber installiert werden, wo man dann in der Node.js / NPM-Schiene landet. Ist am Anfang etwas fummelig.
- Mit 2.4 gibt es daher eine Alternativlösung, nämlich hat Contentify nun einen integrierten LESS-Compiler auf PHP-Basis. Denn kann man über ein Konsolenkommando (`php artisan less:compile`) starten oder im Backend unter Einstellungen der Button "LESS kompilieren"

Jetzt das Problem was bei dir wahrscheinlich zum Tragen kommt: Hat man die CSS-Datei erzeugt muss sie an die richtige Stelle kopiert werden: `public/css/frontend.css` Das kann man manuell machen. Das Kommando in v2.4 macht das selber. Eigentlich soll es aber so sein, dass wenn der Admin im Backend ein anderes Theme auswählt, die CSS-Datei des Themes nach `public/css/frontend.css` kopiert wird. D. h . dazu muss die CSS-Datei im Theme-Order liegen. Beispiel: `/app/Modules/PhobosTheme/Resources/Assets/css/frontend.css` Woher weiß nun aber PHP was wohin kopiert werden muss? Das steht im ServiceProvider des Modules/Themes. Beispiel: https://github.com/Contentify/Contentify/blob/2.3/app/Modules/PhobosTheme/Providers/ModuleServiceProvider.php#L21

**Comment by kamohy** [comment]
ich mach noch alles von hand :D 
jedoch bekommen wir bei uns 2.4 nicht zum laufen sonst würde es wohl leichter sein...
wir haben immer noch eine weiße seite unter contentify.kamohy.de/public/
deine Vendor hat leider auch nicht geholfen :-/

**Comment by chriskonnertz** [comment]
Wahrscheinlich fehlt dir auch was in der Datenbank aber das dürfte eigentlich nicht kritisch sein. Würde es dir helfen wenn ich dir komplett mal meinen Ordner mit allen Dateien plus die Datenbank gebe?

**Comment by kamohy** [comment]
ich glaube das könnte echt helfen, hab schon überlegt einfach ein vorhandenes Template zu überarbeiten.
Aber umgestalten ist schwerer, als neu schreiben.
Neu, weiss man wo alles steht, das macht es einfacher.

Wär also wirklich mal nett wenn du das teilen könntest.
(in der DB steht eigentlich nicht wirklich viel über Themes. Das, das ich erstellt habe wird ja im CMS selbst auch angezeigt nach dem ich es in die .json eingetragen habe.)

**Comment by chriskonnertz** [comment]
Hey, wenn bei dir 2.4 hoffentlich nun läuft könntest du mal in den Einstellungen das "LESS kompilieren" testen, weil dann kann man hier eventuell mal zu machen :)
