### ISSUE TITLE
Morpheus Module LESS Compile

### ISSUE THREAD

**Issue by andakawa** [Contentify/Contentify#318]
Hi, erst einmal vielen Dank für dieses großartige CMS!

Ich habe Contentify auf einem Webspace installieren können und möchte jetzt gerne die Grundfarbe vom Morpheus-Theme ändern.

Meine Webentwicklungs-Kenntnisse hören bereits bei den Grundlagen auf, ich habe jedoch kappiert, dass man eine Less-Datei schreibt, da man mit wenigen Zeilen eine komplexere Verhaltensweise in CSS beschreiben kann.Nun habe ich in der Less-Datei die Grundfarbe (blau) zum Test auf einen rötlichen Ton gesetzt, das ganze mittels https://leafo.net/lessphp/editor.html kompiliert und beide Dateien wieder in die entsprechenden Ordner des Morpheus-Theme Moduls gepackt.

Im Anschluss habe ich den Cache geleert und im Backend das Theme auf ein anderes und wieder zurückgestellt, um eine eventuell eingebaute Funktion anzustoßen

Die Farbe wurde übernommen aber das Theme wurde zerschossen - also die gleiche Prozedur mit dem Original-CSS/Lesss und es war wieder normal.

Ich hänge laut Backend-Footer auf Version 2.2, erinnere mich aber daran, 2.3 händisch eingespielt zu haben.

Gibt es da etwas, was ich übersehen habe?

LG

**Comment by chriskonnertz** [comment]
Hallo,

>  vielen Dank für dieses großartige CMS!

Bitte. Danke. Oder so. ;)

> Meine Webentwicklungs-Kenntnisse hören bereits bei den Grundlagen auf, ich habe jedoch kappiert, dass man eine Less-Datei schreibt, da man mit wenigen Zeilen eine komplexere Verhaltensweise in CSS beschreiben kann

Ja genau das trifft es ganz gut.

> Nun habe ich in der Less-Datei die Grundfarbe (blau) zum Test auf einen rötlichen Ton gesetzt, das ganze mittels https://leafo.net/lessphp/editor.html kompiliert

Die Idee ist gut, die hatte ich auch. Aber ich fürchte sie funktioniert leider nicht, weil die `frontend.less` bzw. `backend.less` via `@import` andere LESS-Dateien einbindet. Die wiederum andere einbinden... Und genau dieser Satz an LESS-Dateien fehlt dann. Hierzu könnte dieser Kommentar hilfreich sein: https://github.com/Contentify/Contentify/issues/315#issuecomment-379534762

Würde dir wohl zu Koala raten, wenn ich mich richtig erinnere musst du da nur einmal die .LESS-Datei einbinden und dann kompilieren und das war's. Imports werden automatisch geladen. Sollte also funktionieren.

> Ich hänge laut Backend-Footer auf Version 2.2, erinnere mich aber daran, 2.3 händisch eingespielt zu haben.

Kann sein dass die Versionsangabe "2.2" in der Datenbank gespeichert ist. 
a) Die korrekte Angabe findest du in der Datei `config/app.php` (Zeile 52 circa)
b) Per phpMyAdmin könntest du sie in der Datenbank ändern, dazu in die Tabelle `config` und dort den die Spalte `value` anpassen in der Zeile in der die Spalte `name`= `app.version` ist

Ansonsten wird es wie oben in dem verlinkten Kommentar so sein, dass man in v2.4 per Button im Backend die CSS-Dateien generieren lassen können wird. Sobald v2.4 final draußen ist.

**Comment by andakawa** [comment]
Hi,
danke für die Antwort :)

Den verlinkten Kommentar habe ich bereits vor meinem Posting hier studiert - leider hat Koala die Imports nicht lesen können, weshalb ich dann diese Online-Alternative nutzen musste.

Vermutlich reicht es nicht, die Less-Datei vom Desktop in Koala zu ziehen und man muss im gesamten Contentify-Verzeichnis arbeiten? Ich werd's versuchen :)

Ansonsten warte ich einfach auf v2.4.

VG
andakawa

**Comment by chriskonnertz** [comment]
Hallo,

> Vermutlich reicht es nicht, die Less-Datei vom Desktop in Koala zu ziehen und man muss im gesamten Contentify-Verzeichnis arbeiten? Ich werd's versuchen :)

Gewisser maßen doch, das reicht, weil Koala die Importe selber lädt. Darum muss man sich nicht kümmern.

**Comment by chriskonnertz** [comment]
Version 2.4 kommt so circa in 10 Tagen. Ich mache daher hier mal zu um aufzuräumen.
