### ISSUE TITLE
Error Directory 'public':	Not writable

### ISSUE THREAD

**Issue by smen8** [Contentify/Contentify#319]
Hi, I have this problem, Directory 'public':	Not writable.
I would like to know why it happens. I'm trying to upload this to the cloud.

**Comment by kamohy** [comment]
Hey guy, use you`re FTP-Ptrogram, connect with the server.
Click with right of the public-directory and go on rights
here set it on 777
the directory: storage
need this rights too

**Comment by smen8** [comment]
What happens is that I'm uploading this cms to the cloud, and I'm working with Google Cloud Engine. At the time of lifting the dispute to install it is that the sale this error.

**Comment by smen8** [comment]
it's more when I work locally everything works fine.

**Comment by chriskonnertz** [comment]
Hello,

well, I guess that you are working locally on a Windows system while the cloud space uses Linux. On Windows permissions are not a big thing so you do not really have to care about them. On Linux  however permissions are an important topic.  Therefore you have to tell the cloud to allow the CMS to write stuff into the `public` directory. It needs to do this when it uploads files, for example images. That's perfectly normal. It depends on your cloud space how to set these permissions. You have to set them to "777" which means all permissions.

**Comment by smen8** [comment]
Locally I'm working on Linux and if you have the permissions that you ask for in the installation, that's why I told you that locally it works well. But I'll look for another way to do it.

**Comment by chriskonnertz** [comment]
Hello,

it is hard to help you in this case, since this seems to be an issue specifically of your server environment.

Did you changed the permissions of the `public` directory and of all sub directories? This is important and if you change the permission via console you have to use the `-R` parameter (r=recursive).: `chmod -R 700 /foo/bar`
