### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Nighteyess** [Contentify/Contentify#32]
Is there an updater in the future? I dont want to code the whole page new with the next update 2.0 (Announcement Twitter).

**Comment by chriskonnertz** [comment]
Yes there will be an update path so you do not have to recode the whole website.

**Comment by chriskonnertz** [comment]
But you will habe to reinstall the Website due to database changes.

**Comment by Nighteyess** [comment]
hmm ok. And why you dont have a forum for questions and Ideas? On Github its very complicated to discuss...

**Comment by chriskonnertz** [comment]
I never felt it was "very complicated" but I agree that some sort of an additional forum might be a good idea. 

However, the answer to your question is: Using GitHub's issue section does not require any further effort. It's a free & available solution. Until now there has not be much user activity so I thought using GitHub does the trick.

**Comment by shoostar** [comment]
Just a thought, but maybe you could look into [Gitter](http://gitter.im). Looks like it's free to start out small, and while I can't attest to how fluid the administration end of things works, everything works great from the perspective of the average end user. It has some deep integrations with Git, which is certainly a nice feature to have.

**Comment by Nighteyess** [comment]
Hey Chris,

when you want i can install and design a simple forum for this CMS. Iam very happy that you and your staff develop a fresh, simple and modern Content Management System,

**Comment by chriskonnertz** [comment]
Hello Nighteyess,

thank you for your offer. I really appreciate it (and I'm not just writing this to be polite). :)

However, I do not like the idea of letting someone "external" host official parts / websites of Contentify. These parts / websites would not be under my control. I would not have any gurantee that the hosting continues in the long-term. Maybe your personal interests change some day and you do not want to continue to maintain the forum(s).

Therefore I have to reject your suggestion. I hope you understand my motivation.

**Comment by zEnry185** [comment]
So, with the database update... will we lose all match/news/users/stats ?

**Comment by chriskonnertz** [comment]
I don't know. Most likely not *all* if you are willing to import tables from your old database to your new.

**Comment by chriskonnertz** [comment]
@shoostar

> Just a thought, but maybe you could look into Gitter. Looks like it's free to start out small, and while I can't attest to how fluid the administration end of things works, everything works great from the perspective of the average end user. It has some deep integrations with Git, which is certainly a nice feature to have.

You were right back in 2016. Finally decided to give Gitter a try: 

https://gitter.im/Contentify/
