### ISSUE TITLE
Startseite ändern

### ISSUE THREAD

**Issue by kamohy** [Contentify/Contentify#321]
Moin Moin oder nabend.
@chriskonnertz ich weiss ich kann echt nerven :D 
Aber kann ich irgendwo die Startseite abändern?
Also statt News einen content laden oder so ?
Das wär echt gut :D

**Comment by chriskonnertz** [comment]
Hallo,

ja kannst du aber das musst du dann direkt im Code machen und könnte durch künftige Updates wieder überschrieben werden.

Diese Zeile musst du ändern: https://github.com/Contentify/Contentify/blob/2.3/routes/web.php#L22
Genauer gesagt nur den Teil hinter 'uses'.

Wie genau hängt davon ab was du machen willst, per default wird ein Controller ( `App\Modules\News\Http\Controllers\NewsController` ) geladen und eine Methode von ihm aufgerufen ( `showStream` ).

Wahrscheinlich wäre aber so was das richtige:
```
 Route::get('/', ['as' => 'home', 'uses' => function() {
    // 1 durch gewünschte Page-ID ersetzen!
    return redirect()->action('App\Pages\Http\Controllers\PageController@show', [1]);
};
```

Irgendwie so, das habe ich jetzt nicht getestet. 

> ich weiss ich kann echt nerven :D

Np ;)

**Comment by kamohy** [comment]
ich danke dir :-) 

Da ich inzwischen weiss, wie man kurzlinks setzt :D (hab einfach nachm Impressum gesucht wie bescheuert :D) kann ich das auch anders machen denke ich 🗡 

Aber wie gesagt danke 👍

**Comment by kamohy** [comment]
Also geklappt hat es, wie ich es mir vorgestellt habe.
```
 else {
    Route::get('/', ['as' => 'home', 'uses' => 'App\Modules\Pages\Http\Controllers\CustomPagesController@showWillkommen']);
}
```
da ich es vorher auch als kurzlink eingefügt habe

so nu die preisfrage :D 
Wie kann ich die News aber so verschachtelt wie sie dort warn aufrufen ? Ö.Ö
denn vom look her find ich sie cool :D und nicht so wie unter /news 
dann :D

**Comment by chriskonnertz** [comment]
Hat sich das erledigt? Bin mir ansonsten nicht ganz sicher wie du das meinst.

**Comment by kamohy** [comment]
Ich hab die Willkommen seite erstellt, dies sollte die startseite werden.
dann hab ich mir ein beispiel am Impressum genommen, das du als kurzlink eingefügt hattest.
hab also aus /pages/2 einfach als Link /willkommen erstellt.
Dann hab ich dort wo du es mir gesagt hast gesucht. und den code eingefügt den ich oben geschrieben habe.

Nur eines find ich schade. das wenn ich jetzt domain.usw/news eingebe sieht das eher nach einem Archiv aus.
da hät ich es gern wie es auf der startseite eigentlich ist. (also nach normaler installation)

**Comment by chriskonnertz** [comment]
Hm, ich dazu müsstest du glaube ich die Route ändern.

Du könntest ziemlich am Anfang der Datei `routes/web.php` einfügen:

`Route::get('/news', 'App\Modules\News\Http\Controllers\NewsController@showStream']);`

Wenn das nichts bewirkt ersetze das hier https://github.com/Contentify/Contentify/blob/2.4/app/Modules/News/Http/web.php#L21 mit der Zeile von oben.
