### ISSUE TITLE
Error Admin

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#322]
When i try to delete an user:
![delete-user](https://user-images.githubusercontent.com/29990653/38768710-862c19d2-4000-11e8-956e-228c883da324.JPG)

**Comment by chriskonnertz** [comment]
Hello,

it seems that a field (attribute / column) in a table of your database is missing.

Please find out if the `cup_points` attribute exists in the `users` table in the database.

If it is missing, you may try this MySQL statement to add it:

```
`ALTER TABLE `users`  ADD  `cup_points` int(11) NOT NULL DEFAULT '0'
```

(I did not test it)
