### ISSUE TITLE
Signatur

### ISSUE THREAD

**Issue by MrcillerYT** [Contentify/Contentify#323]
Wie kann ich bei einer Signatur ein Bild/Gif einfügen

**Comment by kamohy** [comment]
also ich vermute, wenn dann über bbcode's
ein standart davon währ: `[img]bild-url[/img]`
ansonsten weiss ich es auch gerade nicht.

**Comment by MrcillerYT** [comment]
habe ich schon versucht geht leider nicht D:

**Comment by chriskonnertz** [comment]
Hello,

in the current implementation the signature can only be  a plain text string.

- If you add HTML, the tags will pre printed as text, not as HTML 
- If you add BBCode, the tags will be printed as text, not as BBCode

Allowing users to add HTML code to their ...
... warum schreib ich eigentlich auf Englisch? :D 

Also kurz gesagt, HTML-Code erlauben ist keine Option -> unsicher.
Was man machen könnte wäre BBCode-Tags erlauben.

Haltet ihr das für sinnvoll?

**Comment by MrcillerYT** [comment]
Ja

Chris Konnertz <notifications@github.com> schrieb am So., 15. Apr. 2018,
16:38:

**Comment by kamohy** [comment]
Also meiner meinung nach würde ich BBCodes erlauben (aber im adminbereich auch deaktivierbar machen.
Gerade im Forum, finde ich es praktisch, vor allem aber auch für leute die, diese nicht kennen, irgendwie eine hilfe (inform eines editors, wie hier bei github in der comment-function) 
Aber ich glaube wiederum nicht, das es eine hohe prio. hat.

**Comment by MrcillerYT** [comment]
BBCodes wären perfect für mich 👍

**Comment by kamohy** [comment]
@Pega16 und ich hatten das auch schonmal angeregt, jedoch wie gesagt, es ist nicht absolut notwendig (mein empfinden und das als forenuser.

**Comment by chriskonnertz** [comment]
Ok, wird (vermutlich zeitnah) eingebaut, vermutlich auch mit An/Abschalt-Option im Backend.

> eine hilfe (inform eines editors, wie hier bei github in der comment-function)

Ja das sollte eigentlich kommen aber ich hab dem erst mal eine niedrigere Prio gegeben. Weil es ein paar Fragen aufwirft und eher eine größere Aufgabe ist. Daher wird das erst mal verschoben und anderes vorgezogen.

PS: Issue bitte nicht schließen, dient mir als Reminder.

**Comment by MrcillerYT** [comment]
ok danke 👍

**Comment by chriskonnertz** [comment]
In To-Do-Liste für v2.5 https://github.com/Contentify/Contentify/issues/304 aufgenommen, daher mache ich hier zu.
