### ISSUE TITLE
[BUG? 2.3]News werden nicht auf der Startseite sichtbar

### ISSUE THREAD

**Issue by Devilcraft1407** [Contentify/Contentify#324]
Version: 2.3

Hey,
ich wollte heute Contentify aufsetzen. Nach Stundenlangem studieren der issues habe ich bisher nichts darüber gefunden.
Ich habe test weise eine neue News erstellt doch diese wird unter "start" nicht angezeigt.
Entweder ich bin halt zu doof eine Option dafür zu finden oder dies wird wirklich nicht sichtbar.

Hoffe ihr könnt mir da ein wenig Beihilfe leisten.

MFG

**Comment by kamohy** [comment]
Moin, darf ich mir die seite mal ansehen ? 
Weil, eigentlich kann das nicht sein. Bei mir und @Pega16 laufen auf mindestens 3 seiten, contentify.
auch local mit einem server auf dem neuesten stand läuft con 2.3
deswegen kann ich mir das nur schwer erklären.

Vorweg: Alle rechte richtig gesetzt ?
News auch auf Veröffentlicht, gestellt ?
Am datum der News etwas geändert ?
News auch gespeichert? :D (klingt dämlich kann aber jedem passieren xD)

**Comment by Devilcraft1407** [comment]
Aber natürlich...
Nur das ich halt noch nichts eingerichtet habe bisher weil ich die News nicht zum laufen bekomme.

Unsere Homepage läuft hier: http://rubin-esports.de/

Wenn nötig bin ich auch den ganzen tag über im TeamSpeak³ erreichbar.
185.223.28.64

Wenn noch etwas benötigt wird, zögere nicht zu fragen. Ich stehe hier halt wirklich auf den schlauch :P

**Comment by kamohy** [comment]
ich hab mich mal registriert, einen kurzen zugang zum adminbereich wär nett

**Comment by Devilcraft1407** [comment]
Habe dir die admin rechte zugewiesen.
Mfg

**Comment by kamohy** [comment]
gut, was hast du alles abgeändert, in den datein selbst ?
denn eigentlich ist die install sauber (wie gesagt wir nutzen es selbst auf einigen seiten)
nun beginnt also die fehlersuche.
bitte nenn mir mal die dateien die du geändert hast.

**Comment by Devilcraft1407** [comment]
Ich habe lediglich die config/app datei bearbeitet...

**Comment by kamohy** [comment]
kannst du mir kurz mal den code hier posten? (mein internet ist seeeehr langsam deswegen) einfach mal den abgeänderten code einfügen bitte

**Comment by kamohy** [comment]
hast du den composer installiert? sry wenn ich frage aber diesen muss man zusätzlich installieren.
Weil nur damit alles funktioniert.

**Comment by kamohy** [comment]
ich hab es glaub ich schon, bin mir aber nicht ganz sicher.
öffne: config/app.php
suche nacht CET und mach daraus bitte UTC
Dann sollten deine News auch auftauchen.

**Comment by Pega16** [comment]
bei UTC passt dann aber die Zeit nicht @kamohy 

Ich empfehle Dir, lieber @Devilcraft1407 dort anstatt CET einfach "Europe/Berlin" einzutragen... das funktioniert in jedem Fall, da selbst der PHP-Core des Servers dies korrekt interpretiert...

...zumal CET die KURZSCHREIBWEISE für die eigentliche Langform "Europe/Berlin" ist.... ;)

Nähere Referenz gibts HIER: http://php.net/manual/de/timezones.php

und wahlweise nur die Zeitzonen in Europa mit KORREKTER Schreibweise: http://php.net/manual/de/timezones.europe.php


LG
Sascha

**Comment by kamohy** [comment]
CET steht drin Ö.ö und meine uhr aufm Lapi sagt  UTC
aufm lokalen-server: UTC und dort geht alles ! 
ansonsten bleibt echt nur der composer oder aber die rechte nicht richtig verteilt via FTP


![timestamp](https://user-images.githubusercontent.com/37085865/38885632-de1c3d82-4273-11e8-8ffb-9afd346cbdcc.PNG)

**Comment by Pega16** [comment]
@kamohy UTC (Coordinated Universal Time Zone) ist die Koordinierte Weltzeit; die Referenzzeit, von der die Ortszeiten in den verschiedenen Zeitzonen der Erde abgeleitet werden

wir sind hier aber in Deutschland und hier gilt nicht die UTC... ;) zumal das aufm lokalen Testserver nur dann korrekt angezeigt wird (also die Uhrzeit! hierbei gehts rein um die Uhrzeit!!!), wenn der Server denkt, er sei in der UTC (das gibt man bei der Installation an ;) ) so viel zur Erklärung...

Übrigens Deutschland liegt +1 Stunde zur UTC, bzw. +2 Stunden, je nach dem, ob wir Sommer- oder Winterzeit haben... ;)

> meine uhr aufm Lapi sagt UTC

jup, da steht *UTC +01:00* was genau meine Aussage bestätigt... xD

Ich vermute den Fehler weniger bei der Zeitzonenangabe... ich denke, der liegt woanders... eventuell ein " oder ' oder ; vergessen, mit hin zu basteln, als man was gelöscht hat, um was anderes hinzuschreiben in einer der Dateien... das ist mir auch schon oft passiert... ist menschlich!

**Comment by kamohy** [comment]
mhmm okay ^^
ich weiss das bei uns deswegen nix ging damals weil wir irwas nit geändert hatten.

dann wie gesagt gucken ob alle rechte via FTP richtig gesetzt wurden
```
bootstrap/cache
public
storage
```
Diese benötigen die rechte: 777

checke ob du den composer installiert hast und ja lass das CET drin, der mann hat recht, sry...

**Comment by chriskonnertz** [comment]
Kann sein dass das jetzt obsolet ist aber ihr könntet noch mal im Backend -> Einstellungen -> bei "Diagnose" abgleichen, was bei "PHP.date.timezone" und "App.timezone" steht. Da sollte das gleiche stehen.

**Comment by Devilcraft1407** [comment]
Vielen dank für euren ganzen erklärungen.
Ich mich entschuldigen das ich jetzt erst antworte da ich in der fahrschule saß.
Ich werde mich gleich dran setzen und alle vorschläge checken.
Danke euch :)

**Comment by Pega16** [comment]
> Kann sein dass das jetzt obsolet ist aber ihr könntet noch mal im Backend -> Einstellungen -> bei "Diagnose" abgleichen, was bei "PHP.date.timezone" und "App.timezone" steht. Da sollte das gleiche stehen.

Guter Hint, dank Dir @chriskonnertz , An das hatte ich gar nicht mehr gedacht :D

**Comment by Devilcraft1407** [comment]
> Ich empfehle Dir, lieber @Devilcraft1407 dort anstatt CET einfach "Europe/Berlin" einzutragen... das funktioniert in jedem Fall, da selbst der PHP-Core des Servers dies korrekt interpretiert...

Hat schon mal die zeit richtig gesetzt.

> dann wie gesagt gucken ob alle rechte via FTP richtig gesetzt wurden
>bootstrap/cache
>public
>storage
>Diese benötigen die rechte: 777

Sind auf 777 habe es doppelt geprüft.

>checke ob du den composer installiert hast und ja lass das CET drin, der mann hat recht, sry...

Composer habe ich über plesk machen lassen unter den "Anwendungen" diese wurden auch ohne fehler erfolgreich installiert. CET hatte ich drin und habe es jetzt zu "Europe/Berlin" gesetzt.

Hat es villeicht etwas mit dem "APP_KEY" zutun? 
diesen habe ich bisher noch nicht geändert.

EDIT:
Habe da evtl. was gefunden.
Es scheint das mein auf webspace die zeitzone nicht richtig ist.

`2018-04-17 14:31:36 | Error | MEINE IP :P | 404 | GET /news/4 HTTP/1.0`
Ob es daran liegt?

**Comment by Pega16** [comment]
> Composer habe ich über plesk machen lassen unter den "Anwendungen" diese wurden auch ohne fehler erfolgreich installiert.

Das sagt aber leider nicht zwangsläufig, dass es
a) der aktuelle Composer ist
b) das für Contentify tatsächlich funtional installiert wurde...

zu b)
Contentify bringt im Installationspaket bereits einen Composer mit und genau mit dem solltest Du auf SSH-Ebene arbeiten... diese ganzen Plesk-Geschichten KÖNNEN zwar funktionieren, aber meine persönliche Erfahrung sagt mir, dass die Pakete in den ISP Panels (wie Plesk, Confixx, ISPConfig, und wie sie alle heißen mögen) oftmals veraltet sind und daher früher oder später zu Problemen führen... insbesondere bei Contentify vermutlich eher früher bis ganz früh... ;-)
...Das liegt aber nicht am Contentify, sondern daran, dass oftmals von den Herstellern der Panels schlichtweg vergessen wird, auch das "Nebenprodukt", welches sich APS nennt, zu pflegen... ;)


> Hat es villeicht etwas mit dem "APP_KEY" zutun

gute Frage.... rein vom Gefühl her würd ich eher zu nein tendieren...

**Comment by Devilcraft1407** [comment]
@Pega16 Ich habe einen Webspace gemietet bei Zap-Hosting. 
Somit habe ich leider keine möglichkeit per SSH zu arbeiten. 
Mir steht lediglich das Plesk und der FTP zugriff zur verfügung.

@kamohy Ich bin wieder auf dem TS anzutreffen. Habe deinen anstubser gesehen.
War wie gesagt vorhin eben zur Fahrschule :/

**Comment by kamohy** [comment]
Moin allerseits, sry ich bin gestern gegen 20 uhr eingepennt.
Liegt am Sonnenbrand überall. Vor allem auf meiner Glatze :-( ...

So, inzwischen scheint das problem ja gelöst, ich sehe News auf der Seite.
*Freude*
zu deinem spaceanbieter.. naja der scheint mist zu sein, aber wir wollen hier ja keine Werbung machen, also lassen wir das thema vorerst.

@Devilcraft1407 bitte bimm vorerst wieder den Adminstatus wieder raus, wenn ma wieder was ist, dann kannst du ihn ja neu setzen.

Und nein mein text hier ist nicht böse gemeint :-) 
danke @chriskonnertz und @pega16 fürs helfen :-D 
und @Devilcraft1407 such dir nen besseren Anbieter :D

**Comment by Pega16** [comment]
@Devilcraft1407 Okay... derartige Anbiereinschränkungen sind immer so ne Sache... Ich mach Dir mal folgenden Vorschlag...:
Schreib mir ne Mail an Pega16@hpzone.de in der Du schreibst, was Du aktuell bei ZAP Hosting bezahlst und was genau Du dafür bekommst und ich schaue, obs bei nem vernünftigen Anbieter, z.B. mir, wie in den meisten Fällen mehr fürs Geld gibt... :D

Gerade bei Contentify glaube ich, hab ich da schon was vernünftiges im Kopf... :)


LG
Sascha

**Comment by kamohy** [comment]
soviel zum thema werbung mein lieber :D @Pega16 du bist der geilste :D

**Comment by Devilcraft1407** [comment]
> So, inzwischen scheint das problem ja gelöst, ich sehe News auf der Seite.

Diese habe ich auch gesehen. Nun sind diese wieder weg :P 
Ich weiß auch echt nicht was des soll... ich klicke auf die News gerade und Schwupps weg sind die von der Startseite. >_>
Ich tipper mal ZAP an ob sie die Timezone fixxen können.

> Schreib mir ne Mail an Pega16@hpzone.de in der Du schreibst, was Du aktuell bei ZAP Hosting bezahlst und was genau Du dafür bekommst und ich schaue, obs bei nem vernünftigen Anbieter, z.B. mir, wie in den meisten Fällen mehr fürs Geld gibt... :D

Der Webspace ist dass kleinste Problem. 
Nur das er schon für 6 Monate gemietet ist.

**Comment by Devilcraft1407** [comment]
So ich habe den Fehler nun gefunden.
Für alle die das gleiche Problem haben und Plesk benutzen:

## Stellt sicher das euer Hostsystem und im Plesk die Zeitzonen gleich sind.
### Ist dies nicht der Fall so werden die News auf der Startseite nicht korrekt angezeigt.

@kamohy @Pega16 
Ich habe die aktuelle Zeitzone überbrückt mit der aktuellen zeit des Hostsystems.
Jetzt funktioniert es so wie es soll.
Es lag an Plesk das dort nicht die Zeitzone richtig eingestellt war.
Wird aber Morgen dann behoben sein da erst dann das Hostsystem mit der Plesk Anwendung neu gestartet werden kann wenn nicht so viel Traffic fließt.

**Comment by Pega16** [comment]
@Devilcraft1407 auch das ist kein Problem... ;)

Es war an der Stelle ein Vorschlag, den kann man annehmen, oder eben nicht... und den kann man jetzt oder Später annehmen oder es ganz lassen... mir gings nur drum, mal Eckdaten zu haben, um zu sehen, ob ich da mithalten kann... und entsprechend dem, was Du mir per Mail gesandt hast, kann ich da sogar mithalten ;D

Wie gesagt, alles gut, ich freu mich auch jederzeit, wenn Du zu einem späteren Zeitpunkt darauf zurück kommst, eben dann, wenn es Dir passt... :)

LG
Sascha

**Comment by chriskonnertz** [comment]
> Hat es villeicht etwas mit dem "APP_KEY" zutun?
diesen habe ich bisher noch nicht geändert.

Nein. Den App-Key sollte man auf einen anderen Wert setzen. Das hat aber nichts mit dem Problem zu tun.

( Ist mir gerade nur noch mal so eingefallen. )

**Comment by kamohy** [comment]
kann man das hier schließen ?

**Comment by chriskonnertz** [comment]
Gute Frage

**Comment by kamohy** [comment]
ich denkeja @chriskonnertz 

hey @Devilcraft1407 mach ma das issue zu bitte, außer du brauchst hier noch hilfe.
