### ISSUE TITLE
how to fix :Please enable the debug mode to start the installer.

### ISSUE THREAD

**Issue by okonstantinyuk** [Contentify/Contentify#327]
Please enable the debug mode to start the installer. how to fix  ?

**Comment by chriskonnertz** [comment]
Hello,

this should answer your question: https://github.com/Contentify/Contentify/wiki/FAQ#how-can-i-disable-the-debug-mode

[ Of course, to _enable_ the debug mode you have to set the value to `true`, not to `false`. Just sayin. ;)  ]

**Comment by okonstantinyuk** [comment]
@chriskonnertz   where is this file located ?  config/app.php

**Comment by okonstantinyuk** [comment]
@chriskonnertz found Sori

**Comment by chriskonnertz** [comment]
Great :)
