### ISSUE TITLE
Can I edit the design 

### ISSUE THREAD

**Issue by okonstantinyuk** [Contentify/Contentify#329]
Can I edit the design from the files if Yes in what design folder ?

**Comment by chriskonnertz** [comment]
Hello,

yes you can edit the files from the design / theme.

They are in this folder: `<contentify>/app/Modules/<theme-name>/`
The LESS/CSS files are in:  `<contentify>/app/Modules/<theme-name>/Resources/Assets`
The template files are in:  `<contentify>/app/Modules/<theme-name>/Views`

To find out what design / theme is currently active, go to your wesite, log in, go to the backend, go to config (settings) then take a look at the "theme" drop down element.

> ATTENTION: If you change something in a design / theme you should make a backup of your changes before you update to the next version of Contentify, because they might be overwritten!
