### ISSUE TITLE
Doesnt show news

### ISSUE THREAD

**Issue by Nighteyess** [Contentify/Contentify#33]
Hey guys,

when i add a new "news" in the Backend the news are doesnt show on the news page.
The IP is: http://46.101.170.220/

We try something with the new CMS and hope anyone have a solution or an idea.

GZ

**Comment by chriskonnertz** [comment]
Hi,

did you solve the problem?

If not, there are these thins to check:
1. The `published` attribute is set to true
2. The `published_at` date (and time) has a value < now (`time()`)
3. The news module (overview page) is configured to show enough news (default is `5` I think)
4. There is no filter active that hides the specific news
5. If the `internal` attribute (of the news) is set to true only users with the "internal" permission will have access to the news (so you need to have the poermission and you need to be logged in)

**Comment by Nighteyess** [comment]
Oh sry my failure wrong Date :D

**Comment by Nighteyess** [comment]
Ok thats now really crazy. Now i take the right date but the new News is not on my page...

**Comment by chriskonnertz** [comment]
The news overview page is the default page of the frontend. There is also a newsarchive (index) page:  `<baseurl>/news`

**Comment by Nighteyess** [comment]
Hey Chris,
ok when i go to /news i will find all news.
But on the index there just 1 news. I will show in the configuration.

**Comment by Nighteyess** [comment]
Now all News are shown on the Index Page. But now i add a new news it will be doesnt show. Serious?
I send you my Login Data so you can try it please and show me my failure. I think its a date problem because after 1 week the News are on the index page

**Comment by chriskonnertz** [comment]
Did you find a way to fix the issue? I can see three news on your page so it looks like it's all right now?

**Comment by chriskonnertz** [comment]
Oh sorry my bad. I guess the problem is still there, right?

Yes maybe it's a problem with the PHP/server time zone. Do you know the time zone of the server?

**Comment by chywUa** [comment]
Hi to all! The problem with displaying news has not been solved. I put version 3.0 and the news is not displayed on the main page.
