### ISSUE TITLE
[2.3 | Frage]Modul Widget hinzufügen/laden

### ISSUE THREAD

**Issue by Devilcraft1407** [Contentify/Contentify#330]
Hey ich bin es nochmal :D
Ich habe da mal eine frage. Und zwar sehe ich da ganz viele tolle sachen in den Modulen.
z.B. das man die derzeitigen Online User anzeigen lassen kann und so.

in der `layout.blade.php` habe ich schon gesehen wie die Module geladen werden.
Doch wenn ich manch ein Modul laden möchte macht er es nicht.

Hier sieht man ja z.B. die Matches:

```
<h3>
{{ trans('app.latest') }} {{ trans('app.object_matches') }}
<a href="{{ url('matches') }}" title="{{ trans('app.read_more') }}">{!! HTML::fontIcon('plus-square') !!}</a
</h3>
```
Nur wie bekomme ich jetzt genau das Modul der "widget_latest_users.blade.php" oder "widget_online.blade.php" zum laufen?
Oder aber auch sehe ich bei @kamohy eine shoutbox.

Danke nochmal für eure hilfe. 
Auch wenn ich etwas nerve :P 

MFG

**Comment by kamohy** [comment]
Moin mein lieber.
abändern kannst du alles in der layout.blade.php das hast du richtig erkannt.
die shoutbox ist: 
`<h3>
                        Shoutbox
                    </h3>
                    @widget('Shouts::Shouts')
					</br>`

Latest User uff, benutze ich garnicht und ist glaube ich auch nur fürs ACP (Admin-Backend)
das kann dir aber nur Chris sagen. oder einer der etwas alt eingesessenen. Wie gesagt wir nutzen sowas garnicht, da es in der anfangszeit auch nichts bringt. Weil wenn dort nie jemand oder nur einer angezeigt wird, ist das blödsinn. Aber gut ich denke Chris wird dir da helfen.

**Comment by Devilcraft1407** [comment]
Vielen dank @kamohy :)
Ich sehe auch bei deiner Shoutbox das du die Avatare dazu hast.
Hast du das selber gemacht?
Wäre nett wenn es eine liste geben würde was für Module es gibt und mit welchen Code die aktiv werden. ^^

**Comment by chriskonnertz** [comment]
Hallo

> Ich sehe auch bei deiner Shoutbox das du die Avatare dazu hast.
Hast du das selber gemacht?

Ja hat er: https://github.com/Contentify/Contentify/issues/303

**Comment by chriskonnertz** [comment]
> Ich habe da mal eine frage. Und zwar sehe ich da ganz viele tolle sachen in den Modulen.
z.B. das man die derzeitigen Online User anzeigen lassen kann und so.

Ja da fehlt ein wenig die Doku zu. Die anzulegen / zu verbessern ist ein Task der derzeit so neben bei mit läuft. Verweisen möchte ich an der Stelle auf das Kapitel dazu im Wiki: https://github.com/Contentify/Contentify/wiki/Modules Das ist aber sehr unfertig also lückenhaft.

Anmerkung: Das was du meinst sind die "Widgets". Widgets sind eben dazu da um in Templates (normalerweise das Haupt-Template) eingebunden zu werden und zeigen meist Informationen zu den Inhalten eines Moduls an.

> Doch wenn ich manch ein Modul laden möchte macht er es nicht.
Da steckt eigentlich keine große Magie hinter. Insofern, wenn es nicht klappt, wäre am besten zu postest was du konkret eingetragen hast, dann kann man es korrigieren.

> Nur wie bekomme ich jetzt genau das Modul der "widget_latest_users.blade.php" oder "widget_online.blade.php" zum laufen?

Das grundsätzliche Schema ist immer: `@widget('ModuleName::WidgetName')` 

Das heißt für `widget_latest_users`: `@widget('Users::LatestUsers')` weil das Widget im Module `Users` liegt (siehst du ja daran wo das Template gespeichert ist). Und dass das Widget `LatestUsers` heißt: Nun das Standard-Widget eines Moduls heißt normalerweise wie das Modul selber. In diesem Fall mal **nicht**. Welche Widgets ein Modul hast siehst du wenn du in den Ordner `Http/Controllers` eines Modules gehst. Die Dateien die mit `Widget.php` enden sind die Widgets. Da musst du dann schauen welches PHP-Datei zu welchem Template gehört. Dass es in dem Fall `LatestUsersWidget.php` ist dürfte logisch sein. Die Endung `Widget.php` lässt man dann weg und erhält so den Widget-Namen.

Für `widget_online.blade.php` funktioniert es dann genau so. Im Ordner `Http/Controllers` gibt es eine Datei namens `OnlineWidget.php`, ergo heißt das Widget `Online`, ergibt:  `@widget('Users::Online')`

Viele Widgets haben außerdem (meist optionale) Parameter mit denen man sie beeinflussen kann. Welche das sind erfährt man derzeit nur in dem man in die PHP-Datei des Widgets schaut.

> Latest User uff, benutze ich garnicht und ist glaube ich auch nur fürs ACP (Admin-Backend)

Joa, es wird derzeit nur im Backend benutzt. ~Müsste aber auch fürs Frontend gehen. Hat da wahrscheinlich aber kein wirkliches Styling (CSS), wird also wahrscheinlich nicht gut aussehen. Ich schau mir das gleich mal an.~ _Nachtrag_: Geht definitiv im Frontend. Sieht zwar nicht phänomenal aus, ist aber brauchtbar.

> Danke nochmal für eure hilfe. Auch wenn ich etwas nerve :P

Du nervst nicht. Im Gegenteil du hilfst damit. Weil durch solche Fragen deutlich wird wo die Doku noch nicht gut genug ist, wo Unklarheiten bestehen, wie Leute herangehen wenn sie am CMS was ändern wollen. Das ist wichtiges Feedback.

**Comment by chriskonnertz** [comment]
Hab mal das Wiki entsprechend ergänzt: https://github.com/Contentify/Contentify/wiki/Modules#widgets

**Comment by chriskonnertz** [comment]
Das User-Online-Widget ist derzeit noch arg minimalistisch. Verbesserungsvorschläge werden entgegengenommen. :)

**Comment by kamohy** [comment]
Danke für die (likes) :D

Also man kann recht viel machen, was ich auch selbst immer wieder gut finde.
Das einzige was etwas zeitaufwendiger ist, ist tatsache ein design dafür schreiben
vor allem wenn man vorher nur CSS geschrieben hat und nie eine LESS  :-D 

Was benutzt du zum editieren von datein ? 
Ich empfehle Notepad++, dort kannst du ganze ordnerstruckturen rein laden.
Was die suche erleichtert. je mehr man selbst rausfindet, desto weniger ist man auf andere angewiesen.

Ich hab auch mal erklärt wie man eigene kurlinks schreibt.
Was das verlinken einfacher macht.
(findest du auch im #303 )

Was ich dort auch noch reinsetzen werde, ist wie man die startseite verändern kann.

aber alles so step by step, da ich viel unterwegs bin. 
naja und mein inet ist echt kacke :D

**Comment by kamohy** [comment]
> Das User-Online-Widget ist derzeit noch arg minimalistisch. Verbesserungsvorschläge werden entgegengenommen. :)

Ach minmalistisch ist immer gut, um so mehr kann man selbst bestimmen :D

**Comment by kamohy** [comment]
@Devilcraft1407 

> Danke nochmal für eure hilfe.
Auch wenn ich etwas nerve :P

Das ist meine Aufgabe hier :D bitte nicht klauen :-D 
Du nervst nicht aber, ab und an mal gucken und suchen, das kann schon viel ausmachen.

**Comment by chriskonnertz** [comment]
Ich habe das Random-User-Widget noch mal etwas angepasst.
- Nur nicht gebannte User auswählen, die schon mindestens ein mal eingeloggt waren
- Sollte kein entsprechender User gefunden werden, einfach nichts anzeigen

https://github.com/Contentify/Contentify/commit/06fcfd6ed69820e7e3e8ba178065f6eb9b16b9c6

**Comment by Devilcraft1407** [comment]
Ouha, danke jedenfalls für die ganzen Informationen!
Ich werde gerne weiter fragen stellen sobald was nicht klar ist. Auch sehe ich darin das dies anderen Leuten erspart bleibt eine neue gleich frage zu stellen.
@kamohy 
Ich benutze Sublime Text 3 (https://www.sublimetext.com/) kann ich jedem nur weiterempfehlen.
Ist sogar meiner Meinung nach viel besser als Notepad ++ und übersichtlicher.
Zwar nervt auf dauer der blöde "popup" das es nicht gekauft ist, aber man kann es vollkommen kostenlos nutzen.

**Comment by kamohy** [comment]
notepad ist kostenlos, hat nen FTP-plugin was will man mehr ? :D aber ich guck es mir gern mal an.
ich bin vllt. einfach nur oldshool :-) aber hey ick bin so alt, ick darf dat :D

**Comment by kamohy** [comment]
@Devilcraft1407 

öffne ma sublime text
geh auf Help, dann auf lizens und kopier mal das dort rein:

**_-- Ich hab das mal raus genommen... bin nicht sicher ob das zu posten den Richtlinien von GitHub entspricht. Chris --_**

wenn das getan, sag bitte bescheid

**Comment by kamohy** [comment]
und wenn ich sublime mal auf deutsch eingestellt bekommen würde, würde ich auch gern ma ausreichender testen. so jedoch nunja... hab keine lust ewig funktionen zu suchen. :-) 

bei 80 us $ finde ich sollte ein language-pack enthalten sein...

**Comment by Devilcraft1407** [comment]
> wenn das getan, sag bitte bescheid

Habs gemacht...
Du hast es dir echt gekauft? Oo
Ich weiß garnicht wie ich dir dafür danken kann :o

**Comment by kamohy** [comment]
> -- Ich hab das mal raus genommen... bin nicht sicher ob das zu posten den Richtlinien von GitHub entspricht. Chris --

Danke Chris wollt es gerade selbst raus nehmen :-)

**Comment by kamohy** [comment]
> Habs gemacht...
Du hast es dir echt gekauft? Oo
Ich weiß garnicht wie ich dir dafür danken kann :o

Also ähm @Devilcraft1407 Chris hat es nicht umsonst entfernt :-) 

Freu dich einfach das es geht :-D
