### ISSUE TITLE
Password-Reset / E-Mail-Function

### ISSUE THREAD

**Issue by niclasreich** [Contentify/Contentify#332]
When trying to reset my password (wanted to try if the SMTP-Sending works) I get the following error in the log:
`[2018-04-20 07:21:35] production.ERROR: exception 'Swift_TransportException' with message 'Cannot send message without a sender address' in /var/www/play/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:162
Stack trace:
#0 /var/www/play/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#1 /var/www/play/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(395): Swift_Mailer->send(Object(Swift_Message), Array)
#2 /var/www/play/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(217): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#3 /var/www/play/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\Mail\Mailer->send('auth::emails.re...', Array, Object(Closure))
#4 /var/www/play/app/Modules/Auth/Http/Controllers/RestorePasswordController.php(43): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#5 /var/www/play/app/Modules/Auth/Http/Controllers/RestorePasswordController.php(43): Illuminate\Support\Facades\Mail::send('auth::emails.re...', Array, Object(Closure))
#6 [internal function]: App\Modules\Auth\Http\Controllers\RestorePasswordController->postIndex()
#7 /var/www/play/contentify/Controllers/BaseController.php(93): call_user_func_array(Array, Array)
#8 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Contentify\Controllers\BaseController->callAction('postIndex', Array)
#9 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Route.php(190): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Modules\Auth\Http\Controllers\RestorePasswordController), 'postIndex')
#10 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#11 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/play/app/Http/Middleware/VerifyAdminAccess.php(38): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\VerifyAdminAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/play/contentify/Middleware/UpdateUser.php(111): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Contentify\Middleware\UpdateUser->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/play/app/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/play/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/play/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/play/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/play/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/play/contentify/Middleware/HttpsRedirect.php(32): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Contentify\Middleware\HttpsRedirect->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#43 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#44 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#45 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/play/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/play/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 /var/www/play/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}  `

**Comment by chriskonnertz** [comment]
Hello,

did you change the values in the `app/config/mail.php` file from `null` to a string?

https://github.com/Contentify/Contentify/blob/2.3/config/mail.php#L59

**Comment by niclasreich** [comment]
Yes.

```
<?php
return [
	'driver' => env('MAIL_DRIVER', 'mail'),
    /*'driver' => env('MAIL_DRIVER', 'smtp'), currently commented because it won't send any mails at all if uncommented */
    'host' => env('MAIL_HOST', 'mail.escde.eu'),
    'port' => env('MAIL_PORT', 587),
    'from' => [
        'address' => env('no-reply@escde.eu', null),
        'name' => env('Online Tournaments | eSportClubDE', null),
    ],
    'encryption' => env('MAIL_ENCRYPTION', 'tls'),
    'username' => env('no-reply@escde.eu'),
    'password' => env('*removed*'),
    'sendmail' => '/usr/sbin/sendmail -bs',
];
```

**Comment by chriskonnertz** [comment]
Hallo,

denke das muss eher aussehen:

```
    'from' => [
        'address' => 'no-reply@escde.eu',
        'name' => 'Online Tournaments | eSportClubDE',
    ],
```

Was du gemacht hat geht von der Idee her auch - aber die `env`-Funktion erwartet den Default-Wert als _zweiten_ Parameter, nicht wie bei dir als ersten!

Beispiel aus deinem Code:
`env('MAIL_ENCRYPTION', 'tls')`
"MAIL_ENCRYPTION" ist hierbei der Name der Umgebungsvariablen. Wird diese nicht gefunden, wird als Wert "tls" verwendet.

**Comment by niclasreich** [comment]
Hi, ich habe `'from' ...` in das geändert, was du mir geschrieben hast. Leider funktioniert es immer noch nicht. In /var/log/mail.log findet sich folgendes wieder:
```
Apr 23 14:49:49 escde postfix/smtpd[19864]: connect from unknown[185.142.212.126]
Apr 23 14:49:49 escde postfix/smtpd[19864]: Anonymous TLS connection established from unknown[185.142.212.126]: TLSv1 with cipher DHE-RSA-CAMELLIA256-SHA (256/256 bits)
Apr 23 14:49:49 escde postfix/smtpd[19864]: NOQUEUE: reject: RCPT from unknown[185.142.212.126]: 554 5.7.1 <unknown[185.142.212.126]>: Client host rejected: Access denied; from=<no-reply@escde.eu> to=<my@private.email> proto=ESMTP helo=<play.escde.eu>
Apr 23 14:49:49 escde postfix/smtpd[19864]: disconnect from unknown[185.142.212.126]
```

**Comment by chriskonnertz** [comment]
Und die anderen Werte in der `app/config/mail.php` passen auch?
Bei `host`, `username`, `password` etc. hast du was eingetragen? In der Form:

```
'username' => env('MAIL_USERNAME', 'mustermann'),
``` 
Oder

```
'username' => 'mustermann',
``` 

?

**Comment by niclasreich** [comment]
Habe alles andere wie mit der env-Variable (also wie oben gepostet) gelassen oder soll ich das alles wegändern?

**Comment by niclasreich** [comment]
> `'username' => 'mustermann',`

Perfekt, habe jetzt überall einfach mal testmäßig die env-Funktion entfernt und einfach getestet. Funktioniert, vielen Dank für die Hilfe.

**Comment by chriskonnertz** [comment]
Ok super. :)
