### ISSUE TITLE
Can't get the Twitch Module to work

### ISSUE THREAD

**Issue by niclasreich** [Contentify/Contentify#333]
Hi, I have the same issues as described in #148 and #195 - I cannot get an preview of my Twitch Stream, even though I have set the cronjob `1 * * * * /usr/bin/php /var/www/play/artisan jobs`,  set up the API-key in the settings and set folder permissions.

I also have another idea you might consider to add: have you heard of google's invisible recaptcha?

**Comment by chriskonnertz** [comment]
*Push*

**Comment by chriskonnertz** [comment]
> I also have another idea you might consider to add: have you heard of google's invisible recaptcha?

Thank you for this suggestion. When you created this issue I considered to implement it. However, I will not. I'm worried about the GDPR topic. Embedding something from Google in this way probably is dangerous in terms of GDPR.
