### ISSUE TITLE
Hello is there a translation

### ISSUE THREAD

**Issue by okonstantinyuk** [Contentify/Contentify#334]
Hello is there a translation to Russian language ? this engine

**Comment by okonstantinyuk** [comment]
if not then how to translate where is the file with the text ?

**Comment by Devilcraft1407** [comment]
Hey,
take a look in `/resources/lang`  there are some files you can edit

**Comment by okonstantinyuk** [comment]
@Devilcraft1407 where is the main page to find to change TEAMS home and so on ?

**Comment by Devilcraft1407** [comment]
in `app/Modules/THEMENAME/Resources/Views/layout.blade.php` you can see the main page

**Comment by okonstantinyuk** [comment]
@Devilcraft1407 can I change the language of the homepage there ?

**Comment by kamohy** [comment]
Hello @okostantinyuk 
NO not there search the file:
`\resources\lang` create a new folder: ru
go on `eng` copy the files and paste it in `ru`
know u can translate it self in there files

**Comment by okonstantinyuk** [comment]
@kamohy I have translated all page well master page not found

**Comment by chriskonnertz** [comment]
Hello

> Hello is there a translation to Russian language ? this engine

No. I'd love to see more languages but well obviously some one needs to translate them and I do not know anyone who is a native Russian speaker.

> if not then how to translate where is the file with the text ?

As Devilcraft1407 said, most of the translations are in `/resources/lang`. However, some of the modules in `app/Modules` also have translation files. Example: [app/Modules/Matches/Resources/Lang](https://github.com/Contentify/Contentify/tree/v2.3/app/Modules/Matches/Resources/Lang)

The wiki has a  chapter about translating: https://github.com/Contentify/Contentify/wiki/Localisation#add-more-languages

**Comment by okonstantinyuk** [comment]
@chriskonnertz I can translate since I'm a native Russian language

**Comment by chriskonnertz** [comment]
Nice! :)

**Comment by kamohy** [comment]
@chriskonnertz muss er die dann noch in ne .json reinschreiben ? wenn ja sollte man das auch mitteilen, weil themes musst du auch um sie anzuwählen in eine .json eintragen

**Comment by okonstantinyuk** [comment]
@chriskonnertz  Translated text by 90%

**Comment by chriskonnertz** [comment]
> muss er die dann noch in ne .json reinschreiben ? wenn ja sollte man das auch mitteilen, weil themes musst du auch um sie anzuwählen in eine .json eintragen

_(de)_ Nein, das ist nicht nötig, weil dafür kein eigenes neue Modul erstellt werden muss.
_(en)_ No, you do not have to create a .json file, because adding a new language does not require creating a new module.

**Comment by chriskonnertz** [comment]
@okonstantinyuk I hope you will share the results :)

**Comment by chriskonnertz** [comment]
Well it does not seem like this is going to happen.
