### ISSUE TITLE
Idea: FAQ-Page

### ISSUE THREAD

**Issue by niclasreich** [Contentify/Contentify#335]
Maybe implement a FAQ-Page with [extendable Texts like here](https://www.w3schools.com/jquerymobile/tryit.asp?filename=tryjqmob_collapsible)?

**Comment by kamohy** [comment]
Kann man doch selbst anlegen ? Ö.Ö
Einfach unter pages anlegen und als kurzlink einfügen:
beschreibung für kurzlinks: #303

**Comment by niclasreich** [comment]
Ich glaube, du hast den Sinn einer FAQ-Seite nicht verstanden. Ich möchte, dass möglichst viele Fragen auf einer Seite mit jeweils einem kurzen Text beantwortet werden, sodass sich der User bei mehreren Fragen nicht immer über verschiedene Seiten langhangeln muss, er aber auch nicht durch zu viel Text auf einer Seite erschlagen wird (deshalb ausklappbare Texte). [Beispielsweise wie hier](https://escde.eu/help/haeufig-gestellte-fragen/).

**Comment by kamohy** [comment]
auch das kannst du doch selbst erstellen. (ich hab knapp 10 jahre erfahrung mit CMS ich denke ich weiss was eine FAQ ist) 
Wer ein bisschen ahnung hat kann mit CSS und ein wenig HTML mehr machen als man denkt...
Das ist kein Teufelswerk... das liegt alles im rahmen der selbstgestalltung.
Entschuldigung aber nicht alles muss ein Baukastensystem meiner meinung nach beinhalten.
Dies ist ausserdem kein normales CMS wie du sicher schon bemerkt hast. 
Seid erfinderisch... meine güte... wie mussten damals webseiten noch komplett selbst schreiben...

**Comment by kamohy** [comment]
https://t3n.de/news/html5-howto-aufklappboxen-ohne-javascript-337546/ 
sehr schönes beispiel...

**Comment by niclasreich** [comment]
Hi @kamohy, ich habe dieses Issue extra mit "Idea" versehen, damit klar erkenntlich ist, dass es sich hierbei um eine Idee handelt. Ich denke, es gibt vielerlei Möglichkeiten, dieses Feature zu nutzen und wie ich oben bereits erklärt habe, könnte es genau dafür zu gebrauchen sein (vor allem für Leute wie mich, die nicht wie du bereits 10 Jahre mit CMS Erfahrung haben).

Ich finde es super, dass du so motiviert nach einem Beispiel gesucht hast, jedoch habe ich oben bereits eins verlinkt. Wirklich schön finde ich die von dir verlinkte Lösung übrigens nicht.

Im Endeffekt kann @chriskonnertz selbst abwägen, wie aufwendig das ist und wie sinnvoll er das findet.

**Comment by kamohy** [comment]
in deiner beschreibung, nennst du dich selbst developer im frontend-bereich....
dann müsstest du ja auch ein wenig ahnung von CSS haben, was bedeutet du kannst das ganze dennoch vom aussehen her bestimmen wie du möchtest.
Dieses Beispiel ist ja im endeffect nur ein Rohling und lässt sich ohne weiteres erweitern.
Ich hab deine beschreibung gelesen und dachte mir der wird also ein wenig ahnung haben... war wohl ein denkfehler meinerseits... sry... zumal das was ich dir gezeigt habe, quasi das selbe ist in grün...
der vorteil einer reinen CSS und HTML5 geschriebenen seite ist, das er nur text lesen muss (der Browser), was die reaktionszeit verbessert. Je mehr daten im HG geladen werden desto länger der Aufbau einer webseite.

Wie gesagt, auch ich meinte es nur gut.

**Comment by niclasreich** [comment]
> in deiner beschreibung, nennst du dich selbst developer im frontend-bereich....
dann müsstest du ja auch ein wenig ahnung von CSS haben, was bedeutet du kannst das ganze dennoch vom aussehen her bestimmen wie du möchtest.
Dieses Beispiel ist ja im endeffect nur ein Rohling und lässt sich ohne weitere erweitern.
Ich hab deine beschreibung gelesen und dachte mir der wird also ein weig ahnung haben... war wohl ein denkfehler meinerseits... sry... zumal das was ich dir gezeigt habe, quasi das selbe ist in grün...
der vorteil einer reinen CSS und HTML5 geschriebenen seite ist, das er nur text lesen muss, was die reaktionszeit verbessert. Je mehr daten im HG geladen werden desto länger der Aufbau einer webseite.

Auch das war mir bereits alles bewusst. Doch Conentify (und unser Server) an sich lädt schon ziemlich schnell; mit Sicherheit sogar zwanzig Mal schneller als unsere Wordpress-Seite (auch kein Wunder bei all den Seiten, Plugins und Erweiterungen), deshalb kommt es mir primär darauf an, dass es schön aussieht, weil es benutzerfreundlich sein soll - dabei spielt es für mich keine Rolle, ob die Seite jetzt 1,1 oder 1,15 Sekunden zum Laden benötigt.

Nach wie vor: mein Beitrag hier war eine **Idee**, damit es auch Leute nutzen können, die
> nicht wie du bereits 10 Jahre mit CMS Erfahrung haben.

**Comment by kamohy** [comment]
Dein Server ist völlig egal, wenn du einen User hast der eine bescheidene Leitung hat wie ich zum beispiel im moment. Die Ladezeit hängt nicht vom Server allein ab, sondern auch vom endbenutzer.

Was machst du zum beispiel wenn du unterwegs bist (im urlaub in der eifel, ist das beste beispiel) hier is das hobby aller Smartphonenutzer: Such das netz.
Und nun sollst du kurz etwas aufrufen, je mehr java (jquery, ajax, ect.) desto länger die wartezeit, da kann das reine öffnen einer seite schonmal 5 minuten dauern mit zuvielen plugins. 
(Ich achte halt auf aussehen und nutzerfreundlichkeit)
aber auch meines war nur eine Idee...  ohne dich damit angreifen zu wollen....

**Comment by chriskonnertz** [comment]
Ihr könnt aufhören zu diskutieren, das Modul FAQ wurde bereits vor zwei Wochen oder so umgesetzt. :sunglasses:

Es wird in v2.4 enthalten sein, 2.4 wiederum wird in Kürze final sein wenn weiterhin alles planmäßig läuft.

https://github.com/Contentify/Contentify/tree/2.4-dev/app/Modules/Questions

Ich werde mir anschauen ob ich das Auf- und Zuklappen einbaue. Zumindest werde ich sicherstellen, dass der HTML-Code so aufgebaut ist, dass man es jeder via CSS leicht selber nachrüsten kann.

**Comment by chriskonnertz** [comment]
@niclasreich Jedenfalls danke für die Anregung.

**Comment by chriskonnertz** [comment]
> https://t3n.de/news/html5-howto-aufklappboxen-ohne-javascript-337546/ sehr schönes beispiel...

An sich ja, wird aber leider vom Internet Explorer in allen Version einschließlich 11 sowie von Edge nicht unterstützt. Persönlich sehe ich das daher als nicht nutzbar an, auch wenn der typische Gamer eher nicht mit IE/Edge surft. Aber man weiß ja nie.

**Comment by chriskonnertz** [comment]
Update: Auf/zuklappen gibt es erst mal nicht. Das ist ja an sich kein Hexenwerk aber passt gerade nicht mehr in den Zeitplan da ich festgestellt habe, ich muss erst mal die Auf/zuklapp-Funktion im BBCode in Foren-Posts und in Kommentaren fixen. Aber, es wird Kategorien für die Fragen geben. Die fehlten bis heute noch.

Wen die Anzeige der Kategorien stört der kann sie mit CSS Code einfach ausblenden:

```
.page-questions .category-title { display: none }
```
