### ISSUE TITLE
[2.3]Frage: User in eigenes Team einladen

### ISSUE THREAD

**Issue by Devilcraft1407** [Contentify/Contentify#336]
Hey,
I bims nochmal der nicht nervende nerv-bold :D
Ich wollte mal fragen wo die "Invite" "Join" funktion ist für die eigenen Teams fürs Cup Control.
Soweit haben wir alles eingestellt und nimmt Langsam Form an.
Wäre nett wenn mir da jemand nen tipp gibt.

PS: 
Wenn dies nicht vorhanden ist, ist auch nicht schlimm.
So dringend wird diese Funktion nicht benötigt.
Sie wäre nur dazu da um Leute an den Jeweiligen Cups anzumelden für die Leader der Teams um so Leichter eine Übersicht zu haben.

MFG

**Comment by chriskonnertz** [comment]
Hallo

> Ich wollte mal fragen wo die "Invite" "Join" funktion ist für die eigenen Teams fürs Cup Control.

Diese Funktion gibt es derzeit nicht. Klingt aber sinnvoll. Sprich man kann einen User heraussuchen, und der bekommt dann den Invite, vorschlagsweise als Nachricht auf der Website und per Email, und darin ist dann ein Link mit dem er direkt in das Team joinen kann?

> Sie wäre nur dazu da um Leute an den Jeweiligen Cups anzumelden für die Leader der Teams um so Leichter eine Übersicht zu haben.

Hm, das musst du genauer erklären - wodurch käme diese Übersicht zu stande? Habe dazu gerade kein Bild im Kopf...

**Comment by Devilcraft1407** [comment]
> Diese Funktion gibt es derzeit nicht. Klingt aber sinnvoll. Sprich man kann einen User heraussuchen, und der bekommt dann den Invite, vorschlagsweise als Nachricht auf der Website und per Email, und darin ist dann ein Link mit dem er direkt in das Team joinen kann?

Genauso hab ich mir das vorgestellt :D 

> Hm, das musst du genauer erklären - wodurch käme diese Übersicht zu stande? Habe dazu gerade kein Bild im Kopf...

Folgende Verhandlungen sind gerade im Gespräch das wir diese Funktion nutzen möchten um bei den verschiedenen Bomb-Cups z.B. die Mitglieder einsehen können die daran teilnehmen. Da bleibt uns dann das ganze Herumfragen in Whatsapp Gruppen erspart und jeder kann sich dann eintragen mit seinem jeweiligen Team. (Anders geht es ja net) Wenn es nur die Option gäbe sich als "einzelner User" aus einem zugewiesenen Team bei einem Cup anmelden kann und dann in seinem zugewiesenem Team eingeteilt wird. 
Quasi dann so als visuellen vorschlag:

Tam A = Mainteam & Team B Sub Team (Academy)
___________________________________________________
Du nimmst nicht an diesem Cup teil.                   
Teilnehmen? <--- Linkbutton / Button                 
Wenn eingetragen:                                               
Du nimmst an diesem Cup Teil.                            
Austragen? <--- Linkbutton / Button                   
Textfeld mit Begründung                                      
                                                                              
Cub von einstein #123 Europa                              
Spiel: Rainbow Six Siege                                        
Teilnehmer Team A | Teilnehmer Team B               
User A      | User B                                                  
User C      | User D                                                 
User E       | User F                                                  
User G      | User H                                                  
frei/---      | Frei/---                                                 
                                                                               
Anmelde Phase bis: 12.03.2002 05:00:00 Uhr        
Button Eintragen/Teilnehmen                                
____________________________________________________
Wenn Team A voll ist und B (max 5 pro Team)
Dann kann man sich nicht mehr für das anstehende Cup anmelden und die eingetragenen User sind Teilnehmer des Cups. Wenn es sogar gehen würde, das man auch die anmelde Phase bis zu einem bestimmten Datum bzw. Uhrzeit schließt und alle eingetragenen User sich nicht mehr austragen können.
Falls du weiterhin dir kein Bild daraus machen kannst, dann werde ich es natürlich ausfühlicher und genauer beschreiben mit Bildern usw. :D

MFG
Der Nervbold Devilcraft
