### ISSUE TITLE
modules to this cms ?

### ISSUE THREAD

**Issue by okonstantinyuk** [Contentify/Contentify#337]
and there are additional modules to this cms ?

**Comment by niclasreich** [comment]
https://github.com/Contentify/Contentify/wiki/Modules

**Comment by chriskonnertz** [comment]
Hello,

the CMS (version 2.3) has these modules: https://github.com/Contentify/Contentify/tree/2.3/app/Modules

There aren't any other "official" modules at the moment.

However, every one _can_ create new, additional modules.

**Comment by chriskonnertz** [comment]
If you miss a feature please let me know.
