### ISSUE TITLE
Next Matches

### ISSUE THREAD

**Issue by Nighteyess** [Contentify/Contentify#34]
Hey,

is it possible to read the "NExt Matches" only?
I want it for a own DIV Box.

**Comment by chriskonnertz** [comment]
Hi,

when I have time I will create a widget for that behaviour.

Should be almost the same as the `MatchesWidget`.

**Comment by chriskonnertz** [comment]
Done.

Add in a template with this code:

`@widget('Matches::UpcomingMatches')`

Code of the new file:
https://github.com/Contentify/Contentify/commit/8fc519d7e2888c1e34becda82d5af2fb75a87855

**Comment by Nighteyess** [comment]
Mega geil chris 
Very nice chris ty

Von meinem iPhone gesendet

**Comment by chriskonnertz** [comment]
No problem :)

**Comment by Nighteyess** [comment]
Hey,

where can i find the template file for this widget? I want to style the next Matches section otherwise than "Last Matches".

**Comment by chriskonnertz** [comment]
`app/Modules/Matches/Resources/Views/widget.blade.php`
