### ISSUE TITLE
User Attribute hinzufügen/ändern

### ISSUE THREAD

**Issue by justtam** [Contentify/Contentify#340]
Hi,

erstmal vielen Dank für das super CMS!

Ich würde gerne Attribute hinzufügen, bin mir aber nicht sicher in welchen Dateien ich das überall machen muss und wo ich diese finde. Wir wollen beispielsweise auch Events auf Konsole über die Webseite organisieren, da wäre eine Feld "PSN-ID" ja schon ein Pflichtfeld.
Danke schon mal im Voraus!

**Comment by Devilcraft1407** [comment]
Schau mal unter `app/Modules/Users/Resources/Views` Dort findest du eine `show.blade.php` und eine `form.blade.php`

da kannst du unnötiges entfernen und auch hinzufügen.
Ich jedenfalls habe nur etwas entfernt.
Klappt ohne Probleme
Ich denke wenn du etwas neues hinzufügst musst du es auch in der Datenbank bei `users` nachtragen.

MFG

**_Wenn ich etwas falsches gesagt habe bitte korrigieren.
Dachte ich helfe und würde logisches denken kombinieren. Wie genau man so eine zeile hinzufügt zu den Usern habe ich leider keine Ahnung. :P
Noob am werk! forgive me! :D_**

**Comment by chriskonnertz** [comment]
Hallo,

@Devilcraft1407  ja das stimmt schon, das sind die richtigen Templates und wie du auch richtig sagst, man muss in der DB eine neue Spalte in der `users` Tabelle hinzufügen.

Es fehlt noch, das man im User-Model erlauben muss, dass die neue Spalte vom Client modifiziert wird, in dem man den Namen der Spalte hier einträgt: https://github.com/Contentify/Contentify/blob/2.3/contentify/Models/User.php#L34

**Comment by justtam** [comment]
> Es fehlt noch, das man im User-Model erlauben muss, dass die neue Spalte vom Client modifiziert wird, in dem man den Namen der Spalte hier einträgt: https://github.com/Contentify/Contentify/blob/2.3/contentify/Models/User.php#L34

 Danke, das ist es gewesen. Ich gehe davon aus dass dies durch Updates wahrscheinlich überschrieben wird und ich vorher ne Kopie erstellen sollte?

**Comment by chriskonnertz** [comment]
Backups vor einem Update sollten sowieso grundsätzlich angelegt werden!

Aber ja, zumindest die Änderungen an Dateien werden überschrieben.

Um das zu vermeiden müsstest du ein eigenes Modul anlegen mit deinen Änderungen, wobei es aber nicht so einfach ist dann aus dem Modul in die Template etc. einzugreifen und dazu gibt es derzeit auch noch keine Doku, daher ist im Endeffekt der andere Weg leichter.

**Comment by kamohy** [comment]
denkt auch daran eure datenbank zu erweitern.
Da die userdaten ja in der DB gespeichert werden müsst ihr die felder dort auch hinzufügen.
beispiel: DB-Name -> User -> (feldhinzufügen namen's psn_id)
Sonst wird ja nichts gespeichert :-)

**Comment by kamohy** [comment]
ouha, chris hat das ja auch oben schon geschrieben, das habe ich irgendwie überlesen :-D 
Sry also für die doppelte erklärung wegen der datenbank :-D
