### ISSUE TITLE
When you press on the sowing with the Admin how to fix ?

### ISSUE THREAD

**Issue by okonstantinyuk** [Contentify/Contentify#341]
ERROR
Sorry, something bad happened. Our website has crashed.

Don't worry, we will handle this. In the meantime, make a cup of coffee. And stop crushing our website!

"When you press on the sowing with the Admin how to fix ?"

**Comment by chriskonnertz** [comment]
Hello,

which module?

**Comment by okonstantinyuk** [comment]
@chriskonnertz  seeding Click on it and mistake

**Comment by okonstantinyuk** [comment]
and also news is the same mistake

**Comment by okonstantinyuk** [comment]
![default](https://user-images.githubusercontent.com/38087935/39154078-beda97fc-4755-11e8-9093-1c9a767d3d50.PNG)
here is a screen

**Comment by okonstantinyuk** [comment]
@chriskonnertz ?

**Comment by chriskonnertz** [comment]
=> https://github.com/Contentify/Contentify/issues/345

If you still have the issue with the news module, please create a new issue.
