### ISSUE TITLE
2.4 Beta Update probleme

### ISSUE THREAD

**Issue by kamohy** [Contentify/Contentify#342]
`Updating the database...Could not execute the database query: Duplicate column name 'country_id'`
`Error: Code 42S21`

Habe versucht von 2.3 auf 2.4 beta nen update zu machen, ging nur nicht :-/
Er sucht halt country_id und die existiert nicht, ich weiss nur leider nichteinmal wo, er die sucht :-/

**Comment by chriskonnertz** [comment]
Hallo,

cool dass du es getestet hast, schade, dass es nicht ging... :/

> Er sucht halt country_id und die existiert nicht, ich weiss nur leider nichteinmal wo, er die sucht

https://github.com/Contentify/Contentify/blob/2.4-dev/public/update.php#L85

>  "ALTER TABLE {$prefix}teams ADD `country_id` int(10) UNSIGNED DEFAULT NULL",

Hattest du schon zuvor mal das Update-Script aufgerufen? Es klingt für mich so als wäre dieser SQL-Query, der die Spalte `country_id` der Tabelle `teams` hinzufügt, irgendwann schon mal ausgeführt worden.

Naja jedenfalls du könntest ihn auskommentieren. Kann dann aber sein dass du noch mehr auskommentieren musst falls andere Änderung auch schon vorhanden sind.

**Comment by kamohy** [comment]
Hoi, nein.
War eine Frische saubere 2.3 install und dann das update auf 2.4 dev

Ich probiere es mal aus :-)

**Comment by kamohy** [comment]
*zusatz* ich hab es gerade mal versucht, er will quasi fast alle mysql-befehle nicht ausführen

**Comment by kamohy** [comment]
Hast du schon ne 2.4 ohne update, fertig ? 
also als eigenes CMS ? wenn ja würd ich das gern haben :D 
Dann kann ich es vllt. auch testen. Denn wenn ich alle SQL daten rauswerfe, bringt mir das am ende auch nichts :-/

**Comment by chriskonnertz** [comment]
Ich werde vermutlich das Update morgen man selber probieren. Die 2.4 soll jetzt auch final werden. Von daher:

> Hast du schon ne 2.4 ohne update, fertig ?

Nein aber kommt sehr bald.

**Comment by kamohy** [comment]
Haste schon nen start-termin ?

**Comment by chriskonnertz** [comment]
Heute.

**Comment by chriskonnertz** [comment]
Heute.
