### ISSUE TITLE
[2.3|SteamAuth] ErrorException Fehler

### ISSUE THREAD

**Issue by Devilcraft1407** [Contentify/Contentify#343]
Habe heute mal die Steam Login Funktion aktiviert und als Fehlermeldung kam da raus:

ErrorException in SteamAuth.php line 205:
Undefined offset: 1

**Comment by chriskonnertz** [comment]
Hallo,

das ist vermutlich bekannt und wird vermutlich mit v2.4 behoben.
Der Fehler liegt nicht im Core-Code von Contentify sondern in der STEAM-Authentication-Bibliothek die wir nutzen. 

Reich dir das als Antwort oder brauchst du eine schnelle Lösung des Problems?

**Comment by Devilcraft1407** [comment]
@chriskonnertz Nein alles gut :)
Vielen dank.
Zurzeit hatte ich die Funktion eh ausgelassen wegen des Problems das mein Main Steam acc. gebannt war und ich keine neue SteamAPI key besorgen konnte.
Doch versuchen wollt ich das trotzdem mal :)

MFG

**Comment by chriskonnertz** [comment]
Ok :)
