### ISSUE TITLE
ERROR Sorry, something bad happened. Our website has crashed.

### ISSUE THREAD

**Issue by okonstantinyuk** [Contentify/Contentify#345]
ERROR
Sorry, something bad happened. Our website has crashed.

Don't worry, we will handle this. In the meantime, make a cup of coffee. And stop crushing our website!

"When you press on the sowing with the Admin how to fix ?"
![39154078-beda97fc-4755-11e8-9093-1c9a767d3d50](https://user-images.githubusercontent.com/38087935/39386841-2b99d9d0-4a7f-11e8-810b-4c4929d5414a.png)

**Comment by kamohy** [comment]
steam-link ?

**Comment by kamohy** [comment]
is that the same? #341 
If so, then close one of them please.

**Comment by okonstantinyuk** [comment]
I need a solution, not a solution.

**Comment by okonstantinyuk** [comment]
@kamohy I need a solution, not a solution.

**Comment by kamohy** [comment]
okay open a editor.
edit: storage/app.php

`debug: false` to `debug: true`

post the error-text 
after clicking on the link

**Comment by okonstantinyuk** [comment]
storage/app.php such a there 
There is a folderstorage 
a file app.php no

**Comment by okonstantinyuk** [comment]
@kamohy storage/app.php such a there
There is a folderstorage
a file app.php no

**Comment by kamohy** [comment]
sry
`config/app.php`

**Comment by okonstantinyuk** [comment]
@kamohy  
new error 
![default](https://user-images.githubusercontent.com/38087935/39404450-31db6f98-4b9c-11e8-8f54-988d372d24e9.PNG)

**Comment by kamohy** [comment]
and know chris can take a look :-)

**Comment by chriskonnertz** [comment]
Hello @okonstantinyuk 

Please take a screenshot of your cup's settiings page and post it, so that I can create this cup on my local system.

Example: 
![screenshot_example](https://user-images.githubusercontent.com/4319323/39410900-c24a86f0-4bff-11e8-916c-404082893ab6.png)

**Comment by okonstantinyuk** [comment]
@chriskonnertz  
![default](https://user-images.githubusercontent.com/38087935/39553041-6f3ed944-4e74-11e8-8f50-ed556b0ce772.PNG)

**Comment by okonstantinyuk** [comment]
@chriskonnertz  ????

**Comment by chriskonnertz** [comment]
Thanks! I get this error as well. I will investigate what causes this error.

**Comment by chriskonnertz** [comment]
It seems this error occurs when you try to seed the cup without it having any participants.

The naive solution is to not allow seeding in this case: https://github.com/Contentify/Contentify/commit/91c445c6ca97b1aae87440009b0c3e2976db7004

I assume that this is not enough and the cup needs at least two participants. I will figure it out.

**Comment by chriskonnertz** [comment]
**Update**: 
- One participant is enough
- However, the participant has to be "checked in"

**Comment by chriskonnertz** [comment]
Closed. If you have the problem again, please let me know.
