### ISSUE TITLE
[Question] Where can I add Templates to the Cup-Rules and -Description Textboxes?

### ISSUE THREAD

**Issue by niclasreich** [Contentify/Contentify#347]
There is this tiny option to paste in templates, but where can i set them up?

![image](https://user-images.githubusercontent.com/17802721/39394158-bf00a984-4ace-11e8-9c09-e293563c5c03.png)

**Comment by kamohy** [comment]
Ist ganz simpel, du nimmst nicht custom-page sondern Custom-Content
Diese schreibst du unter Quellcode am besten.
SPEICHERN nicht übernehmen (und sichere dir deinen Code auch in einer externen Datei (z.b.: text.txt) )
nach dem Speichern rufst du die Datei nicht mehr auf da der quellcode dann komischerweise überarbeitet wird.
Nun erzeugst du eine Custom-Page dann kannst du den Custom-Content dort hineinladen über die Funktion.
(Da ich weiss das du deusch kannst schreib ich das auch in Deutsch, geht schneller und ist einfacher für so einen alten Mann wie mir. :D )

**Comment by niclasreich** [comment]
Das hat perfekt funktioniert! Ich danke dir vielmals, @kamohy  :)

**Comment by kamohy** [comment]
sehr gut :-)
