### ISSUE TITLE
User Attribute bei Team-Matches anzeigen

### ISSUE THREAD

**Issue by justtam** [Contentify/Contentify#348]
Hey,

ich würde gerne in der Match Übersicht bestimmte User Attribute anzeigen. Bei Einzelspielerturnieren ist das kein Problem, dort kann ich ganz einfach $participant->attribut einfügen und das funktioniert auch wunderbar.
Bei Team-Matches wirds aber kritischer, dort steht ja hinter $participant erstmal kein User, und dann müsste man ja auch ein Array an User-Attributen (für jeden User im Team einen Wert) ausspucken.

Könnte mir hier jemand helfen? @chriskonnertz vielleicht?
Ich befürchte fast dass es nicht so einfach sein wird und ich eine entsprechende function $userAttribute oder so in den Controller schreiben müsste, oder?

Danke für jede Hilfe. :)

**Comment by chriskonnertz** [comment]
Hallo,

deine Überlegungen gehen schon in die richtige Richtung. Aber es ist nicht so schlimm wie du befürchtest.

Mit `@if ($cup->forTeams()) ... @else ... @endif` kannst du herausfinden ob das Match / der Cup für 1on1s oder Team-Matches ausgelegt ist und dementsprechend die Logik bauen.

Es stimmt, dass du bei Teams dann die einzelnen Mitglieder durch gehen musst. Das sollte so gehen: 
`@foreach ($participant->members as $member) ... @endforeach`

Es empfiehlt sich wohl für die Dinge die du pro User anzeigen willst ein eigenes User-Template zu bauen, denn dann musst du das nur für beide Fälle einbauen. Ungefähr so:
`@include('cups::participant_user', ['user' => $member])`
(In dem Fall würde die Datei `participant_user.blade.php` heißen.)

Eine Function im Controller muss nicht geschrieben werden.

**Comment by justtam** [comment]
Danke Chris, funktioniert einwandfrei! 👍
