### ISSUE TITLE
How to get user STEAM_ID after signup?

### ISSUE THREAD

**Issue by jonatant** [Contentify/Contentify#349]
Hi. Does it imposible to get users STEAM_ID after sign up via STEAM? Example: I press login via STEAM button and after registration save user STEAM_ID in steam_id users table? Thanks and sorry for bad english :)

**Comment by kamohy** [comment]
wait of the the update 2.4 
t will be fixed

**Comment by jonatant** [comment]
@kamohy it's not a bug

**Comment by chriskonnertz** [comment]
Hello,

I think it is possible.

You would have to edit this file: `app/Modules/Auth/Http/Controllers/LoginController.php`.
I believe it's `$info->steamid`. 

https://github.com/Contentify/Contentify/blob/2.3/app/Modules/Auth/Http/Controllers/LoginController.php#L58

**Comment by jonatant** [comment]
@chriskonnertz tried, but nothing... can u made example? thanks!

**Comment by chriskonnertz** [comment]
Well it depends on what you have in mind. Here is a very basic example (line 57/58) that just prints out the Steam ID when someone logs in via Steam:

https://text-share.com/view/eb4b2a7d

( Contentify/app/Modules/Auth/Http/Controllers/LoginController.php )

**Comment by jonatant** [comment]
I'm getting message: null. And cannot login. Using 2.4 version

**Comment by jonatant** [comment]
any news? @chriskonnertz

**Comment by chriskonnertz** [comment]
Hello,

is this issue still relevant?

**Comment by torriz** [comment]
AFAIK: The current "STEAM_ID" in the db is used in the Profiles to link to the STEAM Profile, not the actuall "STEAM_0:0:11101" id?

Or did I miss something?

🆒 Would however be cool if user can add their "STEAM_0:0:11101" and it would create a link to their profile from that, but that might be out of scope for now(?)
