### ISSUE TITLE
Installation Steps Not Using Digital Ocean

### ISSUE THREAD

**Issue by chuckwolfman** [Contentify/Contentify#35]
I have been trying to figure out how to upload this through a generic file system and sql database without using Digital Ocean, and using JustHost. The main error I get running the shell script is that it cannot find the MySQL password because of the difference in file layouts from the sites. Any idea in how to upload the demo site without Digital Ocean?

**Comment by chriskonnertz** [comment]
Hello

well basically you can do what the script does:

1. Enable mod_rewrite if it's not enabled:
`sudo a2enmod rewrite`

2. Change the document root. You do not have to do it if you just want to test Contentify. The idea is to make only the `contetnify/public` folder accesible from the outside. 

If you want to change it, open your apache config file (it's somewhere in `etc/apache/`) and change/add this line:
`DocumentRoot /var/www/html/public`
Well it's a bit more than just that but that's the main idea.

3. Install missing PHP extensions. You need these (you won't have to install all):
'mcrypt',
            'fileinfo',
'pdo',
'mbstring',
'tokenizer',
'openssl',
'json'`

For instance the script uses this command to install mcrypt:
`sudo php5enmod mcrypt`

4. You have to create a database [suprise ;) ]

5. The CHMOD stuff:
`chmod -R 777 storage
chmod -R 777 bootstrap/cache
chmod -R 777 public/uploads
chmod -R 777 public/rss
chmod -R 777 public/share`

6. Maybe you have to restart apache:
`sudo service apache2 restart`

NOTE: You can just upload everything BEFORE step one and then navigate to `http://<your-ip-or-domain>/install.php` (or `http://<your-ip-or-domain>/public/install.php` if you have not changed the document root). The installer will show you if the PHP version is okay and which PHP extensions are missing.

If you have trouble installing it let me know.

**Comment by chuckwolfman** [comment]
I have to reupload the files, but creating the database aside I ran the install.php before and it returned the message "Contentify already has been installed." with the demo file, should I ditch the demo file and download the source and go through the steps you provided?

**Comment by chriskonnertz** [comment]
> it returned the message "Contentify already has been installed."
That's... interesting. A little bit scary as well. ;)

When did it display this message? Right at the beginning? Did you see this page?
![Installer Screenshott](http://s14.postimg.org/7mzdfqe9t/screenshot_installer.jpg)

**Comment by chriskonnertz** [comment]
>  should I ditch the demo file and download the source and go through the steps you provided?

Well the demo website should work.
