### ISSUE TITLE
How to Download Beta Version

### ISSUE THREAD

**Issue by Mrciller** [Contentify/Contentify#351]
Hello i wanted to ask how to download the Beta Version of Contentify

**Comment by chriskonnertz** [comment]
Hello,

you should download the version from yesterday (not in `beta` state): https://github.com/Contentify/Contentify/releases/download/v2.4/contentify_2_4.zip

If you really want the `beta` you may download it (with some small changes) here:
https://github.com/Contentify/Contentify/archive/2.4-dev.zip
This is the development version so you would have to run the `php composer install` command!

**Comment by Mrciller** [comment]
Beim update ist ja BBC integriert oder

**Comment by chriskonnertz** [comment]
Wie meinst du das? BBC = BBCode, richtig? Aber was bedeutet das? Alle Versionen von Contentify seit 1.0 haben BBCode integriert. Überlegungen BBCode bspw. gegen Markdown auszutauschen gibt es aber umgesetzt wurde davon nichts in 2.4.
