### ISSUE TITLE
Fehler beim Updaten "Duplicate column name 'country_id'"

### ISSUE THREAD

**Issue by niclasreich** [Contentify/Contentify#352]
Hi,

beim Updaten erhalte ich folgenden Fehler:
`Updating the database...Could not execute the database query: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''app.name', 'xxxxxxxx')' at line 1`

Refreshe ich die Seite dann, erhalte ich folgenden Fehler:

`Updating the database...Could not execute the database query: Duplicate column name 'country_id'
Error: Code 42S21`

Die einzige Datenbank, an der wir etwas geändert haben, ist die Datenbank der "users", dort haben wir am Ende drei Spalten hinzugefügt. Eine zweite Spalte "country_id" konnte ich in "users" nicht finden.

**Comment by niclasreich** [comment]
Scheinbar duplicate of #342

**Comment by chriskonnertz** [comment]
Hallo,

1) Schau bitte mal nach ob deine Datei `public/update.php` diesem Stand hier entspricht: https://github.com/Contentify/Contentify/blob/1111e80eac4d3c68df3c69b53c569e747a2ab21f/public/update.php
Vergleichen kannst du diese Dateien auf die Schnelle hier: https://www.diffchecker.com/

Falls sie gleich sind: Weiter zu 2)
Falls nicht: Bitte den Unterschied posten. Plus, woher du deinen Stand hast. Anschließend auf die neue Version gehen, vermutlich sind dann auch noch andere Dateien alt, also evtl. das ganze CMS neu runter laden.

2) Die Zeile, die zuerst Probleme macht ist: https://github.com/Contentify/Contentify/blob/1111e80eac4d3c68df3c69b53c569e747a2ab21f/public/update.php#L134

```sql
 "INSERT INTO {$prefix}config (name, value) VALUES ('app.name', '{$appName}');",
```

Sollte bei der Ausführung zu so was hier werden:

```sql
INSERT INTO config (name, value) VALUES ('app.name', 'NameDerWebsite');
```

Das Statement bitte einmal ausführen.

3) Wenn das Statement oben fehlschlägt und du das Update erneut auszuführen versuchst, schlägt direkt das erste MySQL-Statement ( https://github.com/Contentify/Contentify/blob/1111e80eac4d3c68df3c69b53c569e747a2ab21f/public/update.php#L85 ) fehl. Das kann nicht zweimal ausgeführt werden, weil dann zwei mal versucht wird eine gleichnamige Spalte hinzuzufügen. Es ist nicht vorgesehen, dass das Update mehr als einmal ausgeführt wird. Der einfachste Workaround wäre die MySQL-Statements vor Zeile 123 auszukommentieren und es dann erneut zu versuchen.

**Comment by niclasreich** [comment]
Danke für die unglaublich schnelle Antwort. Ja, die Dateien waren identisch.

Leider weiß ich nicht ganz, was du mit
> Die Zeile, die zuerst Probleme macht ist:
> Contentify/public/update.php
> 
> Line 134 in 1111e80
> 
>              "INSERT INTO {$prefix}config (name, value) VALUES ('app.name', '{$appName}');", 
>  "INSERT INTO {$prefix}config (name, value) VALUES ('app.name', '{$appName}');",
> Sollte bei der Ausführung zu so was hier werden:
> 
> INSERT INTO config (name, value) VALUES ('app.name', 'NameDerWebsite');
> Das Statement bitte einmal ausführen.

meinst. Soll ich den Befehl einfach in der MySQL-Datenbank-Konsole eingeben oder einfach im Updater  `"INSERT INTO {$prefix}config (name, value) VALUES ('app.name', '{$appName}');",` durch `INSERT INTO config (name, value) VALUES ('app.name', 'NameDerWebsite');` ersetzen (in genau dieser Schreibweise - also ohne Anführungszeichen)?

Ich habe jetzt einfach mal zu Testzwecken `"INSERT INTO {$prefix}config (name, value) VALUES ('app.name', '{$appName}');",` durch `INSERT INTO config (name, value) VALUES ('app.name', '_NameDerWebsite_');` ersetzt. Der Updater hat dann den Fehler `Updating the database...Could not execute the database query: Error on rename of './play/#sql-590f_557e' to './play/news' (errno: 150)` ausgespuckt.

Ich habe es jetzt ebenfalls ohne Anführungszeichen probiert, das ging natürlich nicht (hätte mich auch gewundert).

Hat Contentify möglicherweise ein Problem damit, dass mein 'NameDerWebsite' mehrere Leerzeichen und einen senkrechten Strich (`|`) hat? Selbstverständlich alles innerhalb der Apostrophen.

In storage/logs/laravel.log ergibt sich übrigens beim Klick auf Updaten folgender Fehler:
```
[2018-05-07 20:18:54] production.ERROR: exception 'InvalidArgumentException' with message 'Please provide a valid cache path.' in /var/www/play/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:36
Stack trace:
#0 /var/www/play/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(129): Illuminate\View\Compilers\Compiler->__construct(Object(Illuminate\Filesystem\Filesystem), false)
#1 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/Container.php(726): Illuminate\View\ViewServiceProvider->Illuminate\View\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build(Object(Closure))
#3 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('blade.compiler')
#4 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('blade.compiler')
#5 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/Container.php(1172): Illuminate\Foundation\Application->make('blade.compiler')
#6 /var/www/play/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(133): Illuminate\Container\Container->offsetGet('blade.compiler')
#7 [internal function]: Illuminate\View\ViewServiceProvider->Illuminate\View\{closure}()
#8 /var/www/play/vendor/laravel/framework/src/Illuminate/View/Engines/EngineResolver.php(54): call_user_func(Object(Closure))
#9 /var/www/play/vendor/laravel/framework/src/Illuminate/Support/Facades/Blade.php(17): Illuminate\View\Engines\EngineResolver->resolve('blade')
#10 /var/www/play/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(128): Illuminate\Support\Facades\Blade::getFacadeAccessor()
#11 /var/www/play/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): Illuminate\Support\Facades\Facade::getFacadeRoot()
#12 /var/www/play/app/Providers/AppServiceProvider.php(48): Illuminate\Support\Facades\Facade::__callStatic('directive', Array)
#13 /var/www/play/app/Providers/AppServiceProvider.php(48): Illuminate\Support\Facades\Blade::directive('widget', Object(Closure))
#14 [internal function]: App\Providers\AppServiceProvider->boot()
#15 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(30): call_user_func_array(Array, Array)
#16 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#18 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#19 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(788): Illuminate\Container\Container->call(Array)
#20 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(771): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AppServiceProvider))
#21 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider), 14)
#22 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(772): array_walk(Array, Object(Closure))
#23 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#24 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#25 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#26 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\Foundation\Http\Kernel->bootstrap()
#27 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#28 /var/www/play/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#29 {main}  
[2018-05-07 20:19:14] production.ERROR: exception 'InvalidArgumentException' with message 'Please provide a valid cache path.' in /var/www/play/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:36
Stack trace:
#0 /var/www/play/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(129): Illuminate\View\Compilers\Compiler->__construct(Object(Illuminate\Filesystem\Filesystem), false)
#1 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/Container.php(726): Illuminate\View\ViewServiceProvider->Illuminate\View\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build(Object(Closure))
#3 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('blade.compiler')
#4 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('blade.compiler')
#5 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/Container.php(1172): Illuminate\Foundation\Application->make('blade.compiler')
#6 /var/www/play/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(133): Illuminate\Container\Container->offsetGet('blade.compiler')
#7 [internal function]: Illuminate\View\ViewServiceProvider->Illuminate\View\{closure}()
#8 /var/www/play/vendor/laravel/framework/src/Illuminate/View/Engines/EngineResolver.php(54): call_user_func(Object(Closure))
#9 /var/www/play/vendor/laravel/framework/src/Illuminate/Support/Facades/Blade.php(17): Illuminate\View\Engines\EngineResolver->resolve('blade')
#10 /var/www/play/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(128): Illuminate\Support\Facades\Blade::getFacadeAccessor()
#11 /var/www/play/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): Illuminate\Support\Facades\Facade::getFacadeRoot()
#12 /var/www/play/app/Providers/AppServiceProvider.php(48): Illuminate\Support\Facades\Facade::__callStatic('directive', Array)
#13 /var/www/play/app/Providers/AppServiceProvider.php(48): Illuminate\Support\Facades\Blade::directive('widget', Object(Closure))
#14 [internal function]: App\Providers\AppServiceProvider->boot()
#15 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(30): call_user_func_array(Array, Array)
#16 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#18 /var/www/play/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#19 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(788): Illuminate\Container\Container->call(Array)
#20 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(771): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AppServiceProvider))
#21 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider), 14)
#22 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(772): array_walk(Array, Object(Closure))
#23 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#24 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#25 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#26 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\Foundation\Http\Kernel->bootstrap()
#27 /var/www/play/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#28 /var/www/play/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#29 {main}  
```

**Comment by chriskonnertz** [comment]
> Danke für die unglaublich schnelle Antwort.

Ähem ja... also so allgemein ist meine Reaktionszeit ja eher nicht so gut und 7 Stunden ist jetzt auch nicht so der Hammer :D 

>  Ja, die Dateien waren identisch.

Ok schade, anders wäre es schöner gewesen.

> Soll ich den Befehl einfach in der MySQL-Datenbank-Konsole eingeben

Ja genau das

> Hat Contentify möglicherweise ein Problem damit, dass mein 'NameDerWebsite' mehrere Leerzeichen und einen senkrechten Strich (|) hat?

Kann es mal testen aber an für sich ist das kein Problem.

> In storage/logs/laravel.log ergibt sich übrigens beim Klick auf Updaten folgender Fehler:

> production.ERROR: exception 'InvalidArgumentException' with message 'Please provide a valid cache path.' in /var/www/play/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:36

Sehr interessant. Vielleicht beim manuellen Leeren des Caches Ordner gelöscht, die nicht hätten gelöscht werden sollen? Ich glaube wenn man "Basis"-Cache-Ordner löscht, können diese (u. U.) nicht automatisch angelegt werden. Die Ordnerstruktur sollte schon noch so aussehen:

https://github.com/Contentify/Contentify/tree/2.4/storage/framework

**Comment by niclasreich** [comment]
Ich habe nun, wie du gesagt hast, den entsprechenden Code in die config-Tabelle mittels des Befehls einfügen können.

Ich habe natürlich davor das alte, funktionierende Backup der DB eingespielt und die Update-Datei neugestartet. Jetzt erhalte ich den Fehler
`Updating the database...Could not execute the database query: Duplicate entry 'app.name' for key 'PRIMARY'
Error: Code 23000`

Die config-Tabelle sieht nun wie folgt aus:
![image](https://user-images.githubusercontent.com/17802721/39723892-73acdb3a-5247-11e8-95ba-cb5b01c6bbd0.png)


Ja, beim manuellen Leeren des Caches wurden tatsächlich Ordner gelöscht. Ich habe diese nun wieder manuell hinzugefügt und die Rechte dafür an www-data übergeben.

Edit: ich hatte meinen Twitchkey gepostet, wow

**Comment by niclasreich** [comment]
@kamohy Bist du vielleicht irgendwie um diesen Bug drumherum gekommen?

**Comment by chriskonnertz** [comment]
@niclasreich Sollte es sich bei der DB um eine Datenbank nur zu Testzwecken handeln wäre es wohl das einfachste du schickst mir bspw. an  contact@contentify.org  einen Dump davon plus den gesamten Contentify-Order, dann schau ich das bei mir lokal an und kann es gleich debuggen.

**Comment by niclasreich** [comment]
Nein, ist eine Liveversion, aber schicke sie dir trotzdem später; schätze dich als Vertrauenswürdig ein und würde das echt gerne gefixt bekommen 👀

**Comment by chriskonnertz** [comment]
Ok super, sensible Daten (also eigentlich vor allem Userpasswörter) kannst du ja vorher mit irgend einen Quatsch überschreiben (user-Tabelle).

**Comment by niclasreich** [comment]
Hi, hatte dir die Daten Freitag geschickt - gibts seitdem schon was neues?

**Comment by chriskonnertz** [comment]
Hi, bei mir kam nichts an, werde das noch mal prüfen aber kannst du die Email nochmal an contentifycms@gmail.com schicken? Vllt. ist die irgendwo bei dem Mail-Server der anderen Adresse hängen geblieben...

**Comment by niclasreich** [comment]
Habs nochmal an die e-Mail geschickt :)

**Comment by niclasreich** [comment]
Hi, schade, dass es hier und in #357 (und mehr oder weniger auch in #333) nichts neues gibt, wir hätten das CMS gerne in Production genutzt.

Ein erstes "[Testturnier](https://play.escde.eu/cups/15/4vs4-wwii-allmode-community-tourney)" mit 24 Teilnehmerteams hat leider nicht wie erwartet funktioniert (siehe Matchestabelle, da wurden dann einfach irgendwelche Matches fünf, sechs Mal erstellt). Ebenfalls konnten einige Teams wohl nicht wieder neu joinen, nachdem ich sie aus dem Turnier entfernt hatte. Das Turnier mussten wir dann leider (vor allem zum Leidwesen der Teams und Spieler) abbrechen.

**Comment by kamohy** [comment]
Wir alle hängen gerade leider etwas fest :-/
Ich spiel gerade das 2.3 erstmal wieder auf. 
Abwarten wann Chris zeit hat um die Bugs auszuhebeln.
Man bedenke er macht das alles in seiner Freizeit :-/

**Comment by kamohy** [comment]
also ich häng bei update dort fest: question_cats

zuerst aber: rufe den ordner auf: `config` da geh auf `app.php` unt schreib unter `app_name` deine webseite rein

das ist der erste kleine bug (app.name...)

dann in der DB folgendes mal löschen fürs update: teams -> country_id
dann: cash_flow

und weiter bin ich nicht, den er behauptet Table 'question_cats' already exists
problem: ich finde es in der DB nicht !
Was tun also ? (achja update von 2.3 auf 2.4) hast du dafür ne lösung @niclasreich, @chriskonnertz  oder @pega16 ?

**Comment by chriskonnertz** [comment]
> und weiter bin ich nicht, den er behauptet Table 'question_cats' already exists
> problem: ich finde es in der DB nicht !

Tja, da fällt mir auch nicht wirklich was zu ein. Aufgrund der Fehlermeldung würde ich erwarten, dass die Tabelle existiert. Wenn sie das nicht tut, keine Ahnung...

**Comment by chriskonnertz** [comment]
> Man bedenke er macht das alles in seiner Freizeit :-/

Ja, das ist richtig.

**Comment by kamohy** [comment]
achja und das reine 2.4 gibt übrigens auch nur fehler wie bisher raus @chriskonnertz :-/

**Comment by niclasreich** [comment]
> Was tun also ? (achja update von 2.3 auf 2.4) hast du dafür ne lösung @niclasreich

Nein, wir sind wieder mit einem Backup auf 2.3 zurück, aber wie oben ja bereits geschrieben, hat das Turnier leider nicht erfolgreich geklappt :(

**Comment by chriskonnertz** [comment]
> Hi, schade, dass es hier und in #357 (und mehr oder weniger auch in #333) nichts neues gibt, wir hätten das CMS gerne in Production genutzt.

Habe tatsächlich in den letzten Tagen was anderes gemacht. Nach dem Durchpeitschen von 2.4 brauchte ich etwas Abstand.

**Comment by kamohy** [comment]
@chriskonnertz  ? hast du ne ahnung wo question_cats sein soll ?

**Comment by chriskonnertz** [comment]
> Ein erstes "Testturnier" mit 24 Teilnehmerteams hat leider nicht wie erwartet funktioniert (siehe Matchestabelle, da wurden dann einfach irgendwelche Matches fünf, sechs Mal erstellt). Ebenfalls konnten einige Teams wohl nicht wieder neu joinen, nachdem ich sie aus dem Turnier entfernt hatte. Das Turnier mussten wir dann leider (vor allem zum Leidwesen der Teams und Spieler) abbrechen.

Nicht schön. :( Das ist echt blöd.

**Comment by chriskonnertz** [comment]
> @chriskonnertz ? hast du ne ahnung wo question_cats sein soll ?

Nein. :/

**Comment by kamohy** [comment]
hat sich erledigt... hab sie gefunden...

**Comment by kamohy** [comment]
okay... bin hier gelandet..:

`Updating the database...Could not execute the database query: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''app.name', 'kamohy.de')' at line 1`

**Comment by kamohy** [comment]
auf deutsch der zuerst behobene bug is fürn arsch... egal wie man es machet :-/ @chriskonnertz  hilfe ? :D

**Comment by kamohy** [comment]
hab das einfach mal auskommentiert in der update.php, nach dem ich die DB gesäubert habe, nun habe ich dennoch wieder fehlermeldungen:

Nummer 1:
(3/3) ErrorException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c4content.partnercats' doesn't exist (SQL: select * from `partnercats` where `partnercats`.`deleted_at` is null limit 1) (View: /var/www/clients/client4/web24/web/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php)

Nummer 2:
(2/3) QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c4content.partnercats' doesn't exist (SQL: select * from `partnercats` where `partnercats`.`deleted_at` is null limit 1)

Nummer 3:
(1/3) PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c4content.partnercats' doesn't exist

**Comment by kamohy** [comment]
wenn man das behebt kommt das selbe mit advertcats ect.
hast du vergessen diese irgendwo im hardcode vergessen umzubenennen ? @chriskonnertz

**Comment by kamohy** [comment]
soo... system ein wenig ausgehebelt,hab nu scheinbar 2.4 und was is ? kann keine News ect. schreiben... ```
(1/1) InvalidArgumentException

View [admin_news_form] not found.
```

das selbe bei pages ect... man kann also nichts erstellen

**Comment by chriskonnertz** [comment]
Du fragst dich wahrscheinlich wieso diese Fehler auftreten konnten, die müssten mir ja wohl aufgefallen sein?

_Wären sie._

Daher stehe ich vor einem Rätsel.

Bei mir klappt alles. Keine Probleme mit Kategorien oder Templates oder Tabellen oder sonst was. Schätze ich muss auf unterschiedlichen Systemen testen, das einzige was mir einfällt sich halt Unterschiede zwischen den Umgebungen. Ich lad mir 2.4 noch mal und installier es einfach noch mal.

**Comment by kamohy** [comment]
ich überlege die ganze zeit von wo aus er so zugreifen will Ö.ö
er sucht ja nach: admin_news_form
ich suche also weiter :-D

**Comment by kamohy** [comment]
@chriskonnertz nutz doch unseren server, so wie wir dir es angeboten haben.
dort hast du eine reine linux-basis, windows ist einiges leichter, da windows einfach mehr erlaubt.
dadurch is xampp auch eine einfacherere lösung als linux :-O (hat mir sascha mal erklärt)

**Comment by kamohy** [comment]
fehler gefunden ! das wird witzig...
du hast vergessen dateien umzubenennen... :-/

**Comment by kamohy** [comment]
SOOOOOOO
jetzt bitte folgendes machen 
bearbeitet: update.php

löscht zeilen:
`           "INSERT INTO {$prefix}config (name, value) VALUES ('app.name', '{$appName}');",
            "RENAME TABLE {$prefix}newscats TO {$prefix}news_cats;",
            "RENAME TABLE {$prefix}partnercats TO {$prefix}partner_cats;",
            "RENAME TABLE {$prefix}advertcats TO {$prefix}advert_cats;",
            "RENAME TABLE {$prefix}slidecats TO {$prefix}slide_cats;",
            "RENAME TABLE {$prefix}downloadcats TO {$prefix}download_cats;",
            "RENAME TABLE {$prefix}pagecats TO {$prefix}page_cats;",
            "RENAME TABLE {$prefix}teamcats TO {$prefix}team_cats;",`

das hebelt quasi alles aus was nicht funktioniert.

nun beginnt der doofe teil.... sucht die module nach und nach durch
ihr macht z.b. aus :  admin_form.blade.php
admin_news_form.blade.php

überall wo ein inhalt (beim erstellen) meckert er würde gerne folgendes haben: admin_inhalt_form
müsst ihr in das entsprechende Modul unter resources und die datein: admin_form.plade.php entsprechend umbenennen....

@chriskonnertz bitte danke :D warn jetzt 5 stunden fehlersuche insgesamt :D

**Comment by kamohy** [comment]
achja und der less-compiler geht nicht :-/
und cache leeren auch nicht :-/

das beides hat fehlermeldungen, die ich nicht nachvollziehen kann...

**Comment by chriskonnertz** [comment]
Habe es neu installiert,
1. Tabelle `question_cats `existiert bei mir
2. `app.name` auch, ist aber bei mir Neuinstallation und bei dir Update, das sind zwei unterschiedliche Pfade
3. Gehe ich auf "News erstellen" öffnet sich das entsprechende Formular. Keine Fehlermeldung.
4. Bei Pages das gleiche.
5. Die Tabelle "partnercats" gibt es in der Tat nicht, "partner_cats" muss sie heißen. Wurde umbenannt.  MorpheusTheme ist aktiv,  Fehlemeldungen zu der Tabelle bekomme ich keine. Den String "partnercats" kann ich im gesamten Code nicht finden. Such du mal bitte bei dir falls du einen Editor hast der das kann. Vielleicht ein Problem das nur bei Updates auftritt?
6. Bei mir existiert die Datei "admin_form.blade.php" und sie wird auch verwendet. Bennene ich sie um in "admin_news_form.blade" gibt es eine Fehlwemeldung: "View [admin_form] not found."

Tendenziell liegt für mich die Vermutung nahe, dass das ein Problem nur beim Udpaten ist. Bei einer sauberen Neuinstallation sind die Probleme nicht ansatzweise nachzuvollziehen und derart falsche Dateinamen können auch keine Frage der Umgebung sein. Ich werde morgen ein Update durchführen und dann nochmal alle Punkte durchgehen.

Interessant wäre noch zu wissen ob von 2.3 als Basis auf 2.4 geupdated wurde oder von 2.2 auf 2.3 und dann auf 2.4?

**Comment by kamohy** [comment]
Hey Chris, habe mir eine neue 2.3 gezogen.
Von dort aus das update gemacht, auf 2.4
nachdem ich die updates so ausgehebelt habe wie dort beschrieben ging das auch mit dem update.

aber wie gesagt bei mir will er diese dateinamen ich forsche morgen weiter. allerdings hatten wir diesen fehler schonmal bei der beta von 2.4 ( #342 ), da habe ich dich auch schon darauf hingewiesen.
morgen werde ich die modul im update umschreiben damit er nur admin_form.blade.php nutzt und nicht so wie in der fehlermeldung.
aber zumindest funktionierte es so.

Sollte das klappen wie ich mir denke bekommst du von mir morgen einen bericht dazu.

Ich bin nun im Bett. Gute nacht :-)

P.S.: eine neue install von 2.4 erzeugt bei mir immer noch fehlermeldungen sobald ich die db beschreiben will. (sie install-fehler 2.4 irgendwo hier im github :D ) ( #354 )

**Comment by chriskonnertz** [comment]
**UPDATE**:

> Updating the database...Could not execute the database query: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''app.name', 'xxxxxxxx')' at line 1

This bug has been fixed - there was a mistake in a MySQL statement, but only in the downloadable .zip file, not in the GitHub files. I assume the mistake happened _after_ the tests of the update. / 
Der Fehler wurde behoben - es gab einen Fehler in einem MySQL-Statement, aber nur in der herutneraldbaren .zip-Datei, nicht in den GitHub-Dateien. Ich nehme an der Fehler ist erst -nach_ den Tests des Updates aufgetreten und wurde dann nicht mehr in der .zip-Datei korrigiert.

**Comment by chriskonnertz** [comment]
So nun das ganze mit Update von 2.3 auf 2.4 (nach Bugfix):

1. Tabelle `question_cats `existiert bei mir
2. `app.name` nun auch, den Bug beim Updaten habe ich gefixt
3. Gehe ich auf "News erstellen" öffnet sich das entsprechende Formular. Keine Fehlermeldung.
4. Bei Pages das gleiche.
5. Die Tabelle "partnercats" gibt es in der Tat nicht, "partner_cats" muss sie heißen. Wurde umbenannt.  MorpheusTheme ist aktiv,  Fehlemeldungen zu der Tabelle bekomme ich keine. 
6. Bei mir existiert die Datei "admin_form.blade.php" und sie wird auch verwendet. Benenne ich sie um in "admin_news_form.blade" gibt es eine Fehlwemeldung: "View [admin_form] not found."

Also im Großen & Ganzen verhält sich das Update wie bei einer normalen Installation von 2.4.

Und da liegt mein Problem, ich kann die Fehler nicht reproduzieren...

**Comment by kamohy** [comment]
ich schick dir morgen mal daten zu meinem Space.
(mysql - adminzugang im cont. - ftp zugang)
Damit du es dir mal selbst ansehen kannst.

(schicke es aber über whatsapp, geht ja kein anderen was an :D ) @chriskonnertz

**Comment by chriskonnertz** [comment]
Ok super.

**Comment by chriskonnertz** [comment]
Habe nun vermutlich einen Ansatz, aber werde noch nicht heute dazu kommen das Update erneut durchzuführen, da ich mich erst mal um die Bugs kümmern werde die auch in einer Neuinstallation auftauchen.

**Comment by andakawa** [comment]
@chriskonnertz Wird es in dem Update die Möglichkeit geben, nur einzelne Module zu updaten? Da das CMS nun bei mir läuft (bis auf die Cups), würde ich ungerne alles reinstallen müssen.

**Comment by kamohy** [comment]
@andakawa machsdoch nicht so kompliziert :-) nimm die update.php und kommentiere das aus was du nicht benötigst.
Allerdings wirst du dann beim nächsten update/upgrade probleme haben :-/

@chriskonnertz Super das du scheinbar den fehler gefunden hast.
Freu mich aufs update *.*

**Comment by chriskonnertz** [comment]
Mögliche Lösung die bei mir was gebracht hat: Per Konsole `php composer.phar dumpautoload`  ausführen.
 => https://github.com/Contentify/Contentify/wiki/Troubleshooting#class-not-found

**Comment by kamohy** [comment]
sooo, habe es nun auch geschafft mal ein update zumachen
allerdings gibt es hier wieder datenbank-fehler
habe die datenbank angepasst und schon kam der nächste fehler
um pages aufzurufen braucht er TABLE pagecats
um eine page zu erstellen aber page_cats (ein fehler den ich gefunden habe)
bedeutet ich durchforste heut abend oder am we abends jetzt mal das ganze system
versuche auch das open_basedir zu umgehen, wenn alles klappt gibt es von mir eine updateversion die funktionieren müsste.
sollte das mit dem open_basedir klappen, setze ich selbiges auch in der neuinstall mal ein, mal sehen was da passiert dann.

**Comment by chriskonnertz** [comment]
Ich mache hier zu, da das Ticket bereits recht alt ist und die behandelten Themen seit v2.6 nicht mehr relevant sein dürften.
