### ISSUE TITLE
Debug mode comes up...

### ISSUE THREAD

**Issue by leetnooblet** [Contentify/Contentify#353]
I have all checks before hitting install...

But then I get this error...

Please enable the debug mode to start the installer.

**Comment by chriskonnertz** [comment]
Hello,

this is not an error. It's a feature. But yes, a feature that turned out to be not one of our best ideas so with v2.4 we removed it. (You do use v2.3, right?)

To disable it open the file `config/app.php` with a text editor an change `false` to `true`:
https://github.com/Contentify/Contentify/blob/2.4/config/app.php#L41

**Comment by leetnooblet** [comment]
It should have been 2.4 i just followed the instructions on the wiki page. I am using a droplet and putty. How do I fix this issue.

**Comment by chriskonnertz** [comment]
> To disable it open the file config/app.php with a text editor an change false to true:
https://github.com/Contentify/Contentify/blob/2.4/config/app.php#L41

( Do not let you get confused by the link, there it is already set to `true`.)

**Comment by leetnooblet** [comment]
But im not really sure how to transfer it to my droplet.

**Comment by chriskonnertz** [comment]
For example with FileZilla, an FTP tool. 

Another way is to connect with PuTTY. Then use the `cd` command to switch to the `<contentify>/config` folder. (Most likely the Contentify folder will live in `/var/www`. ) Then open the file with `nano app.php`. If Nano is not installed you have to install it with `apt-get install nano` or maybe `sudo apt-get install nano`. When in Nano, go to the line and change it. Then use CRTL+O to save and CRTL+X to leave Nano. That's it.

**Comment by leetnooblet** [comment]
Omg this was rough!!!! But you are the man this worked! 

File path was /var/www/html/config 

Was able to use filezilla.

**Comment by chriskonnertz** [comment]
Nice!
