### ISSUE TITLE
Sorry, something bad happened. Our website has crashed.

### ISSUE THREAD

**Issue by okonstantinyuk** [Contentify/Contentify#355]
ERROR
Sorry, something bad happened. Our website has crashed.

Don't worry, we will handle this. In the meantime, make a cup of coffee. And stop crushing our website!

"When you press on the sowing with the Admin how to fix ?"

**Comment by kamohy** [comment]
more information? website ? crash-link ?

**Comment by niclasreich** [comment]
Duplicate of #345 - solution was already given by @chriskonnertz, @okonstantinyuk

**Comment by chriskonnertz** [comment]
Yes it seems to be a duplicate?
