### ISSUE TITLE
 FatalErrorException in SimpleXMLElement.php

### ISSUE THREAD

**Issue by Schamus** [Contentify/Contentify#356]
Hey guys,

Successfully installed the script today but when playing with the admin dashboard i got a fatal error when trying to post news. 

"FatalErrorException in SimpleXMLElement.php line 6:
Class 'SimpleXMLElement' not found"

Anyone able to help me with this?

Cheers

**Comment by chriskonnertz** [comment]
Hello,

seems like a PHP extension is missing. However, documentation says it does not need to be installed:

>This extension is enabled by default.

http://php.net/manual/en/simplexml.installation.php

Try to run phpinfo() via script:

```php
<?php
phpinfo();
```

The output should contain a section "SimpleXML".

**Comment by chriskonnertz** [comment]
Hello,

I faced this exception as well. For my setup (Linux, Apache, PHP 7) the solution was:
`sudo apt-get install php7.0-xml`

**Comment by chriskonnertz** [comment]
This is strange, the text is lost during the request...
