### ISSUE TITLE
Bug: Website displays current date in News & Videos

### ISSUE THREAD

**Issue by niclasreich** [Contentify/Contentify#357]
Hi, auf unserer Website wird bei den News und bei den Videos (also allem, was wir auf der Startseite anzeigen), das aktuelle, heutige Datum angezeigt.
https://play.escde.eu/
https://play.escde.eu/news/1/herzlich-willkommen-1

**Comment by chriskonnertz** [comment]
Hi,

hast du da schon was geändert? Mir werden verschiedene Daten angezeigt:

> Herzlich Willkommen!
> 17.05.2018
> Community Talk Folge 2 vom 01.02.2018 - Youth Support & Battleroyal
> 16.05.2018
> First-Steps-Guide - deine ersten Schritte
> 15.05.2018
> Community Talk Folge 1 vom 25.01.2018 - 2/2 Split & Amateur LANs
> 11.05.2018

**Comment by niclasreich** [comment]
Klick mal auf die News selbst und schau zum Beispiel auf das Datum von dessen Beitrag

**Comment by chriskonnertz** [comment]
Hallo,

war gerade nochmal auf der Website und das Datum scheint zu passen? 

Daher mache ich hier mal zu. Falls noch was ist bitte hier melden oder neues Ticket erstellen.
