### ISSUE TITLE
ErrorException ClassLoader.php

### ISSUE THREAD

**Issue by vibratim** [Contentify/Contentify#360]
After the install.php was executed successfully I got an error on the index.php file.
` (2/2) ErrorException

include(/var/www/vendor/composer/../../app/Modules/Partners/Partnercat.php): failed to open stream: No such file or directory (View: /var/www/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php)`

I looked the files up and they do exist, but they are written in CamelCase instead. Renaming the files do solve the problems. But this can`t be the official way :)

Greetings

**Comment by chriskonnertz** [comment]
Hello,

so this is a fresh copy of Contentify?

>  But this can`t be the official way :)

Exactly. We have to figure out where it tries to include "Partnercat.php" instead of "Partmer**C**at.php".

**Comment by chriskonnertz** [comment]
I assume it is some kind of a cache thing. Maybe the class map of the Composer autoloader is incorrect.

**Comment by vibratim** [comment]
Indeed. It's the content of the v2.4 'contentify_2_4.zip'.

**Comment by chriskonnertz** [comment]
And the operation system is Linux or Windows?

**Comment by vibratim** [comment]
It's Linux. Ubuntu, 18.04 LTS.

**Comment by andakawa** [comment]
I had a fresh install of 2.4 yesterday and encountered the same issues.
Some filenames used camelCasing therefore I needed to rename about 3 files.

**Comment by chriskonnertz** [comment]
Hello,

please
1) Per console run `php composer.phar dumpautoload`
2) https://github.com/Contentify/Contentify/commit/cdbfeb6fce3d0b5a0f82b5595203cd3c32a766f1
