### ISSUE TITLE
User Alter

### ISSUE THREAD

**Issue by SlavenTV** [Contentify/Contentify#362]
Hiho
ich bin momentan wieder ein wenig an meiner Seite am basteln.
Leider stehe ich aber momentan ein wenig aufm Schlauch.

Und zwar will ich nicht das Geburtsdatum der User anzeigen sondern nur das reine Alter.

Wie bzw wo muss ich da was ändern?

**Comment by chriskonnertz** [comment]
Hallo,

hm tja, da das Geburtsdatum einfach Text-Feld ist weißt du nicht sicher was drin steht. Daher ist das nicht so einfach. Ich überlege gerade ob man das nicht doch mal durch ein Feld zur Datumsauswahl ersetzen sollte.

Also das einfachste wäre für dich:
1. Entweder einfach hoffen dass alle ihr Geburtsdatum im Format "12.12.1234" angegeben haben oder aber per ReGex (regulärer Ausdruck) bei der Validierung beim Speichern sicherstellen, dass nur gültige Angaben eingetragen werden können. https://github.com/Contentify/Contentify/blob/2.4/contentify/Models/User.php#L192
2. Dann kannst du im Profil-Template das Datum - sofern eines angegeben wurde - als Basis für die Berechnung nutzen, wahrscheinlich so:
`{{ Carbon::createFromDate($user->birthdate)->diff(Carbon::now())->format('%y Jahre alt') }}`
https://github.com/Contentify/Contentify/blob/2.4/app/Modules/Users/Resources/Views/show.blade.php#L32
