### ISSUE TITLE
install 2.4 problem

### ISSUE THREAD

**Issue by kamohy** [Contentify/Contentify#365]
Hey @chriskonnertz 
folgendes
ich hab bei mir auf dem server folgendes prob.
er möchte auf: /usr/bin/php
zugreifen, dies ist aber eigentlich nicht erlaubt

daraus folgt diese fehlermeldung:
 (1/1) ErrorException
is_executable(): open_basedir restriction in effect. File(/usr/bin/php) is not within the allowed path(s): (/var/www/clients/client6/web12/web:/var/www/clients/client6/web12/private:/var/www/clients/client6/web12/tmp:/var/www/kamohy.me/web:/srv/www/kamohy.me/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev/random:/dev/urandom)

jetzt entsteht folgende frage: wozu wird das gebraucht ?
(dieser zugang ist bei webservern eigentlich absichtlich untersagt)
bei mir im lokalen server, kann ich das auch nicht einrichten 
der lokale server lädt sich seit dem zu tode.
preisfrage nun: kann ich das im contentify, unterbinden ?

**Comment by andakawa** [comment]
Kann es sein, dass das darunterliegende Framework(-Update) auf einmal ganz andere Rechte haben will?
Wäre jetzt das einzig logische, was mir dazu einfällt.

**Comment by chriskonnertz** [comment]
Ist nicht auszuschließen. Ist jedenfalls nichts was mir bekannt vorkommt oder durch den Core-Code von Contentify erklärbar wäre.

**Comment by kamohy** [comment]
nach deinstallation und neuer installationsversuch:
https://kamohy.de/install?step=3

geht immer noch nicht :-/

` (1/1) ErrorException
is_executable(): open_basedir restriction in effect. File(/opt/php-7.1/bin/php) is not within the allowed path(s): (/var/www/clients/client4/web24/web:/var/www/clients/client4/web24/private:/var/www/clients/client4/web24/tmp:/var/www/kamohy.de/web:/srv/www/kamohy.de/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin)`

**Comment by andakawa** [comment]
@kamohy in der httpd.conf open_basedir auf none setzen (alternativ auch in der php.ini, je nach umgebung)

**Comment by kamohy** [comment]
@pega16 besteht die möglichkeit oder schalten wir damit irwas ab was aufm server gebraucht wird ?

**Comment by Pega16** [comment]
@kamohy das ist kein Problem, entzieht sich aber meiner Logik, da dieser Pfad erstens nicht existent und zweitens nicht genutzt ist... aber naja... ich machs mal und Du testest es erneut...

**Allerdings sehe ich ernsthaft KEINEN SINN darin, das zu aktivieren, um es dann zu deaktivieren, denn per Standard ist open_basedir deaktiviert!**

*Zur Erklärung:
Auf meinem Server gibt es kein open_basedir... ich müsste diese Einstellung erst aktivieren, um dahinter dann die Deaktivierung zu schreiben und das macht in meinem Kopf keinerlei Sinn...!*

**Comment by kamohy** [comment]
sehr verwunderlich :-/

**Comment by Pega16** [comment]
Kurz noch ein kleiner Nachtrag als eigener Comment @chriskonnertz 
open_basedir ist seit PHP 5.3.0 per Standard DEAKTIVIERT... die Einstellung gibt es seit dem nicht mehr... man KÖNNTE sie dazu basteln, wenn man sie bräuchte, aber es wird auch von php.net strengstens davor gewarnt, dies zu nutzen, da ein Eintrag dort volle Lese- und Schreibrechte auf alle im angegebenen Verzeichnis liegenden Dateien für JEDERMANN einräumt...

Deshalb ist diese Variable seit 5.3.0 gar nicht mehr vorgesehen und bei mir auch gar nicht aktiviert... die große Frage die sich mir stellt, ist nur, WARUM dennoch ein derartiger Fehler ausgegeben wird, wenn das Teil für den Server gesehen gar nicht mehr existiert...!

*Da es allerdings die Möglichkeit gibt, via .htaccess open_basedir zu aktivieren und innerhalb des aktuellen Webs zu nutzen, ist das Einzige, das mir dazu einfällt, eine .htaccess in irgend einem der Ordner (ich tippe auf das Framework!), die versucht auf den Pfad zuzugreifen und ihn für temp-uploads etc. freizugeben und das wird per Sicherheitsrichtlinie logischerweise blockiert... allerdings würde dies die Fehlermeldung erklären...*

werde die Tage mal versuchen die Zeit zu finden und durchsuche alle Ordner nach .htaccess - Dateien und schau mir die entsprechenden Einstellungen darin an... vielleicht liegt genau dort der Hase im Pfeffer... gebe danach Rückmeldung... kann aber bis zum Wochenende dauern...

LG
Sascha

**Comment by kamohy** [comment]
so, mit der grundinstall 2.3 und dann 2.4 update, sowie ein paar kleinen änderungen, ging es nun.
allerdings geht durch open_basedir weder: cache leeren noch less kompelieren.
er versucht weiterhin den pfad: /opt/php-7.1/bin/php...

warum die install selbst von 2.4 nicht geht liegt übrigens am selben pfad...

**Comment by kamohy** [comment]
so trotz update fehler gefunden :-S
befasse mich morgen etwas exersiver damit...

**Comment by Pega16** [comment]
@chriskonnertz Das Problem scheint nicht open_basedir zu sein, sondern tatsächlich der Fakt, dass irgendwas in Contentify die Nutzung der "einfachen Beeinflussung" nehmen möchte, wie sie früher mal genutzt wurde...

Da open_basedir inzwischen aus Sicherheitsgründen schon seit ein paar PHP-Versionen standardmäßig "denied" ist, läuft contentify da in einen Fehler...

Einen Beispielcode (NICHT aus Contentify!) habe ich Dir da... dieser Code ist SCHEMATISCH zu sehen, damit Du weißt, wo in etwa Du suchen musst...

`$tempname=$_FILES['datei']['tmp_name'];
$fname=$_FILES['datei']['name'];
imagecreatefromjpeg($tempname);`

das ist der schematische Code der in KEINEM Fall mehr funktioniert, außer man öffnet seinen Server für alle Welt für allerlei Aktionen wie open-Relay, etc... ;)

ich selbst finde aktuell keine Alternative, mit der man das Problem mit dem verbotenen open_basedir umgehen kann, aber ich weiß, dass das problemlos möglich ist, DENN tausende andere Scripte schaffen Dateiuploads und allerlei anderen Kram auch bei deaktiviertem open_basedir... Contentify aber aus irgend einem Grund nicht... *Wobei ich immernoch vermute, dass laravel das Problem darstellt und nicht Contentify... also das laravel irgendwelche Uploads (ja, nur dafür ist das da!) machen möchte, oder zumindest abprüft, ob diese möglich wären und man damit dann in den Fehler rennt...!*

Eine gute Möglichkeit wäre meines Erachtens nach, bei Contentify bei manchen Funktionen direkt auf shell_exec() zurückzugreifen, denn damit lässt sich problemlos der Inhalt des Cache-Ordners löschen (variable = shell_exec('cd /pfad/zum/cache/ordner/; rm -r *'); echo variable;) und noch so einige andere Dinge auch... im Zweifel können wir uns da mal zusammensetzen, denn auch mich wurmt das, dass irgendwas (und ja, ich find es auch nicht im Code!) versucht, über alte Routinen, die aus Sicherheitsgründen schon lange deaktiviert, bzw. auf den Servern explizit verboten sind, zu gehen...
Vor allem ist es seltsam, dass deathkings (Version 2.2) problemlos funktioniert nachdem wir gemeinsam einiges gefixt haben, aber die Neueren nun doch wieder altbekannte Probleme verursachen...

LG
Sascha


**NACHTRAG:** mir fiel gerade auf, dass deathkings auf PHP5.6 läuft... da gehts... stell ich auf 7.1 oder gar 7.2 hoch, ists wiederum vorbei... mhm...

**Comment by kamohy** [comment]
Hallo @chriskonnertz hast du das open_basedir fixen können ?
Würde mich über ein update freuen.

**Comment by chriskonnertz** [comment]
Leider noch nicht. Werde aber versuchen mich jetzt wieder verstärkt durch die offenen Bug-Tickets zu arbeiten.
