### ISSUE TITLE
Update from 2.3 to 2.4

### ISSUE THREAD

**Issue by andakawa** [Contentify/Contentify#366]
Hi,
ich wollte soeben ein Update von Version 2.3 auf 2.4 durchführen und bekam prompt die Fehlermeldung:

_Error: Cannot update from version 2.2, only from one of these: 2.3
Error: Code -1_

Habe dann die Version in der Datenbank auf 2.3 gesetzt und bekam im Anschluss den Fehler, dass die country_id schon existiert -> habe dann im Update die entsprechende Zeile auskommentiert und nun kam:

_Updating the database...Could not execute the database query: Table 'cash_flows' already exists
Error: Code 42S01_

Also auch diese Zeilen auskommentiert und jetzt habe ich plötzlich zwei Primary Keys, was denke ich nicht zielführend ist :D 
_Updating the database...Could not execute the database query: Multiple primary key defined
Error: Code 42000_

Den Update-Guide habe ich genau wie beim letzten Mal befolgt (Cache geleert, Backup gezogen, Update auf den Server geschmissen, Update.php ausgeführt)

[EDIT]
Die Zeile mit den cash_flows ist wieder drin und ich erhalte den Fehler:
_Updating the database...Could not execute the database query: Table 'cash_flows' already exists
Error: Code 42S01_

Jedoch existiert diese Tabelle nicht in der DB.
[/EDIT]

[EDIT2]
Habe nun die Table in der Zeile davor gedroppt, damit die nächste Zeile das Create ausführen kann und nun ist folgender Fehler aufgetreten:

_Updating the database...Could not execute the database query: Table 'question_cats' already exists
Error: Code 42S01_

Ich erkenne hier ein Muster und bin jetzt etwas ratlos, was der beste Schritt ist.
[/EDIT2]

Gibt es hierfür einen Workaround?

LG

**Comment by kamohy** [comment]
moin, hier haben einige das prob, ich hatte es auch.
Problem ist mit dem update aber noch ein anderes: das is nicht ganz so simpel wie gedacht
schau mal hier: #352 vllt. bringt dich das ein wenig weiter

**Comment by chriskonnertz** [comment]
Hallo,

schaue ich mir nachher an.

Wie kamohy schon sagte, steht vermutlich in Zusammenhang mit https://github.com/Contentify/Contentify/issues/352 .

**Comment by andakawa** [comment]
Hi,
die Infos aus der anderen Issue haben leider nicht geholfen - werde jetzt einen Rollback durchziehen.

LG

**Comment by kamohy** [comment]
@chriskonnertz hast d die neuerungen ins update mit eingesetzt ?
und in der neuinstall ?

**Comment by chriskonnertz** [comment]
Ja habe ich soeben gemacht.

**Comment by kamohy** [comment]
sehr gut, danke *redownload startet* :D

**Comment by andakawa** [comment]
@chriskonnertz hast du zufällig eine übersicht mit den fixes geschrieben? ich würde gerne vermeiden, dass ich jetzt deine fixes übertrage und es dann konflikte gitb da ich selbst welche vorgenommen habe :) Lg
