### ISSUE TITLE
Cash-Flow

### ISSUE THREAD

**Issue by andakawa** [Contentify/Contentify#367]
Hi,
there's a small problem with the cash-flow module.

There is a huge error-list when clicking on the menu-item in the backend.

Screenshot here:
![admin-cash-flows-2018-05-30-10_45_46](https://user-images.githubusercontent.com/19193168/40709999-d111907e-63f7-11e8-80db-0207b398dc73.png)

I hope this helps :)

**Comment by chriskonnertz** [comment]
Hello,

I will check this.

**Comment by chriskonnertz** [comment]
Yep, I get this error as well.

**Comment by chriskonnertz** [comment]
Fixed: https://github.com/Contentify/Contentify/commit/1f224e920714805c270f076b530b439bcc4259b1

**Comment by Ozymandias2** [comment]
To correct this without reinstalling:

mysql> use contentify2;
mysql> alter table cash_flows change revenues integer_revenues int(11);
mysql> alter table cash_flows change expenses integer_expenses int(11);
