### ISSUE TITLE
Filename capitalisation wrong?

### ISSUE THREAD

**Issue by IrealiTY** [Contentify/Contentify#369]
```
(2/2) ErrorException
include(/home/admin/web/domain.xyz/public_html/vendor/composer/../../app/Modules/Adverts/Advertcat.php): failed to open stream: No such file or directory (View: /home/admin/web/domain.xyz/public_html/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php)
--
```
it looks for Advert**c**at.php but the original file was Advert**C**at.php

Had the same issue on Partnercat.php which **_"solved"_** by duplicating and renaming the file - but I doubt that's the right approach....

**Comment by IrealiTY** [comment]
Solution was:
`composer dumpautoload`

**Comment by chriskonnertz** [comment]
Hello,

nice hint, thank you!
