### ISSUE TITLE
Getting errors.

### ISSUE THREAD

**Issue by Eizenbear** [Contentify/Contentify#37]
Hi,

Thought I leave the feedback here rather than on Skype.

File: _Contentify/app/Modules/Streams/Resources/Views/admin_form.blade.php_

Leaves tons of error @ **line: 10**

Code: _{!! Form::smartText() !!}}_

Changed the line to an older version:
{!! Form::smartUrl('url', trans('app.url')) !!}

And now it seems to be working as intended.

**Comment by Eizenbear** [comment]
Errors:
ErrorException in FormBuilder.php line 299:

Missing argument 1 for Contentify\FormBuilder::smartText(), called in url-to-page\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 213 and defined (View: url-to-page\app\Modules\Streams\Resources\Views\admin_form.blade.php)

**Comment by chriskonnertz** [comment]
Hi,

thanks.

Fixed: https://github.com/Contentify/Contentify/commit/a951a893369c0298a547ae88a76cc5b10a33b75c

Regards
