### ISSUE TITLE
Error: Request failed. Code: 500. Message: "Internal Server Error"

### ISSUE THREAD

**Issue by jonatant** [Contentify/Contentify#370]
I'm trying to create comment and i'm getting error

>  Error: Request failed. Code: 500. Message: "Internal Server Error"

Contentify 2.4

**Comment by chriskonnertz** [comment]
Hello,

I can confirm the existence of this bug. There is another, hidden error message which is: ""Cannot create comment. The text field is required." However, the text is part of the request so I need to investigate what the real reason for this error is.

**Comment by chriskonnertz** [comment]
Got it. https://github.com/Contentify/Contentify/commit/c30c4e1df0b97b7c590379425a5fdfed6409dc11
