### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by Mrciller** [Contentify/Contentify#371]
****

2/2) ErrorExceptioninclude(/var/www/html/vendor/composer/../../app/Modules/Partners/Partnercat.php): failed to open stream: No such file or directory (View: /var/www/html/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php)
--
in ClassLoader.php (line 444)
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php (line 44)
at PhpEngine->evaluatePath('/var/www/html/storage/framework/views/13399f3441d7a7ccd3f471004d3f5b6f58f60ee6.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'page' => '<div class="items"> </div> <div class="clearfix"></div> <div class="loading hidden text-center"><i class="fas fa-spinner fa-spin"></i> Lade...</div> <script> $(document).ready(function() { var timestamp = 0; var loading = false; var lastScrollTop = 0; $(document).scroll(function() { var scrollTop = $(this).scrollTop(); if (scrollTop < lastScrollTop \|\| ! 0) { return; } lastScrollTop = scrollTop; var scrollBottom = scrollTop + $(window).height(); var $lastItem = $(\'.page .item\').last(); if ($lastItem.length > 0) { var lastItemBottom = $lastItem.offset().top + $lastItem.height(); if (scrollBottom > lastItemBottom) { timestamp = parseInt($lastItem.attr(\'data-timestamp\')) - 1; if (! loading) { loading = true; $(\'.page .loading\').removeClass(\'hidden\'); $.get(contentify.baseUrl + \'news/showStream/\' + timestamp, function(data) { var $items = $(data).addClass(\'new\'); $(\'.page .items\').append($items).append(\'<div class="bugfix"></div>\'); $(\'.page .items .bugfix\').last().hide().show(0); // Force browsers to show CSS transitions $items.removeClass(\'new\'); }).always(function() { if ($(\'.page .items .item\').last().attr(\'data-more\') == 1) { loading = false; } $(\'.page .loading\').addClass(\'hidden\'); }); } } } }); }); </script>', 'metaTags' => array(), 'openGraph' => null, 'title' => null, 'breadcrumb' => array('Start' => 'http://46.101.200.73', 'News' => null), 'templateClass' => 'page-news-show-stream', 'moduleName' => 'News', 'controllerName' => 'News'))in CompilerEngine.php (line 59)
at CompilerEngine->get('/var/www/html/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php', array('__env' => object(Factory), 'app' =>object(Application), 'errors' => object(ViewErrorBag), 'page' => '<div class="items"> </div> <div class="clearfix"></div> <div class="loading hidden text-center"><i class="fas fa-spinner fa-spin"></i> Lade...</div> <script> $(document).ready(function() { var timestamp = 0; var loading = false; var lastScrollTop = 0; $(document).scroll(function() { var scrollTop = $(this).scrollTop(); if (scrollTop < lastScrollTop \|\| ! 0) { return; } lastScrollTop = scrollTop; var scrollBottom = scrollTop + $(window).height(); var $lastItem = $(\'.page .item\').last(); if ($lastItem.length > 0) { var lastItemBottom = $lastItem.offset().top + $lastItem.height(); if (scrollBottom > lastItemBottom) { timestamp = parseInt($lastItem.attr(\'data-timestamp\')) - 1; if (! loading) { loading = true; $(\'.page .loading\').removeClass(\'hidden\'); $.get(contentify.baseUrl + \'news/showStream/\' + timestamp, function(data) { var $items = $(data).addClass(\'new\'); $(\'.page .items\').append($items).append(\'<div class="bugfix"></div>\'); $(\'.page .items .bugfix\').last().hide().show(0); // Force browsers to show CSS transitions $items.removeClass(\'new\'); }).always(function() { if ($(\'.page .items .item\').last().attr(\'data-more\') == 1) { loading = false; } $(\'.page .loading\').addClass(\'hidden\'); }); } } } }); }); </script>', 'metaTags' => array(), 'openGraph' => null, 'title' => null, 'breadcrumb' => array('Start' => 'http://46.101.200.73', 'News' => null), 'templateClass' => 'page-news-show-stream', 'moduleName' => 'News', 'controllerName' => 'News'))in View.php (line 137)
at View->getContents()in View.php (line 120)
at View->renderContents()in View.php (line 85)
at View->render()in Response.php (line 38)
at Response->setContent(object(View))in Response.php (line 200)
at Response->__construct(object(View))in Router.php (line 615)
at Router->prepareResponse(object(Request), object(View))in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyAdminAccess.php (line 40)
at VerifyAdminAccess->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in UpdateUser.php (line 114)
at UpdateUser->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 24)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HttpsRedirect.php (line 33)
at HttpsRedirect->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

**Comment by chriskonnertz** [comment]
=> https://github.com/Contentify/Contentify/issues/360#issuecomment-393995636
