### ISSUE TITLE
Cash-Flow funktioniert nicht

### ISSUE THREAD

**Issue by Mrciller** [Contentify/Contentify#372]
(2/2) QueryExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'integer_revenues' in 'field list' (SQL: select sum(`integer_revenues`) as aggregate from `cash_flows` where `cash_flows`.`deleted_at` is null)
--
in Connection.php (line 647)
at Connection->runQueryCallback('select sum(`integer_revenues`) as aggregate from `cash_flows` where `cash_flows`.`deleted_at` is null', array(),object(Closure))in Connection.php (line 607)
at Connection->run('select sum(`integer_revenues`) as aggregate from `cash_flows` where `cash_flows`.`deleted_at` is null', array(), object(Closure))in Connection.php (line 326)
at Connection->select('select sum(`integer_revenues`) as aggregate from `cash_flows` where `cash_flows`.`deleted_at` is null', array(), true)in Builder.php (line 1705)
at Builder->runSelect()in Builder.php (line 1690)
at Builder->get(array('integer_revenues'))in Builder.php (line 2025)
at Builder->aggregate('sum', array('integer_revenues'))in Builder.php (line 1986)
at Builder->sum('integer_revenues')in Builder.php (line 1252)
at Builder->__call('sum', array('integer_revenues'))in Model.php (line 1374)
at Model->__call('sum', array('integer_revenues'))in BaseModel.php (line 382)
at BaseModel->__call('sum', array('integer_revenues'))in Model.php (line 1386)
at Model::__callStatic('sum', array('integer_revenues'))in AdminCashFlowsController.php (line 32)
at AdminCashFlowsController->index()
at call_user_func_array(array(object(AdminCashFlowsController), 'index'), array())in BaseController.php (line 114)
at BaseController->callAction('index', array())in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AdminCashFlowsController), 'index')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyAdminAccess.php (line 40)
at VerifyAdminAccess->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in UpdateUser.php (line 114)
at UpdateUser->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 24)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HttpsRedirect.php (line 33)
at HttpsRedirect->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

Ich entschuldige mich wenn ich euch nerve

**Comment by chriskonnertz** [comment]
Hallo,

kein Problem, du nervst nicht. Es ist gut, wenn solche Meldungen kommen! Nur bekannte Bugs können auch gefixt werden.

In diesem Fall hast du Glück, wurde vorhin gefixt: https://github.com/Contentify/Contentify/issues/367

**Comment by chriskonnertz** [comment]
Ich lasse Issues meistens lange offen aber es haben sich derzeit wieder sehr viele angestaut, daher mache ich sie im Moment schnell zu um ein bisschen aufzuräumen. :)

**Comment by chriskonnertz** [comment]
72 sind noch offen und das sieht für mich nicht besonders gut aus, wenn man jetzt zum ersten mal reinschaut denkt man halt dass sich um die Issues nicht gekümmert wird. Der ein oder andere wird jetzt mit den Augen rollen und denken, dass da auch was drin ist. Aber da kennt man auch noch ganz andere Zustände, wo wirklich sich gar nicht mehr gekümmert wird und einfache Fragen auch nach einem Jahr noch nicht beantwortet sind und man eigentlich nur zu dem Schluss kommen kann, das Projekt ist tot und wird nicht maintained. Das ist hier ja nicht so.

**Comment by chriskonnertz** [comment]
Hier ist es eher so, die Verfügbare Zeit muss aufgeteilt werden und da müssen die Issues manchmal etwas warten.

**Comment by Mrciller** [comment]
muss ich es dann neuinstallieren oder wie?

**Comment by chriskonnertz** [comment]
Nein, nur die Spalten in der Datenbanktabelle umbenennen. ( Mit phpMyAdmin oder dergleichen )

**Comment by Mrciller** [comment]
und dass gleiche ist auch bei news

**Comment by Mrciller** [comment]
bei mir kommen jetzt bei vielen Sachen errors

creates kommen error (zB faw oder cash-flow create)

error sieht so aus


(1/1) InvalidArgumentExceptionView [admin_news_form] not found.
--
in FileViewFinder.php (line 137)
at FileViewFinder->findInPaths('admin_news_form', array('/var/www/html/app/Modules/News/Resources/Views'))in FileViewFinder.php (line 92)
at FileViewFinder->findNamespacedView('news::admin_news_form')in FileViewFinder.php (line 76)
at FileViewFinder->find('news::admin_news_form')in Factory.php (line 128)
at Factory->make('news::admin_news_form', array('modelClass' => 'App\\Modules\\News\\News'))in Facade.php (line 221)
at Facade::__callStatic('make', array('news::admin_news_form', array('modelClass' => 'App\\Modules\\News\\News')))in BaseController.php (line 223)
at BaseController->pageView('news::admin_news_form', array('modelClass' => 'App\\Modules\\News\\News'))in ModelHandler.php (line 356)
at ModelHandler->create()in Facade.php (line 221)
at Facade::__callStatic('create', array())in ModelHandlerTrait.php (line 19)
at AdminNewsController->create()
at call_user_func_array(array(object(AdminNewsController), 'create'), array())in BaseController.php (line 114)
at BaseController->callAction('create', array())in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AdminNewsController), 'create')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyAdminAccess.php (line 40)
at VerifyAdminAccess->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in UpdateUser.php (line 114)
at UpdateUser->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 24)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HttpsRedirect.php (line 33)
at HttpsRedirect->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

**Comment by chriskonnertz** [comment]
Hm... das sollte eigentlich behoben sein.

**Comment by Shiffed** [comment]
I am also having the (1/1) InvalidArgumentExceptionView [admin_news_form] not found after fresh installation of 2.4
