### ISSUE TITLE
Installation in Sub-Directory of webroot

### ISSUE THREAD

**Issue by GaneshKandu** [Contentify/Contentify#374]
Hi,

I want to install Contentify in Sub-Directory not in web-root as there are some other installation all ready exist in web-root
**ie.** 

**PATH** /public_html/Sub-Directory/Contentify-installed-here ```public_html is web-root here```
**URL**   http://mydomain.com/Sub-Directory/Contentify-installed-here/public

but config file is .ini file which is web accessible and downloadable

Any solution ?

**Comment by jonatant** [comment]
@GaneshKandu create virtualhost

**Comment by GaneshKandu** [comment]
Hi, i am using shared hosting
i cant create virtualhost

**Comment by andakawa** [comment]
It should work fine if your provider offers the php extentions. You will maybe get an error attempting to initially install the cms regarding a connection limit. If you comment that line out you'll be able the install it.

**Comment by GaneshKandu** [comment]
I have installed Contentify 
there is no problem in installation
my point is its not safe if i am installing Contentify in Sub-Directory because .ini file web accessible
and any one can download .ini file just by hitting url

**Comment by chriskonnertz** [comment]
Hello,

the solution is a `.htaccess` file that protects the folder. I recommend googling for a tutorial or looking around here in the issue section, for example: https://github.com/Contentify/Contentify/issues/80#issuecomment-258619915

**Comment by GaneshKandu** [comment]
Ok! Thanks @chriskonnertz 
```xml
<files *.ini>
  order deny,allow
  deny from all
</files>
```
works

**Comment by GaneshKandu** [comment]
It's a best to make ```.php``` file instead of ```.ini ``` .htaccess will not works in Nginx server
in My case its working but still
