### ISSUE TITLE
Banned user still can login

### ISSUE THREAD

**Issue by jonatant** [Contentify/Contentify#377]
Hello. I banned 1 user from admin CP. And he is still can write forum topics, write comments and still can login. :)

**Comment by chriskonnertz** [comment]
Hello,

okay, that's a problem. Quick solution: Delete the user account.

**Comment by jonatant** [comment]
I just made a little code edit. I check if user creating forum threads, comments, and etc are not banned. :) if they banned they cannot create any things.
