### ISSUE TITLE
Position Bug

### ISSUE THREAD

**Issue by iktray** [Contentify/Contentify#378]
There is a Position bug when trying to organize things.

**Comment by chriskonnertz** [comment]
Hello,

thank you for reporting this bug. However, your description is a bit vague. It would be great if you add a screenshot or a more detailed text.

**Comment by iktray** [comment]
**

> **Also its just not for the teams page it also on other pages as well.**

**
![image](https://user-images.githubusercontent.com/30093468/41512234-5e15eb78-7253-11e8-80df-2b2a5889cb3a.png)
![image](https://user-images.githubusercontent.com/30093468/41512252-80b3b052-7253-11e8-8deb-9c0531839061.png)

**Comment by kamohy** [comment]
Bug besteht immer noch !

**Comment by chriskonnertz** [comment]
Please try this bug fix: https://github.com/Contentify/Contentify/commit/1d0290c693cc1236776abc10ba79c6dbb6016b34

**Comment by kamohy** [comment]
mach ich morgen :-)

**Comment by kamohy** [comment]
fertig und danke :-)
