### ISSUE TITLE
Image size position bug 

### ISSUE THREAD

**Issue by iktray** [Contentify/Contentify#379]
![image](https://user-images.githubusercontent.com/30093468/41551176-1d97cdb8-72f9-11e8-8ff7-9ddbf1d4f113.png)

**Comment by chriskonnertz** [comment]
Hello,

uhrgs... yep, that should not happen. Thank you for reporting the bug.

However, I am a bit confused why this happened. There should be CSS code that limits the size of images:
```
.page-news-show-overview .news .image img, .page-news-show .news .image img {
    max-width: 100%;
}
```

This style should be active in all versions of Contentify.

Did you apply any custom CSS code to this image?

**Comment by iktray** [comment]
No, I didn't.

**Comment by chriskonnertz** [comment]
Please open the website in your browser, then open the browser, then open "page" and then "save as" (these steps might differ a bit depending on your browser) to save the website as a HTML file. Then send this file (or the file and the folder if there is a also folder) to `contentifycms [at] gmail [dot] com`. Then I can debug it.

**Comment by chriskonnertz** [comment]
I somehow need to get access to your website to debug the issue, because I have no explanation why this happens. So you have to send it to me via email or something else.

**Comment by kamohy** [comment]
besteht auch leider noch :-/

**Comment by chriskonnertz** [comment]
@kamohy Hast du dafür ein Beispiel? Kann ich darauf zugreifen? Wenn nicht, kannst du mal das hier machen?

> Please open the website in your browser, then open the browser, then open "page" and then "save as" (these steps might differ a bit depending on your browser) to save the website as a HTML file. Then send this file (or the file and the folder if there is a also folder) to contentifycms [at] gmail [dot] com. Then I can debug it.

**Comment by kamohy** [comment]
http://voll-verbrickt.de da ist ein beispiel :)
auf dem handy sieht das echt doof aus :-/

**Comment by chriskonnertz** [comment]
Ja gut das liegt an der Art wie das HTML-Attribut `width` angegeben wurde:
![fehler](https://user-images.githubusercontent.com/4319323/46915586-de429f00-cfad-11e8-9056-30bb0368ad50.png)
Die Anführungszeichen innerhalb der äußeren Anführungszeichen `"` müssen weg. Dann klappt es.

**Comment by kamohy** [comment]
omfg :-D 
so blöd muss man erstma sein xD
danke dir... war wohl nen flüchtigkeitsfehler :-D 

*mich ma gerade fühl wie nen anfänger-noob
