### ISSUE TITLE
Getting Error while installing Contentify 2.4

### ISSUE THREAD

**Issue by GaneshKandu** [Contentify/Contentify#380]
#### I am Getting Error while installing Contentify 2.4
Getting this error on button click of database fill up step

Contentify 2.4 trying to get database details for table creation and insertion from ```database.ini``` which is field with default value

you should update ```database.ini``` first before table creation and insertion while install so that Contentify 2.2 can connect with right database details instead of default value 

Laravel Log --> [laravel.log](https://github.com/Contentify/Contentify/files/2114716/laravel.log)

![screenshot-webuzo web-2018-06-19-15-07-40](https://user-images.githubusercontent.com/12833130/41590075-a4703454-73a5-11e8-84da-827d70a648e7.png)

**Comment by GaneshKandu** [comment]
#### Contentify 2.4 

Laravel Log --> [laravel.log](https://github.com/Contentify/Contentify/files/2114779/laravel.log)


![screenshot-webuzo web-2018-06-19-15-33-50](https://user-images.githubusercontent.com/12833130/41591185-8aa044c6-73a8-11e8-8c4f-dca62a80aaf0.png)

**Comment by chriskonnertz** [comment]
Hello,

seems like my comment disappeared... 

So, again: Thank you for creating this issue. So the database credentials in the `storage/app/databse.ini` are correct?

**Comment by GaneshKandu** [comment]
yes, credentials  are correct in ```storage/app/databse.ini```
but my database credentials are different from default value in ```storage/app/databse.ini```
```ini
; Auto-generated file with database connection settings.
; See config/database.php for more settings.

host = 127.0.0.1
database = contentify2
username = root
password = 
```

**Comment by chriskonnertz** [comment]
What part is different? Do you have a special port? You can change the port in this file: https://github.com/Contentify/Contentify/blob/v2.4/config/database.php#L45

**Comment by GaneshKandu** [comment]
No i don't have special port i am using default port 3306

**Comment by GaneshKandu** [comment]
Did you able to reproduce ?  i got solution of it

**Comment by chriskonnertz** [comment]
@GaneshKandu What solution did you find? :)

**Comment by GaneshKandu** [comment]
Moved 
```php
                $this->createDatabase();
                $this->createUserRoles();

                /*
                 * Create the daemon user (with ID = 1)
                 */
                $user = Sentinel::register(array(
                    'email'     => 'daemon@contentify.org',
                    'username'  => 'Daemon',
                    'password'  => Str::random(),
                    'activated' => false,
                ));

                $this->createSeed();
```
 function to ``step 5`` from ``step 4`` where ``config/database.php`` and ``createDatabase `` was written to run at same time

i used 4 step to create database file so that ``createDatabase `` function can run after creating creating database file only

step 5 is to ``createDatabase `` ,``createUserRoles`` and ``createSeed``

**Comment by GaneshKandu** [comment]
https://github.com/Contentify/Contentify/pull/383

**Comment by GaneshKandu** [comment]
https://github.com/Contentify/Contentify/pull/383
Hi @chriskonnertz Please look at the changed i made

**Comment by chriskonnertz** [comment]
Hi, yes I will take  a closer look tomorrow. I *believe* I understand the problem now, I have to look at it from different angles and do some testing but you might have a point there...

**Comment by chriskonnertz** [comment]
Hello,

finally had time to write a bug fix. I hope this fixes excatly this problem.

In your pull request you were right about what the problem was, but I was also right that there had to be a redirect (okay, acutally I've added a new step instead of a redirect), so I kinda combined our solutions. c9d58d4

Thank you for your contribution, it helped a lot (even though it did not get merged)!
