### ISSUE TITLE
failed to open stream no such file or directory

### ISSUE THREAD

**Issue by GaneshKandu** [Contentify/Contentify#384]
Hi,
Getting following error after install

**failed to open stream no such file or directory**

i think issue is Contentify trying to include some file which is present at the location but not in same case
will work in `windows` but not on `linux` as its case sensitive

**Pagecat > PageCat**
![screenshot-webuzo web-2018-06-21-15-37-29](https://user-images.githubusercontent.com/12833130/41714895-4a544ed6-7541-11e8-8bdb-4048df9e6da4.png)
![img_20180621](https://user-images.githubusercontent.com/12833130/41714907-5610ef04-7541-11e8-9ebe-57f1deb31d67.png)
**Partnercat > PartnerCat**
![screenshot-webuzo web-2018-06-21-15-32-21](https://user-images.githubusercontent.com/12833130/41714936-6cbe6b82-7541-11e8-8a0a-c73f91de365b.png)
![img_20180621 1](https://user-images.githubusercontent.com/12833130/41714949-72ff6988-7541-11e8-9749-e54e4aab5ec7.png)
**Advertcat > AdvertCat**
![screenshot-webuzo web-2018-06-21-15-36-16](https://user-images.githubusercontent.com/12833130/41715005-9c9f8070-7541-11e8-941e-f67cd2bae335.png)
![img_20180621 2](https://user-images.githubusercontent.com/12833130/41715006-9f1ee71e-7541-11e8-8bc1-c36b507403e7.png)

**Comment by GaneshKandu** [comment]
i found only three may be there are more

**Comment by iktray** [comment]
Rename it to "Advertcat.php", "Partnercat.php", and "Pagecat.php".

**Comment by GaneshKandu** [comment]
they should change in package

**Comment by chriskonnertz** [comment]
Hello,

thank you for creating the issue. Solution: https://github.com/Contentify/Contentify/issues/360#issuecomment-393995636

Yes you are right, this should be changed in the .zip file.
