### ISSUE TITLE
Erstellen einer Forums nicht möglich / Cant Create Forum

### ISSUE THREAD

**Issue by RaceTubeGermany** [Contentify/Contentify#386]
Hallo,

leider ist es in Contentify nicht möglich ein Forum zu erstellen.
Fehler: forum id muss eine ganze Zahl sein

Es gibt keine Eingabe einer ID:

-------------------------------------------------------------------------

Hello,

Unfortunately it is not possible to create a forum in Contentify.
Error: forum id must be an integer

There is no input of an ID:

Danke für Eure Hilfe / Thanks for your Help

<img width="501" alt="2018-06-22 12_39_20-" src="https://user-images.githubusercontent.com/40469647/41772558-5e6f71c4-7619-11e8-9321-6d7a2e440637.png">

**Comment by chriskonnertz** [comment]
Hallo,

wie schon beim Impressum: Ich glaube das ist ein alter Bug in einer älteren Version von Contentify, inzwischen sollte das gefixt sein.
