### ISSUE TITLE
Brauche Hilfe - Ansicht/Boxen der HP anpassen

### ISSUE THREAD

**Issue by RaceTubeGermany** [Contentify/Contentify#389]
Hallo liebe Community,

ich möchte gerne auf meiner Homepage einige Sachen anpassen. Leider bekomme ich es selber einfach nicht hin. Oh man, wie oft ich schon das Backup wieder einspielen musste. :)

<img width="920" alt="2018-06-22 12_19_34-" src="https://user-images.githubusercontent.com/40469647/41772386-be9b6874-7618-11e8-9002-d1ce29ba5d4a.png">

Die Felder auf dem Bild (rot markiert) sollen angepasst bzw. erweitert werden.

1. Dort soll Sponsoren stehen. Bestimmt leicht zu ändern. Finde ich aber nicht.
2. Dort soll neuste Matches weg und dafür eine ShoutBox und Last Forum hin (Forum Beiträge)

Vielleicht kann mir ja jemand von Euch helfen oder Tipps geben.

PS: Super CMS !!!

Gruß

Dennis

**Comment by RaceTubeGermany** [comment]
zu 1. konnte ich lösen.

 app / Modules / MorpheusTheme / Resources / Views / layout.blade.php

                        {{ trans('Sponsoren') }}     <----wurde hier angepasst
                        <a href="{{ url('partners') }}">{!! HTML::fontIcon('plus') !!}</a>
                    </h3>
                    @widget('Partners::Partners')

**Comment by RaceTubeGermany** [comment]
ShoutBox konnte ich auch einfügen. Allerdings kann ich keinen Text in das Textfeld schreiben.

**Comment by chriskonnertz** [comment]
Hallo,

`{{ trans('Sponsoren') }}`

Wenn du das so machst wird es nicht übersetzt. Allerdings gibt es auch keine Übersetzung von Haus aus. Daher:
a) Einfach statt `{{ trans('Sponsoren') }}` nur `Sponsoren` ohne irgend was
b) Übersetzung einbauen in den Sprachfiles (`app.php` in den verschiedenen Sprachordnern in `resources/lang`) und dann mit `{{ trans('app.sponsors') }}` darauf zugreifen.

> ShoutBox konnte ich auch einfügen. Allerdings kann ich keinen Text in das Textfeld schreiben.

Eingeloggt bist du? JavaScript ist aktiviert?
