### ISSUE TITLE
InvalidArgumentEception and deleting users

### ISSUE THREAD

**Issue by josephzigler** [Contentify/Contentify#39]
Hello,

First at all I would like to say that this project is amazing! I have succesfully installed the Contentify demo on a local virtual machine, everything is working correctly beside when I click on "Modules" in the backend panel I recieve this error:
`InvalidArgumentException in Finder.php line 677: The "/var/www/html/contentify/app/modules" directory does not exist.` here is the fully detailed error: http://pastebin.com/uAyHufNE

This is from the standard demo installation without any adjustements made running on Ubuntu 14.04. I expect this error occurs because certain files link to the directory contentify/app/modules/ while the folder is called contentify/app/Modules/ ?

I also wonder if it's possible to delete certain users instead of just deactivating them (suggestion?), I tried deleting them manually in the database with a query to remove them on ID in the users table but that caused the site to go blank after removing serveral users, I guess because certain users are linked to a team this causes the database to go faulty?

Thank you in advance!

Regards,
Joseph

**Comment by chriskonnertz** [comment]
Hi,

> First at all I would like to say that this project is amazing!

Thanks! :)

> everything is working correctly beside when I click on "Modules" in the backend panel I recieve this error

The demo website is not 100% up-to-date. I believe there is a fix for this bug:

https://github.com/Contentify/Contentify/commit/180dad83d35462444dc03050c2526bc33aac9435

Sounds like that is what you ahve already detected. Can you apply the fix from the commit and leave a note here if it worked?

> I also wonder if it's possible to delete certain users instead of just deactivating them (suggestion?)

That's not possible atm. Why? Well you have experienced why. ;) There are a lot of dependencies and SQL queries might fail if a user is missing but models / content created by this user still exists. 

Honestly, deleting is a general problem. It's on the to-do-list for Contentify 2 but currently I do not expect that deleting users will make it the code.

**Comment by josephzigler** [comment]
> Sounds like that is what you have already detected. Can you apply the fix from the commit and leave a note here if it worked?

Applied the commit and that did fix the issue, Thank you!

> That's not possible atm. Why? Well you have experienced why. ;) There are a lot of dependencies and SQL queries might fail if a user is missing but models / content created by this user still exists.

>Honestly, deleting is a general problem. It's on the to-do-list for Contentify 2 but currently I do not expect that deleting users will make it the code.

No problem, that's understandable.


I did encounter a different 'bug', when a user has an avatar on he's profile and a thread or post on the forum the avatar is too huge as shown here: http://imgur.com/zBHyVF1 I think this is an easy fix but my css/php knowledge is basic to none, which i'm aiming to improve :) 
Haven't been able to check out the up-to-date version to see if it's there the case aswell.
