### ISSUE TITLE
Eigene Teams / Team Invite

### ISSUE THREAD

**Issue by RaceTubeGermany** [Contentify/Contentify#390]
Hallo zusammen, habe schon die ganze Seite nach einer Info abgesucht aber nichts gefunden.

Die Option auf der Seite, das jeder User sein Team erstellen kann ist echt top.
Nur das Problem ist, ich finde nicht, wo ein User einen weiteren User in das Team einladen/hinzufügen kann. 

Beitreten scheint auch nicht zu gehen. Gibt nigends die Option.

**Comment by chriskonnertz** [comment]
Hallo,

> Beitreten scheint auch nicht zu gehen. Gibt nigends die Option.

Doch die gibt es an sich, vielleicht wird sie dir nur nicht angezeigt.
1. Du musst dich auf der Seite eines Teams befinden - klar
2. Das Team darf  nicht auf unsichtbar gestellt sein (was der Fall ist wenn es gelöscht wurde)
3. Du musst eingeloggt sein
4. Du darfst noch nicht in diesem Team sein

Dann sollte ein Button erscheinen, mit dem man joinen kann. Eventuell ist es sinnvoll wenn du dir zum Testen einen zweiten Account anlegst, der nicht in dem Team ist, da ich mal vermute, das Team wurde von dir selber erstellt - also bist du schon drin.

**Comment by RaceTubeGermany** [comment]
Hall,

vielen Dank für die schnelle Antwort. Scheint nicht zu klappen oder ich mache etwas falsch.

1. Team Bereich den ich meine
<img width="99" alt="2018-06-24 09_58_13-rtg esports - racetube germany" src="https://user-images.githubusercontent.com/40469647/41817138-62db4e4a-7795-11e8-8615-f69d6433ec11.png">
2. Neues Team erstellen
<img width="159" alt="2018-06-24 09_58_24-teams - racetube germany" src="https://user-images.githubusercontent.com/40469647/41817140-6d6ca016-7795-11e8-8eba-a6169645f748.png">
3. Erstellen
<img width="274" alt="2018-06-24 09_58_39-teams - racetube germany" src="https://user-images.githubusercontent.com/40469647/41817142-75ae1ad4-7795-11e8-8ed4-835be8ec553a.png">
4. So sieht es erstellt aus
<img width="452" alt="2018-06-24 09_58_50-test - racetube germany" src="https://user-images.githubusercontent.com/40469647/41817148-7fa7d232-7795-11e8-85f3-ea305201f14f.png">

es gibt keine Möglichkeit es öffentlich zu stellen.
Wo soll die Möglichkeit für andere angemeldete User zu joinen?
Im Profil ist nichts zu erkennen. Beim erstellen eines Teams auch nicht und unter Teams wird es nicht mit aufgelistet.

Danke Dir

**Comment by RaceTubeGermany** [comment]
Neue Info, wenn ich ein Team erstelle, kann ich es mit einem anderen User über die suche finden.
Dazu muss ich den exakten namen eingeben.

Das ist für die User aber nicht so komfortabel. 
Es müsste eine Box (Widget) oder Seite geben, wo diese angezeigt werden. 

Gibt es da sowas oder kann das jemand bauen?

**Comment by RaceTubeGermany** [comment]
Team Beitritt hat nun geklappt. mache für weitere Fragen ein neuse Thema auf. Passt dann besser.

Danke Dir !!!
