### ISSUE TITLE
Contentify Update 2.2 -> 2.3

### ISSUE THREAD

**Issue by RaceTubeGermany** [Contentify/Contentify#391]
Hallo Community,

ich habe das Update 2.3 ausgeführt und es lief auch sauber durch.
Wie ich es überblicken kann, wurden auch Bugs behoben.

Allerdings wird bei mir noch die Version 2.2 im Admin Pannel angezeigt.

Ich wollte nun das Update auf 2.4 durchführen. Das ist nicht möglich und ich bekomme die Meldung, das ich nur von 2.3 auf 2.4 updaten kann.

Jemand auch dieses Problem oder einen Tipp?

Gruß

Dennis

**Comment by chriskonnertz** [comment]
Hallo

> Allerdings wird bei mir noch die Version 2.2 im Admin Pannel angezeigt.

Okay, vermutlich hast du aber dann 2.3 und es wurde nur in der DB nicht korrekt aktualisiert. Nachschauen kannst du die Version in der Datei `config/app.php` ( https://github.com/Contentify/Contentify/blob/2.4/config/app.php#L52 ).

> Ich wollte nun das Update auf 2.4 durchführen. Das ist nicht möglich und ich bekomme die Meldung, das ich nur von 2.3 auf 2.4 updaten kann.

Schau mal in der Datenbank ob die Version auf 2.2 steht, obwohl du 2.3 hast. Dazu benötigst du ein Tool wie phpMyAdmin, damit gehst du zur Tabelle `config` und suchst nach der Zeile mit `app.version`, wenn ich mich nicht irre. Die Versionsnummer kannst du dann ändern wenn sie wirklich falsch ist. (Möglicherweise musst du noch den Cache leeren, bin mir gerade nicht sicher).
