### ISSUE TITLE
User Teams in einer Box (Widget anzeigen

### ISSUE THREAD

**Issue by RaceTubeGermany** [Contentify/Contentify#392]
Zuerst, danke an den Supper Support von Contentify. Mega gut.

Nun zu meiner nächsten Frage an Euch.

Ich benötige eine Box (Widget) und eine Seite, wo alle von den Usern angelegten Teams angezeigt werden.
Leider bin ich trotz probieren nicht in der Lage mir das zu bauen. Da frage ich lieber mal die Pros von Euch.

Wer kann mir so eine Box (Widget erstellen, damit die ganzen User auch Ihre Teams finden können.

Geht zwar derzeit über die Suche, ist aber nicht so toll.

Danke an Euch

**Comment by chriskonnertz** [comment]
Hallo,

> Ich benötige eine Box (Widget) (...), wo alle von den Usern angelegten Teams angezeigt werden.

wirklich **alle** Teams? Das können ja theoretisch hunderte sein... Stell dir mal vor du gehst auf die ESL-Website und alle von Spielern erstellte Teams werden angezeigt. Da hätte der Browser einiges zu tun ;)

**Comment by RaceTubeGermany** [comment]
Hallo,

stimmt. Hatte ich gar nicht auf dem Schirm. Guter Einwand.
Damm würde eine Seite wohl mehr sin machen und über das Menü einbinden.

Hast Du eine Idee zu der Seite.

Eine weitere Idee ist das Team im Profil anzeigen zu lassen. (parallel zu einer Seite)

Aufwendig? ich bin nur in der Lage paar Sachen anzupassen...

Gruß und Danke

Dennis

**Comment by chriskonnertz** [comment]
> Ich benötige (...) eine Seite, wo alle von den Usern angelegten Teams angezeigt werden.

Hab das mal eingebaut, die Seite wird allerdings nirgendwo verlinkt d. h. du musst die selber irgendwo verlinken.
https://github.com/Contentify/Contentify/commit/28978e4d2614ad324365c6869f9b494d9f15984a

Ich hab das jetzt nicht groß getestet, aber im Schnelltest funktionierte es.

PS Hab noch was vergessen: https://github.com/Contentify/Contentify/commit/39a13d6c76011752c3f2b73186ec0d8b5e33224a

**Comment by RaceTubeGermany** [comment]
Hab das mal eingebaut, die Seite wird allerdings nirgendwo verlinkt d. h. du musst die selber irgendwo verlinken.
28978e4

Habe das nun gemacht. Klappt auch. Nur besteht nun das problem, das unten rechts meine Teams nicht mehr geht und umbenannt werden muss.
sollte nun zur seite gehen

**Comment by RaceTubeGermany** [comment]
Weiter ist mir aufgefallen, das immer nur ein Team angezeigt wird und man muss blättern.
Wie macht man denn mehr auf eine seite. so wie bei den usern in der Ansicht.

**Comment by chriskonnertz** [comment]
Hatten sich hier alle Probleme gelöst?
