### ISSUE TITLE
Create servers games

### ISSUE THREAD

**Issue by davidllauce** [Contentify/Contentify#396]
Hello, in the server part, ask for the IP of the server. This means that the contentify can create the lobby automatically if it were for Dota 2. I could explain how the tournaments, the cups and the server works in contentify. Thank you very much.

**Comment by chriskonnertz** [comment]
Hello,

thank you for creating this issue. I am not sure what you mean when you talk about "the server part", because in the server moduel there already is support for the IP: 

![edit_server](https://user-images.githubusercontent.com/4319323/42344309-36d94774-809c-11e8-8eec-82dd60fc5283.jpg)

**Comment by davidllauce** [comment]
Thank you very much for your reply. I want to know if Contentify can create the game lobby automatically by registering the server IP.
Or maybe you know an API that can do this job

**Comment by Jpofin** [comment]
Mainly it's server first and you just want to collect data and show it.
I don't see the point in creating a game lobby via a webpanel.

**Comment by chriskonnertz** [comment]
> I want to know if Contentify can create the game lobby automatically by registering the server IP.

No, this is not implemented.

> Or maybe you know an API that can do this job

Unfortunately I do not know such an API. :(

**Comment by chriskonnertz** [comment]
> Mainly it's server first and you just want to collect data and show it.
I don't see the point in creating a game lobby via a webpanel.

I partially agree. Adding automation makes sense to me. However, I'd go further than just adding lobby creation. But there are not enough resources at Contentify to realise this.

**Comment by davidllauce** [comment]
Thank you very much for your reply

**Comment by BlueStormNetwork** [comment]
Is it possible to add other games in the list? or use a URL instead of IP address for browser based games? thank you in advance for your answer

**Comment by chriskonnertz** [comment]
Yeah it's possible to add new games.
