### ISSUE TITLE
How to remove the grayness in Phobos Theme?

### ISSUE THREAD

**Issue by iktray** [Contentify/Contentify#397]
![image](https://user-images.githubusercontent.com/30093468/42363617-49cc6652-80c6-11e8-85f0-b776df23323a.png)

**Comment by MrFoxyOfficial** [comment]
You mean the navigation bar?

**Comment by chriskonnertz** [comment]
Hello,

in v2.4:

1. Open `app/Modules/PhobosTheme/Resources/Assets/less/frontend.less` with a text editor
2. Go to line 721 and remove this code: `filter: grayscale(1) brightness(0.4); -webkit-filter: grayscale(1) brightness(0.4); `
3. Go to the website, log in, got to the backend, go to the config page, then click on the "Compile LESS" button.

> NOTE: These changes might be overwritten by updates! There will be a way to modify LESS/CSS code in the backend at some point in the future but for now you might have to apply the change again when you update to v2.5.

@FoxyWhite2541 

> You mean the navigation bar?

I guess ikTray is talking about the big slider image.
