### ISSUE TITLE
[Bug] Errors everywhere. Nothing works at all.

### ISSUE THREAD

**Issue by ApertureDevelopment** [Contentify/Contentify#398]
So I installed this for a friend, and already at the installation I noticed that much stuff doesn't work.

The current release version has errors with the apache_get_modules function, which is disabled due to security reasons, the script wants access to the php main directory, which a php script NEVER should have access to. And after I gave him all this, I just get that:

![screenshot 480](https://user-images.githubusercontent.com/16450982/42374657-1e151588-8119-11e8-8c99-efb934849791.png)

What the hell.

**Comment by ApertureDevelopment** [comment]
Ok I found the mistake. Ever heard of case sensitive?

Apperently not

**Comment by chriskonnertz** [comment]
Hello

> Ever heard of case sensitive?

Contentify is an open source software without any funding or commercial background (currently at least). Creating and maintaining an entire CMS usually keeps whole companies busy over years, costing up to millions of dollars / euros. Lacking these means you have to try to find smart cutoffs. 

This is why Contentify has zero tests (automatic tests via PHPUnit etc.) and this is why there is no huge testing phase before a new version of Contentify is released. Sometimes this causes errors. You faced one of these, because Contentify is developed on Windows, not on Linux. Windows is case insensitive regarding file names.

**Comment by chriskonnertz** [comment]
Closing this one. Please stick to constructional criticism if you want to get help.

**Comment by ApertureDevelopment** [comment]
The fact that you say "Developt on Windows" shows me that you have no idea. Case Sensivity is something that everyone should follow, and I am sorry that you don't see that.

Here your critic:

First: apache_get_modules is a security issue and by default on most webservers disabled
Second: Your installer ignores the entry at the MySQL data and tries as root anyways, you have to reload the page and try again for it to work, I would guess thats because you first try to connect before reading and saving the mysql data.
Third: Case sensivity is something that exists since years, and it became a standard under developers to always keep case sensivity in mind.

and last but not least:
If it was developt on windows and does not work on Linux by nature, you should write that in the requirements.

**Comment by ApertureDevelopment** [comment]
And also thank you for being in the EU and not following the laws.

Read it up kiddo: DSGVO

**Comment by ApertureDevelopment** [comment]
Oh also btw WoltLab and WordPress are also Open Source and they have way more features.

**Comment by chriskonnertz** [comment]
> The fact that you say "Developt on Windows" shows me that you have no idea

Another afront, and again you do not care about the reasons. Ofcourse every developer who creates software that typically runs on a Linux OS has to know about the important differences between the target OS and the development OS. Thus however does not guarantee no typos etc are made. Take a look at your own quote, you quoted me wrong ("Develo**pt**"). Nothing else happened @ Contentify. A stupid mistake, yes. But if you do not take the circumstances into account you should be very careful with attacking others. And again, you blame others for not creating a perfect software *for free*. It's great when you report bugs and give useful feedback but please leave the rest out of here.

**Comment by ApertureDevelopment** [comment]
But whatever, I will fork it, exchange it and do a pull request. Is that enough Constructive critic for you?

**Comment by ApertureDevelopment** [comment]
Good. Whatever. I don't care. I am not a user of this, a friend asked me to setup it for him and I said yes and since 24 hours I just have problems. I fixed it now, you know about the Case Sensivity error, I don't care about anything else.

**Comment by chriskonnertz** [comment]
Thank you, for reporting the issues and giving explanations why they are issues. 

Believe it or not, I understand why you are upset. I work as a professional software developer and I’d be very upset if a software that I have bought does not work. But that is the point, this is not the case here. The only “payment” is... if some say “thank you”, I guess. Getting negative feedback is okay but it is frustrating as well if it feels like an attack against the persons that spend their free time on creating something without making any money with it.

**Comment by chriskonnertz** [comment]
Sorry for being a bit harsh. It was just that the tone of your second and third post was quite unfriendly.

Honestly, Contentify cannot reach the same high quality level as for example WordPress. WP has a huge community and lots of contributors plus a strong commercial background. None of these is true for Contentify. Therefore, it has no ads ad all, nowhere at all (except of some recommendations which do not generate any money). It does not spy on you or restrict you. 

DSVGO / GDPR...  If this really is something that interests you, let me ensure you, the only thing you have to worry about is the use of Google Analytics on the contentify.org website. That's the only "evil" third party software that is in use. And on our side, we do collect very (extremely?) few client data and we do very rarely / almost never perform analysises of the collected data. And ofcourse we do not sell / share any user data (not including Google Analytics).

**Comment by NamerEsports** [comment]
@chriskonnertz Do not listen to him this CMS is great and thanks for creating!

**Comment by chriskonnertz** [comment]
Thank you!

**Comment by chriskonnertz** [comment]
> the only thing you have to worry about is the use of Google Analytics on the contentify.org website. That's the only "evil" third party software that is in use

**Update**: Google Analytics is no longer in use on the contentify.org website.

**Comment by chriskonnertz** [comment]
**Update**: Contentify.org is officially GDPR compliant.
