### ISSUE TITLE
Twitch streams not showing at all

### ISSUE THREAD

**Issue by MrFoxyOfficial** [Contentify/Contentify#399]
Hello. 

Upon checking the streams today, i see that nothing appears. Not even a player, showing them or who they host. 

Is it a bug or error on my side. 

Please find the attached pictures on how it looks like:

![image](https://user-images.githubusercontent.com/1783339/42381803-868e1f88-8132-11e8-8b42-f6646541e952.png)

![image](https://user-images.githubusercontent.com/1783339/42381867-be1ff412-8132-11e8-856e-251126d7a567.png)

**Comment by chriskonnertz** [comment]
Hello,

I got an email from another person describing the same or a very similar problem. I'll take a look at it.

Here is something I wrote to this person:

> You should setup a cron job if you want to let the CMS get the infor,ation about the streams (are they online, how many viewers) automatically every x minutes.
You do not have to do anything with PHP, only set up the cron job in your operation system (Linux): https://github.com/Contentify/Contentify/wiki/Installation#create-cron-job

But I believe that is not the (whole) solution.

**Comment by PapyOak** [comment]
The solution with crontab works well but you need to launch at least one stream before have a stream visualization.

**Comment by Shiffed** [comment]
I have managed to finally get the Cron Job working for mine but when clicking on a Stream from the sidebar and it taking me to the page for it, the embed does not work.
Using Chrome's 'Inspect' I have found this error

`Refused to display 'https://www.twitch.tv/MyTwitchChannel/embed' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

I've had a browse around the land of Google and looked at many results and still couldn't find a solution to work for me :(

**Comment by iktray** [comment]
@chriskonnertz What's the best way to contact you?

**Comment by chriskonnertz** [comment]
@Shiffed I‘ll take a look later today.

@ikTray Regarding Contentify topics? Via email. contact@contentify.org

**Comment by chriskonnertz** [comment]
Fixed: https://github.com/Contentify/Contentify/commit/fcebeedd7b21b0dee5a99fc012dce10bf58db0c6

The embed code just needed an update.

Thank you all for reporting this issue. :)

**Comment by PapyOak** [comment]
Works, Thank you for your support.

2018-07-07 13:44 GMT+02:00 Chris Konnertz <notifications@github.com>:
