### ISSUE TITLE
Installer: MySQL connection text fields

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#4]
> "Just as a suggestion, instead of having people go into the config files to fill out the sql info, you could have it within the install process as text fields. which then leads to some other things I am encountering."

( https://github.com/Contentify/Contentify/issues/2 )

**Comment by creativewild** [comment]
Hi again, i haven't been active this last few days, I am updating my branch from the master and rework the install process to create for now a config file that can be loaded into the /app/config/database.php. 

soon i get that added in I will deploy it into a dev vps i have so you can have a look and check if you are happy with it. - this is a temp measure and i agree that probably is not very laravelish.

**Comment by chriskonnertz** [comment]
Hi

> i haven't been active this last few days
No problem. I haven't been that active as well. 

>  I am updating my branch from the master and rework the install process to create for now a config file that can be loaded into the /app/config/database.php.
If you do that I'll merge it afterwards.

> soon i get that added in I will deploy it into a dev vps i have so you can have a look and check if you are happy with it. 
Well that would be very convenient.

**Comment by chriskonnertz** [comment]
Feature has been added with https://github.com/Contentify/Contentify/commit/a3411f5cf4f0fbda8da8839a5c5fab2a72d2433b .

(Did not made it in third beta release any more.)

![Installer Screenshot](http://i.imgur.com/xkhTgvI.jpg)
