### ISSUE TITLE
Forum avatar not resizing to a smaller size

### ISSUE THREAD

**Issue by josephzigler** [Contentify/Contentify#40]
Hello,

I encountered a bug, when a user has an avatar on he's profile and made a  thread or post on the forum the avatar is too huge as shown here: http://imgur.com/zBHyVF1 I checked out the latest production release and it's there the case aswell.

I also wonder if it's possible to restart the installation procedure by deleting certain files in the website directory or do too many files get adjusted during the process?

Regards, 
Joseph

**Comment by chriskonnertz** [comment]
Okay that *is* a bug, thanks for reporting it.

> I also wonder if it's possible to restart the installation procedure by deleting certain files in the website directory

_Create _an (empty or not, it does not matter) file named `storage/app/.install` - then you can repeat the installation.

**Comment by chriskonnertz** [comment]
Bugfix: https://github.com/Contentify/Contentify/commit/0a1e5a56668aa9fb135229f7c56137f621eed3a9

**Comment by josephzigler** [comment]
Thank you!
