### ISSUE TITLE
Update Hilfe benötigt

### ISSUE THREAD

**Issue by RaceTubeGermany** [Contentify/Contentify#400]
Hallo Chris,

ich benötige unbedingt Hilfe bei dem Einspielen des Updates. Ich bekomme es einfach nicht hin.
Hast Du evtl ein Tag mal Zeit mir das Update per TeamViewer einzuspielen?
Aktuell läuft Contentify noch auf der 2.2.

Habe aber bei einigen Aktionen noch Fehler drin und so macht es keinen Spaß.

Danke für Dein Feedback

**Comment by chriskonnertz** [comment]
Hallo,

besteht alternativ die Möglichkeit, dass du mir die Dateien zippst und die
DB dumpst und per Email zuschickst? Kritische Daten würdest vorher entfernen,
also insbesondere User-Passwörter (Spalte in der "users"-Tabelle leeren)
und im Grunde den ganzen "public/uploads"-Ordner löschen. Ggf. außerdem
API-Keys rausnehmen (siehe "config"-Tabelle).

Dann könnte ich das in aller Ruhe auf meinem eigenen System updaten und
Fehler mit meinen Debugging-Tools fixen.

**Comment by RaceTubeGermany** [comment]
Hi Chris,
habe ich Dir per Mail gesendet.
Danke Dir !!!

**Comment by chriskonnertz** [comment]
An welche Mail-Adresse? (Es gibt mehrere die du verwendet haben könntest.)
Bei mir ist noch nichts angekommen. Falls es nicht die hier war bitte nochmal an die schicken: contentifycms@gmail.com

**Comment by RaceTubeGermany** [comment]
Hatte ich an die aus Deinem Profil gesendet. mail@chriskonnertz.de
Habe ich Dir eben nochmal an contentifycms@gmail.com gesendet.

Vielen Dank an Dich.

Gruß

**Comment by RaceTubeGermany** [comment]
Hat alle geklappt mit de DB?
Konntest schon was erreichen/finden?

Gruß

**Comment by chriskonnertz** [comment]
Hoffen wir es. :)
