### ISSUE TITLE
No Images for News setable

### ISSUE THREAD

**Issue by KoEnix** [Contentify/Contentify#401]
Hi, first, I want to thank you for this awesome Clan-CMS.
I set my own little Clan-Site up a few days ago, and ran into a problem, which dont seem to be a problem on the demo-site.

When writing a news-article, I can set images and pictures in the text field, but the image of the article itself isnt showing up on the main landing page. Can you maybe guess why and help me, where I have to set the main preview/header image of the article, so it is displayed on the start page?

Thanks a lot in advance.

**Comment by chriskonnertz** [comment]
Hello,

just a quick fess: permissions. Maybe the script cannot create the image file in the uploads directory. Did you check this?

**Comment by KoEnix** [comment]
Well, I think its best for a quick support, escpecially for me to describe my problem, to write in german.

Ich habe es eben noch einmal durchgeschaut, "public" und alle Unterordner gehören www-data:www-data, somit sollten die also eigentlich schreiben dürfen.
Ich habe halt in der News-Gestaltungsseite nur die Option, Bilder, entweder aus der Galerie, oder direkt aus einer Datei hochgeladen, in den Artikel-Text zu packen. Sollten diese dann automatisch auf der Startseite erscheinen?
Wenn ich die Demo samt dem Demo-Konto nutze und mir da den Aufbau anschaue, verstehe ich nicht ganz, wie du die Bilder da auf die Startseite bekommen hast ^^

**Comment by KoEnix** [comment]
Habe jetzt eine weitere News angelegt, mit einem Bild im ersten und zweiten Editor Feld, da gab es auch sofort Fehler auf der Seite. Wenn es recht ist, hänge ich mal das laravel.log mit an (Es sind nur die Fehler, die nach der News aufgetreten sind)

[laravel.log](https://github.com/Contentify/Contentify/files/2200476/laravel.log)

**Comment by chriskonnertz** [comment]
>  failed to open stream: No such file or director

Sieht nach wie vor sehr nach ein Problem mit Berechtigungen aus

Bitte prüfen ob für das Verzeichnis `/var/www/html/storage/framework/cache/`Schreibberechtigungen gesetzt sind. Immer daran denken, die muss man rekursiv setzen damit sie auch für Unterordner gelten!
