### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by Shootify** [Contentify/Contentify#403]
Can someone guide me how to install Contentify in a VPS running ubuntu without messing up my current websites? thanks

**Comment by Shiffed** [comment]
If you follow the documentation, you can download all the files, upload them to the desired location, create a mysql database and go to yourdirectory/install.php

**Comment by Shootify** [comment]
ok, i got this sort it up, i uploaded the contentify into my server, but when i go to the browser and point 
http://websitex/public/install.php  a precheck list came up, all are green check mark exept for 

Vendor libraries installed: | No - please run "composer install"!

what should i do?
thanks

**Comment by Shiffed** [comment]
I'm on my mobile and not experienced with github so I'm copy/pasting this from another issue that looks the same

Quote:
it seems you do not have the vendor libraries in <contentify-path>/vendor installed.

a) Install them via console: php composer.phar install
b) Download the production package and use it or copy the vendor directory https://github.com/Contentify/Contentify/releases/download/v2.3/contentify_2_3.zip

**Comment by Shootify** [comment]
dont know... since im using ubuntu and php7 it looks that what i need to do is get on my ubuntu server and ssh with putty and run this command
Download the script: wget http://contentify.org/share/install.sh
Run the script: sudo bash install.sh 

anyone ?

**Comment by Shiffed** [comment]
You could do that but it would plonk all the files into your /var/www/ directory, but I'm not a pro with Linux servers and I guess you can just relocate the folders after.

**Comment by Shootify** [comment]
thats what i want to be sure about, i have websites running on my server, so i dont want to mess that up...so i dont know if running that command on my ubuntu server, it will get wiped out and delete my current websites! hope someone can clarify this. thanks for responding

**Comment by chriskonnertz** [comment]
Hello,

> Download the script: wget http://contentify.org/share/install.sh

Nah, don't do this. This is only meant for fresh droplets of DigitalOcean.

**Comment by chriskonnertz** [comment]
All you need to do is to get that `vendor` folder.
Again:

> a) Install them via console: php composer.phar install
> b) Download the production package and use it or copy the vendor directory

**Comment by Shootify** [comment]
chriz can you take at look, i got an error, i posted on gitter. thanks

**Comment by acamilleri** [comment]
@chriskonnertz PR #407 fix this error:

`In ConfigServiceProvider.php line 24: syntax error, unexpected '!' in /home/users/contentify/www/storage/app/data/base.ini on line 7`

**Comment by chriskonnertz** [comment]
Oh wow yes, haha I did not know this is a thing in .ini files. Thanks!
