### ISSUE TITLE
Forum deleting bug

### ISSUE THREAD

**Issue by NamerEsports** [Contentify/Contentify#405]
Hi. Nice CMS! I love it becouse its based on laravel. We have a strange bug, if admin tries to delete forum thread getting error:

`No query results for model [App\Modules\Forums\ForumPost] 6`

Thanks and we waiting for fix!

**Comment by chriskonnertz** [comment]
Hello,

do you use version 2.4?

**Comment by NamerEsports** [comment]
Thanks for answer @chriskonnertz , yeah im using 2.4

**Comment by chriskonnertz** [comment]
Thank you for reporting this bug, here is a fix (= delete line 176):  https://github.com/Contentify/Contentify/commit/7e825fe61e5ca947833968770223b164e9682b97#diff-a1733d74a209110d3c674d07888b90faL176
