### ISSUE TITLE
Contentify 2.4 Fehler in der Installation im letzten Schritt

### ISSUE THREAD

**Issue by ghost** [Contentify/Contentify#409]
Hey Leute,

ich wollte der Contentify-Installation gerade noch einen Versuch geben, nachdem es die letzten Tage partout nicht geklappt hat. Nachdem ich nun die Installation aufgerufen habe und bei Step 4 die MySQL-Zugangsdaten alle korrekt eingegeben habe, bekomme ich zwei Fehlermeldungen. Aufgrund der Fehlermeldung sieht es für mich so aus, als ob irgendwas an den Daten nicht korrekt wäre. Sie stimmen jedoch. 👎 

Vielleicht ist das Problem ja bekannt oder jemand hätte einen Ansatz, wie ich an die Lösung rangehen kann.
Anbei zwei Bilder der Fehlermeldungen:
![unbenannt](https://user-images.githubusercontent.com/42274428/43963237-0b46a194-9cba-11e8-84a0-3f7badf1dc9c.PNG)
![unbenannt2](https://user-images.githubusercontent.com/42274428/43963238-0b5ff9fa-9cba-11e8-862c-74b94ee9ef53.PNG)

**Comment by chriskonnertz** [comment]
Hallo,

tut mir leid, dass das mit der Installation nicht so richtig klappt.

Grundsätzlich: Bitte überprüf mal die Datei `storage/app/database.ini`. Dort hin werden die Datenbank-Zugangsdaten gespeichert. Ist dort alles korrekt eingetragen? 
Falls es in der Datei Zeichenprobleme gibt, hier ist das Original: https://github.com/Contentify/Contentify/blob/2.4/storage/app/database.ini

**Comment by ghost** [comment]
Ich habe sogar schon versucht hier die Daten manuell von Hand einzutragen. Kurzzeitig habe ich die oben genannten Fehlermeldungen weggebracht, indem ich manuell Änderungen in der database.ini, sowie der database.php vorgenommen habe. Dafür hatte ich einen anderen Bugreport, der weitaus länger war. Nachdem es dann partout nicht funktioniert hat, habe ich die database.php wieder auf Standard zurückgesetzt, was mir wieder die oben genannten Fehler brachte. Zu jeder Zeit stimmen soweit die Zugangsdaten zur Datenbank.

Ich bin so langsam aber sicher mit meinem Latein am Ende. Und nachdem die einfachen CMS-System wie webspell und Clansphere nicht mehr weitergeführt werden und Webspell Nor bei mir noch kritischere Fehler im Live-Betrieb hervorrufen, sehe ich eigentlich Contentify am Idealsten für meine Bedürfnisse. Auch wenn hier weitaus mehr Arbeit in der Konfiguration und Gestaltung liegt. Daher möchte ich soweit noch nicht aufgeben.

Woran könnte es liegen, außer, dass die Datenbankdaten nicht korrekt wären?

**Comment by ghost** [comment]
Halt mich für bescheuert, mach ich inzwischen selbst.
Neue Datenbank angelegt mit neuem Benutzer und Passwort.
Beim Pfad der Datenbank zudem nicht den Port angegeben. Bekomme nun eine neue Fehlermeldung.
Anbei ein Screenshot.
![unbenannt3](https://user-images.githubusercontent.com/42274428/43995600-357d30de-9db1-11e8-88a4-16fd547206a4.PNG)

**Comment by ghost** [comment]
So, nach etwas Brainfuck habe ich nun alles gelöst bekommen. Vieles wurde zum Glück im Github hier ja schon geklärt... Allerdings sind die drei Dateien Pagecat, Partnercat und und Advertcat immer noch falsch benannt in der Zip.
Diese heißen immer noch in der jeweiligen Struktur "PageCat", "PartnerCat" und "AdvertCat"...
In meinem Fall habe ich diese jetzt einfach über FTP umbenannt, damits funktioniert. Mag sein, dass das auf einem Windows-Server kein Problem ist. In jeglichen Linux-Distris, die case-sensitive arbeiten ist dies jedoch ein Problem und eine Hürde für neue User von Contentify. Hier sollte man nachbessern und die Dateien richtig benannt packen, bzw. diese mit den jeweiligen Großbuchstaben aufrufen.

Ich danke an dieser Stelle für deine Hilfe @chriskonnertz , auch wenn ich meine Probleme widerwillig selbst gelöst habe. Ging mir nicht schnell genug. xD

Vielen Dank und von mir gibts einen 👍 für den super Support den ihr den Usern hier liefert. Vor allem auch noch multilingual. :-)

**Comment by ghost** [comment]
Morgen werd ich mich mal noch ransetzen müssen und eine Menge Dateien bearbeiten.
Beim Anlegen eines Teams habe ich festgestellt, dass auch hier noch weitere Dateien falsche Groß-/Kleinschreibung besitzen. Zumindest falsch aufgerufen werden... Die gehe ich morgen noch alle in den Modules durch und werde sie umbenennen. Ich hoffe, dass das nichts ausmacht.

Zudem habe ich noch ein kleines Problem festgestellt...
Habe die Installation soweit durch, den Cronjob angelegt wie im Tutorial empfholen und soweit noch nichts angelegt auf der Homepage... Allerdings ist sie arg langsam beim Laden der Seiten... Das habe ich mit anderen CMS-Systemen soweit noch nicht festgestellt. Ist da vielleicht was bekannt? Habe ich vllt. irgend etwas übersehen? Über eine kleine Hilfestellung hierzu wäre ich noch ganz froh. :-)

Edit(h) sagt: Zudem habe ich festgestellt, dass im Backend unter Diagnose bei "Jobs.last_execution" folgendes steht: "Niemals. Keinen Cron-Job erstellt?" obwohl ich wie gesagt den Job erstellt habe. Hier meine Cron-Aufgaben:
![unbenannt4](https://user-images.githubusercontent.com/42274428/43996344-3d8e0a4a-9dc1-11e8-9245-45fab68364d3.PNG)

Edit(h) 2 sagt: Fehler gefunden... Nicht einfach übernehmen, sondern natürlich den Pfad anpassen... Er führt den Cronjob trotzdem nicht aus. Wenn ich als root "artisan jobs" aufrufe bekomme ich ein Permission denied... Ich hab keine Lust mehr. 👎

**Comment by kamohy** [comment]
Wie habt ihr den open_basedir fehler umgangen ? Ö.ö

**Comment by ghost** [comment]
Ähm, gute Frage... ich kämpfe mich seit der Installation von Fehler zu Fehler und stoße irgendwie bei jedem Modul was ich mir ansehe auf einen neuen kritischen Fehler. 

Ich habe so langsam das Gefühl, dass man Contentify/Laravel nicht in einen Server integriert, sondern den Server darum herum aufbaut und konfiguriert. Würde es nicht schon von Installation an so geil aussehen, wäre dieses CMS schon lange wieder in die Tonne gekloppt. 

Ich schau mal heute Abend oder morgen, wie ich auf die Lösung gekommen bin, verspreche aber nicht, ob ich das auch wieder finde.

**Comment by kamohy** [comment]
Ich weiss was du meinst.
open_basedir ist hardcodet integriert 
dann kommen aber noch pagecat ect. (fehler)
ich hab es mal versuchg zu fixen habs irgendwann aber mal gelassen...
Das ding ist, das system hat mega potential...
aber ich kann nicht dinge aktivieren die eigentlich aus sicherheitsgründen schon seit php 5.6 abgeschaltet wurden
open_basedir ist ein downloadbereich soweit ich weiss kann man also aucb anders lösen...
wie gesagt würde mich interessieren wie du das hinbekommen hast xD

**Comment by ghost** [comment]
Und dazu musste mich wie gesagt sobald ich Zeit habe nachsehen lassen. Kann’s nun nicht aus dem Kopf sagen. ;-)

**Comment by chriskonnertz** [comment]
> Ich habe so langsam das Gefühl, dass man Contentify/Laravel nicht in einen Server integriert, sondern den Server darum herum aufbaut und konfiguriert.

Da ist in gewisser Weise durchaus etwas dran. 

Exkursion: Contentify ist was seine Ursprünge angeht sehr alt (rund 10 Jahre), weil es ab circa 2008 einen Vorgänger hatte. Der wurde in der letzten produktionsreifen Ausbaustufe eigentlich nur noch für größere Websites eingesetzt. ESCENE, eFever, angedacht war auch die Website von Team Thermaltake ( https://www.ttesports.com/teamList.aspx ) damit umzusetzen. Keiner von denen hatte/hätte 0815-Webspace eingesetzt. Die hatten/hätten alle irgendwo ihre eigenen Server und Admins gehabt.

Contentify als Nachfolger hat erst mal überhaupt eine richtige Installationsroutine bekommen und viel um die Installation zu verbessern, aber es ist trotzdem eine anspruchsvolle Webapplikation, kein WebSPELL oder so. Aber ich kann dir versichern, wenn du denkst, Contentify wäre wirklich anspruchsvoll - nö. Keineswegs. Es gibt z. B. keine Suche (Elasticsearch/Solr) die ihren eigenen Webserver benötigte. Und hey es läuft ganz normal mit Apache + MySQL. Kein zusätzlicher Cache nötig (auch wenn das unterstützt wird). Elasticsearch fordert übrigens 16 GB RAM als Minimum. 

Zum Teil werden die hohen Anforderungen einfach durch Laravel erzwungen, daran kann man dann nichts ändern. Einige Dinge kann man ganz klar auch noch verbessern.

**Comment by chriskonnertz** [comment]
> Allerdings sind die drei Dateien Pagecat, Partnercat und und Advertcat immer noch falsch benannt in der Zip.
Diese heißen immer noch in der jeweiligen Struktur "PageCat", "PartnerCat" und "AdvertCat"...

Was eigentlich **richtig** ist. Aber wenn es nun bei dir klappt dann lass dich nicht durch mich verwirren.

**Comment by chriskonnertz** [comment]
> Mag sein, dass das auf einem Windows-Server kein Problem ist. In jeglichen Linux-Distris, die case-sensitive arbeiten ist dies jedoch ein Problem und eine Hürde für neue User von Contentify. Hier sollte man nachbessern und die Dateien richtig benannt packen, bzw. diese mit den jeweiligen Großbuchstaben aufrufen.

Man sollten den richtigen Code nachschieben, der mit der korrekten Camel-Case-Schreibeweise ("Partner**C**at") klar kommt. Wenn du mir sagen kannst welcher das ist kommt er nach denn ja du hast natürlich recht, das Problem sollte behoben werden.

**Comment by chriskonnertz** [comment]
> Vielen Dank und von mir gibts einen 👍 für den super Support den ihr den Usern hier liefert. Vor allem auch noch multilingual. :-)

Danke, schön zu hören, dass es für dich eine angenehme Erfahrung war. Insgesamt ist der Support aber nicht zufriedenstellend. Bei vielen Gelegenheiten hat es in der Vergangenheit gehapert. Allerdings ist es schwierig das zu ändern.

**Comment by chriskonnertz** [comment]
> Habe die Installation soweit durch, den Cronjob angelegt wie im Tutorial empfholen und soweit noch nichts angelegt auf der Homepage... Allerdings ist sie arg langsam beim Laden der Seiten...

Sollte an sich kein Problem sein. Auf einem schnellen Server ist das CMS normalerweise schnell. Dazu aber einfach mal ein paar Anmerkungen:

- SSD Festplatte sollte heute Standard sein. Wenn dein Webspace keine haben sollte, dann ist ein Grund gefunden
- Ausreichende CPU-Leistung + RAM muss natürlich auch da sein, wenn die Website auf einem völlig überlasteten Server läuft ist klar, dass die langsam ist
- Contentify nutzt für verschiedene Dinge Caching. Ist die Website ganz neu, muss erst mal viel gecacht werden. Das wird dann aber schnell weniger.
- OPCache bei PHP sollte aktiv sein, das kannst du bei der Diagnose nachschauen
- Kein XDebug an, aber zu 99% ist das nicht an

**Comment by chriskonnertz** [comment]
> Er führt den Cronjob trotzdem nicht aus. Wenn ich als root "artisan jobs" aufrufe bekomme ich ein Permission denied... Ich hab keine Lust mehr. 👎

- Der Cron-Job ist nur für bestimmte Dinge (insbesondere (Twitch-)Streams) nötig, notfalls kann auf ihn verzichtet werden
- Du kannst den Cron-Job auch von extern triggern lassen, wenn das hilft. Dazu gibt es kostenlose Services wie (hab es nicht getestet) https://cron-job.org/de/

**Comment by ghost** [comment]
@kamohy , habs gefunden. Hatte einfach die richtigen open_dir Einstellungen gesetzt. Plesk hat bei mir als Auswahl webspaceroot/ und tmp/
Damit hats funktioniert.

@chriskonnertz Wegen der Geschwindigkeit lags glaube ich größtenteils am noch nicht vorhandenen Caching. Inzwischen ist die Seite "normal" schnell. Mein vServer hat auch keine SSDs soweit ich das sehen kann, wobei das meines Erachtens auch gleich ist. Früher gabs auch nur HDDs in den Servern und die Seiten waren schneller als meine nach der Erstellung.
CPU-Leistung und RAM sind soweit sichergestellt. Ich habe zu jeder Zeit laut Server-Hoster mind. 16GB RAM zur Verfügung, sowie 10vCores (auch wenn hier die Geschwindigkeit nicht näher angegeben wird).
OPCache steht auf "0" in der Backend-Diagnose. 0 heißt es  wäre deaktiviert, oder? Ist bei mir jedoch sowohl im Plesk aktiviert, wie auch installiert und auf dem neuesten Stand. Hmmm.
Wie wichtig wirkt sich XDebug aus? Wie wäre dies zu aktivieren?

Bezüglich des Cronjobs hat er anscheinend nachdem ich schlafen gegangen bin damit angefangen den Job regelmäßig auszuführen. Das Stream-Module ist mir auch wichtig, wird Verwendung finden bei mir. :-)

Bezüglich der Dateinamen und der caseSensitivity... Irgendwo muss im Quellcode ja der Aufruf der Dateien stattfinden. Dort einfach nur anpassen? Oder wie gesagt einfach die Dateien richtig benennen. Dann muss man auch nicht darauf achten, ob alles caseSensitiv richtig ist.

So und was nun das Thema mit Server um Contentify/Laravel herum konfigurieren angeht... Ich habe hier auch nicht nur nen Webspace, sondern meinen vServer... Ja, ist nichts dediziertes und ich bin nicht vor Ort anwesend. Dennoch ist es ein eigenständiger Server und ich bin mein eigener Admin. Ich kann mir auch nicht vorstellen, dass berufliche Administratoren begeistert davon sind von Fehlermeldung zu Fehlermeldung zu konfigurieren und zu versuchen das CMS zum Laufen zu bekommen. Ich finde das CMS richtig geil... Es kommt im Standardaussehen schon richtig geil rüber und Anpassungen wären soweit (für meine Bedürfnisse einer GamingCommunity; nichts wirklich persönliches und hervorhebendes) nur für einige kleine Details notwendig.
Anders sieht es hingegen mit der Integration von Menüs, Containern usw. aus. Hier könnte man sich ruhig mal was von Webspell (Nor), Joomla, Wordpress und Co. abschauen. Und zwar, dass man sehr viel übers Backend erledigen kann. Würde nochmals eine Reichweitensteigerung bringen, da auch Nutzer die nicht sehr CSS, HTML und PHP-gewandt sind einfach und effektiv ihr System anpassen könnten.

Gibt es eigentlich weitere, vorgefertigte Module von Usern oder dem Team, die sich (vielleicht sogar mit Anleitung) ins CMS integrieren lassen? Ich würde gern noch einiges ansehen und vielleicht gibts ja noch passende Sachen für meinen Bedarf.

Und doch... Ich für meinen Teil kann den Support durch dich wirklich nur loben. Du bist zwar auch nicht besonders schnell in der Antwort, jedoch konnte ich mich bisher immer darauf verlassen, dass ich eine Hilfestellung bekommen habe. Auch wenn ich für meinen Teil meine Probleme immer schon vorher selbst gelöst hatte. (Was ja auch durchaus zum Lerneffekt und dem Wissen beiträgt und sich dadurch positiv auswirkt).

**Comment by chriskonnertz** [comment]
> OPCache steht auf "0" in der Backend-Diagnose. 0 heißt es wäre deaktiviert, oder?

Ja und das  macht das ganze langsamer. Eigentlich sollte es per default aktiv sein. In deinem Fall solltest du es nachträglich in der `php.ini` aktivieren. Hier mal schnell eine Anleitung aus Google die was zu taugen scheint: https://lastplaceonthe.net/how-to-enable-php-7-opcache-on-ubuntu-16-04/

> Wie wichtig wirkt sich XDebug aus? Wie wäre dies zu aktivieren?

Ne, das **soll** aus sein, an = langsam.

> Bezüglich des Cronjobs hat er anscheinend nachdem ich schlafen gegangen bin damit angefangen den Job regelmäßig auszuführen. 

Gut, dann ist das ja geklärt.

> Bezüglich der Dateinamen und der caseSensitivity... Irgendwo muss im Quellcode ja der Aufruf der Dateien stattfinden. Dort einfach nur anpassen? Oder wie gesagt einfach die Dateien richtig benennen. Dann muss man auch nicht darauf achten, ob alles caseSensitiv richtig ist.

Ja. Naja in v2.5 wird sich das eh ändern, da wird dann immer auch auf Linux getestet vor einem Release, sodass solche Fehler hoffentlich zukünftig vorab auffallen.

**Comment by kamohy** [comment]
hey chris, ich hab das open_basedir ausgetauscht (hardcodet) werde dir heit abend sagen ob es läuft wenn ja geb ich dir den codeschnipsel 
hätte den vorteil, das man nichts mehr am server abändern bzw einstellen müsste

grüße Kamo

**Comment by chriskonnertz** [comment]
> Ja, ist nichts dediziertes und ich bin nicht vor Ort anwesend. Dennoch ist es ein eigenständiger Server und ich bin mein eigener Admin.

Das genügt auch.

> Ich kann mir auch nicht vorstellen, dass berufliche Administratoren begeistert davon sind von Fehlermeldung zu Fehlermeldung zu konfigurieren und zu versuchen das CMS zum Laufen zu bekommen.

Mit Sicherheit nicht, aber das eine ist ja die Frage was grundsätzlich für Anforderungen existieren und das andere was für Fehler. An den Fehlern kann was geändert werden und sollte es selbstverständlich auch.

> Ich finde das CMS richtig geil

👍

> Anders sieht es hingegen mit der Integration von Menüs, Containern usw. aus. Hier könnte man sich ruhig mal was von Webspell (Nor), Joomla, Wordpress und Co. abschauen. Und zwar, dass man sehr viel übers Backend erledigen kann.

Ein paar Dinge sind in diese Richtung geplant.

> Gibt es eigentlich weitere, vorgefertigte Module von Usern oder dem Team, die sich (vielleicht sogar mit Anleitung) ins CMS integrieren lassen?

Es gibt keinen offiziellen Store oder so etwas. Es gibt hier und da was aber das schwirrt halt irgendwo im Internet herum. Hier in den GitHub Issues gibt es auch ein paar Tutorials wie man dieses und jenes macht.

**Comment by chriskonnertz** [comment]
> hey chris, ich hab das open_basedir ausgetauscht (hardcodet) werde dir heit abend sagen ob es läuft wenn ja geb ich dir den codeschnipsel
hätte den vorteil, das man nichts mehr am server abändern bzw einstellen müsste

Super, hoffe es läuft!

**Comment by kamohy** [comment]
nein tut es nicht... :-/

**Comment by kamohy** [comment]
@DevilTwist und schon alles behoben ? :D 
Wenn nein gib mir noch ein paar Tage, ich sitz dran. :D

**Comment by kamohy** [comment]
@DevilTwist habe eine teillösung für dich... zieh dir, die aktuelle 2.5 dev überspiele sie auf dein aktuelles 2.4
dann, musst du nur noch einige wenige dateien renamen (NewsCats.php zu Newscats.php z.b.)
der updater funktioniert nicht und wird auch nicht gebraucht 

entferne vor dem update folgende datei aus der 2.5: storage/app/database.ini da sie sonst nicht übereinstimmt

**Comment by kamohy** [comment]
@DevilTwist na wie sieht es aus?
Biste Bugfrei?
Wenn nein, hab da ein wenig was für dich.
