### ISSUE TITLE
Help with a few issues

### ISSUE THREAD

**Issue by dieago** [Contentify/Contentify#41]
Hello,

I am having a few issues with things on the website.

First of all, I am wondering why the twitch doesn't show up? For some reason it shows up when you click on the streams tab however it doesn't update the viewers or who is online at all on the module to the right.

Second, I would like to know how it is possible to add an image rather than text on the team page.

Third, I was wondering if it is possible to make the videos so that the latest video added is the first video to show on the website or do i have to manually set that somehow?

Fourth, on the events page, is it possible to put the "Starts At" on the same row rather than two rows.

I am also wondering where I upload my favicon files to get them to display?

Lastly, I am wondering if it is possible to set the game icon under "Latest Matches" rather than having the team icon because we have several teams and that would be better for us as an organisation.

I am really sorry if this is being picky etc, and really sorry if it makes me sound like a noob however I am not a coder and know nothing about coding :/

Thanks and hopefully these are quick easy things that you guys can help me with :)

**Comment by dieago** [comment]
www.nemeanesports.org - sorry i should have added it for you :)

**Comment by Vexena** [comment]
As an offtopic sidenote: this open source project is under an MIT license meaning that you are allowed to copy, modify, merge, publish, distribute,... but have to include the copyright holders at the footer of the page, in this case Contentify.

More information about the license can be found here:
https://opensource.org/licenses/MIT

You will have to change the copyright text back to the original one to give credits to the creator of this project.

**Comment by dieago** [comment]
Yes, I am in the proccess of editing the footer and it's currently in the privacy policy. I'm new to this coding shizzle but I've got the design on my desktop on how i want it to look but i've just got to learn how to make it that's all.

Date: Tue, 1 Mar 2016 02:37:55 -0800

**Comment by chriskonnertz** [comment]
Hello

> First of all, I am wondering why the twitch doesn't show up? 
https://github.com/Contentify/Contentify/wiki/Built-In-Modules#streams

> Second, I would like to know how it is possible to add an image rather than text on the team page.
On which of tham? Team overview (`http://46.101.143.161/teams/`) or team detail (`http://46.101.143.161/teams/1/csgo`)? Additional to the team image? And instead of what text?

> Third, I was wondering if it is possible to make the videos so that the latest video added is the first video to show on the website or do i have to manually set that somehow?

You can change it in the code. Where to change it depends on where you want to change it - there are multiple files that deal with videos. The widget? The overview page?

> is it possible to put the "Starts At" on the same row rather than two rows

Yes. Open `resources/lang/en/app.php`, find `'starts_at'     => 'Starts At'` (most likely in line 82) and replace it with `'starts_at'     => 'Starts&nbsp;At'`. (I am not 100% sure if it will work but please give it a try)

> I am also wondering where I upload my favicon files to get them to display?

`public/img/favicon_180.png` (big) and `public/img/favicon.png`(small, at least 16x15 pixels)

> Lastly, I am wondering if it is possible to set the game icon under "Latest Matches" rather than having the team icon.

You mean on the `/matches`page? Yes sure. Open `App/Modules/Matches/Http/Controllers/MatchesController.php`, and replace the `tableHead`and `tableRow`lines with these lines (but backup the original file before... I did not test the new code!): 
http://pastebin.com/dvMUQN1b

> I am really sorry if this is being picky etc, and really sorry if it makes me sound like a noob however I am not a coder and know nothing about coding :/

No problem. :)

**Comment by chriskonnertz** [comment]
@Vexena Hey, thanks for taking care. :) 

However, it's enough to keep the notice on the impressum (imprint) page http://www.nemeanesports.org/impressum : 

> CMS
> Powered by Contentify CMS.

**Comment by dieago** [comment]
I think i didn't write down a few things properly, but i've also edited some of it so thank you so much for the details etc. I'll post some images up of what I am looking to get done as it would make it easier for you to understand me because i'm bad at explaining things in writing haha :package: 

1. https://gyazo.com/7c038a5688b7664ed8e56b86601f35c2
1. This part, I would possibly like it to display the game icon rather than the opponents team logo however if it's not possible that's np.

2. https://gyazo.com/94d3b3feb9d315fea215a0948f2398e5
2. So on this page, the first video I added was the Nemean eSports intro however I would like that to be at the bottom of the page and have the "newest videos" at the top.

3.https://gyazo.com/cfa5c9602b30dab57c9c3c677ef5ffc6
3. So on this page, instead of the text with the name i.e n1ko, Twinkey etc, I would like it to display a custom image (that i will make) that will also link to their profiles but would look a little more proffesional. This would also be the same on the team page so on both pages looking the same. If possible, would there be a possibility that it could capture the players uploaded profile picture?

4. https://github.com/chriskonnertz/Jobs
4. So with this page, do i literally just install this and the streams will work and update? Sorry I'm not good with coding so I'll have to get someone to help me if I need to change things etc.

5. http://nemeanesports.org/partners/6
5. Just found this issue when I click on any of the partners I have added to the site.

6. http://nemeanesports.org/forums/threads/2/introduce-yourself
6. We also have this issue, however someone else opened up an issue post so I will keep an eye on that post updating.

Dang, I didn't realise how OCD I am :P but thanks so much for helping me so far. I'm going to try and edit the footer today I just need to learn a few things to do it xD

Thanks in advance,
Dieago

p.s the "Starts_At" doesn't work, because it adds the "_" too, so i've changed it to "Starting"

**Comment by chriskonnertz** [comment]
Hello,

A:
Open `app/Modules/Matches/Resources/Views.widget.blade.php`. Replace

```
@if ($match->right_team->image)
                        <img src="{!! $match->right_team->uploadPath().$match->right_team->image !!}" width="30" height="30" alt="{{ $match->right_team->title }}">
                    @endif
```

with

 ```
@if ($match->game->icon)
                        <img src="{!! $match->game->uploadPath().$match->game->icon !!}" width="16" height="16" alt="{{ $match->game->title }}">
                    @endif
```

B:
That's a very good idea in general. You can see how to change it here: https://github.com/Contentify/Contentify/commit/0684be894b3ffee821256977460f6486d3b8c20a

C:
Yes you can use the player pictures. The tempaltes you have to edit are `app/Modules/Teams/Resources/Views/index.blade.php` (team overview) and `app/Modules/Teams/Resources/Views/show.blade.php` (team detail).

Change this

`<a href="{!! url('users/'.$user->id.'/'.$user->slug) !!}">{{ $user->username }}</a>`

to

`<a href="{!! url('users/'.$user->id.'/'.$user->slug) !!}"><img src="{!! $user->uploadPath().$user->image !!}" alt="{{ $user->title }}" style="max-width: 30px; max-height: 30px;"> {{ $user->username }}</a>`

And change the maximum width & height to whatever you like.

(I have not tested this solution.)

D:

> So with this page, do i literally just install this and the streams will work and update?

No, you do not have to install it! It is a part of Contenitfy ( see `vendor/chriskonnertz/jobs` )
All **you** have to do is to create a cron job on your server (or use an external service). Just ask Google for a tutorial - for example; "how to cron job linux"

E:

Fixed here: https://github.com/Contentify/Contentify/commit/9f00dbc5c5baa4e0a560579c754ecbf6579f073c

(Copy the new code to your file.)

F:

This has been fixed: https://github.com/Contentify/Contentify/commit/0a1e5a56668aa9fb135229f7c56137f621eed3a9

(Copy the new code to your files. If you use a LESS compiler, you only have to change the .LESS file and recompile it.)

**Comment by dieago** [comment]
FANTASTIC! Everything near enough sorted, thank you so much you are a GOD!

Last problem then i'm done xD 

http://nemeanesports.org/teams/2/counterstrike-global-offensive
I can't figure out how to get the images to be horizontal rather than vertical and If possible I would like to remove their text names that are displaying to the right.

Also, we don't own the server, so I will have to do some searching around to get someone to create a cron job externally for me.

Thanks so much,
Dieago

**Comment by chriskonnertz** [comment]
No. But I believe there are many services out there that will do the trick. 

For example: [https://cron-job.org/en/](https://cron-job.org/en/)

All you have to do is to register/create a cron job that calls this URL every 5 minutes:
`http://www.nemeanesports.org/jobs`

**Comment by dieago** [comment]
You sir, are a legend. thank you so much!

**Comment by chriskonnertz** [comment]
No problem :)
