### ISSUE TITLE
Can´t run installer

### ISSUE THREAD

**Issue by MintKind** [Contentify/Contentify#410]
Hello, I am currently trying to install Contentify 2.4, but if I open the install.php I just see the requirements all green 
![screenshot_installer](https://user-images.githubusercontent.com/21332730/44055999-3f6b1542-9f47-11e8-9f42-26b62f514bda.png)

Before 2.4 I installed 2.2 and it worked fine.

**Comment by chriskonnertz** [comment]
Hello,

wow, that is a strange bug. 

Please copy the source code of the website and paste it here. (Right click on the document then there should be an entry in the context menu such as "Show page source text").

Also try to use another browser and to deactivate any advertisement blockers.

**Comment by MintKind** [comment]
Trying another browser didn't help :/ 
But here is the source code
https://pastebin.com/hGBMZ4KS

edit:
here is also the website
https://teambonfire.de/gaming/public/install.php

**Comment by chriskonnertz** [comment]
Sorry for not replying but to be honset I have not idea why it is going wrong :( There should be a big blue install button but it's missing, also in the HTML source code of the page.

**Comment by chriskonnertz** [comment]
Workaround: Call the `/install` URL manually (for example: `example.org/install`)

**Comment by chriskonnertz** [comment]
You may also try this: https://github.com/Contentify/Contentify/issues/305#issuecomment-442244603

Could be the problem here, `apache_get_modules()` not working / allowed on you server but due to the configuration of your server you did not see the error message but the rendering of the page was aborted, so the button was missing.

**Comment by chriskonnertz** [comment]
=> https://github.com/Contentify/Contentify/issues/458
