### ISSUE TITLE
Getting same error while installing on both 2.4 or 2.3

### ISSUE THREAD

**Issue by itsmemac** [Contentify/Contentify#411]
![capture](https://user-images.githubusercontent.com/37410297/44077129-3badec6c-9fc0-11e8-8fe0-76f93673a5ee.JPG)

**Comment by itsmemac** [comment]
fixed it by removing symbols from db password.
Having symbols is blocking the install.
Fix it

**Comment by chriskonnertz** [comment]
Thank you for this information.

Symbols = Unicode symbol characters? For example: 🛪

**Comment by itsmemac** [comment]
nah, just using ~ ? < '
any symbols, its giving the issue.
Tried with separate install in different hosting. Same issue happens
only fix is to use alphanumeric combination for DB to fix the issue

**Comment by chriskonnertz** [comment]
I will check if this issue exists in v2.5/2.6 as well.
