### ISSUE TITLE
Admin panel broken after installation v2.4

### ISSUE THREAD

**Issue by itsmemac** [Contentify/Contentify#412]
![capture8](https://user-images.githubusercontent.com/37410297/44115512-b63b9c2a-a02b-11e8-9d21-afd2126f0d08.JPG)
its broken and options are limited and showing only some options.

and how to change from www.domain.com/public --->>> www.domain.com

**Comment by chriskonnertz** [comment]
Hello

> its broken and options are limited and showing only some options.

Maybe it is just a caching issue of your browser. Please force the browser to reload all resources. For example press F5 twice or try SHIFT+F5. (It depends on the brwoser.)

**Comment by chriskonnertz** [comment]
> how to change from www.domain.com/public --->>> www.domain.com

https://github.com/Contentify/Contentify/wiki/Troubleshooting#installation-what-to-do-with-the-public-folder

**Comment by itsmemac** [comment]
Thanks.
Issue is fixed

**Comment by chriskonnertz** [comment]
Nice!
