### ISSUE TITLE
Opponents Module and Games Module SVG Support

### ISSUE THREAD

**Issue by renegade1337** [Contentify/Contentify#413]
Für das Opponents und Games Modul sollte SVG als Bildformat hinzugefügt werden ;-)

**Comment by chriskonnertz** [comment]
Hallo,

sprich dass sowohl der Upload möglich ist als auch die so hochgeladenen Bilder dann auch als SVG ausgeliefert (statt zu bspw. JPEG) konvertiert werden?

**Comment by renegade1337** [comment]
Das die Bilder im Frontend auch als SVG ausgegeben werden können.

**Comment by chriskonnertz** [comment]
Ok das ist eine gute Idee, ich habe mir das heute mal kurz angeschaut und denke das kann noch in die v2.5 mit rein. Der Support würde dann (zumindest im Backend) überall greifen, also bei (vermutlich) allen Modulen.

Danke für die Anregung.

**Comment by chriskonnertz** [comment]
=> https://github.com/Contentify/Contentify/issues/304

**Comment by chriskonnertz** [comment]
Mache daher hier mal zu, ist ja jetzt in der To-Do-Liste.

**Comment by chriskonnertz** [comment]
Nun experimentell in v2.6-dev enthalten.

https://github.com/Contentify/Contentify/commit/3c38c31987857f2c3ee127612a44c9f9ea724de2
