### ISSUE TITLE
[Feature Request] Youtube streams in stream tab

### ISSUE THREAD

**Issue by itsmemac** [Contentify/Contentify#414]
Youtube stream in streams option
![capture](https://user-images.githubusercontent.com/37410297/44185581-1bb3b900-a132-11e8-8cf3-816d6082a40c.JPG)

**Comment by chriskonnertz** [comment]
Hello,

thank you for this suggestion! I like the idea. I do not know when it will come but yes I believe this should be implemented. When? Depends on how much work it is to implement it. I have to take a look at the API to decide when to schedule it.

**Comment by roachy** [comment]
@chriskonnertz Going to assign myself to this functionality if that's cool

**Comment by chriskonnertz** [comment]
Hi, sure! :)

**Comment by torriz** [comment]
I know it's been a while since the request now.. but I would still like to see this added to the Streams module!

[YouTube > Live Streaming API > PHP Code Samples](https://developers.google.com/youtube/v3/live/code_samples/php)

**Comment by torriz** [comment]
@roachy Any progress? 
@chriskonnertz Are you able to make this happen? 👼

**Comment by chriskonnertz** [comment]
Hi maybe... their PHP examples are a nightmare. I had to dig into that chaos... Maybe in v3.1? :stuck_out_tongue_winking_eye:

**Comment by torriz** [comment]
😢 😭 
Okay..  well, I hope someone with more knowledge than me picks this up before that time!
