### ISSUE TITLE
Install 2.4 problem auf Webspace gefunden.

### ISSUE THREAD

**Issue by kamohy** [Contentify/Contentify#415]
Wir haben heut (Sascha ist zu besuch)
Einen lokalen server neu aufgesetz und einfach mal deine install drüber laufen lassen. 
Siehe da es funktioniert.
Dann haben wir uns gefragt warum nicht, auf einem Webspace...
Ganz einfach, du hast scheinbar, shell befehle im installer bzw. bei einigen aufgaben des CMS eingebaut.
Diese benötigen root-rechte... ein normaler webspace-kunde, wird dies also Niemals nutzen können, außer du findest eine möglichkeit, shell befehle zu deaktivieren und dennoch, das cms am laufen bzw. zum installieren zu bekommen.

Fehler 1 gefunden...
Fehler 2 immer noch falsche DB-anknüpfungen sowie fehlerhaft benannte dateien 
bsp.: Pagecat.php nicht gefunden heisst auf dem server PagesCats.php (linux nimmt es sehr genau)
bsp. 2: admin_partners_form wird gesucht und heisst: auf dem server entweder: admin_partner_cats_form

problem beim umbenennen: die falsche verlinkung ist im code immer noch aktiv, nach dem speicher, bzw. ändern sucht er dann nämlich genau die andere datei...

@chriskonnertz bitte, märze diese fehler in 2.5 aus... wobei ich mich frage, wozu die shell's in der install aus einem web-browser heraus, nötig sind. bzw auch im laufenden betrieb des CMS...

zusatz: In zahlungen (cash_flows) fehlten in der DB zwei eintragungen: integer_expenses & integer_revenues

**Comment by chriskonnertz** [comment]
Hi,

> Siehe da es funktioniert.

Ja sieh mal einer an! Es geschehen noch Zeichen und Wunder. ;)

> Dann haben wir uns gefragt warum nicht, auf einem Webspace...

Ja, die große große Frage.

> Ganz einfach, du hast scheinbar, shell befehle im installer bzw. bei einigen aufgaben des CMS eingebaut. Diese benötigen root-rechte

Das kann schon sein. Es wäre eine Erklärung warum mir das nie aufgefallen ist.

>  außer du findest eine möglichkeit, shell befehle zu deaktivieren und dennoch, das cms am laufen bzw. zum installieren zu bekommen.

Ich glaube ich muss das mal selber mit einem User ohne Root-Rechte durchspielen da ich spontan auch nicht weiß was da für Shell_Befehle ausgeführt werden. Ich vermute das kommt nicht direkt von mir, das ist irgend was vom Framework oder einer Drittanbieter-Bibliothek.

Jedenfalls super, dass ihr das herausgefunden habt denn so habe ich eine konkrete Möglichkeit dem Problem auf den Grund zu kommen. Bislang war für mich völlig unklar dass es so ein Problem gibt. Also vielen Dank für die Information.

**Comment by chriskonnertz** [comment]
> bitte, märze diese fehler in 2.5 aus.

Ja das ist geplant.

**Comment by kamohy** [comment]
Hallo Chris... Ja hat ja nur wieviele Monate gebraucht, das rauszufinden ? :D 
Wir wissen das aber auch nur, da wir das halbe ding durchsucht haben auf bestimmte dinge, die im install-verfahren auf dem LOKALEN server durch gelaufen sind. (install.sh)

Wir haben uns gefragt, was läuft dort anders.

Dann haben wir das fertig installierte auch noch genommen, es auf unseren space geklont (hauptserver) und dort liefen wieder nicht alle sachen...

da lag es irwie (dank log...) auf der hand das es nur so sein kann und haben nach exec( und shell_exec gesucht... und das im GANZEN cms... (sind ja nur knapp 12.000 dateien die notepad +++ durchsucht hat)

gute nacht... genug internet für heute :-D

**Comment by kamohy** [comment]
2.4 install fehler:
CashFlow DB fehlen zwei einträge

2.4 / 2.5 fehlerliste:
Groß/Kleinschreibung bei benennung von datein (only cat/Cat)
abegändert in: 
/vendor/composer/autoload_classmap.php 
& 
/vendor/composer/autoload_stats.php


ForumReport geht mal wieder nicht:

 (2/2) QueryException

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'contentify2.forum_reports.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select post_id, COUNT(id) as report_counter, MAX(updated_at) AS updated_at from `forum_reports` group by `post_id` order by `created_at` desc)

 (1/2) PDOException

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'contentify2.forum_reports.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

ansonsten keine Fehler gefunden, nach dem ich auf 2.4 einfach nur die 2.5-dev draufgelegt habe 
(update.php geht irwie nicht)

Updater geht übrigens auch nicht wird aber von mir jetzt überarbeitet mit der abfrage dann:
Ist DB-eintrag da? wenn ja nächste spalte wenn nein dann ADD bzw UPDATE oder aber RENAME
Denn, es nervt das man quasi alle DB-einträge auskommentieren muss bis er alles hat findet was ein update bzw erstellt werden muss, da er sonst in die fehler rennt...

**Comment by andakawa** [comment]
>Dann haben wir uns gefragt warum nicht, auf einem Webspace...

Ich habe das CMS in Version 2.4 auf dem günstigsten One.com Webspace zum laufen gekriegt und bis heute keine Probleme mehr feststellen können. Sofern alle PHP-Extentions vorhanden sind, sollte es bei den meisten Nutzern eigentlich auch kein Problem geben.
