### ISSUE TITLE
Bugs in 2.4 und 2.5 dev

### ISSUE THREAD

**Issue by kamohy** [Contentify/Contentify#418]
Dateien falsch benannt (bsp.: Newscat.php -> NewsCat.php) ist aber nicht der dateiname der geändert werden muss, sondern im /vendor/composer/autoload_classmap.php und die autoload_static.php im selben ordner.

in der 2.4 fehlt in der DB zwei einträge unter cashflow in der combi mit 2.5 neu installiert, ist es dabei

einziger bisher gefundene weitere bug ist: Forum-Report (vorhanden in 2.4 UND 2.5)

`(2/2)QueryException
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'kamohy.forum_reports.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select post_id, COUNT(id) as report_counter, MAX(updated_at) AS updated_at from `forum_reports` group by `post_id` order by `created_at` desc)`
und:
`(1/2)PDOException
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'kamohy.forum_reports.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

leider habe ich keine Ahnung, wie ich das beheben soll... also falls einer ne idee hat her damit :-D
@chriskonnertz wir haben es sauber installiert, erst 2.4 allein dann mit dem update auf 2.5
und auch eine 2.4 aufm "server" die 2.5 drüber und dann erst installiert, alle drei versionen brachten das hervor. in 2.2 und 2.3 sowie die offiziele version von deathkings (unsere schon abgeänderte und bisher kein update eingespielte version) haben diesen fehler nicht mehr nach deinem bugfix.

**Comment by chriskonnertz** [comment]
> einziger bisher gefundene weitere bug ist: Forum-Report (vorhanden in 2.4 UND 2.5)

Glaube den kenne ich und dachte eigentlich der wäre gefixt. Naja es gibt einen einfachen Workaround: https://github.com/Contentify/Contentify/blob/v2.4/config/database.php#L50 
strict auf false setzen, dann ist MySQL weniger kritisch und erlaubt die MySQL-Abfrage die er sonst bemängelt. Dazu muss man sagen, früher war der strikte Modus nicht aktiv aber in Laravel 5-irgendwas wurde es dann eingebaut und auf true gesetzt, daher macht plötzlich dieses alte MySQL-Statement Probleme. Potenziell könnte es zudem sein das irgendwo in den Tiefen noch andere alte Statements sind die jetzt Probleme machen nur dass das bisher noch nicht aufgefallen ist.

**Comment by onavascuez** [comment]
Sorry in advance about my german google translator level... :P 
I tried to change srtrict to false, also include to my .env file a global variable DB_STRICT=false, and add  `'strict'    => env('DB_STRICT', false), ` on my database.php.
I've tried clearing all caches, and have he same result.

**Comment by onavascuez** [comment]
OK, I found a solution for this error... And I think is very specific error, and really strange.
When I install Contentity 2.4, under PHP7.2 and MySQL 8.0.12 I need to do this on my database.php: https://github.com/Contentify/Contentify/issues/423#issue-357109062

But this "improvement" affect to some queries. In specific the command affect to this, is "**ONLY_FULL_GROUP_BY**". If we delete this line from database.php, all site will works correctly.

**Comment by kamohy** [comment]
@chriskonnertz dein kleiner fix, funktioniert.
Ich bin gerade dabei alles genauer zu testen.
News haben auch einen Bug, nun aber das problem.
Ich habe dazu einen Beitrag gefunden, allerdings hilft der nicht.
sobald ich News, speichere oder auf der Webseite aufrufe kommt eine Fehlermeldung:
```
(1/1) FatalErrorException
Class 'SimpleXMLElement' not found
in SimpleXMLElement.php (line 6)
```
ich habe wie du es empfohlen hast in einem anderen Beitrag, simpleXML nachinstalliert.
Hat nur nichts gebracht...
(Ich kann es leider nicht vorführen, da es ein lokaler Server ist auf dem ich alles Fixe...)


Soll ich dir meine Version, am Ende zukommen lassen Chris wenn ich alle fixes durch habe? :D

**Comment by kamohy** [comment]
Hat sich erledigt, Bug ist behoben !
nach einem: apt-get update && apt-get upgrade -y
und init 6, läuft nun auch der News-bereich.
keine weitere Forschung hierzu benötigt, vorerst.

Issue dennoch bitte geöffnet lassen, falls weitere Bugs folgen. :-/

**Comment by chriskonnertz** [comment]
> But this "improvement" affect to some queries. In specific the command affect to this, is "ONLY_FULL_GROUP_BY". If we delete this line from database.php, all site will works correctly.

Yeah taht makes sense.

**Comment by chriskonnertz** [comment]
> Issue dennoch bitte geöffnet lassen, falls weitere Bugs folgen. :-/

Ok.

**Comment by kamohy** [comment]
Hab leider noch einen gefunden.
 Passwort zurücksetzen, auf zwei Seiten der selbe Fehler.
ein HTTPError die route ist nicht bekannt :-/
getestet auf kamohy und deathkings...

**Comment by kamohy** [comment]
Die entsprechende Fehlermeldung dazu:


(1/1) MethodNotAllowedHttpException
in RouteCollection.php (line 251)
at RouteCollection->methodNotAllowed(array('POST'))
in RouteCollection.php (line 238)
at RouteCollection->getRouteForMethods(object(Request), array('POST'))
in RouteCollection.php (line 176)
at RouteCollection->match(object(Request))
in Router.php (line 546)
at Router->findRoute(object(Request))
in Router.php (line 525)
at Router->dispatchToRoute(object(Request))
in Router.php (line 511)
at Router->dispatch(object(Request))
in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))
in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))
in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))
in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))
in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))
in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))
in Pipeline.php (line 102)
at Pipeline->then(object(Closure))
in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))
in Kernel.php (line 116)
at Kernel->handle(object(Request))
in index.php (line 53)

**Comment by chriskonnertz** [comment]
Wann genau tritt das auf? Ich konnte auf "Passwort vergessen" klicken und dort auf der Seite dann meine Mail und das Captcha angeben und dann kam eine Erfolgsmeldung. Oder tritt das erst später auf nach Erhalt der Email?

**Comment by chriskonnertz** [comment]
Ok hab was: https://github.com/Contentify/Contentify/commit/b5f552919d8b7c39303908e43addae9316e4f555

**Comment by kamohy** [comment]
läuft, jetzt noch die phpinfo abfrage im ACP und wir haben alles mir bekannt.

Achja der RSS-Feed im ACP ist noch auf dem stand vom contentify 2.3
auch hier würde ich ein update des feeds anraten

**Comment by chriskonnertz** [comment]
Ist die PHPInfo-Abfrage auf dem für mich eingerichteten Server auch defekt? Wenn ja könnte ich das gleich da debuggen.

**Comment by kamohy** [comment]
ja

**Comment by kamohy** [comment]
Sag mal, bekommste auch nen umfrage modul hin?
das wär neben nem newslater (newsmailer/infomailer) das was mich noch interessieren würde.

**Comment by chriskonnertz** [comment]
> läuft, jetzt noch die phpinfo abfrage im ACP und wir haben alles mir bekannt.

Hatte es ganz vergessen, das wurde bereits gefixt: 
https://github.com/Contentify/Contentify/commit/b45a27aa12adf5c65d8ef7f03232da50b49f72b6

**Comment by chriskonnertz** [comment]
> Sag mal, bekommste auch nen umfrage modul hin?

Hinbekommen: Ja, sicher. :) Nur wann? ;)

**Comment by kamohy** [comment]
> > läuft, jetzt noch die phpinfo abfrage im ACP und wir haben alles mir bekannt.
> 
> Hatte es ganz vergessen, das wurde bereits gefixt:
> [b45a27a](https://github.com/Contentify/Contentify/commit/b45a27aa12adf5c65d8ef7f03232da50b49f72b6)

Gut, werde ich dieses WE umsetzen.

**Comment by kamohy** [comment]
das 

> > Sag mal, bekommste auch nen umfrage modul hin?
> 
> Hinbekommen: Ja, sicher. :) Nur wann? ;)

Deine aussage finde ich halb positiv xD

**Comment by kamohy** [comment]
> > läuft, jetzt noch die phpinfo abfrage im ACP und wir haben alles mir bekannt.
> 
> Hatte es ganz vergessen, das wurde bereits gefixt:
> [b45a27a](https://github.com/Contentify/Contentify/commit/b45a27aa12adf5c65d8ef7f03232da50b49f72b6)

läuft

**Comment by chriskonnertz** [comment]
Ich schließe das Ticket nun da die Bugs hoffentlich inzwischen alle gefixt sind (in v3.0).
