### ISSUE TITLE
FatalErrorException Contact module

### ISSUE THREAD

**Issue by josephzigler** [Contentify/Contentify#42]
Hello,

When trying out the contact form I noticed when submitting a message an FatalErrorException gets thrown with syntrax error, unexpected ';' here is the error in detail: http://imgur.com/OqjwLRH

The messages that have been submitted do show up in the admin panel.

Is there a way to fix this?

Thank you in advance,
Regards

**Comment by chriskonnertz** [comment]
No problem.
