### ISSUE TITLE
Laravel 5 with MySQL 8.0.12, 'sql_mode' ERROR

### ISSUE THREAD

**Issue by onavascuez** [Contentify/Contentify#423]
If we have MySQL 8.+ version, is possible to show this error when install Contentify:
`ERROR 1231 (42000): Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'`

**[SOLUTION]**
In this case, we only go to `/config/database.php` and add this lines at the end of block of Mysql:

'mysql' => [
'driver' => 'mysql',
.
.
.
'engine' => null,
**'modes' => [
    'ONLY_FULL_GROUP_BY',
    'STRICT_TRANS_TABLES',
    'NO_ZERO_IN_DATE',
    'NO_ZERO_DATE',
    'ERROR_FOR_DIVISION_BY_ZERO',
    'NO_ENGINE_SUBSTITUTION',
],**
],

**Comment by chriskonnertz** [comment]
Thank you for this hint!! Very helpful.
