### ISSUE TITLE
Issues with Installation even if I have all green with the setup

### ISSUE THREAD

**Issue by Roknthegreat** [Contentify/Contentify#426]
Everytime I try to install Contentify I get these errors:
(2/2) QueryException
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'username' (SQL: alter table `users` add `username` varchar(20) not null, add `slug` varchar(255) not null, add `updater_id` int unsigned not null default '0')

(1/2) PDOException
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'username'

How do I fix these errors? I'm new to terminals and downloading databases

**Comment by ExpertSunny** [comment]
Happened with me too. I just changed the number in the url to proceed to next step. It worked for me.

**Comment by chriskonnertz** [comment]
Closing this, since this should be fixed with the upcoming version  3.0.
