### ISSUE TITLE
Admin-backend generates URLs based off server_addr and not server_name

### ISSUE THREAD

**Issue by ashmandias** [Contentify/Contentify#429]
When browsing the admin control panel, I have noticed that the admin urls are generated based on PHP's server_addr variable, and not server_name. This means that even though my server is publicly accessible by hostname, the admin URLs are using 192.168.1.100 as the URL base -- which breaks when trying to access the host remotely.

This is on 2.4

Pretty good CMS so far -- looks like it will fit my needs nicely.

**Comment by kamohy** [comment]
okay delete all, in the database (phpmyadmin)
and run the install again

**Comment by ashmandias** [comment]
Anyway to do it without deleting and starting over? I have a decent chunk of configuration done already.

**Comment by kamohy** [comment]
okay, there is a little trick, maybe it works. Enter your URL at the top of the address bar and set it:
 /install?Step=4 
(could also be step 5)

**Comment by chriskonnertz** [comment]
> Anyway to do it without deleting and starting over?

Well the left sidebar navigation in the ACP is cached so to force regeneration you just have to [clear the cache](https://github.com/Contentify/Contentify/wiki/FAQ#how-can-i-clear-the-cache).

But of course, this will only have an effect if you change the way the URLs are built.
