### ISSUE TITLE
Contact form extend & hard delete bug

### ISSUE THREAD

**Issue by josephzigler** [Contentify/Contentify#43]
Hello,

Is it possible when you extend the textbox from 'Message' to prevent it from being able to extend it out of the Contact module? I provided an image to explain this better: http://imgur.com/Yqyh95R

I also experienced after soft deleting a match for example when you hard delete the match in the recycle bin you recieve an BadMethodCallException Call to undefined method Illuminate\Database\Query\Builder::withTrashed() when trying to open certain pages from modules in the admin panel.
Here are the full details: http://pastebin.com/vNErzJ4i This is when trying to hard delete anything from matches to teams, ... (this does not ruin the database, just the website files)

/diag gives NotFoundHttpException, tried dumpautoload in shell but that did not work
http://pastebin.com/acwm22cd

Would be amazing if there was a fix for this.

Thank you in advance!

Regards,
Joseph

**Comment by chriskonnertz** [comment]
Hello,

1. This CSS code should do it: `textarea { resize: horizontal; }`
The quick and dirty way is to add it directly to `app/Modules/Contact/Resources/Views/form.blade.php` by prepding this code to the top of the template:
`<style>#text { resize: horizontal; }</style>`

**Comment by chriskonnertz** [comment]
2. There is not "silver bullet" to solve these problems. So with other words there is no practicable solution at all. "_Do not delete things_" is the best "solution" atm. Or wait for the next version of Contentify that will address this problem.

**Comment by chriskonnertz** [comment]
PS: When I created Contentify I assumed that I can avoid these problems by adding constraints to the database (via `ON DELETE`) but then it turned out that soft deleting makes this impossible. If you soft delete something, `ON DELETE` is not triggered because from the database's view it's not a deletion. That clearly is a failure of design, mea culpa. But there is no easy way to solve the problem. I belive that a lot of code has to be changed to fix this.

**Comment by josephzigler** [comment]
> 1) This CSS code should do it: textarea { resize: vertical; }
The quick and dirty way is to add it directly to app/Modules/Contact/Resources/Views/form.blade.php by prepding this code to the top of the template:
<style>#text { resize: vertical; }</style>

Thank you that worked :)

> 2) There is not "silver bullet" to solve these problems. So with other words there is no practicable solution at all. "Do not delete things that have dependencies" is the best "solution" for now. Or wait for the next version of Contentify that will address this problem.

No problem.

> PS: When I created Contentify I assumed that I can avoid these problems by adding constraints to the database (via ON DELETE) but then it turned out that soft deleting makes this impossible. If you soft delete something, ON DELETE is not triggered because from the database's view it's not a deletion. That clearly is a failure of design, mea culpa. And there is no easy way to solve the problem. I believe that a lot of code has to be rewritten to fix this.

That is unfortunate but I believe not being able to hard delete and only soft deleting is not that big of a deal, I don't expect the database becoming that huge

**Comment by chriskonnertz** [comment]
> I don't expect the database becoming that huge
I am pretty sure this won't become a problem. :)

**Comment by josephzigler** [comment]
I have one more last question :) 

Would it be possible when adding a slide that you don't have to fill in the text and url field? To achieve a slide without any text? 

To make my explanation clear I added an image:
http://imgur.com/a/1jcDo (the string text and black background should not be included)

Would be great if this was possible!

**Comment by chriskonnertz** [comment]
This is something I have to think about.

For now here is a quick fix:

Open `public/vendor/contentify/slider.js` and replace the content with this code:
http://46.101.143.161/vendor/contentify/slider.js

To create a slide without title:
- Set the title to "notitle"
- Set the URL to: `#`

**Comment by josephzigler** [comment]
> To create a slide without title:

    Set the title to: notitle
    Set the URL to: #

Tried clearing cache and reloading few times with F5 but the url textbox still asks to give an url: http://imgur.com/jSxB70t

**Comment by chriskonnertz** [comment]
Ok. Open `app/Modules/Slides/Resources/Views/admin_form.blade.php`. Change

`{!! Form::smartUrl('url', trans('app.url')) !!}`

to

`{!! Form::smartText('url', trans('app.url')) !!}`

Let me know if it complains *after* clicking on "Save".

**Comment by josephzigler** [comment]
> 

Ok. Open app/Modules/Slides/Resources/Views/admin_form.blade.php. Change

{!! Form::smartUrl('url', trans('app.url')) !!}

to

{!! Form::smartText('url', trans('app.url')) !!}

Let me know if it complains after clicking on "Save".

Hi, thank you for the comment. Now it says that the format is invaled: http://imgur.com/l1QOsIe

**Comment by chriskonnertz** [comment]
No such big surpise ;)

Please open `app/Modules/Slides/Slide.php` and delete line 17:
`        'url'           => 'required|url',`

**Comment by josephzigler** [comment]
> Not a big surpise ;)
Please open app/Modules/Slides/Slide.php and delete line 17:
'url' => 'required|url',

That solved the issue regarding the url :) the 'notitle' seems to be still there tho

**Comment by josephzigler** [comment]
Still seem to have problems when setting notitle, it still show a title with the text 'notitle'

**Comment by chriskonnertz** [comment]
Ok I know why. The demo server overwrites the .js files...

Open `public/vendor/contentify/slider.js` and replace the content with this code:
https://jsfiddle.net/1khpzcg8/

**Comment by josephzigler** [comment]
> Amazing, that worked! Thanks alot.
