### ISSUE TITLE
Where do the 'FAQ' appear?

### ISSUE THREAD

**Issue by Ozymandias2** [Contentify/Contentify#430]
We have installed Contentify, and have added some 'Questions' content -- but cannot seem to figure out where they get listed on the site -- are we missing something, or running into a bug?

Thanks!

**Comment by kamohy** [comment]
domain/questions 
example: https://google.com/questions

**Comment by Ozymandias2** [comment]
I think I was assuming that the Morpheus Theme would have a link somewhere by default -- I had to add one to get it to work.

This is not a real issue, but may help others looking for things in the future.

**Comment by chriskonnertz** [comment]
An ideal solution would be to allow website administrator to edit the footer area of the website. Ofcourse this is a solution that is possible from a technical point of view, but to be honest this is not a feature that will make it to a release any soon.

**Comment by chriskonnertz** [comment]
> domain/questions
> example: https://google.com/questions

In general, you should always be able to click on the content-items in the backend. So if you have created a new question-answer-pair/item, go to the FAQ overview in the backend and click on the question. Then a new browser tab opens and shows the question in the frontend and you can copy the URL to create a link to the content. And again, this is a general behaviour that has to work for every module/content-item type, with very few exceptions (for example not working for comments atm).
