### ISSUE TITLE
Addon: erweiterung für suchmaschinen

### ISSUE THREAD

**Issue by kamohy** [Contentify/Contentify#432]
Mir ist aufgefallen das es schlagworte und eine beschreibung, für suchmaschinen fehlt.
Hab dazu mal nen kleines Addon gebaut.

Falls es dafür interesse gibt. 
(ist über das ACP steuerbar)

**Comment by chriskonnertz** [comment]
Hi, ja das hört sich doch spannend an. Das hat auf jeden Fall noch gefehlt.

**Comment by kamohy** [comment]
Diese erweiterung sorgt für die Optimierung der Webseite für Suchmaschinen (bsp. google.com)


![](https://kamohy.de/uploads/downloads/50/1_file.zip.png)



geht auf https://kamohy.de/downloads/1/metainformation-contentify
ladet euch dort die Erweiterung runter.

Folgende Dateien sind enthalten:

/app/Modules/Config/Resources/Lang/de/main.php
/app/Modules/Config/Resources/Lang/en/main.php
/app/Modules/Config/Resources/Lang/fr/main.php

/app/Modules/Config/Resources/Views/admin_index.blade.php

/app/Modules/Config/SettingsBag.php

/resources/lang/de/app.php
/resources/lang/en/app.php
/resources/lang/fr/app.php

Alles von mir geänderte ist makiert mit einem Komentar zum besseren verständniss, was verändert wurde.

**Schritt 1**

Entpackt die heruntergeladene Datei und ladet diese so wie sie sind,im standart-verzeichnis, in eurem FTP hoch.
Die oben genannten Datein werden überschrieben. (bis auf config.sql diese bitte nicht hochladen!)
(Diese änderungen haben keine negative Auswirkung auf eure Webseite.)

**Schritt 2**

Nun müsst ihr noch eure layout.blade.php bearbeiten je nachdem welches Theme ihr benutzt, findet ihr diese hier:

app/Modules/MorpheusTheme/Resources/Views/
oder:
app/Modules/PhobosTheme/Resources/Views/

fügt dies bitte unter Zeile 13 ein:

```
<!-- erweiterungen start | kamohy.de -->
	<meta name="author" content="{!! Config::get('app.author') !!}">
	<meta name="keywords" content="{!! Config::get('app.keywords') !!}">
	<meta name="description" content="{!! Config::get('app.description') !!}">
	<!-- erweiterungen ende | kamohy.de -->
```
	
Damit alles Funktioniert, noch folgendes.
Öffnet PHPmyAdmin (in der regel so: https://domain/phpmyadmin

geht auf eure Datenbank, dann auf Importieren und ladet die config.sql hoch.

ihr bekommt jetzt in der tabelle config, eurer datenbank 3 neue Einträge diese sind mit beispielen ausgefüllt:
Author = max mustermann
Keywords = Testseite, contentify, ect
Description = Dies ist eine Testbeschreibung für google.

Jetzt sollte folgendes passiert sein:

geht in euren Adminbereich der Website, weiter auf einstellungen
dort sollte nun ein neuer Tab/Reiter sein.


have fun to use!

Grüße Kamohy

**Comment by chriskonnertz** [comment]
Vielen dank dafür, das ist super! Damit wird eine Lücke gefüllt die von einigen in der Vergangenheit angemerkt wurde. Also wirklich sehr nützlich.

Wie soll es damit langfristig weiter gehen? Eine Möglichkeit wäre natürlich das direkt in Contentify zu integrieren. Das ist deine Entscheidung.

**Comment by kamohy** [comment]
Also kunden von hpzone.de, haben dies automatisch drin später.
Bei unseren Seiten (die wir aktuell hosten) füge ich es noch ein.
(jedoch nur wo wir die erlaubnis haben)

Du darfst es gern ab 2.6 integrieren
auch ohne meine kommentare

viel wichtiger ist aktuell die 2.5 raus bringen (apropro wochenende schmeiss ich dir meine version rüber)

Alle andere die es haben wollen, können diese erweiterung ja bei mir downloaden ohne probleme

**Comment by chriskonnertz** [comment]
@kamohy Ich werde das nun integrieren. Sieht auf den ersten Blick schon mal gut aus. ich erwarte also keine Probleme :) Ich werde es nicht verändern bis auf dass ich die Darstellung leicht anpassen werde, also wohl die Texte anders anordnen. Einfach damit es einheitlich ist wie der ganze Rest vom Backend.

**Comment by chriskonnertz** [comment]
Fertig: https://github.com/Contentify/Contentify/commit/7248f6889875ef7861ceba6725446c90ddf30205

Ich hab den Übersetzungs-Einträgen mal noch sprechende Namen gegeben.

**Comment by chriskonnertz** [comment]
Du hast ja auch eine .sql-Datei geschrieben. Ging es bei dir ohne die nicht?

**Comment by kamohy** [comment]
die sql ist nur zum schnellen updaten der DB
fand das einfacher als die update.php zu überschreiben oder nen installer neu zu schreiben dafür

quasi kirz im phpmyadmin anmelden hochladen und gut ist

**Comment by kamohy** [comment]
kann dann zu oder?

**Comment by chriskonnertz** [comment]
Ja.
