### ISSUE TITLE
Bugfix Navigation Widget

### ISSUE THREAD

**Issue by kamohy** [Contentify/Contentify#433]
go to this file:
app/Modules/Navigations/Resources/Views/navigaton_widget.blade.php

change the first line
`<div class="widget-navigation-default widget-navigation">`
to
`<div class="widget widget-navigation-default widget-navigation">`

ready !

**Comment by chriskonnertz** [comment]
Hi, so what does your change do? I assume it does remove some CSS styling?

**Comment by kamohy** [comment]
Yes it is for CSS 

mal in deutsch: es passt die navigation an (entsprechend des theme)
dadurch sieht alles in der navigation gleich aus.
Angepasst halt
bsp. findest du auf kamohy.de

**Comment by chriskonnertz** [comment]
Hm... aber da hast du doch die "widget"-Klasse noch mit drin?

```html
<div class="widget widget-navigation-default widget-navigation">
    <ul class="list-unstyled">
            <li class="item-level-0">
                <a href="https://kamohy.de/webmaster">Webmastertätigkeit</a>
            </li>
...
```

**Comment by kamohy** [comment]
die klasse **widget** ist normal nicht mit drin
dadurch sieht in der rechten navigation alls was über das navigations.widget drin ist so komisch aus
setzt man die klasse dazu
sieht man kein unterschied mehr gegenüber den anderen widgets

dadurch sieht alles gleichmäßiger aus
