### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by abdulsami34** [Contentify/Contentify#434]
Hello there,
I'm having problem with installation again.

I have tried every OS almost.

/contentify_2_4/public/install was not found on this server.

After clicking "Launch Installer" it goes to this.

**Comment by chriskonnertz** [comment]
Hi, the new 2.5 version will be released _very_ soon so I recommend to try it again when it is released.

**Comment by abdulsami34** [comment]
Waiting!!!. 

I tried almost every way installing tho xd

**Comment by chriskonnertz** [comment]
Rolling it out right now.

**Comment by chriskonnertz** [comment]
Out now: https://github.com/Contentify/Contentify/releases/tag/v2.5

Hope it works and helps you with the issue.

**Comment by abdulsami34** [comment]
Is it possible to install this on a cPanel server?

**Comment by abdulsami34** [comment]
SQLSTATE[28000] [1045] Access denied for user 'user233'@'107.189.2.213' (using password: YES) (SQL: SHOW TABLES LIKE "migrations") PS: I got passed through this error some how.


P.S = I got it to work on a cPanel! Working fine right now.
Thank you so much!

**Comment by kamohy** [comment]
go one step back, an click it again

**Comment by abdulsami34** [comment]
I installed it, Only one step is left. 
How do i setup HTACCESS for this?

**Comment by kamohy** [comment]
htaccess? for what, do you need that?

**Comment by abdulsami34** [comment]
To actually hide the main folder which includes database info etc.

**Comment by kamohy** [comment]
webspace or server ?

4 server go in: /etc/apache2/sites-available
copy the file, with the domain from u'r site

edit it so:
```
			<VirtualHost *:80>
				ServerAdmin webmaster@u'r domain
				ServerName u'r domain
				ServerAlias u'r domain
				DocumentRoot /var/www/u'r domain/public/
				<Directory />
					AllowOverride All
				</Directory>
				<Directory /var/www/u'r domain/public/>
					Options Indexes FollowSymLinks MultiViews
					AllowOverride all
					Require all granted
				</Directory>
				ErrorLog /var/log/apache2/u'r domain-error.log
				LogLevel error
				CustomLog /var/log/apache2/u'r domain-access.log combined
			</VirtualHost>
```

safe it and upload it
go to the console: **service apache2 restart**


**exemple**
```
			<VirtualHost *:80>
				ServerAdmin webmaster@contentify.org
				ServerName contentify.org
				ServerAlias contentify.org
				DocumentRoot /var/www/contentify.org/public/
				<Directory />
					AllowOverride All
				</Directory>
				<Directory /var/www/contentify.org/public/>
					Options Indexes FollowSymLinks MultiViews
					AllowOverride all
					Require all granted
				</Directory>
				ErrorLog /var/log/apache2/contentify.org-error.log
				LogLevel error
				CustomLog /var/log/apache2/contentify.org-access.log combined
			</VirtualHost>
```
please adjust the path to your web folder

**Comment by abdulsami34** [comment]
It's a cPanel server. I do not have access to console or SSH.

**Comment by kamohy** [comment]
ah okay... you have an admin-interface for u'r domain-control ?
search there: forwarding.
you can in an admin panel, determine where the path should go (for example, a subfolder)

**Comment by abdulsami34** [comment]
can't i do without the domain control?

**Comment by chriskonnertz** [comment]
> How do i setup HTACCESS for this?

=> https://github.com/Contentify/Contentify/wiki/Troubleshooting#installation-what-to-do-with-the-public-folder

**Comment by kamohy** [comment]
can it closed?

**Comment by chriskonnertz** [comment]
Closed. This really seems to be a bug and I will try to solve it.
