### ISSUE TITLE
Team Kategorisierung 

### ISSUE THREAD

**Issue by NePhiTV** [Contentify/Contentify#438]
Hallo Zusammen,
 
ich hab mal eine Frage. Ist es möglich z.B Teams mit der Kategorie "Community" anzeigen zu lassen und wenn man ein Team in die Kategorie "Pro" steckt diese separat anzeigen zu lassen?. Ich hoffe ihr wisst was ich meine. ^^

lg
NePhi

**Comment by chriskonnertz** [comment]
Hi,

ja und nein. Zwar gibt es Team-Kategorien, aber die haben bereits eine vorgegebene Bedeutung. Daher würde ich das eher als "Pro: Ja/Nein"-Attribut (Boolean/Flag) sehen und darüber lösen. 

Das lässt sich an sich recht einfach umsetzen. Datenbankspalte `pro` als INT erstellen in der `teams`-Tabelle, Attribut befüllbar machen im Model ( https://github.com/Contentify/Contentify/blob/v2.5/app/Modules/Teams/Team.php#L41 ), Checkbox-Formularfeld für die Editieren-Seite einbauen ( https://github.com/Contentify/Contentify/blob/v2.5/app/Modules/Teams/Resources/Views/admin_form.blade.php#L18 ). Dann hat man das drin und kann einfach per `$team->pro` darauf zugreifen. 

Wie es dann weiter geht hängt natürlich davon ab was genau du damit tun willst.

> ACHTUNG: Solche Änderungen immer per Backup sichern damit man sie nicht versehentlich mit einem zukünftigen Update überschreibt!

**Comment by NePhiTV** [comment]
Hi chriskonnertz,

vielen dank für die schnelle Antwort! Ich werde mir das ganze dann mal anschauen :) 

lg
NePhi

**Comment by NePhiTV** [comment]
Hab alles eingebaut es wird auch gespeichert und ausgelesen. Aber ich glaube das wir beide was anderes meinen, ich meine z.B das man auf der Seite eine Verlinkung einrichten kann wo z.B nur Teams mit der Kategorie "Staff" auf einer Seite angezeigt werden und wenn man wieder rum auf "Pro" zum Beispielt geht alle Teams mit der Kategorie "Pro" angezeigt werden. Ich vermute mal mein Text war etwas unverständlich, deshalb noch einmal diese Erklärung. ^^

lg
NePhi

**Comment by chriskonnertz** [comment]
Wie gesagt:

> Wie es dann weiter geht hängt natürlich davon ab was genau du damit tun willst.

Das müsstest du dann zusätzlich einbauen. 

An sich auch nicht schwer. Die allereinfachste Lösung: Bau an die URL so was an wie `?filter=pro`, also z. B. `http://example.com/teams?filter=pro`

Dann öffnest du dieses Template: https://github.com/Contentify/Contentify/blob/2.5/app/Modules/Teams/Resources/Views/index.blade.php

Dort fügst du nach Zeile 3, also hinter das `foreach...`, das hier ein:

```php
    @if (isset($_GET['filter']) and $_GET['filter'] === 'pro' and ! $team->pro)
        <?php continue; ?>
    @endif
```

(Kein schöner Code aber funktioniert.)

D. h. per default werden *alle* Teams angezeigt aber mit angehängtem  `?filter=pro` nur die Pro-Teams.

PS: hatte mich in dem älteren Post vertan, der Typ für die Spalte in der Datenbank ist nicht VARCHAR (ist ja kein Text) sondern INT oder TINYINT.

**Comment by NePhiTV** [comment]
Ah. Okay vielen Dank! Das geht eigl. auch :)
