### ISSUE TITLE
Bug? FeaturedMatch

### ISSUE THREAD

**Issue by NePhiTV** [Contentify/Contentify#439]
Heyho,

ich weiß nicht ob es ein Bug ist oder so gewollt ist, aber wenn ich ein Match nicht mit Featured kennzeichne sollte es vermutlich dann auch nicht ausgegeben werden, denke ich mal.

Bsp. http://prntscr.com/l7utd3

Ich hab auch die Rohdatei noch einmal drauf geladen um zu schauen ob ich evtl. etwas kaputt gemacht habe, dem ist nicht so.

lg
NePhi

**Comment by chriskonnertz** [comment]
Hallo,

schaue ich mir an.

**Comment by chriskonnertz** [comment]
Öhm ja da ist wohl was dran. :innocent:
Es wurde in der Tat nicht geprüft ob das Match überhaupt featured ist, was natürlich wenig Sinn ergibt.

Das hier sollte das beheben:
https://github.com/Contentify/Contentify/commit/771af072d28b9718d786a3cf1eeaa07887eb3157

Bitte hier schließen falls es nun wie erwartet funktioniert.

**Comment by chriskonnertz** [comment]
Hab was vergessen: https://github.com/Contentify/Contentify/commit/49f7a2c679820387e53e1788aa218950effddb8f

**Comment by NePhiTV** [comment]
Leider funktioniert das ganze noch nicht so wie gewollt, das Featured Match bleibt dennoch oben stehen. Außerdem werden jetzt die letzten Spiele nicht mehr ausgelesen.

Das Match was oben ausgegeben wird (FeaturedMatch) ist immer das Match was am längsten von der Zeit weg liegt, allerdings wird nach abschluss des Matches das ganze nicht deaktiviert und leider muss man dafür auch keinen Featured haken setzen damit das ganze aktiviert wird ^^

Hier ist die Seite um die es sich handelt https://www.immortal-rogues.de/

Gruß
NePhi

**Comment by chriskonnertz** [comment]
Hol mich bitte kurz ab: Das ist in dem Template `/app/Modules/PhobosTheme/Resources/Views/layout.blade.php` der Code hier, ja? `@widget('Matches::Matches')` 
Oder nutzt du was anderes?

**Comment by NePhiTV** [comment]
Hallo Chris,

Ja das Template stimmt, und ich benutze einmal für die letzten Spiele "@widget('Matches::Matches', ['limit' => 5])" und für das Featured Match "@widget ('Matches::FeaturedMatch', ['limit' => 1])"

lg
NePhi

**Comment by NePhiTV** [comment]
Gibt es dazu evtl. schon eine Lösung oder hat noch jemand eine Idee?

lg
NePhi

**Comment by chriskonnertz** [comment]
Ah sorry du hast recht ich hatte mich da wohl blöd in den Dateien vertan, hier ein neuer Lösungsversuch: https://github.com/Contentify/Contentify/commit/1bd19db2ccad1094ab22b34c72dff8335ffa4dd2

**Comment by NePhiTV** [comment]
Heyho,

merci! Hat funktioniert. :)

Gruß
NePhi
