### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by porphyryr** [Contentify/Contentify#44]
Hello,

I setted up my website with contentify but have problems with the password reset not working, I think because no correct mail account is set up in mail.php . I use zoho mail as mail provider and set the smtp server to smtp.zoho.com but i'm not sure how I can set the username and password from my account correctly in the mail.php file, I expect if I install and configure sendmail on my Ubuntu 14.04 vps and set the correct ports and account in mail.php the password reset function will work?

As sidenote: Would it be possible when someone fills in the contact form that a notification email gets sent to the administrator to notify him that there's a new message in the backend panel?

Thank you

**Comment by chriskonnertz** [comment]
Hi,

well the whole email functionality is part of the underlying framework, [Laravel](https://laravel.com/docs/5.2/mail). To be honest I am not an expert in questions about this.

Maybou you can post your `config/mai.php` (without password ;) ) somewhere?

**Comment by porphyryr** [comment]
@chriskonnertz No problem, I did some research and will use an HTTP API service and set that up in the mail.php and services.php files so I won't have to install and configure the smtp package on my server.

**Comment by chriskonnertz** [comment]
Ok.
