### ISSUE TITLE
HTTPS error (BUG)

### ISSUE THREAD

**Issue by ausryan** [Contentify/Contentify#440]
So when you go on my website: https://fadehq.com it works but if you click a page like teams you get "Not Found

The requested URL /teams was not found on this server.
Apache/2.4.25 (Debian) Server at fadehq.com Port 443" 

If I change the URL to http://fadehq.com/teams it works... I have ticked https in the admin config and I've also done restarts still having the issue.

**Comment by mrc4tt** [comment]
Do you have updated the .htaccess ?

**Comment by ausryan** [comment]
> 
> 
> Do you have updated the .htaccess ?

No, what do I do to the .htaccess?

**Comment by mrc4tt** [comment]
Hmm.. Seems like.. it wont know.. there is https.. if you are enter: The requested URL /teams was not found on this server. (as example).

**Comment by mrc4tt** [comment]
I'm pretty sure @chriskonnertz can help with that. i don't have the same issues. :o

**Comment by ausryan** [comment]
Someone please help @chriskonnertz

**Comment by kamohy** [comment]
https://github.com/Contentify/Contentify/wiki/Troubleshooting#installation-what-to-do-with-the-public-folder

**Comment by chriskonnertz** [comment]
@ausryan Did you change something special in the configuration (of your server)? Any changes to a `.htaccess` file?

**Comment by chriskonnertz** [comment]
Closing this issue. Please create a new issue if this topic is still relevant.
