### ISSUE TITLE
error artisan

### ISSUE THREAD

**Issue by rodseb** [Contentify/Contentify#441]
Hello
I have an error when I make the command  " php artisan " 

`PHP Fatal error:  Interface 'JsonSerializable' not found in /datas/vol4/yulpa165653/var/www/spm-corp.fr/site/vendor/laravel/framework/src/Illuminate/Database/Eloquent/M                                                                     odel.php on line 22`

`PHP Fatal error:  Interface 'JsonSerializable' not found in /datas/vol4/yulpa165653/var/www/spm-corp.fr/site/vendor/laravel/framework/src/Illuminate/Support/Collection.                                                                     php on line 18`

**Comment by chriskonnertz** [comment]
Hello,

please take a look into the `contentify` directory. Does it have a sub directory called `vendor`  that again has a bunch of sub directories? If it does not then I'd assume you have to run `php composer.phar install`.

**Comment by rodseb** [comment]
in the folder ~/contentify/Vendor I have a single file MySqlDump.php

when I do " php composer.phar " install in the root folder he tells me

`PHP Fatal error:  Uncaught Error: Class 'Phar' not found in /site/composer.phar:23`
`Stack trace:`
`#0 {main}`
 `thrown in /site/composer.phar on line 23`

**Comment by rodseb** [comment]
diagnostic
https://hastebin.com/ofubaruheb.cpp

**Comment by chriskonnertz** [comment]
> diagnostic https://hastebin.com/ofubaruheb.cpp

Ahhh ok thanks. This means that you do have the vendor stuff. :)

**Comment by chriskonnertz** [comment]
My assumption is that the PHP JSON extension is missing on your system.

To verify my assumption, please go to the admin backend -> settings -> click on the "PHP Info" button. Then use your browser to search for "json" on the page. You should find a section looking similar to this:
![json](https://user-images.githubusercontent.com/4319323/47374692-da6df580-d6ee-11e8-9cfa-c17bb266615d.png)

If you do **not** find this (which I assume will happen), you need to install the PHP JSON extension. You might try `sudo apt-get install php7.2-json` but this is just a guess, it depends on your operating system, of course.

**Comment by rodseb** [comment]
hi 
it's enabled with version 1.6.0
![site 2](https://user-images.githubusercontent.com/11620540/47375543-cf1bc980-d6f0-11e8-8f0f-881eedacb8e7.png)

**Comment by chriskonnertz** [comment]
I am not yet convinced! ;)

Please try this via console(! _not_ via web browser!): `php public/install.php` This will show you some information. What is it displaying after "PHP Json Extension:"?

**Comment by rodseb** [comment]
![screenshot 2018-10-25 01 06 27](https://user-images.githubusercontent.com/11620540/47466601-3e2d1700-d7f2-11e8-85ef-e3255acdf795.jpg)

**Comment by roachy** [comment]
Could your server have more than one php.ini file?

**Comment by chriskonnertz** [comment]
Hi, @roachy yes that might be true.

**Comment by chriskonnertz** [comment]
According to the screenshot of `phpinfo()` the web `php.ini` is located in `/etc/phpini/php72/spm-corp.fr.ini`.
To find out where the console `php.ini` is located you might use this command: `php --ini`

**Comment by chriskonnertz** [comment]
Closing this. Please create a new issue ticket if this problem is still relevant.
