### ISSUE TITLE
Twitch Widget funktioniert nicht mehr

### ISSUE THREAD

**Issue by NePhiTV** [Contentify/Contentify#442]
Hallo Leute,

leider funktioniert das Twitch Widget nicht mehr, der Cronjob wird ordnungsgemäß ausgeführt, leider wird das ganze aber nicht aktualisiert. An der Artisan Datei genauso wie an den Twitch API Dateien wurde nichts verändert. Der Twitch API Key ist auch korrekt, es wurde sogar ein neuer angelegt. Leider ohne Erfolg. 

Ist aktuell ein Problem in diese Richtung bekannt?

lg
NePhi

**Comment by chriskonnertz** [comment]
Hallo,

möglicherweise, zumindest steht schon länger ein mögliches Problem im Raum: https://github.com/Contentify/Contentify/issues/420

**Comment by NePhiTV** [comment]
Heyho,

keiner eine Idee? :/ 

lg
NePhi

**Comment by chriskonnertz** [comment]
Hi,

ich hab mir Twitch generell vor ein paar Tagen noch mal angeschaut und da hat es bei mir soweit funktioniert.

Okay also die Frage für ist, wo genau der Fehler liegt? Im Backend kann man ja unter Einstellungen -> Diagnose -> Jobs.last_execution schauen wann der Cron-Job zuletzt ausgeführt wurde. Hast du das mal eine gewisse Zeit beobachtet und kannst bestätigen dass er wirklich regelmäßig ausgeführt wird?

Dann würde ich in die Datenbank schauen bspw. mit phpMyAdmin in der Tabelle `streams` die Spalte `renewed_at`, sie gibt halt für jeden Stream an wann seine Meta-Informationen zuletzt tatsächlich geupdatet wurden. Das müsste sich dann circa mit den Ausführungszeiten des Cron-Jobs decken.

Wenn wir schon dabei sind, bitte ich um deine Meinung: Hältst du es für sinnvoll diese Information im Backend bei der Streams-Übersicht mit anzuzeigen?

**Comment by NePhiTV** [comment]
Hallo Chris,

tatsächlich gibt es ein Fehler.

> [2018-10-29 11:57:58] production.WARNING: Streams job: cURL error: Couldn't resolve host 'api.twitch.tv'
[2018-10-29 11:57:58] production.ERROR: ErrorException: Trying to get property of non-object in /var/www/vhosts/xxxx/httpdocs/xxxx/xxxx/app/Modules/Streams/Api/TwitchApi.php:78

Normal sollte es doch aktualisiert werden wenn man z.B einfach https://immortal-rogues.de/jobs in die URL Zeile eingibt oder irre ich mich da? Weil der Cronjob macht ja auch nichts außer durch die Artisan das ganze abzurufen oder?

> Wenn wir schon dabei sind, bitte ich um deine Meinung: Hältst du es für sinnvoll diese Information im Backend bei der Streams-Übersicht mit anzuzeigen?

Ja, finde ich schon sinnvoll.

** Edit: Komischerweiße funktioniert es nun.. evtl. gab es Seitens Twitch Probleme. **

Gruß
NePhi
