### ISSUE TITLE
Error 500 installation

### ISSUE THREAD

**Issue by darksidefr** [Contentify/Contentify#446]
Hello, (sorry for my english i'm french) after clicking on "installation" y have an error 500 ;(
My log lavarel.log : 

[2018-11-04 12:26:14] production.ERROR: PDOException: SQLSTATE[HY000] [2002] Connection refused in /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:68
Stack trace:
#0 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(68): PDO->__construct('mysql:host=127....', 'root', '', Array)
#1 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(44): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'root', '', Array)
#2 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#3 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Connection.php(883): call_user_func(Object(Closure))
#6 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Connection.php(470): Illuminate\Database\Connection->getPdo()
#7 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('delete from `ac...', Array)
#8 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('delete from `ac...', Array, Object(Closure))
#9 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Connection.php(477): Illuminate\Database\Connection->run('delete from `ac...', Array, Object(Closure))
#10 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Connection.php(428): Illuminate\Database\Connection->affectingStatement('delete from `ac...', Array)
#11 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2225): Illuminate\Database\Connection->delete('delete from `ac...', Array)
#12 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(821): Illuminate\Database\Query\Builder->delete()
#13 /homepages/5/d759942488/htdocs/osg/vendor/cartalyst/sentinel/src/Activations/IlluminateActivationRepository.php(173): Illuminate\Database\Eloquent\Builder->delete()
#14 /homepages/5/d759942488/htdocs/osg/vendor/cartalyst/sentinel/src/Laravel/SentinelServiceProvider.php(400): Cartalyst\Sentinel\Activations\IlluminateActivationRepository->removeExpired()
#15 /homepages/5/d759942488/htdocs/osg/vendor/cartalyst/sentinel/src/Laravel/SentinelServiceProvider.php(381): Cartalyst\Sentinel\Laravel\SentinelServiceProvider->sweep(Object(Cartalyst\Sentinel\Activations\IlluminateActivationRepository), Array)
#16 /homepages/5/d759942488/htdocs/osg/vendor/cartalyst/sentinel/src/Laravel/SentinelServiceProvider.php(47): Cartalyst\Sentinel\Laravel\SentinelServiceProvider->garbageCollect()
#17 [internal function]: Cartalyst\Sentinel\Laravel\SentinelServiceProvider->boot()
#18 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#19 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#21 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#22 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(788): Illuminate\Container\Container->call(Array)
#23 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(771): Illuminate\Foundation\Application->bootProvider(Object(Cartalyst\Sentinel\Laravel\SentinelServiceProvider))
#24 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Cartalyst\Sentinel\Laravel\SentinelServiceProvider), 33)
#25 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(772): array_walk(Array, Object(Closure))
#26 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#27 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#28 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#29 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\Foundation\Http\Kernel->bootstrap()
#30 /homepages/5/d759942488/htdocs/osg/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#31 /homepages/5/d759942488/htdocs/osg/public/index.php(53): Illuminate\Foundation

**Comment by chriskonnertz** [comment]
Hello,

> sorry for my english i'm french

No problem! :) 

> after clicking on "installation" y have an error 500 ;(

a) Check the database credentials in `storage/app/database.ini? . Fix them if they are wrong. Then try again to install Contebtify.

b) Do you use the "developer version" by cloning it from GitHub? If so, I recommend that you try the `2.6-dev` branch, because it has some bug fixes for the installer.

**Comment by darksidefr** [comment]
hello i use the 2.5 download on your website

**Comment by chriskonnertz** [comment]
Ok yes it has some small but very annoying bugs in the installation script. 

Did you try it again after it failed the first time? If not, please try again, due to a bug with saving the database credentials sometimes itonly works at the second try.

**Comment by darksidefr** [comment]
In fact I can not even install, I run install.php all and green when I click on install I have an error page 500
https://www.team-osg.fr

**Comment by chriskonnertz** [comment]
Ah okay, looks like there is a mistake in `/..../htdocs/osg/storage/app/database.ini`. Please copy and paste it here. But of course, remove your MySQL password. ;)

**Comment by darksidefr** [comment]
; Auto-generated file with database connection settings.
; See config/database.php for more settings.

host = db759946410.hosting-data.io
database = db759946410
username = dbo759946410
password = ****

**Comment by chriskonnertz** [comment]
Ah okay, please try to add `"`, similar to this example:

```
; Auto-generated file with database connection settings.
; See config/database.php for more settings.

host = "db759946410.hosting-data.io"
database = "db759946410"
username = "dbo759946410"
password = "****"
```

**Comment by chriskonnertz** [comment]
In general, you might try to use a password without special chars. They might cause trouble.
