### ISSUE TITLE
ErrorException set_time_limit () a été désactivé pour des raisons de sécurité

### ISSUE THREAD

**Issue by darksidefr** [Contentify/Contentify#448]
Hello,
Another problem with another hoster :( 
i have and error at the step=4 : ErrorException
set_time_limit () a été désactivé pour des raisons de sécurité

i contact my hoster he say to me the limit it fix at 15 sec, how do change in Contentify for work it ?
Thank

**Comment by chriskonnertz** [comment]
Hi,

well it seems like this is the code that causes the error: https://github.com/Contentify/Contentify/blob/2.6-dev/contentify/Controllers/InstallController.php#L324
But I wonder why? There are a bunch of checks that are performed to avoid issues with permissions.

I'll try to figure out why you get this error message anyway.

**Comment by chriskonnertz** [comment]
> i contact my hoster he say to me the limit it fix at 15 sec, how do change in Contentify for work it ?
Thank

Did they tell you *how* they deactivated it?

**Comment by darksidefr** [comment]
hello, my hoster don't accept the modification, i say to me time limit is fixed to 15 sec :'(

**Comment by darksidefr** [comment]
can u say me the code for fix limit to 15 sec to time_limit ?

**Comment by chriskonnertz** [comment]
> hello, my hoster don't accept the modification, i say to me time limit is fixed to 15 sec :'(

That's okay, even though 15 seconds is pretty short, 30 is the default value.

> can u say me the code for fix limit to 15 sec to time_limit ?

=> https://github.com/Contentify/Contentify/blob/v2.5/contentify/Controllers/InstallController.php#L305

Change `set_time_limit(self::MAX_TIME_LIMIT);` to `#set_time_limit(self::MAX_TIME_LIMIT);` or just delete the whole line.

But if the ins tallation needs more than 15 seconds, it will fail, of course. So I hope your hoster uses fast SSD disks etc. :P

**Comment by chriskonnertz** [comment]
Closing this, because I have no idea how to solve the initial issue (the exception).
