### ISSUE TITLE
ErrorException in UpdateUser.php line 81:

### ISSUE THREAD

**Issue by GenDorMetie** [Contentify/Contentify#45]
Trying to get property of non-object
in UpdateUser.php line 81
at HandleExceptions->handleError('8', 'Trying to get property of non-object', '/var/www/contentify/Middleware/UpdateUser.php', '81', array('request' => object(Request), 'next' => object(Closure), 'today' => '1457609745', 'isNewVisitor' => false, 'lastActive' => '1457609711')) in UpdateUser.php line 81

Whats the problem? And thanks for answer of this good cms :)

**Comment by GenDorMetie** [comment]
One more bug:

@if (user()->countMessages() > 0)

Call to undefined method Illuminate\Database\Query\Builder::countMessages() (View: /var/www/app/Modules/Auth/Resources/Views/widget_logged_in.blade.php) (View: /var/www/app/Modules/Auth/Resources/Views/widget_logged_in.blade.php)

**Comment by chriskonnertz** [comment]
Hey,

which version do you use? You find it in `config/app.php` (somewhere around line 38).

**Comment by GenDorMetie** [comment]
Hi, thanks for answer.     'version' => '1.1.0',

**Comment by GenDorMetie** [comment]
That bug started, then i loaded command: php artisan vendor:publish

**Comment by chriskonnertz** [comment]
Solution:
Delete `config/cartalyst.sentry.php`

Explanation:
The artisan `publish` command creates this file. But that file already exist, just with another name: `config/cartalyst/sentry.php`. Obviously the new file overwirtes the settings from the old and that causes the error.

So if you have to use the `publish` command not only once an even better solution is to copy `config/cartalyst/sentry.php` to `config/cartalyst.sentry.php`.

**Comment by chriskonnertz** [comment]
PS: My second proposal is better.

(Also added this change to thegit repo: https://github.com/Contentify/Contentify/commit/631ba0fd2cd7b928cbb32bedfd856725dc1b9441 )

**Comment by GenDorMetie** [comment]
Thanks for answer. But then  i changed sentry file, now (user()->countMessages() > 0) not showing anything.

**Comment by chriskonnertz** [comment]
Did you try both of my suggestions?

**Comment by GenDorMetie** [comment]
Sorry, my fail. Everythings working fine now. Thanks! :)

**Comment by chriskonnertz** [comment]
Ok fine! :)
