### ISSUE TITLE
[Official] Contentify 3

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#451]
The focus of v3 will be technical. It will not have many/big new features. It is very important to keep this CMS up-to-date from a technical point of view.

**Schedule**:
Start of development: Early 2019
Release: Early June 2019
**Feature List:**

- [x] Laravel 5.5 (requires PHP 7, has LTS)
- [x] Full support of PHP 7 (types etc.), PHP 7.0 becoming the minimal supported PHP version
- [x] New image system (hashed paths etc.)
- [ ] ~Stand-alone file uploader class~ -> Later
- [ ] ~jQuery v3~ -> Later
- [x] General Refactoring (template inheritation + sections, events, module decoupling, ...)

**Ideas List:**

- [x] Add (runtime) events
- ~Custom style for check boxes and radio buttons~ In 3.1
- ~Add iCalendar support for events in the frontend and backend ( https://en.wikipedia.org/wiki/ICalendar )~ Sure - but not in 3.0
- ~Bootstrap 4~ No. We have to move this to Contentify 3.1 + Laravel 5.6, because Laravel 5.5 does not seem to support Bootstrap 4, see https://laravel.com/docs/5.6/upgrade section "Pagination"
- ~Use markdown in comments and forum posts~ Absolutely no. This has no priority.
- ~Color adjustment? # 32c5d2 / # 13b1cd ...~ No, let's keep the current color scheme.
- ~Form builder? (Text area with/without  WYSIWYG, simple text fields, check/radioboxes, file upload)~ Not in this version. Maybe in 3.1 or 3.2...
- ~Add game server API ( https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Protocol.php )~ Not in 3.0
- ~Add more logins (FB, Twitch?)~ Not in 3.0. Will be done with https://socialiteproviders.netlify.com/about.html
- ~New theme ("Deimos") with a bright (white) body area~ Not in 3.0

**Layouter**

The "layouter" (this is just a code name) is the next big thing in the Contentify universe. Let's assume you want to create a new custom page for your website. Then the pages module is the tool of your choice. To create a new page you would use the integrated WYSIWYG editor (CKEditor). It works. However, you are very limited by the features of the editor. The editor isn't meant to truly support the unique features of Contentify and it also isn't meant to 100% integrate into a CMS. Plus usability isn't too great. The content builder is meant to actually layout and style pages and to unleash the power of Contentify. For example, this means that you will be able to add Contentify's widgets to your page. With UX and mobile devices in mind. Since this is a very big feature we will roll it out in several steps. 

Or with other words: It's similar to the new editor of WordPress, which they call "Gutenberg" ( https://de.wordpress.org/gutenberg/ ) and to "Bard" of Statamic ( https://statamic.com/blog/statamic-2.11 ).

Note: Check if we should use Vue.js to build this.

**_Update_**: It might be possible to integrate Gutenberg.

**Related:**
- Old C3 issue: https://github.com/Contentify/Contentify/issues/234
- 2.6 issue: https://github.com/Contentify/Contentify/issues/450

**Comment by mrc4tt** [comment]
FB, Twitch, Steam, GitHub e.g ;) for "logins" ^^

**Comment by kamohy** [comment]
Steam is aktive

**Comment by kamohy** [comment]
Twitter wär ganz nett 


eine andere idee
Forumsränge, oldshool ohne ende
aber, abhängig von der anzahl der post‘s hat man halt forenränge.

is halt nur eine idee

**Comment by lukasmk87** [comment]
Moin Chris,
ist der Zeitpunkt noch realistisch?
> Release: Early May 2019

**Comment by chriskonnertz** [comment]
Hi,

vom heutigen Stand ausgesehen recht realistisch, ja. Das ist nämlich nicht mehr der ursprüngliche Zeitpunkt, der wurde bereit etwas nach hinten verlegt.  Es fehlt aber eigentlich auch nicht mehr so viel, einiges wurde erst mal raus genommen aus der 3.0 und wird später kommen.

**Comment by lukasmk87** [comment]
Cool,
ich werde dann drauf warten bevor wir uns Verein das Grundgerüst packen und dann weiterbauen. Werden dann unsere Sachen auch gerne zur Verfügung stellen.

**Comment by chriskonnertz** [comment]
Hi,

wird sich nun doch etwas verzögern, auf Anfang Juni.

**Comment by chriskonnertz** [comment]
**Status update:** 
- Two of the three open taks of the to-do-list are still almost complete, the jQuery 3 Task is the only one that is actually incomplete. 
- So the plan is to have a release candidate afternext weekend (third of June) and then a final version one week later (10th of  june).
- To achieve this some less improtant features will not be implemented in 3.0 but in later versions

**Comment by chriskonnertz** [comment]
@MikkelDK 

> FB, Twitch, Steam, GitHub e.g ;) for "logins" ^^

Yes this is on the schedule (not for 3.0 any more but it will be implemented in the future). There is a cool library for Laravel (a [Socialite extension](https://socialiteproviders.netlify.com/about.html)) that we can use and that has all of these logins built-in, also others such as Google and Discord. With this library is should be very easy to integrate and maintain all relevant login variants. :tada:

**Comment by stanginator** [comment]
ciao riscontro alcuni problemi puoi aiutarmi? 
Quando inserisco un risultato nel Cups brackets mi dice Undefined variable: left

**Comment by kamohy** [comment]
Vorschläge die umgesetzt werden könnten.

1. Das Logo -> Im Config bereich sollte man das ändern können, das machts einfacher und würde über di DB gesteuert werden können. (bei einem Update könnte es somit nicht überspielt werden)

2. Infomailer -> das hatte ich schonmal vorgeschlagen, als möglichkeit für Admins emails zu versenden an alle user

3. blocklist 

- man sollte eine wildcard einsetzen, diese sperrt nicht nur domains sondern auch subdomains
- man sollte auch einzelne emails sperren können (leider nicht möglich) 
man kann aber nicht gmail.com / t-online komplett sperren wenn ein user dort seine mail hat is das schon kacke
- Schlagworte sperren -> gern genutzt: viagra

4. Captcha erneuern auf v3
