### ISSUE TITLE
[Feature] Languages editor

### ISSUE THREAD

**Issue by mrc4tt** [Contentify/Contentify#452]
it could be nice. if there is a "Language Editor" for edit the "english language" to own language (as example) i'm working to language "Danish" ;) 

But i don't know, which files needed to be "translated" ^^

Maybe you can help: @chriskonnertz

**Comment by chriskonnertz** [comment]
Hello,

> it could be nice. if there is a "Language Editor" 

You are right. That's why we have developed such a tool. :)

https://github.com/chriskonnertz/translation-factory

But to be honest it's not so well tested and I do not know if it works well with Contentify 2.5.

> But i don't know, which files needed to be "translated" ^^

=> https://github.com/Contentify/Contentify/wiki/Localisation---Translation#add-more-languages

**Comment by mrc4tt** [comment]
@chriskonnertz cool to hear! ;)

I will working on the Danish language! :-D 

Is there anything to be aware of. regarding the new version possibly 2.6?

**Comment by chriskonnertz** [comment]
> I will working on the Danish language! :-D

Nice!!

> there anything to be aware of. regarding the new version possibly 2.6?

Well, yes, 2.6 will have some new translations so if you use 2.6 as the base for your work it would be awesome.

**Comment by mrc4tt** [comment]
> Well, yes, 2.6 will have some new translations so if you use 2.6 as the base for your work it would be awesome.

I will try do.

Maybe i can use the translation-factory? on the 2.6 version?

**Comment by mrc4tt** [comment]
Hey @chriskonnertz i can't getting translation-factory to works..... it dont supporting https.
