### ISSUE TITLE
Login funktioniert nicht in Webseite

### ISSUE THREAD

**Issue by Unclesam1970** [Contentify/Contentify#453]
Hallo Zusammen!
Hoffe es kann mir hier jemand helfen!
Ich habe die aktuelle Contentify Version 2.5 installiert und seid Tagen funktioniert eigentlich alles Prima.
Aber seid heute kann ich mich nicht mehr einloggen in die Webseite. Es erscheint dann folgende Fehlermeldung:

**ERROR
Sorry, something bad happened. Our website has crashed.

Don't worry, we will handle this. In the meantime, make a cup of coffee. And stop crushing our website!**

Da ich die Seite noch am bearbeiten/gestalten war, hatte ich bis jetzt keine htaccess Datei erstellt und so zeigte die Domain auf den /public Ordner. Das habe ich jetzt geändert und die Seite funktioniert nunmehr auch über die tatsächliche Domain:

http://www.noobs-unlimited.de

Aber weder ich, noch ein 2 angelegter Account können uns jetzt einloggen.
Vielleicht weiss jemand Rat von euch. Aber Achtung....bin Hobby Installierer und Programmierer ;)

LG und Danke vorab !

**Comment by kamohy** [comment]
um den fehler zufinden, altiviere mal den debug modus.
dann zeigt er dir statt *website has a crash

einen fehlerbericht

**Comment by Unclesam1970** [comment]
Hallo! Danke erstmal für Antwort:

Hier der Debug Bericht:


(1/1) TokenMismatchException
--
in VerifyCsrfToken.php (line 29)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HttpsRedirect.php (line 33)
at HttpsRedirect->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

**Comment by kamohy** [comment]
okay folgendes: ftp öffnen -> gehe in -> storage/framework -> nun in folgende ordner nacheinander: cache (alles darin löschen) dann: session (auch alles löschen)
und views: auch hier nochmal alles löschen

dann ruft ihr im browser eure seite neu auf
(kann etwas dauern beim ersten mal)

und testet ob ihr euch wieder einlogen könnt
wenn ja super und debug-modus wieder deaktivieren

**Comment by Unclesam1970** [comment]
Alles ausgeführt...geht immer noch nicht ;(
Fehlerausgabe ist die selbe

**Comment by kamohy** [comment]
okay hab gerade mal neu nachgelesen bei dir
probier mal folgendes bei dir
in deinem browser löschst du bitte mal cache und cookies
(kein F5 oder STRG+F5)

dann versuch es nochmal

**Comment by Unclesam1970** [comment]
Habe ich auch gerade versucht und zusätzlich mit 2 weiteren Browsern. Immer der selbe Fehler

**Comment by kamohy** [comment]
was habt ihr zuletzt verändert ?
weil ich nu überfragt bin

**Comment by Unclesam1970** [comment]
Eigentlich seid dem letzten Login nichts. Ich war danach noch ein paar mal im Backend und auf der Seite. Gestern auch noch ...eingeloogt und alles ging.
Seid heute der Fehler

**Comment by Unclesam1970** [comment]
Frage mich langsam ob es ein Server Fehler ist vom Anbieter! Aber da kann wohl nur der CMS Entwickler selber was zu sagen. Aber trotzdem danke für deine Tips

**Comment by kamohy** [comment]
hab mal ne andere frage
schau mal nach welche rechte die ordner unter storage/framework/ haben
diese sollten in der regel 777 haben
wenn die, die falschen rechte haben kann auch sowas passieren

-> cache
-> views
-> sessions 

diese drei überprüfen

**Comment by chriskonnertz** [comment]
Welche Version nutzt ihr denn? Es gab mal in älteren Versionen Probleme beim Login, wobei die eigentlich auch sich durch andere Symptome äußerten... naja trotzdem bitte mal nachschauen. Z. B. einloggen -> Backend -> runter scrollen im Footer steht die Version.

TokenMismatchException kann wie schon gesagt wurde was mit Cache im Browser oder Server zu tun haben - aber die habt ihr ja geleert. Habt ihr was an den Config-Dateiein im Config-Ordner geändert? Z. B. App Key geändert? Daran könnte es _vielleicht_ auch liegen.

Einfach so ohne irgendein auslösendes Ereignis kann das eigentlich nicht passiert sein. Irgend was muss eigentlich geschehen sein... Einstellungen verändert, Version geupdated, Rechte verändert, Code verändert, irgendwas...

**Comment by kamohy** [comment]
>  naja trotzdem bitte mal nachschauen. Z. B. enloggen -> Backend -> runter scrollen im Footer steht die Version.

Ich mag dein Humor :-)

**Comment by chriskonnertz** [comment]
Ok, ungünstig ausgedrückt. 
a) Einen Account nehmen der noch eingeloggt ist (weil Cookie und so)
b) oder in die Config-Datei `config/app.php` gehen und schauen was dort bei "version" gesetzt ist.
c) In die DB gehen (z. B. mit phpMyAdmin) und in der config Tabelle nachschauen

**Comment by Unclesam1970** [comment]
Hi!
Also alle Ordner haben die Rechte 777.
Zusätzlich nochmal alle gelöscht...Browser Cache geleert.....selbe Problem!
Die Version ist die V2.5 !Habe die letzte Woche erst von der Page gezogen.
Das einzige was ich geändert habe, ist einen User angelegt mit SuperUser Rechten...sonst nichts. Und PNG Logo auf der Index Seite oben (Contentify) geändert.

Wenn ich in die Datenbank schaue, dann haben alle User ( auch die SuperUser) Permission NULL.
Ist das richtig?

Tja wie gesagt...sonst nichts geändert oder an einer Config rumgefummelt.
Was ich mitlerweile recherchiert habe, ist wenn dieser Fehler auftaucht dann ist es augenscheinlich ein Laravel Fehler!
Siehe Artikel hier:
https://laravel.io/forum/01-30-2015-laravel5-tokenmismatchexception-in-verifycsrftoken

**Comment by kamohy** [comment]
haste auch sämtliche cookies vom browser gelöscht?

das hatte ich mal 🤔

**Comment by chriskonnertz** [comment]
> Die Version ist die V2.5 !Habe die letzte Woche erst von der Page gezogen.

Hm okay das müsste dann passen, in de 2.6-dev hat sich dahingehen meiner Erinnerung nach nichts geändert.

**Comment by chriskonnertz** [comment]
>  dann ist es augenscheinlich ein Laravel Fehler!
> Siehe Artikel hier:
> https://laravel.io/forum/01-30-2015-laravel5-tokenmismatchexception-in-verifycsrftoken

Ist vermutlich kein Laravel Fehler im eigentlichen Sinne, nach dem Motto dass im Laravel Code ein Fehler gemacht wurde.

Was mir da aber noch einfällt: 

- Die Sessions werden im Ordner storage/cache/sessions gespeichert, die nochmal explizit löschen und schauen dass die Dateien wirklich auch weg sind
- Noch mal Schreibrechte CHMOD 777 auf den Ordner geben. Da vertut man sich schon mal, geht mit CHMOD 777 auf den cache Ordner los und vergisst anzugeben dass es rekursiv auch auf die Unterordner angewendet werden soll.
- In der `config/app.php` den `url`-Wert angepasst? https://github.com/Contentify/Contentify/blob/2.5/config/app.php#L65
- Eine Sache über die sie da in dem Thread diskutieren ist die Zeitzone, ja die könntest du mal überprüfen wobei das ohne ins Backend zu gehen etwas hakelig sein könnte.

**Comment by Unclesam1970** [comment]
Bis auf die Zeitzone alles ausprobiert....jedoch ohne Erfolg.
Ich könnte es ja neu installieren, aber wer sagt mir das der Fehler nach ein paar Tagen nicht wieder da ist?
Hat ja jetzt auch einwandfrei erst funktioniert und erst seid vorgestern geht es aus heiterem Himmel nicht mehr !

**Comment by kamohy** [comment]
Also, was ich vorschlagen kann:
ich wollt mir gerade eure seite noch einmal ansehen...
Leider sehe ich dort kein contentify mehr :-/

Schade, denn das system ist wirklich genial :-/

**Comment by chriskonnertz** [comment]
Hat sch dann vermutlich (leider) erledigt. :(
