### ISSUE TITLE
Error modules admin panel

### ISSUE THREAD

**Issue by jopa50** [Contentify/Contentify#455]
Hello, I'm still working on this cms.
But currently I have a problem with the administration panel.
In WEBSITE -> Modules
I have this displayed:
```
ERROR
Sorry, something bad happened. Our website has crashed.

Do not worry, we will handle this. In the meantime, make a cup of coffee. And stop crushing our website!
```

In the log I have this:
`production.ERROR: ErrorException: Undefined index: slug in /var/www/html/contentify/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1563`

Thanks for your help

**Comment by jopa50** [comment]
Hello, problem solved with php composer.phar install

**Comment by chriskonnertz** [comment]
Great to hear! :)
