### ISSUE TITLE
app.key

### ISSUE THREAD

**Issue by jopa50** [Contentify/Contentify#456]
Hello, always on this cms. I have a question can be silly.
But in my admin / diag
I have `App.key Default development key, you have to change it!`

What is the procedure for replacing it?

Thanks for your help.

**Comment by chriskonnertz** [comment]
Hello,

you may change the application key by editing the file `config/app.php` with a text editor. 

However I am not sure if this a good idea *after* installing the CMS. I will investigate and let you know what I learn.

**Comment by jopa50** [comment]
Yes I change a number that makes the site crash

**Comment by roachy** [comment]
I don’t think you are supposed to change the app.key as it is set when the CMS is installed

**Comment by chriskonnertz** [comment]
> Yes I change a number that makes the site crash

I recommend to clear the cache ( [manually](https://github.com/Contentify/Contentify/wiki/FAQ#how-can-i-clear-the-cache) ).

**Comment by jopa50** [comment]
Actually it works better, thanks again problem solved.

**Comment by chriskonnertz** [comment]
Great!

But since this caused you trouble I believe it is a good idea to set this key automatically. I have created a new issue to remind me to implement this: https://github.com/Contentify/Contentify/issues/463
