### ISSUE TITLE
Disabling modules

### ISSUE THREAD

**Issue by udarmolota** [Contentify/Contentify#457]
Hello.
I have the same question as it here, but I didn't find the answer:
https://github.com/Contentify/Contentify/issues/210#event-1243897376
Is there any way to disable some modules from the backend admin page? I see there is Modules page, I have super admin user but I don't have the ability to disable modules that I don't need, like: **Forums** for example. Can I do it somehow without opening the source code?

**Comment by jopa50** [comment]
Hello, you can hide the forums module which is in your menu via this page:
\ Contentify \ app \ Modules \ yourtheme \ Resources \ Views \ layout.blade.php

line: <li> {!! link_to ('forums', trans ('app.object_forums')) !!} </ li> as an example
<! -- <li> {!! link_to ('forums', trans ('app.object_forums')) !!} </ li> -->

Waiting for a more concrete answer from Chris Konnertz

**Comment by chriskonnertz** [comment]
> Is there any way to disable some modules from the backend admin page

Hello, no, not at the moment. Disabling modules is a feature that is planned to be implemented in the future. (Altough not in the near future.)

If you want to hide them from the admin navigation, you may open the `module.json`of the module, for example `app/Modules/Cups/module.json` and delete the "admin-nav" entry.

**Before**:

```
{
    "slug": "Cups",
    "search": ["cups", "teams"],
    "admin-nav": [
        {
            "url": "admin/cups",
            "icon": "share-alt",
            "category": 3
        }
    ]
}

```
**After**:

```
{
    "slug": "Cups",
    "search": ["cups", "teams"]
}
```

Afterwards clear the cache to enforce re-building of the admin panel navigation.

For the frontend, take a look at the suggestion of jopa50. :)
