### ISSUE TITLE
Small bug & question

### ISSUE THREAD

**Issue by porphyryr** [Contentify/Contentify#46]
Hello,

I recently discovered a small bug when you click for example on "Galleries" and than click on the Contentify logo at the top to go back to the home page, the navigation bar does not change the blue underline and stays on Galleries when on the home page.

I also got the password reset and contact form working with smtp but when clicking on 'Send' the page waits for the mail to be sent which takes like 3 seconds, Do you have any idea what would be the best way to make this asynchronous?

Thank you in advance!

**Comment by chriskonnertz** [comment]
Hello,

1. open this file: `public/vendor/contentify/frontend.js` and replace its content with this:
https://gist.github.com/chriskonnertz/2899629644af05a4592c

2. Unfortunately no. One way to make it asynchronous would be a cron job that starts a PHP script that sends the email. However this would cause an increased delay until the email is sent. Depending on the cron job a minute or more.

**Comment by porphyryr** [comment]
Thank you!
