### ISSUE TITLE
How to add header banner?

### ISSUE THREAD

**Issue by rozemek** [Contentify/Contentify#460]
How can i add a header banner? I tryed installing all your releases from 2.0 to the newest one and in none of them there is a HEADER BANNER the big big banner . How can i add it? Please help...

**Comment by rozemek** [comment]
hello?

**Comment by chriskonnertz** [comment]
Hello,

do you mean  the logo in the header?

**Comment by rozemek** [comment]
yes

**Comment by rozemek** [comment]
i want that sliding banner like you have on your demo website but i don't know how to get it. My website has totally no banner after installing

**Comment by chriskonnertz** [comment]
1) Header logo: Replace this image: `public/img/header_logo.png`
2) Slider: It **is** there but since you did not create any slides it is not displayed. Log into your account, go to the backend (admin control panel), then go to "slides" and create a new slider.

**Comment by rozemek** [comment]
may i upload the new 2.6 version and do it there ?

**Comment by chriskonnertz** [comment]
Well, yes, it's pretty stable I think, so actually you may use the 2.6 version, even though it's still under development (but nothing is broken so that's not a problem). 

**But**: Currently there is only the developer edition available so you would have to run `composer install`. If you have no experience with website development / server administration I'd recommend you stick to 2.5.

**Comment by rozemek** [comment]
And can i use any plugins from any other cms? Or i have to make them?

**Comment by rozemek** [comment]
Oh and where is the main template ? i would like to edit it like change the design

**Comment by chriskonnertz** [comment]
> And can i use any plugins from any other cms? Or i have to make them?

Most likely you cannot use plugins from other plugins. However, you can use stuff that is made for the Laravel framework, because Contentify is built upon Laravel.

**Comment by chriskonnertz** [comment]
> Oh and where is the main template ? i would like to edit it like change the design

=> `app/Modules/MorpheusTheme/Resources` 
(`app/Modules/MorpheusTheme/Resources/Views/layout.blade.php` = template,  `app/Modules/MorpheusTheme/Resources/Assets/less/frontend.less` = CSS code  )

**Comment by rozemek** [comment]
Can i just use bootstrap templates to implement your cms into them or do i need to use laravel templates?

**Comment by chriskonnertz** [comment]
Contentify uses Bootstrap 3, so yes, Bootstrap 3 themes are compatible.

**Comment by rozemek** [comment]
Chris. One more question. Would You be able to create some plugins if i’d pay for them? Good money! :D :)

**Comment by rozemek** [comment]
Thanke You! Danke!

**Comment by chriskonnertz** [comment]
You are welcome :)
