### ISSUE TITLE
Adding icon to links in menu

### ISSUE THREAD

**Issue by rozemek** [Contentify/Contentify#461]
Hey again. If i would like to add a bootstrap icon next to a link in a user profile menu like for instance fa fa icon next to this link : 
    <li>{!! link_to('users/'.user()->id.'/edit', trans('app.edit_profile')) !!}</li>
I would like to add a fas fas users icon next to edit profile link

Question 2
How can I add another form of avatar? I would like to add a possibility for a user to upload his background image to a his team profile just like om facebook you can upload a bacground photo to your profile. I understand the php language a little bit but would anyone just help me with where to add it or how to add it?

**Comment by chriskonnertz** [comment]
Hello,

>  If i would like to add a bootstrap icon

Function ( https://github.com/Contentify/Contentify/blob/2.5/contentify/HtmlBuilder.php#L377 ) :
`function fontIcon($icon, $color = null, $class = null, $category = null)`


Example:
`{!! HTML::fontIcon('star') !!}`

Or maybe what you are looking for is this function:
`function iconLink($icon, $title, $url, $showTitle = false, $attributes = array())`

=> https://github.com/Contentify/Contentify/blob/2.5/contentify/HtmlBuilder.php#L377

Ofcourse you can write good old plain HTML code as well.

>  I would like to add a possibility for a user to upload his background image to a his team profile

Do you want the user to be able to upload the background image to the **team** profile or **user** profile?

**Comment by rozemek** [comment]
Both team and profile.

2 more questions. I’m sorry im asking but i’m creating themes for your cms so later i can share them as i really appreciate your work and i would like to help you by adding themes so your cms community will be huge!!
So my question is how to add notifications for a team that has a match in a cup/tournament. For example they are in a team bracket and they have an opponent . I would like the system to jnform them they have a match now .

Another question
How can i add a possibility for a team to upload files like screenshot or a zip file to a specific match.
For example a team played a match and finished it so they go to the page where they had their match and upload files to that specific match with screenshots from the match.

And one more :D
Is there any ready script that lets the teams ban maps? Like a team and their opposite team bans maps and the left 3 last maps are the maps they will play. By saying ban i mean they have the possibility to choose which map they want to ban and then it will be the opposite team choice to ban the next map and then the teams choice to ban the next map etc..

**Comment by chriskonnertz** [comment]
> Both team and profile.

Well you have to add a new field to the `Contentify\Model\User(.php)` model and to the  ` App\Modules\Teams\Team(.php)` model. This means you have to create a new column in the database tables (`users` and `teams`). Also you have to register the attributes fillable in the model files, which means you have to add their names to the `$fileHandling` array. THen you have to create a fiel upload form field in the templates (`app/Modules/Users/Resources/form.blade.php` and `app/Modules/Teams/Resources/form.blade.php`). I recommend to simply copy+paste+modify code from the existing form fields.

> I’m sorry im asking but i’

No problem.

> i really appreciate your work

Thank you! :)


> So my question is how to add notifications for a team that has a match in a cup/tournament. For example they are in a team bracket and they have an opponent . I would like the system to jnform them they have a match now .

Maybe something like this (**not tested!**):
```php
if (user()) { # Ensure user is logged in
    $cups = $cup->cupsByUser(user(), true); # Get open cups of current user
    foreach($cups as $cup) {
        $cacheKey = 'cups::match_essage'.user()->id; # Build invidual key to create item in cache
        $sentMessage = \Cache::get($cacheKey); # Check if already snt message
        if (! $sentMessage and $cup->start_at >= time()) { # If msg not yet sent and cup has started
             $user->sendSystemMessage('New match', 'You have a new match now!'); # send msg
              # https://github.com/Contentify/Contentify/blob/v2.5/contentify/Models/User.php#L325
             \Cache::forever($cacheKey, true); # Save in cache that we sent a msg
        }
    }
}
```

> How can i add a possibility for a team to upload files like screenshot or a zip file to a specific match.

Similar to how you implement uploading another image.

> Is there any ready script that lets the teams ban maps? 

Nope.
