### ISSUE TITLE
wie installiere ich Contentify

### ISSUE THREAD

**Issue by Fear2706** [Contentify/Contentify#462]
Guten Tag, ich habe grade dieses CMS gefunden und wollte es gerne mal teste. 

Bei mir läuft froxlor mit nginx
Php 7.2

ich habe die Daten auf mein FTP hochgeladen. Die Daten habe ich direkt über ihre seite runtergeladen. 
Wenn ich aber den installer starten möchte  mit "DOMAIN/public/install.php"

Steht bei mir alles im Grün und unten drücke ich dann auf "Launch Installer"

wenn ich drauf drücke ändert sich oben der Link in "DOMAIN/public/install" 
und die meldung "404 Not Found"

Was mach ich grade falsch?

Danke für eure Hilfe

**Comment by jopa50** [comment]
HALLO, VERSUCHEN KANN EINE DATEI 777 MODUS UND DATEI sein.

**Comment by Fear2706** [comment]
Bitte was?

**Comment by jopa50** [comment]
Versuchen Sie, die in 777 installierten chmod-Dateien über Ihren FTP-Client zu installieren.

**Comment by chriskonnertz** [comment]
Hallo,

das wurde wohl maschinell übersetzt.
Er meint du sollst schauen ob die Berechtigungen für die Ordner (und Unterordner) auf 777 steht.

**Comment by Fear2706** [comment]
Welche Ordner müssen den alle 777 haben?

Die hier haben alle von mir 777 bekommen. Stand so in der Anleitung im wiki

/storage
/bootstrap/cache
/public/uploads
/public/share
/public/rss

**Comment by chriskonnertz** [comment]
Auch rekursiv? Also auch alle Unterordner?

**Comment by Fear2706** [comment]
diese Ordner 

/storage
/bootstrap/cache
/public/uploads
/public/share
/public/rss 


und alle Unterordner haben jetzt 777 bekommen. Leider noch der selbe fehler


![ok](https://user-images.githubusercontent.com/43447701/49340597-6d7d4200-f642-11e8-8fc7-5a4d9092097a.PNG)

**Comment by chriskonnertz** [comment]
> wenn ich drauf drücke ändert sich oben der Link in "DOMAIN/public/install"
> und die meldung "404 Not Found"
> 
> Was mach ich grade falsch?

Ich habe mit Nginx leider kaum praktische Erfahrungen. Bei Apache würde das jetzt auf ein Problem mit dem Rewriting (Umschreiben) der URLs hindeuten. Die URL "DOMAIN/public/install" gibt es ja nicht wirklic, das ist eine virtuelle URL die es nicht direkt als Ordner gibt (den Ordner "public" gibt es aber der hat keine Unterordner namens "install".

Contentify baut auf dem PHP-Framework Laravel auf und das kümmert sich auch um das Routing (= die virtuellen URLs). Daher würde ich so vorgehen, dass ich nach Tutorials in Zusammenhang von Laravel und Nginx suche. Beispiel: https://www.digitalocean.com/community/tutorials/how-to-deploy-a-laravel-application-with-nginx-on-ubuntu-16-04#step-5-—-configuring-nginx

Vielleicht findest du so eine Lösung.

Ansonsten, falls du die Wahl hast: Apache. Ich halt es für eher unwahrscheinlich, dass du die bessere Performance von Nginx wirklich benötigst.
