### ISSUE TITLE
Todo: Set App.key to random value

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#463]
Set the app.key config value to a random value when installing the CMS to improve security and avoid problems when changing the key later on.

Idea: Do not try to write the key in the config file but to write it to another location (.ini, env?) and then just load it in the config file.

**Comment by jopa50** [comment]
Can we have an example please?

**Comment by chriskonnertz** [comment]
Hi, this issue is just a reminder for me. I will implement this in the future.

So the idea is no to hard-code the key in the config: https://github.com/Contentify/Contentify/blob/v2.5/config/app.php#L143
Because this cannot be done by the installer of the CMS. But I want the isntaller to set the key. So one idea is to store it in a .ini file similar to the `storage/app/database.ini`. The other idea is to use an enviroment variable: https://github.com/Contentify/Contentify/blob/v2.5/.env.example#L3

**Comment by funtimeerror** [comment]
To be handled via #493 ?
Trying to go thru all the active issues to see what’s needed :)

**Comment by chriskonnertz** [comment]
Hi yes you are right this issue here is kinda obsolete.

(Note that if you think about writing code for the CM/S you might consider to start with the alpha tag of v3.0.)
