### ISSUE TITLE
ToDo: Add links to frontend pages in the backend

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#467]
In the admin control panel ( = backend), add links to the overview pages of the modules in the frontend. We already have links to specific content items. For example in the teams module the teams in the backend teams overview are linked to their pages in the frontend. However, there is no link to the frontend team overview page. 

Idea: Add a button in the top of the backend module overview page.

**Comment by chriskonnertz** [comment]
This has a very low priority right now, there are so many other ideas for improvements that have a higher benefit so I am closing this issue. 

Maybe this will be relevant in the future but not mid-term.

**Comment by torriz** [comment]
AND pages like 
![chrome_2019-03-14_15-21-00](https://user-images.githubusercontent.com/2656806/54364258-c8c0c680-466c-11e9-8451-ce12b4ecf7a1.png)
you should be able to just click the "News" part and get back to the "main" news part..
or add back arrows
