### ISSUE TITLE
Google indexing

### ISSUE THREAD

**Issue by jopa50** [Contentify/Contentify#470]
Hello, I work on the indexing of my site and the referencing of the site. currently i have a problem, google warned me that i have either a noindex or robots.txt that blocks this one.
So I watch the robots.txt, it does not block google. So I still have noindex would you have an idea where he can be?
thank you

**Comment by chriskonnertz** [comment]
Hello,

hm, no, I do not have any idea why this happens to your website. Neither noindex-tags nor the robots.txt should be a problem. There are no noindex-tags and the robots.txt is not disallowing anything.
