### ISSUE TITLE
Name under avatar (Team page)

### ISSUE THREAD

**Issue by porphyryr** [Contentify/Contentify#48]
Hello,

I currently use
`<a href="{!! url('users/'.$user->id.'/'.$user->slug) !!}"><img src="{!! $user->uploadPath().$user->image !!}" alt="{{ $user->title }}" style="max-width: 142px; max-height: 142px;"> {{ $user->username }}</a` in app/Modules/Teams/Resources/Views/index.blade.php & app/Modules/Teams/Resources/Views/show.blade.php to list the avatars from the players in the team page aswell. I wonder if it was possible to have these 5 avatars next to each other and the name under the avatar in the center for eacher player.

Thank you in advance for the help!
porphyryr

**Comment by chriskonnertz** [comment]
https://gist.github.com/chriskonnertz/db7716ce49d425eb60a8

**Comment by porphyryr** [comment]
> https://gist.github.com/chriskonnertz/db7716ce49d425eb60a8

Thank you that worked! I tried adjusting it manually in css before but that did not work out well :) this is a great solution

**Comment by chriskonnertz** [comment]
Ok cool :)
