### ISSUE TITLE
Website Crashes at "Pages" page

### ISSUE THREAD

**Issue by ExpertSunny** [Contentify/Contentify#482]
Hello! Whenever I try to open "Pages" from Admin-backend-->DAILY CONTENT-->Pages. I get the following error(attatched picture) in Debug mode. When I turn off Debug mode and try to access "Pages", the CMS crashes and I get the Crash page. I am using Contentify 2.6
![screenshot from 2018-12-28 20-15-38](https://user-images.githubusercontent.com/15859928/50518834-e35bb880-0add-11e9-9980-3dbc7ab20338.png)

**Comment by ExpertSunny** [comment]
Doing a fresh install of Contentify solved this problem. Maybe it was a fault of FTP. Sorry if I caused any inconvenience! I am closing this issue.
PS: Thanks for this wonderful, beautiful,open-source and powerful CMS!

**Comment by chriskonnertz** [comment]
Hello,

> Doing a fresh install of Contentify solved this problem. Maybe it was a fault of FTP

I'm glad this solved the issue! 

> Sorry if I caused any inconvenience! I am closing this issue.

No problem. But, one last question: You said you were using v2.6. Did you get 2.6 by installing a fresh copy or did you update from 2.5? I wonder if there might be a bug in the update from v2.5 to v2.6.

> PS: Thanks for this wonderful, beautiful,open-source and powerful CMS!

I'm glad you like it! :)

**Comment by ExpertSunny** [comment]
It was a fresh copy. I didn't update from 2.5. :-)

**Comment by chriskonnertz** [comment]
Ok, thanks.
