### ISSUE TITLE
Error by creating PERMANENT CONTENT

### ISSUE THREAD

**Issue by DoktorDuckyy** [Contentify/Contentify#487]
Hello,
always when i try to add PERMANENT CONTENT in the admin panel i get this error:

"preg_match(): Compilation failed: invalid range in character class at offset 1825"

Here is the full error log i get from the page

https://pastebin.com/fDKuHmJu

**Comment by chriskonnertz** [comment]
Hello,

the version of Contentify is 2.6? It seems you tried to create a new partner entry, is that correct?

**Comment by DoktorDuckyy** [comment]
Yes that´s correct.

**Comment by chriskonnertz** [comment]
Hallo,

ich antworte mal auf Deutsch. Ich versuche das Problem bei mir auf meinem System nachzustellen. An sich scheint das Speichern von Partnern nicht komplett kaputt zu sein, zumindest konnte ich jetzt einen neuen Eintrag erstellen. Besonders auch merkwürdig weil ich als URL "https://google.com" verwendet habe, so wie du ja laut Log auch.  

Ist das eine neue Installation des CMS oder ein Update? Die Meldung besagt wohl so in etwa ein Problem in dem regulären Ausdruck mit dem die eingegebene URL auf Gültigkeit geprüft wird. Komisch, weil eigentlich sollte ich genau den gleichen Ausdruck haben wie du - und bei mir klappt das.

Allerdings habe ich das jetzt gerade mit Version 3.0, die gerade in Entwicklung ist, getestet. Ich werde das noch mal mit 2.6 testen müssen. Vielleicht gab es da ein Problem mit der Validator-Variante das inzwischen behoben wurde. Naja wäre etwas überraschend aber einen anderen Erklärungsansatz habe ich gerade nicht. 

Als Übergangslösung könntest du das Validieren der URL ausbauen. Dazu die markierte Zeile löschen: https://github.com/Contentify/Contentify/blob/v2.6/app/Modules/Partners/Partner.php#L56 Allerdings ist anzunehmen, dass das auch andere Module betrifft bei denen URLs validiert werden, müsste also ggf. auch noch an anderen Stellen geändert werden.

**Comment by DoktorDuckyy** [comment]
Jo danke schon mal.
Werde ich mal versuchen

**Comment by chriskonnertz** [comment]
Ich mache hier mal zu, eine Quick-And-Dirty-Lösung für das Problem in v2.6 besteht ja und ich hoffe in 3.0 wird das Problem nicht mehr existieren.

**Comment by chriskonnertz** [comment]
**UPDATE**: Problem ist erneut aufgetreten und wurde von einem anderen User identifiziert: https://github.com/Contentify/Contentify/issues/420#issuecomment-473133623

Das ist ein Laravel-Problem, das Contentify 2.6 betrifft, in v3.0 vermutlich aber nicht mehr auftritt da dort eine neuere Laravel-Version eingesetzt wird.
