### ISSUE TITLE
I cant install Contentify sub directory.

### ISSUE THREAD

**Issue by powner1** [Contentify/Contentify#489]
Hey, I can install my localhost but when I try install my sub directory, cant find public url.

I trying; sitename.com/sub-directory/public but cant find anything. What can I do for fix it?

Sorry for my bad English.

P.S; Shared hosting.

Thank you.

**Comment by chriskonnertz** [comment]
Hello,

is URL rewriting (mod_rewrite) active on your (Apache) server?

**Comment by chriskonnertz** [comment]
Since you did not reply to my question I cannot provide any help.

So I am closing this issue.

Please create a new issue if this problem still exists.
