### ISSUE TITLE
Streams question and Galleries <h2> title bug

### ISSUE THREAD

**Issue by josephzigler** [Contentify/Contentify#49]
Hello,

I been attempting to change the code so it shows Online if viewers > 0 and Offline if viewers are <0 instead of the viewer count, but been failing so far and can't seem to get this working. I wonder if there is an easy way to change this without messing with too much code? 

I also noticed a small 'bug' with the `<h2>` gallery title on the Galleries page, the title does not seem to change to the color `#00AFFF` and is just white while the other pages their h2 titles are blue.

Thank you in advance for the help!

Regards,
Joseph

**Comment by chriskonnertz** [comment]
Hi

1.
Open `app/Modules/Streams/Resources/Views/StreamsWidget.php` and replace this line
`<span class="viewers">{!! $stream->viewers !!}</span>
with
`<span class="viewers">{!! $stream->viewers ? trans('app.online') : trans('app.offline') !!}</span>`

Then apply these changes (translation for 'offline'): https://github.com/Contentify/Contentify/commit/84b1147dc3e5a646bc2e16645fa70cc735f6ca08

2. Quick 'n dirty solution:
Replace
`<h2>{{ $gallery->title }}</h2>`
with
`<h2 style="color: #00AFFF">{{ $gallery->title }}</h2>`

**Comment by josephzigler** [comment]
> Quick 'n dirty solution: Replace `<h2>{{ $gallery->title }}</h2> with <h2 style="color: #00AFFF">{{ $gallery->title }}</h2>`

Thank you that worked!

> Open app/Modules/Streams/Resources/Views/StreamsWidget.php and replace this line
<span class="viewers">{!! $stream->viewers !!}</span> with {!! $stream->viewers ? trans('app.online') : trans('app.offline') !!}`

That worked aswell, but would it be possible to place it underneath instead of next of it? Here's example how it looks right now: http://imgur.com/TPIffOF

**Comment by chriskonnertz** [comment]
Maybe instead of
`{!! $stream->viewers ? trans('app.online') : trans('app.offline') !!}``
this:
`<br>{!! $stream->viewers ? trans('app.online') : trans('app.offline') !!}``

**Comment by josephzigler** [comment]
> Maybe instead of
{!! $stream->viewers ? trans('app.online') : trans('app.offline') !!}
this:
<br>{!! $stream->viewers ? trans('app.online') : trans('app.offline') !!}

That places it at the bottom like shown here:  http://imgur.com/V2tyqeE  I think this can be placed in the middle like on the demo page by adding padding inside the css? 

I'd also like to add green color for the Online text and red color for the Offline text, not sure how you can do this

> It works fine. That's just how it works. All exceptions (erros) will be logged in storage/logs/. You can also open this file in the CMS: Log in, go to the admin backend, then click on "Config", then on "Log File". (Click on a date/time to see the whole log entry.)

Ah I see, Thank you!

**Comment by chriskonnertz** [comment]
1. Maybe you have to wrap it like this:
<div class="text-center">{!! $stream->viewers ? trans('app.online') : trans('app.offline') !!}</div>

2. Try this:
{!! $stream->viewers ? '<span style="color: green">'.trans('app.online').'</span>' : '<span style="color: red">'.trans('app.offline').'</span>' !!}

**Comment by josephzigler** [comment]
> `<div>{!! $stream->viewers ? '<span style="color: green">'.trans('app.online').'</span>' : '<span style="color: red">'.trans('app.offline').'</span>' !!}</div>`

http://imgur.com/rD3K2QK Colors are working perfect now :) but would like the height to be tesame like the original

I tried  `<div>{!! $stream->viewers ? '<span style="color: green line-height: 20px;">'.trans('app.online').'</span>' : '<span style="color: red line-height: 20px;">'.trans('app.offline').'</span>' !!}</div>`

but that did not work

**Comment by chriskonnertz** [comment]
Add a ; before line-height.

**Comment by josephzigler** [comment]
> Add a ; before line-height.

<div>{!! $stream->viewers ? '<span style="color: green; line-height: 20px;">'.trans('app.online').'</span>' : '<span style="color: red; line-height: 20px;">'.trans('app.offline').'</span>' !!}</div>

Didn't seem to work either somehow, pressed few times win+f5 aswell

**Comment by chriskonnertz** [comment]
I guess you have to change the `line-height` of the surrounding `<a>` element:

`<a style="line-height: 20px" href="...`

**Comment by josephzigler** [comment]
Fixed, thanks!

**Comment by creativewild** [comment]
Hi,

Just take a look at this nice stuff, the quality and prices are quite worthy, here is the link <http://fyspafypry.nirandjay.com/aenfgcp>

See you around, luisgomes@creativewild.net

**Comment by creativewild** [comment]
Hey,

Our friend have written to me a couple of days ago, they have a surprise for you, just take a look <http://pribisluka.takehertothecourt.com/aeajw>

Faithfully, luisgomes@creativewild.net
