### ISSUE TITLE
Remove /public from URL

### ISSUE THREAD

**Issue by khalifaone** [Contentify/Contentify#494]
Hi guys, i install again the new version of contentify!
I have and VPS and the link are elitedota.com but isn't work on this address i need to access elitedota.com/public for using the website.

How can i remote that /public to acces the website when i use simple domain URL?

As feedback: The new features looks great and will help us to improve the community.
I try your hosting partner HPzone, i made a payment 4 days ago, they did't send me the credentials details and package don't work. They don't answer at my emails for 3 days. Nvm, i don't recommend their services anymore.

I wish you guys good luck with Contentify, you did a great JOB!

PS: 
My next improvments for this CMS:
1. When a CUP start all participans will recieve an POP-up with CONNECT button who invite players in Dota2 Game Custom Lobby 
2. A new design for frontend
3. Players account will be linked at Dota2 database match history and create Levels and ranks on the website.
4. Achivments for participating at our cups

and more great stuffs.

Thank you again for keep a great job on this CMS.
C.

**Comment by khalifaone** [comment]
Problem solved!

Thank you!

**Comment by mrc4tt** [comment]
Remember to close the issue! ;)

**Comment by chriskonnertz** [comment]
Hello @khalifaone ,

thank you for creating this issue.

> I try your hosting partner HPzone, i made a payment 4 days ago, they did't send me the credentials details and package don't work. They don't answer at my emails for 3 days. 

Hm... okay :( I will contact them and ask them for feedback... **ofcourse it is not in my or their interest that you had a negative experience**!

> My next improvments for this CMS

Cool ideas! Would be great to see some of this stuff being published (on GitHub or whereever). :)
