### ISSUE TITLE
found my question answered already - I'm stupid.

### ISSUE THREAD

**Issue by torriz** [Contentify/Contentify#498]
found answer [here](https://github.com/Contentify/Contentify/issues/155)

**Comment by torriz** [comment]
found answer [here](https://github.com/Contentify/Contentify/issues/155)

**Comment by chriskonnertz** [comment]
Great! :)

**Comment by chriskonnertz** [comment]
PS: Another way is to just hide it visually with CSS when (or when not) on specific pages.
