### ISSUE TITLE
[Question] How to access "Custom Content"

### ISSUE THREAD

**Issue by torriz** [Contentify/Contentify#506]
Q2: How do I get access to the "Custom Content" stuff, after it's published?
What's the difference between Custom Pages and Custom Content? 🤔

**Comment by chriskonnertz** [comment]
Hi,

this is explained here: https://github.com/Contentify/Contentify/wiki/Modules#pages

**Comment by torriz** [comment]
🙈 Ahh, sorry! sumBlind

**Comment by chriskonnertz** [comment]
No problem.
