### ISSUE TITLE
[HELP] Dropdown with data from Maps DB, but set selection in User DB (noob)

### ISSUE THREAD

**Issue by torriz** [Contentify/Contentify#507]
**Case:**  Want to add a "Favorite Map", "Favorite Team" etc in my User Profiles.

I can get the maps from the Maps DB like this: 
**/contentify/app/Modules/Users/Resources/Views/form.blade.php**
`{!! Form::smartSelectForeign('map_id', trans('app.object_map')) !!} `
but that will (obviously) not set the "fav_map"

![2019-03-14_14-45-31](https://user-images.githubusercontent.com/2656806/54361694-d9227280-4667-11e9-8944-b7fb31b045b5.png)

**I tried this too**
`{!! Form::smartSelectForeign('map_id', $user->fav_map, null, ['class' => 'form-control']) !!}`

I dunno, I'm kinda stuck.. ❓ 

![chrome_2019-03-14_14-46-14](https://user-images.githubusercontent.com/2656806/54361737-f35c5080-4667-11e9-97fd-6c6275969738.png)
(ye, the 'null' makes the first selection be **-**)

**Comment by chriskonnertz** [comment]
Hi,

please try this: `{!! Form::smartSelectForeign('fav_map_id', $user->fav_map, null, ['class' => 'form-control']) !!}`

**Comment by torriz** [comment]
Thanks for answering,
but this doesn't seem to fix my "issue".

I wanted the user to be able to **pick a map** from the "map_id" already added in the "maps" table. 

the `{!! Form::smartSelectForeign('map_id', $user->fav_map, null, ['class' => 'form-control']) !!} ` 
does get me the correct map_id (and magically gives it a name in the dropdown 👼), 
but it doesn't allow me to set the fav_map ID in User DB - what have I forgotten?

**??**
Is there no way I can get the names/ids from the table and re-use them for the Users table: 
users =>"fav_map"  

I already added a new column in the **users** (table), called "fav_map" - I want this to store the "ID" from the =>**maps** (table) => id .
