### ISSUE TITLE
[Suggestion] News article should have it's own IMAGE rather than using NewsCat

### ISSUE THREAD

**Issue by torriz** [Contentify/Contentify#508]
As the title suggests:
I think the "NewsCat" shouldn't set the image for the News Article **IF** there is one set in the Article itself.

So we'll have to add a "Image" uploader in the `admin_form.blade.php` (?) etc.

**Comment by chriskonnertz** [comment]
Hello,

I agree, we should implement this, this makes sense and gives editors more power/flexibility about the image of the news. :+1: 

> So we'll have to add a "Image" uploader in the admin_form.blade.php (?) etc.

Yes you would have to add an image upload form field in the admin form template of the new module. You would also have to a an `image` column to the `news` table in the database and you would have to make the `image` mass-assignable in the model class `News` and configure it as an image field there. Plus ofcourse add code to the news templates to use the new image if it is set.

Feel free to implement it. :P :)

**Comment by chriskonnertz** [comment]
I'm going to implement that, since it seems very useful to me.

=> Branch: https://github.com/Contentify/Contentify/tree/add-individual-image-for-news
=> PR: https://github.com/Contentify/Contentify/pull/520

**Comment by torriz** [comment]
Great! 👍
