### ISSUE TITLE
Bug: Soft deleting Images & no layout for edit comment

### ISSUE THREAD

**Issue by porphyryr** [Contentify/Contentify#51]
Hello! 

I noticed when uploading a image to the demo site, and then trying to soft remove it, throwns an BadMethodCallException: `production.ERROR: exception 'BadMethodCallException' with message 'Method [show] does not exist.' in /var/www/html/bootstrap/cache/compiled.php:8584`

Also when a comment has been added on a stream, match,.. and you click on edit. There seems to be no layout set for this page, it does not seem to work either. Example: http://i67.tinypic.com/2uek706.png

**Comment by chriskonnertz** [comment]
Hello

`I noticed when uploading a image to the demo site, and then trying to soft remove it, throwns an BadMethodCallException`

Solved: https://github.com/Contentify/Contentify/commit/b11c959d4d569e9cef830b5840704a0531b4cfce

**Comment by chriskonnertz** [comment]
> Also when a comment has been added on a stream, match,.. and you click on edit. There seems to be no layout set for this page, it does not seem to work either

This is how it *should* look like: http://sendvid.com/dmb1nmzd

**Comment by porphyryr** [comment]
> Hello,

thanks for reporting these bugs!

I noticed when uploading a image to the demo site, and then trying to soft remove it, throwns an BadMethodCallException
Solved: b11c959

Thank you for the fix!
