### ISSUE TITLE
[Suggestion] Backend links should be generated based on Role/Access

### ISSUE THREAD

**Issue by torriz** [Contentify/Contentify#524]
**As title suggest:** The backend menu should only show links to what the user have access to, set by the "Role" (with all the permissions set there) he/she is in.

Right now it shows all the links and posts a "Access denied. You need permissions." if you try to enter anything you're not allowed to.

It's annoying for f.ex a "content creators" role with limited access to Video/Stream/Images etc

**Comment by chriskonnertz** [comment]
Hi,

sounds good.

From a technical point of view the question is how to implement that in a nice way.

So the items in the backend menu have to be linked to a permission. For example (derived from https://github.com/Contentify/Contentify/blob/v3.0-alpha/app/Modules/Games/module.json#L3 ):

```json
{
    "slug": "Games",
    "admin-nav": [
        {
            "icon": "gamepad",
            "category": 3,
            "position": 2,
            "permissions": {
                "game": 4
            }
        }
    ]
}
```

Does not seem to be too much of challenge to implement that.

**Comment by BlueStormNetwork** [comment]
i created a profile for permission for all with create level then gave it to super admin i am still having this issue access denied. I am afraid i want be able to grant permission to moderators on forums or editor on q/a can you help to fix this even manually in db or code thanks in advance
