### ISSUE TITLE
[Suggestion] Allow users to upload their game config(s?)

### ISSUE THREAD

**Issue by torriz** [Contentify/Contentify#525]
Allow users to upload their config to the profile:

**Uploads - Either/or:**
1. Allow multiple file uploads for CFG (formats: ini, .cfg, .config, .txt) and create a zip of them.
2. A zip with content (for games that use more than 1 config file), max size X
3. A .cfg/.ini file

**Comment by funtimeerror** [comment]
Please make sure to include mimetype validation validating ‘text/plain’ during the upload process so that we don’t get file types that shouldn’t get uploaded! (Executable/image disguised as .ini)

**Comment by chriskonnertz** [comment]
Interesting. Obviously we would have to make sure this cannot be abused for sharing of generic files or uploading malicious content. But I doubt checking the MIME type will be enough.

**Comment by funtimeerror** [comment]
For sure, it won’t be enough, but it would be a good first step. I would also suggest that as a pre-requisite, an api to call virustotal is implemented. ( https://www.virustotal.com/en/documentation/public-api/ ) that way we can scan uploaded files as another safety net.
