### ISSUE TITLE
[Suggestion] Crop/Editing images: user, news image & avatars etc.

### ISSUE THREAD

**Issue by torriz** [Contentify/Contentify#526]
1. Allow croping of "too wide" user image & avatar
2. Allow the content creator of news/news category images to resize the image to fit the site better.

And/or allow Site owners to set max height/width of uploaded image

**Comment by chriskonnertz** [comment]
Hi,

thank you for your feedback. This is a common feature on many websites / in many content management systems so for sure **it is a legit proposal**.

However, priority would be so low that in my opinion it is not useful to deal with this feature at the moment. Cropping images can be done before uploading it so this for sure is not an urgent one. There are plenty of other features / improvements that have a bigger benefit.
