### ISSUE TITLE
Wierd problems with the streams module

### ISSUE THREAD

**Issue by FollowCandyPanda** [Contentify/Contentify#53]
Hello Chris,

first of all thank you for this amazing Content Management System :) I'am following the project since the first Alpha Release, but until today, unfortunately i didn't had the time to Test it ^^

But i needed a new CMS for my new Esport Team so i thought now will be the right time.

The Installation went smoothly and now after adding some Livestreams to the streams Module i discovered, that the Crobjob only updates the first Livestream added to the list.

My PHP error_log also doesn't show up any errors or warnings..

Regards,

Marcel "CandyPanda"

**Comment by chriskonnertz** [comment]
Hello,

I'm glad you like it! :)

Would you navigate to this URL and tell me what the output is?

`http://<your-site>/jobs`

**Comment by FollowCandyPanda** [comment]
https://www.gfesports.gg/jobs

Output:

1

**Comment by chriskonnertz** [comment]
Can you access the database for example with phpMyAdmin? If so go to the `streams` table. There you can see all the streams and their attributes. One attribute is named `renewed_at`. Whenever a stream is updated the value of this attribute is set to the current date and time. Do you see any anomalies? For example only the `renewed_at` value of the stream with the lowest ID (=the first stream) seems to have a plausible date & time?

**Comment by FollowCandyPanda** [comment]
Looks completely okay:

http://d.pr/i/HmJA

**Comment by chriskonnertz** [comment]
Well are you sure the that more than just one stream was live (=streaming)?

**Comment by FollowCandyPanda** [comment]
At that Moment, 3 from 3 where live

I will now add 5 Streams and see how it goes.

**Comment by chriskonnertz** [comment]
Ok.

**Comment by FollowCandyPanda** [comment]
Statusreport:

12 Streams = 9 Online = Only 3 updating

**Comment by chriskonnertz** [comment]
Are all of them Twitch streams?

**Comment by FollowCandyPanda** [comment]
Yes

**Comment by chriskonnertz** [comment]
I'll investigate. Although I have no clue what the reason for this behaviour is.

**Comment by chriskonnertz** [comment]
Had no time to look at it yet but I won't forget tihs issue.

**Comment by chriskonnertz** [comment]
Maybe I should have mention that the update will only run every 5 minutes no matter how often you call `http://<your-site>/jobs`. If you think one update every 5 minutes is not enough go to `app/Modules/Streams/UpdateStreamsJob.php` and change the value in this line:

    protected $timeSpan = 5; // Minutes

**Comment by FollowCandyPanda** [comment]
This i had already changed :D Maybe there is the Problem?

**Comment by chriskonnertz** [comment]
Well, set it to 1 and test again? :p

**Comment by FollowCandyPanda** [comment]
It is set to 1 ^^ I will now set it to 5 back and change the cronjob

**Comment by FollowCandyPanda** [comment]
Set and i will report back later ^^

**Comment by FollowCandyPanda** [comment]
Some as before

**Comment by ThomasKedie** [comment]
@chriskonnertz if we want to update stream viewers count we need to run `php artisan jobs` every time?

**Comment by chriskonnertz** [comment]
Yes but not "you" in person. Let a cron job do this for you. You can learn here how to setup one on your own machine: https://github.com/Contentify/Contentify/wiki/Going-Live (third list item)

If you cannot create a cron jopb on your machine you might use an external service, for example https://www.cron-job.org/ It then has to call `http://<your-site>/jobs`.

**Comment by FollowCandyPanda** [comment]
Because there was not much content on the Page I will reinstall the Page again, maybe it fixes the problem.

I look into it and will report back later.

**Comment by chriskonnertz** [comment]
Okay!

**Comment by FollowCandyPanda** [comment]
So after the Reinstall the same thing:

4 Channels added (all from Twitch.tv) all 4 are live -> only 1 is updating

**Comment by ThomasKedie** [comment]
Really strange, becouse in my server all channels are working fine

**Comment by chriskonnertz** [comment]
Yeah for me as well... that's really strange and I have no idea so far what could cause this. I'll have to do more testing...

**Comment by chriskonnertz** [comment]
Sorry but I do not know how to help. I'll leave this issue open for a while but I have no ideas how to fix this bug.

**Comment by creativewild** [comment]
Hi,

Have you heard the latest gossip? This is what you have to read <http://geshopigy.lifeworksimaging.com/aezsbrjj>

Later, luisgomes@creativewild.net

**Comment by chriskonnertz** [comment]
Hi,

got infected by malware? :stuck_out_tongue: 

I removed the spam link and deleted your other spam posts.

**Comment by chriskonnertz** [comment]
I'm cleaning up so I close this now. If someone of you has more to say please create a new issue! Thanks.

**Comment by chriskonnertz** [comment]
Regarding the streams issue:
Lately there have been made some changes to the Twitch API. I do not know if this has something to do with the problem. Most likely it does not, however, please notice the latest update.

https://github.com/Contentify/Contentify/commit/9bb712b72d5512f7540d63e99e68bdd28aa46d45
