### ISSUE TITLE
Class 'Fideloper\Proxy\TrustProxies' not found

### ISSUE THREAD

**Issue by reneb71** [Contentify/Contentify#532]
- Contentify 3.0
- Shared hosting

[26-Mar-2019 09:40:37 UTC] PHP Fatal error:  Class 'Fideloper\Proxy\TrustProxies' not found in /home/*mydomain*/public_html/app/Http/Middleware/TrustProxies.php on line 8

**Comment by chriskonnertz** [comment]
Hello,

thank you for the feedback.

Did you run the `php composer.phar install` command?

**Comment by reneb71** [comment]
fixed with command `composer update`. tho new errors

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Too few arguments to function Contentify\Installer::createDatabaseIni(), 0 passed in /home/mydomain/public_html/hub/contentify/Controllers/InstallController.php on line 120 and exactly 4 expected

**Comment by reneb71** [comment]
Re installed with some changes. PHP settings enable `proc_open` and `proc_close`. Now it works

**Comment by chriskonnertz** [comment]
Ok fine! :D 

> fixed with command composer update

`composer update` is dangerous. With `install` Composer looks into the `composer.lock` file and installs all dependencies (third party libraries) exactly in the version from the  `composer.lock` file. If you run `composer update` Composer might install newer versions that are not compatible.

**Comment by reneb71** [comment]
Second try didnt use `composer update`

**Comment by chriskonnertz** [comment]
> Type error: Too few arguments to function Contentify\Installer::createDatabaseIni(), 0 passed

Fixed this: https://github.com/Contentify/Contentify/commit/abccab55dc2ac24df1ed6096f117300178ff1627

Thanks for reporting this bug!

**Comment by reneb71** [comment]
> > Type error: Too few arguments to function Contentify\Installer::createDatabaseIni(), 0 passed
> 
> Fixed this: [abccab5](https://github.com/Contentify/Contentify/commit/abccab55dc2ac24df1ed6096f117300178ff1627)
> 
> Thanks for reporting this bug!

No problem. Ill let you know if i found more bugs
