### ISSUE TITLE
Cannot use 'Contentify\true' as class name as it is reserved when clinking "matches"

### ISSUE THREAD

**Issue by reneb71** [Contentify/Contentify#534]
Contentify 3.0

https://i.imgur.com/haR7xfM.png

**Comment by chriskonnertz** [comment]
Hi,

thank you for creating this issue. I made a change, please try this: https://github.com/Contentify/Contentify/commit/e6d160fb2562b1fb533e81c089519370e115a56b

> But also note that you need PHP 7.0 (at least) to run Contentify 3.0!

**Comment by chriskonnertz** [comment]
@PeliManne Does it work now?

**Comment by reneb71** [comment]
> @PeliManne Does it work now?

Yeah it does, thanks
