### ISSUE TITLE
Problem with my stable website

### ISSUE THREAD

**Issue by reneb71** [Contentify/Contentify#536]
- Contentify 2.6

When going to https://www.exeretro.com it has unserialize(): Error at offset 0 of 40 bytes

but not when going with https://exeretro.com

**Comment by chriskonnertz** [comment]
Hello,

cannot confirm. Both work for me. Please try to logout / login, clear your browser cache or [clear the application cache](https://github.com/Contentify/Contentify/wiki/FAQ#how-can-i-clear-the-cache).

If that does not help, please take a look at the log (log in -> admin interface -> settings page -> click on the log button). Maybe it contains information that helps you to figure out what's wrong. If not, you may post it here, but be aware that it might contain sensitive data (for example passwords).

**Comment by reneb71** [comment]
> Hello,
> 
> cannot confirm. Both work for me. Please try to logout / login, clear your browser cache or [clear the application cache](https://github.com/Contentify/Contentify/wiki/FAQ#how-can-i-clear-the-cache).
> 
> If that does not help, please take a look at the log (log in -> admin interface -> settings page -> click on the log button). Maybe it contains information that helps you to figure out what's wrong. If not, you may post it here, but be aware that it might contain sensitive data (for example passwords).

It was a website caching proplem. Sorted by purging cache and clearing browser cache

**Comment by chriskonnertz** [comment]
Great!
