### ISSUE TITLE
Meta tag description

### ISSUE THREAD

**Issue by josephzigler** [Contentify/Contentify#54]
Hello,

I noticed my website doesn't have a proper description in search engines, so I think implementing the description meta tag should resolve this. I wonder how to properly implement this, I have added `<meta name="description" content="@yield('description')">` to my layout_main.blade.php and would like to add `@section('description', 'This is a description')` to all the views that I want a description to be set. I expect I have to add this to all the main view pages in app/modules from each page?

I also wonder if it's possible to remove the "News" viewbag title from the home page

Thank you in advance!

Regards, Joseph

**Comment by chriskonnertz** [comment]
> I also wonder if it's possible to remove the "News" viewbag title from the home page

You can change it or even completely remove it. To do the latter:
1. Open `App/Modules/News/Http/Controllers/NewsController`. Find the `showOverview`method  and this (around line 54):

    $this->title('no-title');
2. Open `<cms-folder>/contentify/HtmlBuilder.php`. Find the `title`method (around line 66). At its beginning add this:

if ($title = 'no-title') return '<title>'.Config::get('app.title').'</title>';

So it should look like this:

    public function title($title = null)
    { 
        if ($title = 'no-title') return '<title>'.Config::get('app.title').'</title>';
        if ($title) {
            $title .= ' - '.Config::get('app.title');
        } else {
            $title = Config::get('app.title');
        }

        return '<title>'.$title.'</title>';
    }

**Comment by chriskonnertz** [comment]
> I noticed my website doesn't have a proper description in search engines

Some pages of your website should have an OpenGraph description. But yes, not the good old `<meta name="description" content="whatever">` description.

> I expect I have to add this to all the main view pages in app/modules from each page?

Assumed that your code works: yes. I understand that you want to have individual descriptions for particular pages. Then ofcourse you have to implement this for all of these pages.

**Comment by josephzigler** [comment]
Thank you!

**Comment by josephzigler** [comment]
I noticed the App/Modules/News/Http/Controllers/NewsController notitle change, changes the viewbag title from http://localhost/newsid/newstitle. I wonder if it's possible to remove the News - Website Name when going to http://localhost/

**Comment by chriskonnertz** [comment]
I am 100% sure that I understand what your plan is - but try this:
Open `App/Modules/News/Http/Controllers/NewsController`. Find the `index` (ine 16). Add this code at the beginning or the end of the method (I am not sure if it matters so if it does not work in the first place try it the other way): 

    $this->title('no-title');

**Comment by josephzigler** [comment]
Thank you so far! It removes the viewbag title from /news but not from the 'root ' index domain, I have been looking but not sure where it loads this page from

**Comment by chriskonnertz** [comment]
Now I am confused. I guess I missunderstood something but I do not know what.

Did you add this

    $this->title('no-title');

do both, the `index` and the `showOverview` method?

**Comment by josephzigler** [comment]
Yes, that removes the 'News -' from the http://www.website.com/news title, and when placing the no-notitle in showoverview it removes the title from http://www.website.com/news/newsid/titleslug. What I would like to achieve is remove the 'News-' from the http://www.website.com/ all the changes that i've done to the NewsController haven't been able to achieve this yet

**Comment by chriskonnertz** [comment]
No offense but I am quite sure that you did not follow my instructions in the right way. :stuck_out_tongue: 

This is how your `app/Modules/News/Http/NewsController.php` should look like (or at least very similar):
http://pastebin.com/XPmn2i2d

Line 54 is the important line. It's inside the `showOverview()` method, This method is called when you navigate to your website without navigating to a particular page. Example: http://demo.contentify.org/ 
So there *is no way* that this behaviour occurs:

> I noticed the App/Modules/News/Http/Controllers/NewsController notitle change, changes the viewbag title from http://localhost/newsid/newstitle

If this happens then I assume you made the wrong change to the code. So compare your `NewsController.php` to the one I've posted above.

**Comment by kevindefrene** [comment]
I did indeed make a mistake :smile: I was adding it in the show() method instead of the showOverview(). It is working properly now,  Thank you!

**Comment by josephzigler** [comment]
I did indeed make a mistake  I was adding it in the show() method instead of the showOverview(). It is working properly now, Thank you!
