### ISSUE TITLE
css is not loading from public sub folders

### ISSUE THREAD

**Issue by gaganpreetkaur1469** [Contentify/Contentify#554]
(No description provided)

**Comment by chriskonnertz** [comment]
Hello,

please can you add a description of the problem? I think just the title is not precise enough to help you...

**Comment by BlueStormNetwork** [comment]
I had this issue before on my first attempt install, if you did install contentify on a sub folder check your .htaccess file if it has the proper base/redirect needed rules to point to subfolder/public directory. If you can't edit or don't have access to .htaccess file just move your installation to the root public html or www folder. will solve the issue.
