### ISSUE TITLE
ToDo Check admin permission in Polls module

### ISSUE THREAD

**Issue by BlueStormNetwork** [Contentify/Contentify#555]
- Contentify v2.6
- no need for logs (issue appears all the time the message in red access denied in the backend)
    - Linux,
    - Apache,
    - MySQL
- shared hosting, heliohost.org

Hi guys thank you for the great work ^^
my issue is that super admin can't create polls. i created several roles respectively with create/update/read and delete access to all modules available (polls isn't mentioned there) and added them to superAdmin just to make sure still I end up with access denied need permission...

**Comment by BlueStormNetwork** [comment]
just an answer plz is this feature working on contentify 2.6 or not i mean creating and using polls cause even super admin gets the access denied message.

**Comment by torriz** [comment]
Try creating it manually in db?

**Comment by chriskonnertz** [comment]
Hi @BlueStormNetwork ,

did you upate from 2.5 or start with 2.6? This is an important question, because if you updated this might indicate there is something wrong with the update.

**Comment by Zai** [comment]
Same problem with fresh install on 2.6 with super-admin role

**Comment by mazzorini** [comment]
Same here with clean install of 2.6

**Comment by chriskonnertz** [comment]
I see... In the installer the part that creates this permission is missing:

https://github.com/Contentify/Contentify/blob/2.6/contentify/Controllers/InstallController.php#L1212

Yeah, this is a bug. It has been added in 3.0 but not in 2.6.

**Workaround:**
- Go to the `roles` table in the database.
- Go to the row with the ID 5 (I am not sure and can't check it right now, but that should be the super admin role -- well it's the role with ther highest ID as long as you have not added any other roles)
- Now there is aa column with the permissions. These are stores in JSON. You maybe should copy, paste and save them somewhere before you edit them, to have a  backup.
- Now add add an entry for `polls`, I think it should look like this: `"polls": 5, "` - Don't forget the comma!
