### ISSUE TITLE
How to use my model ?

### ISSUE THREAD

**Issue by krysennn** [Contentify/Contentify#56]
Hello,

I use your CMS :+1:

I would make my own module:

- php artisan make:module Testmodules
I create Testmodule.php on App\Module\Testmodules\Testmodule.php
- php artisan make:migration Testmodules
Created Migration: 2016_05_05_120759_Testmodules

but there nothing in 2016_05_05_120759_Testmodules.php
I think my Testmodule.php (model) is not use when i create the migration ?

Can you help me please  ?:sos:

Thank you,
Alexis

**Comment by chriskonnertz** [comment]
Hello.

Honestly when I create a new module I start with a copy of an existing one.

I'll try to investigate your problem but in the meanwhile I recommend to try my way. Just copy the direcotry of a module (for example the games module `app/Modules/Games`) and look into its files (about 5 or so) and replace the name of the original module with the name of the new everywhere.

**Comment by krysennn** [comment]
Hello,

thanks, i try your method when i use your cms for the first time, but i see this wiki: https://github.com/caffeinated/modules/wiki

I will share my files:
app\Modules\Tstournaments\module.json
`{
	"name": "TSTournaments",
	"slug": "tstournaments",
	"namespace": "TSTournaments",
	"version": "1.0",
	"description": "Module for management tournaments",
	"enabled": true,
	"admin-nav": [
        {
            "icon": "cog",
            "category": 5,
            "position": 1       
        }
    ]
}
`
app\Modules\Tstournaments\TSTournament.php
`<?php namespace App\Modules\TSTournaments;

use SoftDeletingTrait, BaseModel;

class TSTournament extends BaseModel {

    use SoftDeletingTrait;

    /**
     * Tournament state "hidden"
     */
    const STATE_HIDDEN = 0;

    /**
     * Tournament state "open"
     */
    const STATE_OPEN = 1;

    /**
     * Tournament state "check-in"
     */
    const STATE_CHECK = 2;

    /**
     * Tournament state "started"
     */
    const STATE_START = 3;

    /**
     * Tournament state "delayed"
     */
    const STATE_DELAYED = 4;

    protected $dates = ['deleted_at', 'join_at', 'check_at', 'start_at', 'closed_at'];

    protected $fillable = [
        'state',
        'title',
        'game_id',
        'slot',
        'prize',
        'arbiter',
        'featured',
        'broadcast',
        'teams',
        'text',
        'join_at',
        'check_at',
        'start_at',
        'closed_at',
    ];

    public static $fileHandling = ['icon' => ['type' => 'image']];

    protected $rules = [
        'state'     => 'integer|min:0',
        'title'     => 'required|min:3',
        'slot',     => 'required',
        'game_id'   => 'required',
        'featured'  => 'boolean',
        'broadcast' => 'sometimes|url',
        'text'      => 'required',
    ];

    public static $relationsData = [
        'game'         => [self::BELONGS_TO, 'App\Modules\TSGames\Game'],
        'arbiter'  => [self::HAS_MANY, 'App\Modules\TSArbiter\Arbiter'],
        'teams'     => [self::HAS_MANY, 'App\Modules\TSTeams\Team'],
        'creator'      => [self::BELONGS_TO, 'User', 'title' => 'username'],
    ];

    const STATE_HIDDEN = 0;

    /**
     * Tournament state "open"
     */
    const STATE_OPEN = 1;

    /**
     * Tournament state "check-in"
     */
    const STATE_CHECK = 2;

    /**
     * Tournament state "started"
     */
    const STATE_START = 3;

    /**
     * Tournament state "delayed"
     */
    const STATE_DELAYED = 4;

    /**
     * Array with the names of available match states.
     *
     * @var array
     */
    public static $states = [
        self::STATE_HIDDEN  => 'Hidden', 
        self::STATE_OPEN    => 'Open', 
        self::STATE_CHECK   => 'Check-in', 
        self::STATE_START   => 'Start'
        self::STATE_DELAYED => 'Delayed'
    ];

}`
app\Modules\Tstournaments\Database\Migrations\2016_05_05_121107_tstournaments.php
`<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Tstournaments extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('tstournaments', function (Blueprint $table) {
			$table->increments('id');
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('tstournaments');
	}
}`

I would'nt create schema of my table, on symfony2 i create my Entity and the schema of table is automaticly create in the database, do you know my problem ? i know i have bad english :cry:

**Comment by chriskonnertz** [comment]
>  i know i have bad english
No problem! :)

> I wouldn't create schema of my table, on symfony2 i create my Entity and the schema of table is automaticly create in the database, do you know my problem ?

Yes. Well Laravel / Contentify can't do that. You need to create a schema by your own. (Or you find a package that can do it but well I do not have any experience with those packages.)

So what you have to do is to use the Migration class to create the database table.

Example:

        Schema::create('tstournaments', function (Blueprint $table) {
            $table->increments('id');
            $table->timestamp('deleted_at'); // same for join_at etc.
            $table->integer('state');
            $table->string('title'); // string = VARCHAR
            $table->boolean('featured'); // boolean = TINYINT
            $table->text('text');
            ... and so on ...
        });

-> https://laravel.com/docs/5.2/migrations#creating-columns

Ofcourse you can add default values (via `->default($value)`) and make attributes nullable (`->nullable()' ) etc.

Note that -  at least - you can let Contentify create the form template for you. :) 
https://github.com/Contentify/Contentify/wiki/Artisan#generate-forms

**Comment by krysennn** [comment]
Oh thank you very much ! I'm lost because i work more on Symfony2 and i'm used to create my Entity and doctrine create table for me ^^
So now i return to work with laravel i will prepare my schema ^^

Thank you for your help, you can close the issue :+1:

**Comment by chriskonnertz** [comment]
Ok! :)
