### ISSUE TITLE
Local xampp Windows 10 install - Contentify Error when adding a link to a twitch stream

### ISSUE THREAD

**Issue by Daxing246** [Contentify/Contentify#566]
Hi All,
I have some knowledge of web dev, but i am a back bedroom tinkerer at night and a IT Programme Manager during the day. I'm struggling with an error post install of contentify which is when I try to do some functions. The error in short is (1/1) ErrorExceptionpreg_match(): Compilation failed: invalid range in character class at offset 1825 when I am trying to add a URL to the streaming or video pages via the backend admin page.

System Info
- Windows 10  Pro version 10.0.17763.504
- xampp windows x64-7.3.5-1-VC15
- laravel (v5.8.17)
- Contentify 2.6

I've installed xampp, updated the php.ini with extension=php_fileinfo.dll - All OK
set the database via my.ini to use: 
                  - collation_server=utf8_unicode_ci
                  - character_set_server=utf8
Created a virtual host called contentify and updated the localhost - All OK
I started up apache and MSQL went to contentify/ and it started the installation and went through successfully - All OK

I installed laravel in C:\xampp\htdocs\laravel using windows powershell 'composer create-project --prefer-dist laravel/laravel' - installation went flawless and i set another virtual machine called laravel just to test it was up and running (after starting and stopping xampp) - all OK
(Im not sure if i have done this step correctly) but all is working and I can hit the laravel landing page.

So the laravel landing page loads up, the contentify site loads up, so all is good so far - Check, all  ok :-)

The issue I have is that when I log into contentify and navigate to http://contentify/admin/streams/create to add a link to a twitch stream, as soon as i click save or apply i get the  nasty error below.

Im at a loss on how to resolve. Im not sure if i am meant to be running contentify via laravel. Im just really stuck. Ive googled the error, and there are lots of sql code, which i have tried and adapted and I am at a loss. (I know it will most likely be a two min job for someone to resolve and its probably very simple.

My guess is its something to do with laravel and me not placing the contentify in the right location, but im just guessing now.

Error Message 
(1/1) ErrorExceptionpreg_match(): Compilation failed: invalid range in character class at offset 1825
--
in ValidatesAttributes.php (line 1356)
at HandleExceptions->handleError(2, 'preg_match(): Compilation failed: invalid range in character class at offset 1825', 'C:\\xampp\\htdocs\\contentify\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Concerns\\ValidatesAttributes.php', 1356, array('attribute' => 'url', 'value' => 'http://www.twitch.tv/', 'pattern' => '~^ ((aaa\|aaas\|about\|acap\|acct\|acr\|adiumxtra\|afp\|afs\|aim\|apt\|attachment\|aw\|barion\|beshare\|bitcoin\|blob\|bolo\|callto\|cap\|chrome\|chrome-extension\|cid\|coap\|coaps\|com-eventbrite-attendee\|content\|crid\|cvs\|data\|dav\|dict\|dlna-playcontainer\|dlna-playsingle\|dns\|dntp\|dtn\|dvb\|ed2k\|example\|facetime\|fax\|feed\|feedready\|file\|filesystem\|finger\|fish\|ftp\|geo\|gg\|git\|gizmoproject\|go\|gopher\|gtalk\|h323\|ham\|hcp\|http\|https\|iax\|icap\|icon\|im\|imap\|info\|iotdisco\|ipn\|ipp\|ipps\|irc\|irc6\|ircs\|iris\|iris.beep\|iris.lwz\|iris.xpc\|iris.xpcs\|itms\|jabber\|jar\|jms\|keyparc\|lastfm\|ldap\|ldaps\|magnet\|mailserver\|mailto\|maps\|market\|message\|mid\|mms\|modem\|ms-help\|ms-settings\|ms-settings-airplanemode\|ms-settings-bluetooth\|ms-settings-camera\|ms-settings-cellular\|ms-settings-cloudstorage\|ms-settings-emailandaccounts\|ms-settings-language\|ms-settings-location\|ms-settings-lock\|ms-settings-nfctransactions\|ms-settings-notifications\|ms-settings-power\|ms-settings-privacy\|ms-settings-proximity\|ms-settings-screenrotation\|ms-settings-wifi\|ms-settings-workplace\|msnim\|msrp\|msrps\|mtqp\|mumble\|mupdate\|mvn\|news\|nfs\|ni\|nih\|nntp\|notes\|oid\|opaquelocktoken\|pack\|palm\|paparazzi\|pkcs11\|platform\|pop\|pres\|prospero\|proxy\|psyc\|query\|redis\|rediss\|reload\|res\|resource\|rmi\|rsync\|rtmfp\|rtmp\|rtsp\|rtsps\|rtspu\|secondlife\|service\|session\|sftp\|sgn\|shttp\|sieve\|sip\|sips\|skype\|smb\|sms\|smtp\|snews\|snmp\|soap.beep\|soap.beeps\|soldat\|spotify\|ssh\|steam\|stun\|stuns\|submit\|svn\|tag\|teamspeak\|tel\|teliaeid\|telnet\|tftp\|things\|thismessage\|tip\|tn3270\|turn\|turns\|tv\|udp\|unreal\|urn\|ut2004\|vemmi\|ventrilo\|videotex\|view-source\|wais\|webcal\|ws\|wss\|wtai\|wyciwyg\|xcon\|xcon-userid\|xfire\|xmlrpc\\.beep\|xmlrpc.beeps\|xmpp\|xri\|ymsgr\|z39\\.50\|z39\\.50r\|z39\\.50s)):// # protocol (([\\pL\\pN-]+:)?([\\pL\\pN-]+)@)? # basic auth ( ([\\pL\\pN\\pS-\\.])+(\\.?([\\pL]\|xn\\-\\-[\\pL\\pN-]+)+\\.?) # a domain name \| # or \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3} # an IP address \| # or \\[ (?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::)))) \\] # an IPv6 address ) (:[0-9]+)? # a port (optional) (/?\|/\\S+\|\\?\\S*\|\\#\\S*) # a /, nothing, a / with something, a query or a fragment $~ixu'))
at preg_match('~^ ((aaa\|aaas\|about\|acap\|acct\|acr\|adiumxtra\|afp\|afs\|aim\|apt\|attachment\|aw\|barion\|beshare\|bitcoin\|blob\|bolo\|callto\|cap\|chrome\|chrome-extension\|cid\|coap\|coaps\|com-eventbrite-attendee\|content\|crid\|cvs\|data\|dav\|dict\|dlna-playcontainer\|dlna-playsingle\|dns\|dntp\|dtn\|dvb\|ed2k\|example\|facetime\|fax\|feed\|feedready\|file\|filesystem\|finger\|fish\|ftp\|geo\|gg\|git\|gizmoproject\|go\|gopher\|gtalk\|h323\|ham\|hcp\|http\|https\|iax\|icap\|icon\|im\|imap\|info\|iotdisco\|ipn\|ipp\|ipps\|irc\|irc6\|ircs\|iris\|iris.beep\|iris.lwz\|iris.xpc\|iris.xpcs\|itms\|jabber\|jar\|jms\|keyparc\|lastfm\|ldap\|ldaps\|magnet\|mailserver\|mailto\|maps\|market\|message\|mid\|mms\|modem\|ms-help\|ms-settings\|ms-settings-airplanemode\|ms-settings-bluetooth\|ms-settings-camera\|ms-settings-cellular\|ms-settings-cloudstorage\|ms-settings-emailandaccounts\|ms-settings-language\|ms-settings-location\|ms-settings-lock\|ms-settings-nfctransactions\|ms-settings-notifications\|ms-settings-power\|ms-settings-privacy\|ms-settings-proximity\|ms-settings-screenrotation\|ms-settings-wifi\|ms-settings-workplace\|msnim\|msrp\|msrps\|mtqp\|mumble\|mupdate\|mvn\|news\|nfs\|ni\|nih\|nntp\|notes\|oid\|opaquelocktoken\|pack\|palm\|paparazzi\|pkcs11\|platform\|pop\|pres\|prospero\|proxy\|psyc\|query\|redis\|rediss\|reload\|res\|resource\|rmi\|rsync\|rtmfp\|rtmp\|rtsp\|rtsps\|rtspu\|secondlife\|service\|session\|sftp\|sgn\|shttp\|sieve\|sip\|sips\|skype\|smb\|sms\|smtp\|snews\|snmp\|soap.beep\|soap.beeps\|soldat\|spotify\|ssh\|steam\|stun\|stuns\|submit\|svn\|tag\|teamspeak\|tel\|teliaeid\|telnet\|tftp\|things\|thismessage\|tip\|tn3270\|turn\|turns\|tv\|udp\|unreal\|urn\|ut2004\|vemmi\|ventrilo\|videotex\|view-source\|wais\|webcal\|ws\|wss\|wtai\|wyciwyg\|xcon\|xcon-userid\|xfire\|xmlrpc\\.beep\|xmlrpc.beeps\|xmpp\|xri\|ymsgr\|z39\\.50\|z39\\.50r\|z39\\.50s)):// # protocol (([\\pL\\pN-]+:)?([\\pL\\pN-]+)@)? # basic auth ( ([\\pL\\pN\\pS-\\.])+(\\.?([\\pL]\|xn\\-\\-[\\pL\\pN-]+)+\\.?) # a domain name \| # or \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3} # an IP address \| # or \\[ (?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9]))\\.){3}(?:(?:25[0-5]\|(?:[1-9]\|1[0-9]\|2[0-4])?[0-9])))))))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))\|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::)))) \\] # an IPv6 address ) (:[0-9]+)? # a port (optional) (/?\|/\\S+\|\\?\\S*\|\\#\\S*) # a /, nothing, a / with something, a query or a fragment $~ixu', 'http://www.twitch.tv/')in ValidatesAttributes.php (line 1356)
at Validator->validateUrl('url', 'http://www.twitch.tv/', array(), object(Validator))in Validator.php (line 352)
at Validator->validateAttribute('url', 'Url')in Validator.php (line 267)
at Validator->passes()in ValidatingTrait.php (line 417)
at BaseModel->performValidation(array('title' => 'required\|min:3', 'short' => 'required\|max:6', 'url' => 'nullable\|\|url'))in ValidatingTrait.php (line 270)
at BaseModel->isValid()in ValidatingObserver.php (line 51)
at ValidatingObserver->performValidation(object(Tournament), 'saving')in ValidatingObserver.php (line 20)
at ValidatingObserver->saving(object(Tournament))
at call_user_func_array(array(object(ValidatingObserver), 'saving'), array(object(Tournament)))in Dispatcher.php (line 367)
at Dispatcher->Illuminate\Events\{closure}('eloquent.saving: App\\Modules\\Tournaments\\Tournament', array(object(Tournament)))in Dispatcher.php (line 199)
at Dispatcher->dispatch('eloquent.saving: App\\Modules\\Tournaments\\Tournament', array(object(Tournament)), true)in Dispatcher.php (line 159)
at Dispatcher->until('eloquent.saving: App\\Modules\\Tournaments\\Tournament', object(Tournament))in HasEvents.php (line 148)
at Model->fireModelEvent('saving')in Model.php (line 506)
at Model->save()in ModelHandler.php (line 545)
at ModelHandler->update('1')in Facade.php (line 221)
at Facade::__callStatic('update', array('1'))in ModelHandlerTrait.php (line 57)
at AdminTournamentsController->update('1')
at call_user_func_array(array(object(AdminTournamentsController), 'update'), array('tournament' => '1'))in BaseController.php (line 114)
at BaseController->callAction('update', array('tournament' => '1'))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AdminTournamentsController), 'update')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyAdminAccess.php (line 40)
at VerifyAdminAccess->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in UpdateUser.php (line 114)
at UpdateUser->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 52)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HttpsRedirect.php (line 33)
at HttpsRedirect->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

Kind regards,
Dax

**Comment by Franpepper** [comment]
I had a similar problem when adding content. The problem was the php version. Version 7.3.x does not work with contentify, try using version 7.1 or 7.2

**Comment by Daxing246** [comment]
Thanks Franpeper. I'll try this shortly once I get home. I really hope it's this 👍👍

**Comment by Daxing246** [comment]
Thanks Frapepper, thats worked a treat. All seems to be good. 

Is there any need to install laravel as I havent done at the mo, but all seems to be working correctly. Cant believe how simple that was lol. Thanks again, its really appreciated.
