### ISSUE TITLE
 Installation: QueryException & PDOException error

### ISSUE THREAD

**Issue by TheHotz** [Contentify/Contentify#570]
Habe heute versucht die Version 2.6 auf meinem DigitalOcean Droplet zu installieren nach den im FAQ angegebenen Anweisungen. Bin leider im vierten Schritt beim anlegen der Datenbank auf zwei Probleme gestoßen.

Nummer 1
`(1/2) PDOException
SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'`

Nummer 2
`(2/2) QueryException
SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' (SQL: SHOW TABLES LIKE "migrations")`

Habe mich hier schon durch zahlreiche Posts gelesen und einiges durchgeschaut/probiert. Einmal habe ich regelmäßig gelesen, dass dieses Problem ab Version 2.5 bereits behoben sein sollte (installiere 2.6). Auch meine Datenbank-Daten habe ich inzwischen mehrmals überprüft und sichergestellt, dass alles richtig ist.

Vielen Dank schon mal für die Hilfe!

**Comment by chriskonnertz** [comment]
Hi,

das problem (es handelt sich im Grunde bei beiden um das gleiche Problem) ist mir bekannt. Leider aber dessen Ursache nicht und daher habe ich auch keine richtige Lösung parat.

Vermutlich ist da irgendwo ein Fehler tief in der Logik des Installers vergraben.

Workaround für v2.6 wäre einen MySQL-Dump zu laden statt den Installer auszuführen: https://github.com/Contentify/Contentify/wiki/Troubleshooting#installation-execution-time-exceeded

Baue ich mal als Tipp ins Wiki ein.

**Comment by TheHotz** [comment]
Habe es nun mit dem MySQL-Dump versucht. Leider bekomme ich nun andere QueryException und PDOException Fehlermeldungen. Könnte gut sein, dass ich mich grad nur blöd anstelle, aber ich komme hier aktuell einfach nicht weiter. Vielen Dank schon mal für die Hilfe!

`QueryException
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'username' (SQL: alter table `users` add `username` varchar(20) not null, add `slug` varchar(255) not null, add `updater_id` int unsigned not null default '0')`

`PDOException
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'username'`

**Comment by TheHotz** [comment]
So bin immerhin ein bisschen weitergekommen (nach MySQL-Dump) ;-) Habe nun allerdings einen neuen Fehler erhalten.
`(1/1) Exception
Error: Could not retrieve the theme name from the config!`

Ein Blick in die "FrontController.php" Datei hat mich nur verwundert zurückgelassen, hier scheint alles wie es sein soll.

Noch etwas anderes: Gibt es professionelle/semi-professionelle Administratoren/Webdeveloper, die sich mit Contentify auskennen und das für "Noobs" einrichten/betreuen? Habe Contentify früher sowohl bei eFever als auch escene genutzt aber musste als Redakteur nie administrative Arbeiten machen. Da beiden Seiten inzwischen tot bzw. so gut wie tot sind wollte ich es mal selbst versuchen. Bin inzwischen aber ein bisschen an meine Grenzen gestoßen.... Wie gesagt: Noob :-P

**Comment by chriskonnertz** [comment]
Hallo,

> So bin immerhin ein bisschen weitergekommen (nach MySQL-Dump) ;-) Habe nun allerdings einen neuen Fehler erhalten. (1/1) Exception Error: Could not retrieve the theme name from the config!

Schau mal bitte - z. B. mit phpMyAdmin - in die Tabelle `config`. Dort müsste es einen Eintrag mit `name`=`app.theme` geben. Setz da mal den `value` auf `MorpheusTheme`.

Zu der Frage: Stand heute gibt es das nicht, jedenfalls wohl nicht so wie du dir das wünschst. Aber du bist mit deinem Anliegen nicht allein, sodass als nächstes großes Feature geplant ist, dahingegend einen Service aufzubauen der sich um die grundlegende Einrichtung & Maintenance kümmert. Es ist allerdings noch völlig unklar wann das kommen wird.
