### ISSUE TITLE
Videos in den News

### ISSUE THREAD

**Issue by RaceTubeGermany** [Contentify/Contentify#571]
Hallo,

wenn ich neue Videos über das Backend einstelle, erscheinen diese unendlich in den News.
Ist der Fehler bekannt?

Gruß

**Comment by chriskonnertz** [comment]
Hallo,

nein, ist nicht bekannt. Was genau heißt "unendlich"?

**Comment by RaceTubeGermany** [comment]
Hi. 

Ich stelle ein paar Videos ein und in den news kann ich ohne Ende nach unten scrollen und die sind da endlos angezeigt. Wiederholen sich immer in den news. 

Mit freundlichen Grüßen 

RaceTube Germany
