### ISSUE TITLE
Call to undefined function Contentify\getclass()

### ISSUE THREAD

**Issue by ddb69** [Contentify/Contentify#572]
Hallo,

erstmal vorab, cooles CMS. Leider habe ich ein paar Probleme.

Ich habe Contentify 3.0 mehr oder weniger erfolgreich installiert. Zu sehen unter www.inperpetuum.eu. Soweit so gut. Auf meinem Root-Server läuft die aktuelleste LTS-Versioin von Ubuntu, PHP 7.2, MySQL, also alles in allem keine großen Besonderheiten. Die Voraussetzungen für die Installation waren alle erfüllt und das lief auch reibungslos.

Wann immer ich ein Team, ein Forum, News oder diverse andere Dinge anlegen möchte, erhalte ich folgende Fehlermeldung:
 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined function Contentify\getclass()

![grafik](https://user-images.githubusercontent.com/47409865/60725324-1a050680-9f39-11e9-81a8-b404189c1453.png)

Da dieser Fehler bei diversen Aktionen auftritt, denke ichm dass es sich eher um ein generelles Problem handelt. Hat irgendwer eine Lösung, eine Idee oder einen Rat?

Vielen Dank im voraus

Marco

**Comment by chriskonnertz** [comment]
Hallo,

 danke für das Melden dieses Bugs! Wertvolles Feedback.

Der Methodenname ist wohl  falsch geschrieben.

Bitte mal diesen Bugfix ausprobieren:

https://github.com/Contentify/Contentify/commit/a65b0e5e8421e3924ceb13db983d73649d0d039b

**Comment by ddb69** [comment]
Hallo, danke für den schnellen Fix. Das Problem tritt nicht mehr auf, aber beim Aufräumen der ganzen angelegten Dinge tritt der nächste Fehler auf. Auch hier wieder auf diversen Seite, ob News, Teams etc.

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR) 
Call to undefined function Contentify\deleteModelFiles()

![grafik](https://user-images.githubusercontent.com/47409865/60900382-5eabdd00-a26c-11e9-912e-593ae0d060d5.png)

**Comment by ddb69** [comment]
Ich bin mir ja gerade nicht so sicher ob die 3er-Version schon eine gewisse Einsatzreife hat.

Weitere Fehler:

1.Beim Anklicken der angelegten News:
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR) 
Call to undefined method ChrisKonnertz\OpenGraph\OpenGraphFacade::title()
![grafik](https://user-images.githubusercontent.com/47409865/60960946-5787dc00-a30b-11e9-8ca3-97de15c605dc.png)

2.Beim Anklicken von Matches (es sind zwar keine angelegt, aber so ein harter Fehler?):
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR) 
Type error: Return value of App\Modules\Matches\Match::scopeFilter() must be an instance of Illuminate\Database\Eloquent\Builder, none returned
![grafik](https://user-images.githubusercontent.com/47409865/60961035-8d2cc500-a30b-11e9-9875-3861d18a4758.png)

**Comment by ddb69** [comment]
Und noch einer. Beim Bearbeiten eines bereits angelegten Forums:
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR) 
Type error: Return value of Contentify\Uploader::uploadModelFiles() must be of the type array, none returned

![grafik](https://user-images.githubusercontent.com/47409865/60973580-d50e1500-a328-11e9-9e8e-b2a3b92250ef.png)

**Comment by chriskonnertz** [comment]
Hallo,

> Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined function Contentify\deleteModelFiles()

ein Syntaxfehler, wird hiermit behoben: https://github.com/Contentify/Contentify/commit/41491436138a5c2a5eb5ba23c77c7b18732decde

Danke für die Meldung! :)

**Comment by chriskonnertz** [comment]
> Beim Anklicken von Matches (es sind zwar keine angelegt, aber so ein harter Fehler?):
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Return value of App\Modules\Matches\Match::scopeFilter() must be an instance of Illuminate\Database\Eloquent\Builder, none returned

Probier mal bitte ob das hier hilft: https://github.com/Contentify/Contentify/commit/d6eb2735c71c341f57c559bb84a4befb92faed54

**Comment by chriskonnertz** [comment]
> Und noch einer. Beim Bearbeiten eines bereits angelegten Forums:
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Return value of Contentify\Uploader::uploadModelFiles() must be of the type array, none returned

Bitte diese Änderung probieren: https://github.com/Contentify/Contentify/commit/bd3f923b397e34474f00287a6f9be0cbb9952cf5

**Comment by chriskonnertz** [comment]
> Beim Anklicken der angelegten News:
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method ChrisKonnertz\OpenGraph\OpenGraphFacade::title()

Versuch mak das hier, ist aber ehrlich gesagt ziemlich geraten: https://github.com/Contentify/Contentify/commit/2c57ba0d30f72a466fb9c069f8e56381131ba0db

**Comment by chriskonnertz** [comment]
> Ich bin mir ja gerade nicht so sicher ob die 3er-Version schon eine gewisse Einsatzreife hat.

Der aktuelle Stand ist: Beta. Dementsprechend musst du leider mit Fehlern rechnen. Das ist unvermeidbar und die zu finden ja auch gerade Teil dieser Phase im Entwicklungsprozess. :bulb:

**Comment by ddb69** [comment]
> 
> 
> > Beim Anklicken der angelegten News:
> > Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
> > Call to undefined method ChrisKonnertz\OpenGraph\OpenGraphFacade::title()
> 
> Versuch mak das hier, ist aber ehrlich gesagt ziemlich geraten: [2c57ba0](https://github.com/Contentify/Contentify/commit/2c57ba0d30f72a466fb9c069f8e56381131ba0db)

Hallo, vielen Dank für die schnellen Korrekturen. Der geratene Fix im Zitat hat leider nicht geklappt, sonst alle gemeldeten Dinge prima. :)

Ich bin ja selber Entwickler und mir ist klar was Beta-Status heißt. Ich bin nur mit der naiven Vorstellung an die Sache gegangen dass die grundlegenden Funktionalitäten mehr oder weniger zuverlässig funktionieren. Aber wenn die Dinge so schnell gefixt werden, kann ich gerne fleißig weiter melden. Die Frage ist wie? Einfach weiter hier im Thread anhängen oder für jedes Thema einen neuen Issue aufmachen?

Einige Fehler habe ich noch. Hier aber erst mal nur ein ziemlich wichtiger für mich, da wir das Forum ungeachtet weiterer Bugs intern schon nutzen wollen. Und zwar kann ich "Membership" nicht ändern. Ich vermute dass das über den rot umrandeten Button geht:
![grafik](https://user-images.githubusercontent.com/47409865/61054648-2c2aed00-a3f0-11e9-90cd-e0b81c1e513d.png)

Bei Klick auf den Button erhalte ich allerdings folgenden Fehler:
ErrorException (E_ERROR) 
Type error: Return value of Contentify\Models\User::isActivated() must be of the type boolean, object returned (View: /XXX/contentify/app/Modules/Users/Resources/Views/admin_form.blade.php)
Previous exceptions
• Type error: Return value of Contentify\Models\User::isActivated() must be of the type boolean, object returned (0) 
![grafik](https://user-images.githubusercontent.com/47409865/61054785-77450000-a3f0-11e9-819f-196d8fcc73f8.png)

**Comment by chriskonnertz** [comment]
Hallo,

das sollte hierdurch behoben werden: https://github.com/Contentify/Contentify/commit/8eb5406505a3b01b057d16e47be1522398f70a64

Mit 3.0 sind halt Parameter- und Rückgabetypen hinzugekommen. Und wenn man wie in diesem Fall nicht exakt ist was die irgendwann mit PHPDocBlock angegebenen Typen angeht, macht es jetzt plötzlich Peng. 

Schätze auf so etwas wirst du irgendwo anders noch mal treffen. Lässt sich aber zum Glück im Normalfall schnell und einfach beheben.

**Comment by chriskonnertz** [comment]
ich würde vorschlagen, Fehler die du in den nächsten Tagen findest und melden willst, postest du einfach hier mit in das Issue. Dann sind sie gebündelt.

> Ich bin ja selber Entwickler und mir ist klar was Beta-Status heißt. Ich bin nur mit der naiven Vorstellung an die Sache gegangen dass die grundlegenden Funktionalitäten mehr oder weniger zuverlässig funktionieren. 

Es wurde einfach noch nicht viel getestet.

**Comment by ddb69** [comment]
Danke auch für den Fix. Aber genau auf der Seite taucht dann der nächste Fehler auf wenn ich eine Rolle zuweisen möchte:
 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Argument 2 passed to Contentify\ModelHandler::fillRelations() must be an instance of Contentify\Models\BaseModel, instance of App\Modules\Users\User given, called in /XXX/contentify/ModelHandler.php on line 495

![grafik](https://user-images.githubusercontent.com/47409865/61110827-7c558e00-a488-11e9-8158-42d84c41fe17.png)


In diesem Zusammenhang auch eine Frage. Ich hätte jetzt auf untenstehender Seite auch einen Button in der Actions-Spalte erwartet. Oder ist es nicht gewünscht dass existierende Rollen bearbeitet werden? Ist kein großes Problem, eigene Rollen gehen ja auch. Falls die Bearbeitung nicht nicht erwünscht ist, wo kann ich denn dann sehen welche Rechte diese Rollen haben?
![grafik](https://user-images.githubusercontent.com/47409865/61110921-a5761e80-a488-11e9-940c-175156238551.png)

Danke vorab schon mal. Klingt alles nicht sonderlich kompliziert was die Behebung betrifft, aber ich mag da ungern selber dran rumpfuschen, zumal auch Java eher meine Sprache ist. ;)

**Comment by chriskonnertz** [comment]
Genau, das sind Standard-Rollen die einfach da sein **müssen**. Die sollen nicht editiert werden; wenn man sie editeren möchte statt dessen einfach eine entsprechende neue Rolle erstellen.

Guter Punkt bezüglich der Frage, woher man eigentlich wissen soll, welche Rechte bei diesen Rollen gesetzt sind! Das fehlt definitiv. Habe dazu ein Ticket erstellt: https://github.com/Contentify/Contentify/issues/573

Als Workaround: Wennn du Datenbankzugriff z. B. mit phpMyAdmin hast kannst du in die Tabelle `roles` schauen, dort sind die Rechte der Rollen vermerkt.

**Comment by chriskonnertz** [comment]
>  Aber genau auf der Seite taucht dann der nächste Fehler auf wenn ich eine Rolle zuweisen möchte:
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Argument 2 passed to Contentify\ModelHandler::fillRelations() must be an instance of Contentify\Models\BaseModel, instance of App\Modules\Users\User given, called in /XXX/contentify/ModelHandler.php on line 495

Notfall-Workaround: In https://github.com/Contentify/Contentify/blob/3.0-dev/contentify/ModelHandler.php#L630 `BaseModel` rausnehmen.

**Comment by ddb69** [comment]
> 
> 
> > Aber genau auf der Seite taucht dann der nächste Fehler auf wenn ich eine Rolle zuweisen möchte:
> > Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
> > Type error: Argument 2 passed to Contentify\ModelHandler::fillRelations() must be an instance of Contentify\Models\BaseModel, instance of App\Modules\Users\User given, called in /XXX/contentify/ModelHandler.php on line 495
> 
> Notfall-Workaround: In https://github.com/Contentify/Contentify/blob/3.0-dev/contentify/ModelHandler.php#L630 `BaseModel` rausnehmen.

Dann gibt es leider den nächsten Fehler in Zeile 670 und ich denke das auch die darauffolgenden Zeilen kritisch sein werden. Ist hier mit einem echten Fix zu rechnen?

Vielen Dank auf jeden Fall schon mal für die schnelle Beantwortung und Bearbeitung.

Edit: Sorry, mein Fehler, aber die Frage nach dem echten Fix bleibt. :)

**Comment by chriskonnertz** [comment]
Probier bitte mal https://github.com/Contentify/Contentify/commit/0513fa13dac385641a98aba1a705926e054bb38e und https://github.com/Contentify/Contentify/commit/d6bdb83718d3e21ff8606bddbaca2e07bba3cb4c

**Comment by ddb69** [comment]
Danke Dir, funktioniert. :D

> 
> 1.Beim Anklicken der angelegten News:
> Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
> Call to undefined method ChrisKonnertz\OpenGraph\OpenGraphFacade::title()
> ![grafik](https://user-images.githubusercontent.com/47409865/60960946-5787dc00-a30b-11e9-8ca3-97de15c605dc.png)
> 

Dieser hier ist leider noch offen.

Außerdem habe einen Fehler gefunden wenn man bei Forums im Admin-Backend auf Config klickt:
 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Return value of Contentify\Models\ConfigBag::getFillable() must be of the type string, array returned
![grafik](https://user-images.githubusercontent.com/47409865/61182582-eeb7a100-a635-11e9-9500-08047db2f4af.png)

**Comment by chriskonnertz** [comment]
Hi,

okay für das erste: https://github.com/Contentify/Contentify/commit/0a16d9075b053c79932906af43de690d9b85380d

Für das zweite:
https://github.com/Contentify/Contentify/commit/cce142eb120856e7deb7319f7e5cb147d86bc5e6

**Comment by ddb69** [comment]
Grundsätzlich hat beides was bewirkt. Bei den News gibt es leider einen Folgefehler:
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR) 
Type error: Argument 1 passed to Contentify\Controllers\BaseController::openGraph() must be an instance of OpenGraph, instance of ChrisKonnertz\OpenGraph\OpenGraph given, called in /var/www/sites/gg.inperpetuum/src/contentify/app/Modules/News/Http/Controllers/NewsController.php on line 159
![grafik](https://user-images.githubusercontent.com/47409865/61441387-ceddf100-a945-11e9-9225-04b1b6c77899.png)

Unter Contact fehlt ein Button um irgendwas tun zu können:
![grafik](https://user-images.githubusercontent.com/47409865/61441504-12d0f600-a946-11e9-8c49-236cf74f31a7.png)

Wenn ich auf Forum Reports klicke, erhalte ich folgenden Fehler:
Illuminate \ Database \ QueryException (42000)
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'gg_inperpetuum.forum_reports.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select post_id, COUNT(id) as report_counter, MAX(updated_at) AS updated_at from `forum_reports` group by `post_id` order by `created_at` desc)
Previous exceptions
• SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'gg_inperpetuum.forum_reports.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (42000) 
![grafik](https://user-images.githubusercontent.com/47409865/61441824-b15d5700-a946-11e9-9b14-eee0fb2b1f16.png)

Ansonsten nutzen wir das Forum schon recht intensiv. Dabei sind mir ein paar Dinge aufgefallen, die Foren in der Regelm standardmäßig mitbringen. So vermisse ich zum Beispiel die Möglichkeit, BB-Code oder ähnliches zu verwenden oder allgemeiner gesprochen einfache Formatierungsmöglichkeiten. Außerdem fehlt mir die Möglichkeit, Dateien an einen Post anzuhängen und Grafiken einzubinden. Ist sowas für die Zukunft angedacht oder wäre das eventuell einen Feature Request wert?

**Comment by chriskonnertz** [comment]
> So vermisse ich zum Beispiel die Möglichkeit, BB-Code oder ähnliches zu verwenden oder allgemeiner gesprochen einfache Formatierungsmöglichkeiten. 

Huch, die gibt es aber. Probiert hast du es? :P

**Comment by chriskonnertz** [comment]
> Unter Contact fehlt ein Button um irgendwas tun zu können:

Es gibt dort keinen Button. Der bereich bezieht sich auf Nachrichten die über das Kontaktformular eingesendet werden. Ein "Erstellen"-Button wäre dort wenig sinnvoll da es sich um User Generated Content handelt.

**Comment by chriskonnertz** [comment]
> Wenn ich auf Forum Reports klicke, erhalte ich folgenden Fehler

Versuchmal den strikten Modus von MySQL zu deaktivieren: https://github.com/Contentify/Contentify/blob/3.0-dev/config/database.php#L50 `true` durch `false`ersetzen

**Comment by ddb69** [comment]
> 
> 
> > So vermisse ich zum Beispiel die Möglichkeit, BB-Code oder ähnliches zu verwenden oder allgemeiner gesprochen einfache Formatierungsmöglichkeiten.
> 
> Huch, die gibt es aber. Probiert hast du es? :P

Ups, vergiss alles, ich habe tatsächlich ein Leerzeichen im schließenden Tag gehabt, das ich übersehen habe. Sorry. ;)

Contact wusste ich nicht, aber habe ist verstanden.

MySQL probiere ich aus und gebe dann ein Feedback. Ansonsten wäre dann nur der Newsteil offen.

Danke. :+1:

**Comment by ddb69** [comment]
`    'connections' => [

        'mysql' => [
            'driver'    => 'mysql',
            /*
             * These settings are set by the installer and are stored in storage/app/database.ini
             */
            //'host'      => env('DB_HOST', '127.0.0.1'),
            //'database'  => env('DB_DATABASE', 'contentify'),
            //'username'  => env('DB_USERNAME', 'root'),
            //'password'  => env('DB_PASSWORD', ''),
            'port'      => env('DB_PORT', '3306'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset'   => 'utf8',            // Laravel 5.4 recommends utf8mb4
            'collation' => 'utf8_unicode_ci', // Laravel 5.4 recommends utf8mb4_unicode_ci
            'prefix'    => '',
            'strict'    => true,
            'engine'    => null,
            'modes'     => [
                'ONLY_FULL_GROUP_BY',
                'STRICT_TRANS_TABLES',
                'NO_ZERO_IN_DATE',
                'NO_ZERO_DATE',
                'ERROR_FOR_DIVISION_BY_ZERO',
                'NO_ENGINE_SUBSTITUTION',
            ]
        ],
`

Die Settings hatte ich schon so. Ich meine mich erinnern zu können dass dort mit der Einstellung "false" noch einieg SQL-Fehler mehr auftreten.

Dann haben wir aktuell noch den SQL-Fehler und den Fehler bei Klick auf News offen.

In Sachen Feature-Requests würde ich mir folgendes wünschen.
1.Bei den Downloads bereits auf Kategorien-Ebene die Möglichkeit "intern" anbieten.
2.Kategorien bei den Downloads hierarchisch anordnen, ähnlich wie Foren.
2.Im Forum Grafiken einbetten und Dateien anhängen

Meinst Du da geht was?

**Comment by chriskonnertz** [comment]
Auf die Schnelle geht das nicht, bestenfalls mittelfristig.

**Comment by ddb69** [comment]
Ich habe einen neuen Fehler gefunden. Und zwar wollte sich ein Mitglied einloggen, hatte das Passwort vergessen und hat dann so einiges probiert. Die Webseite hat zwar das Richtige gemacht, aber die Präsentation sollte nicht in Form eines harten Fehlers passieren, denke ich.
![ThrottleCheckpoint](https://user-images.githubusercontent.com/47409865/61938821-46d59800-af92-11e9-98d8-9c502d0d7310.jpg)

Der SQL-Fehler ist leider auch noch immer offen, ebenso wie der bei Klick auf die News.

Zu den Feature-Requests: Auch wenn da zeitnah nichts geht, soll ich die mal als Feature-Requests einstellen?

**Comment by chriskonnertz** [comment]
Hallo, 

ja du hast recht, da sollte keine solche interne Fehlermeldung angezeigt werden! Die müsste abgefangen und als normale Meldung auf der Website angezeigt werden.

Ok werde versuchen mir das am Wochenende anzuschauen, kann aber nichts versprechen.

**Comment by chriskonnertz** [comment]
Wegen der Fehlermeldung bei zu vielen fehlgeschlagenen Login-Versuchen: https://github.com/Contentify/Contentify/commit/a802cc5970a43f4ac53a9e255d9feb0d5afbc889

**Comment by ddb69** [comment]
Dieser Fehler hier ist leider nach wie vor offen:
 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Argument 1 passed to Contentify\Controllers\BaseController::openGraph() must be an instance of OpenGraph, instance of ChrisKonnertz\OpenGraph\OpenGraph given, called in /var/www/sites/gg.inperpetuum/src/contentify/app/Modules/News/Http/Controllers/NewsController.php on line 159

![grafik](https://user-images.githubusercontent.com/47409865/63106401-078fdb00-bf83-11e9-9087-4f35ed8f0c29.png)

Genau wie der gemeldete SQL-Fehler. Beides sehr unschön.

Neben den ganzen Fehlern habe ich aber noch eine andere Frage:
Kennst Du zufällig jemanden, der, selbstverständlich gegen Bezahlung, aus einem fertigen Design (psd-Datei mit allen Ebenen vorhanden) ein Contentify-Template erstellen kann oder wie ich danach suchen kann?
