### ISSUE TITLE
Modify Specific HTML/PHP Awards

### ISSUE THREAD

**Issue by PapyOak** [Contentify/Contentify#576]
- Contentify 3.0 beta
 - Windows 10 OS
[https://prnt.sc/on6bsv](url)
I'm looking for the HTML location of this page, in order to modify the tables

**Comment by PapyOak** [comment]
Same with this page which is the matches list
[https://prnt.sc/on6fre](url)

**Comment by chriskonnertz** [comment]
Hello,

these are not real pages, they jsut use a helper that renderes a page with a table on it. You would have to created apges for them. It's not difficult but requries a little bit of coding: Creating a tempalte file, adding some HTML and Blade code to it and then laoding the file in the controller.

**Comment by PapyOak** [comment]
Okay, so every pages that has a table are auto rendered or is there any exception?

**Comment by PapyOak** [comment]
Actually, I would like to modify the helper so it's not tables anymore. Where is it?

**Comment by chriskonnertz** [comment]
> Okay, so every pages that has a table are auto rendered or is there any exception?

I think that's correct. :+1:

**Comment by chriskonnertz** [comment]
> Actually, I would like to modify the helper so it's not tables anymore. Where is it?

The code that collects the data of the table is here: https://github.com/Contentify/Contentify/blob/2.6/contentify/ModelHandler.php#L57

The table is here: https://github.com/Contentify/Contentify/blob/2.6/contentify/HtmlBuilder.php#L117

(Oh these links are for 2.6 ... line numbers might be a bit different in 3.0!)

What exactly do you plan? That code is also used in the backend where you probably do not want to modify it.

**Comment by PapyOak** [comment]
> The code that collects the data of the table is here: https://github.com/Contentify/Contentify/blob/2.6/contentify/ModelHandler.php#L57
> The table is here: https://github.com/Contentify/Contentify/blob/2.6/contentify/HtmlBuilder.php#L117
> (Oh these links are for 2.6 ... line numbers might be a bit different in 3.0!)

Okay got it, shouldn't be too hard to modify it

> What exactly do you plan? That code is also used in the backend where you probably do not want to modify it.

I'm looking for a better way to show it to users. The tables are okay but I'm sure that there is a better way with bootstrap. Now I'm just going to look how it looks in the back end, and eventually create new pages.

**Comment by chriskonnertz** [comment]
You are right, minimalistic tables are not the most beautiful way to present information to the users. They are quite boring.
