### ISSUE TITLE
Bug - News updated_at changes

### ISSUE THREAD

**Issue by Franpepper** [Contentify/Contentify#577]
`updated_at` changes when superadmin open news

That causes that the order news in the main page is altered. With normal users it doesn't happen

Some way to show the news by its creation date, and not by the update date?

**Comment by DrCha0z** [comment]
My solution: 
replayce the value

"updatet_at" 
with
"published_at"

**Comment by chriskonnertz** [comment]
Should be solved:

https://github.com/Contentify/Contentify/commit/8dadc272982dbbd591814977fc81526295f7887f
