### ISSUE TITLE
Kontakt Spam

### ISSUE THREAD

**Issue by DrCha0z** [Contentify/Contentify#579]
Hey,

ich hatte auch das Problem mit dem Spamregister, darau hin habe ich recaptcha eingesetzt nach anleitung.
Inzwischen wird das Problem umgangen, ich habe trotz captcha nun wieder hunderte spam register.
Nun habe ich mich erstmal enschlossen die Registration zu Deaktivieren. Seit dem ich das geändert habe nehmen meine Kontakt Spams zu, könnte man da auch ein Recaptcha einsetzen?

Lg

Dennis

**Comment by chriskonnertz** [comment]
Hi Dennis,

ja an sich auf jeden Fall! Versuche mir das zeitnah anzuschauen um die
genaueres sagen zu können.

Leider bietet  ReCAPTCHA keinen kompletten Schutz, ich kenne das selber aus
einem Forum in dem ich aktiv bin, da ist das auch für die Registrierung
aktiv - und trotzdem wird es täglich von Bots überlaufen.

Viele Grüße

Chris

Am Do., 29. Aug. 2019 um 06:58 Uhr schrieb Dennis <notifications@github.com

**Comment by DrCha0z** [comment]
Leider kommen die Bots durch alles irgendwann wieder durch. Nur die Kontakt Spam Mails nerven langsam. Vor allem bekommen ja Alle Admins eine email als Benachichtigung. Aber man möchte sie ja auch nicht Ignorieren, es könnte ja auch mal was ernstes sein ;)
