### ISSUE TITLE
[Official] Installation Mini Guide

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#58]
1) Enable mod_rewrite if it's not enabled:
`sudo a2enmod rewrite`

2) Change the document root. You do not have to do it if you just want to test Contentify. The idea is to make only the `contentify/public` folder accessible from the outside. 

If you want to change it, open your apache config file (it's somewhere in `etc/apache/`) and change/add this line:
`DocumentRoot /var/www/html/public`
Well it's a bit more than just that but that's the main idea.

3) Install missing PHP extensions. You need these (you won't have to install all):
`mcrypt,
fileinfo,
pdo,
mbstring,
tokenizer,
openssl,
json`

For instance the script uses this command to activate mcrypt:
`sudo php5enmod mcrypt`

4) You have to create a database [surprise ;) ]

5) The CHMOD stuff:
`chmod -R 777 storage
chmod -R 777 bootstrap/cache
chmod -R 777 public/uploads
chmod -R 777 public/rss
chmod -R 777 public/share`

6) You should restart apache:
`sudo service apache2 restart`

7) Navigate to the installer: Navigate to `http://<your-ip-or-domain>/install.php` (or `http://<your-ip-or-domain>/public/install.php` if you have not changed the document root) with your browser. The installer will ask you to tell it the database connection details.

NOTE: You can just upload everything BEFORE step one and then do step 7) once before step 1). The installer will show you if the PHP version is >= 5.5.9 and which PHP extensions are missing.

_If you have trouble installing it let us know._

**Comment by krysennn** [comment]
if you want i have modify your script "digitalocean" for "scaleway".
i have got VPS servers with 2cores, 2gb ram, 50gb SSD, 1 IPV4 for 2.99€/Month.
http://163.172.152.153/install.sh

I'm on debian 8.2 with PHP 5.6.20-0+deb8u1.

**Comment by chriskonnertz** [comment]
Okay sounds promising! How in the world do they manage to only demand 3 €/month for that hardware? What is it that I'm missing? There must be a catch! ;)

**Comment by krysennn** [comment]
In France we would the world for nothing so this host make this offer :P ^^
Seriously i dont know, but i'm happy ^^

It's french hoster -> Online.net and Online it's ISP in france (name: FREE)
Online is concurrent of OVH (ovh it's 3.59€/month for 1core 2.4ghz, 2go ram and 10 go ssd).

**Comment by Hisosow** [comment]
Hey ! Thanks for the mini guide, I have a little issue on my side.

I've ran the install.php but if I go to the index.php I have the following:

_Sorry, the page you are looking for could not be found.
NotFoundHttpException in RouteCollection.php line 161:_

http://www.noelshack.com/2016-43-1477433650-screen-shot-2016-10-25-at-6-13-20-pm.png

Any idea ? Thanks in advance !
