### ISSUE TITLE
Error when trying to display profile

### ISSUE THREAD

**Issue by caileanofficial** [Contentify/Contentify#581]
Hello
I am using the Contentify Beta 3.0
It is deployed on a shared hosting at Unoeuro on a Linux server, with MySQL - i do not know if it is Nginx or Apache

I have logged in on my admin account and try to click into my profile then i get

 /var/www/website/public_html/newsite/contentify/Models/User.php
 
    /**
     * Returns true if the current user is a super admin
     * 
     * @return boolean
     */
    public function isSuperAdmin() : bool
    {
        return $this->hasAccess('superadmin');
    }
 
    /**
     * The throttle system is not part of the Sentinel core module.
     * This helper method accesses the activated attribute.
     *
     * @return boolean
     */
    public function isActivated() : bool
    {
        return Activation::completed($this);
    }
 
    /**
     * This is a copy of a BaseModel method (for compatibility).
     * 
     * @return boolean
     */
    public function isSoftDeleting() : bool
    {
        return property_exists($this, 'forceDeleting');
    }
 
    /**
     * This is a copy of a BaseModel method (for compatibility).
     * 
     * @param  bool $local If true, return a local path (e. g. "C:\Contentify\public/uploads/games/")
     * @return string
     */
    public function uploadPath(bool $local = false) : string
    {
Arguments
"Type error: Return value of Contentify\Models\User::isActivated() must be of the type boolean, object returned"

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Return value of Contentify\Models\User::isActivated() must be of the type boolean, object returned

**Comment by chriskonnertz** [comment]
Hello,

you seem to use an old revision. The problem has been fixed already:

https://github.com/Contentify/Contentify/blob/3.0-dev/contentify/Models/User.php#L396

**Comment by caileanofficial** [comment]
> Hello,
> 
> you seem to use an old revision. The problem has been fixed already:
> 
> https://github.com/Contentify/Contentify/blob/3.0-dev/contentify/Models/User.php#L396

might be because i downloaded it through the "releases" tab
