### ISSUE TITLE
file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0

### ISSUE THREAD

**Issue by GamerzReef** [Contentify/Contentify#582]
Hi guys i am trying to install this but ever time i hit next after Create super-admin user i get this error.
file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0
fopen is set to on on the server.

Help on this will be great?.

**Comment by chriskonnertz** [comment]
Hi,

I'm assuming that you get a little bit more text then just than? Can you please copy and paste the whole error message? It schould include information such as the file and line number where the error occured.
