### ISSUE TITLE
Images not uploading

### ISSUE THREAD

**Issue by Impulse1337** [Contentify/Contentify#583]
Hi,

I recently installed Contentify, and for some odd reason, my images aren't uploading to the site. As i can see trough FTP, the images aren't on the server aswell. 

There isn't anything on the wiki where this is highlighted

 to what the issue can be. Maybe you can point me in the right direction?

![Screenshot_1](https://user-images.githubusercontent.com/7289057/65526241-17d79600-def1-11e9-8c89-68527531fe9b.png)
![Screenshot_2](https://user-images.githubusercontent.com/7289057/65526242-17d79600-def1-11e9-918f-9b70354b294b.png)

**Comment by chriskonnertz** [comment]
Hi,

make sure that uploading images is possible at all:
- is it even possible to write in the `pubpic/uplaods` directory **and its sub directories**? (CHMOD)
- GD Lib extension for PHp installed?

**Comment by Impulse1337** [comment]
yes, i can upload to the directorys, as in the installation guide i used chmod 777 on the directories
gd is enabled.

**Comment by Impulse1337** [comment]
Hello?

**Comment by chriskonnertz** [comment]
Hello, please try again and then take a look at the log. ( You can reach the Log in the Backend on the settings page. )

**Comment by Impulse1337** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/7289057/68672499-0a827380-0552-11ea-98d8-d0a7796fe0b3.png)
there you go. This is what happens after the logo upload https://pastebin.com/JddUMqt5
The tekst in the title isn't empty btw. i've used test as a title

**Comment by DrCha0z** [comment]
Hey,
ich denke mal das ich den selben oder einen ähnlichen Fehler habe / hatte.

Ich bekomme beim Upload auch eine Fehlermeldung das etwas schief gegangen ist. Aber danach ist das Bild trotzdem in der Gallerie, es wird lediglich nicht in der Vorschau und im Adminbereich angezeig. 

Dafür gibt es aber eine Lösung.
Hier ein Auszug aus der "admin_index.blade.php"

```
<div class="toolbar top">
    {!! button(trans('app.create'), route('admin.images.create'), 'plus-circle') !!}

    <div class="model-search-box">
        {!! Form::open(['url' => URL::current().'/search']) !!}
                {!! Form::text('search', $searchString, ['class' => 'search-string']) !!}
                {!! Form::submit(trans('app.search'), ['class' => 'btn btn-default']) !!}
        {!! Form::close() !!}
    </div>
</div>

<div class="clearfix">
    @foreach ($images as $image)
        <div class="image" style="background-image: url('{{ $image->uploadPath().'200/'.$image->image }}')">
            <a class="show" href="{{ $image->uploadPath().$image->image }}" target="_blank"></a>
            <div class="info">
                {{ $image->tags }}
                @if ($image->gallery)
                    <div class="gallery">{!! link_to('galleries/'.$image->gallery->id, 'Gallery: '.e($image->gallery->title)) !!}</div>
                @endif
            </div>
            <div class="actions">
                {!! icon_link('edit', trans('app.edit'), route('admin.images.edit', [$image->id])) !!}
                {!! icon_link('trash', trans('app.delete'), route('admin.images.destroy', [$image->id]).'?method=DELETE&_token='.csrf_token(), false, ['data-confirm-delete' => true]) !!}
            </div>
        </div>
    @endforeach
</div>

{!! $images->render() !!}
```

In Zeile 14 steht folgendes:

`<div class="image" style="background-image: url('{{ $image->uploadPath().'200/'.$image->image }}')">`

Hier muss dies entfernt werden, dann klappt es auch:     **.'200/'**

danach sollte das ganze so aussehen:

```
<div class="toolbar top">
    {!! button(trans('app.create'), route('admin.images.create'), 'plus-circle') !!}

    <div class="model-search-box">
        {!! Form::open(['url' => URL::current().'/search']) !!}
                {!! Form::text('search', $searchString, ['class' => 'search-string']) !!}
                {!! Form::submit(trans('app.search'), ['class' => 'btn btn-default']) !!}
        {!! Form::close() !!}
    </div>
</div>

<div class="clearfix">
    @foreach ($images as $image)
        <div class="image" style="background-image: url('{{ $image->uploadPath().$image->image }}')">
            <a class="show" href="{{ $image->uploadPath().$image->image }}" target="_blank"></a>
            <div class="info">
                {{ $image->tags }}
                @if ($image->gallery)
                    <div class="gallery">{!! link_to('galleries/'.$image->gallery->id, 'Gallery: '.e($image->gallery->title)) !!}</div>
                @endif
            </div>
            <div class="actions">
                {!! icon_link('edit', trans('app.edit'), route('admin.images.edit', [$image->id])) !!}
                {!! icon_link('trash', trans('app.delete'), route('admin.images.destroy', [$image->id]).'?method=DELETE&_token='.csrf_token(), false, ['data-confirm-delete' => true]) !!}
            </div>
        </div>
    @endforeach
</div>

{!! $images->render() !!}
```

Dies muss dann auch in der index.blade.php angepasst werden, dann Funktioniert das ganze.
Der Uploadfehler ist natürlich trotzdem noch da obwohl es keinen Fehler gibt. **Aber ich schaue mal wie das ganze dann in der 3.0 aussieht, denn der Fehler hat sich bei mir erst im Laufe der Zeit eingeschlichen und war nicht von Anfang an da.**

Lg

Dennis
