### ISSUE TITLE
News - Beim Anschauen ändert sich Datum updated_at

### ISSUE THREAD

**Issue by ddb69** [Contentify/Contentify#584]
Ich beziehe mich auf Contentify 3.0. Wenn ich das richtig sehe, hatte die 2.6er-Version den Fehler auch schon.

Eigentlich steht alles im Betreff. Die Datenbankspalte "updated_at" ändert sich auf den aktuellen Timestamp. Das ist sehr ärgerlich, so stehen ständig andere News oben und es ist nicht mehr nachvollziehbar. Es ist auch unerheblich ob der Besucher eingeloggt ist oder nicht.

Darüber hinaus möchte ich nochmal an folgendes erinnern, da hatten wir v or weit über einem Monat per Mail was besprochen, inzwischen musste ich aber doch was selber fixen weil sich nichts tut:
https://github.com/Contentify/Contentify/issues/580

**Comment by chriskonnertz** [comment]
Hallo,

leider kann ich zu dem Bug wenig sagen... der ist bekannt, ich weiß aber nicht, wodurch er ausgelöst wird.

**Comment by ddb69** [comment]
Hallo Chris,

mach' Dir keinen Stress wegen der von mir gemeldeten Bugs. Ich bin auf  
ein anderes CMS umgestiegen weil mir die Behebung der Bugs einfach zu  
lange dauert und weil die Reaktionszeit einfach zu groß ist. Ich weiß,  
ist erklärbar und verständlich, aber so ist es für mich einfach nicht  
zu gebrauchen, auch wenn es grundsätzlich ein schönes CMS ist.

Gruß

Marco

Zitat von Chris Konnertz <notifications@github.com>:

> Hallo,
>
>   leider kann ich zu dem Bug wenig sagen... der ist bekannt, ich  
> weiß aber nicht, wodurch er ausgelöst wird.
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].



Links:
------
[1]  
https://github.com/Contentify/Contentify/issues/584?email_source=notifications&email_token=ALJWVSIIBP4FB34TKMCSTVLQTKKCJA5CNFSM4I47EBA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDZ76CY#issuecomment-552861451
[2]

**Comment by DrCha0z** [comment]
Ich habe das Problem auch schon am Anfang der V2.5 gehabt. Ich habe da eine Lösung für mich gefunden ich nutze nicht die Variable "updatet_at" sondern nutze dafür "published_at"

**Dies ist keine Behebung des Bugs, aber ich umgehe ihn damit. Und das meiner Meinung nach trotzdem Sauber.**

Hier mal ein Auszug aus meiner "stream_item.blade.php"

```
@if ($item->itemType == 'news')
    <div class="item news" data-timestamp="{{ $item->published_at->timestamp }}" data-time-offset="{{ $item->updated_at->offsetHours }}" data-more={{ $more }}>
        <div class="meta above clearfix">
            <div class="category pull-left">
                {!! HTML::fontIcon('newspaper') !!}{!! trans('app.object_news') !!}
            </div>
            <div class="comments pull-right" title="{!! trans('app.comments') !!}">
                {!! HTML::fontIcon('comments') !!} {{ $item->countComments() }}
            </div>
        </div>

        @if ($item->newsCat->image)
            <a class="image text-hide" href="{!! 'news/'.$item->id.'/'.$item->slug !!}" style="background-image: url({!! $item->newsCat->uploadPath().$item->newsCat->image !!}">{{ $item->title }}
            </a>
        @endif

        <h2 title="{{ $item->title }}">
            <a href="{!! 'news/'.$item->id.'/'.$item->slug !!}">{{ $item->title }}</a>
        </h2>

        <div class="meta below">
            <time>{{ $item->published_at }}</time> - {!! link_to('users/'.$item->creator->id.'/'.$item->creator->slug, $item->creator->username) !!}
        </div>
    </div>
@endif
```

Wie gesagt für mich war das eine gute Lösung, ich habe zumindest nun immer meine Aktuelle News oben.

**Comment by chriskonnertz** [comment]
Danke, ich übernehme das jetzt mal, sonst kommen wir da nie weiter...

https://github.com/Contentify/Contentify/commit/8dadc272982dbbd591814977fc81526295f7887f

Bei dir @DrCha0z ist übrigens noch ein `updated_at` übersehen worden 😛

**Comment by DrCha0z** [comment]
Danke, tatsächlich. Ging witziger weise trotzdem ;)
