### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Stormez1998** [Contentify/Contentify#585]
Hay,
i need some help pls.
I have upload the files into my var/www/html path.
I have give all rights 777 to the Folders, but wehn i type in my URL with the install .php i see the install screen, its all green. When i want to klick on Install it shows me 404

![Not Found](https://user-images.githubusercontent.com/57358176/68126199-89086100-ff13-11e9-9318-6735ed8931ef.PNG)

Can anyone help me to fix this please?

Best wishes

**Comment by Franpepper** [comment]
Rewrite module is enabled?

**Comment by Stormez1998** [comment]
Yes

**Comment by chriskonnertz** [comment]
Hello,

please try something like `http://your-domainname.com/public` - does this work?

**Comment by Stormez1998** [comment]
@chriskonnertz 
when i type this in the URL i get Http Error 500

**Comment by Franpepper** [comment]
What version of php you have?

And we can see your .htacess file?

**Comment by Stormez1998** [comment]
@Franpepper 
Php 7.3
Where i can find the .htacess file ?
