### ISSUE TITLE
Installation fails at step 4

### ISSUE THREAD

**Issue by LeventeNagy** [Contentify/Contentify#586]
Hi

The installation fails at step 4, all credentials are fine, I am running version 2.6, are server requirements are fine

The following error occurs

`SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' (SQL: SHOW TABLES LIKE "migrations")`

**Comment by Stormez1998** [comment]
Have you create a User in mysql and enter it in the requierd field?

**Comment by chriskonnertz** [comment]
Hello,

hmmmm... I am not familiar with this error! Please can you tell me your MySQL version?

And please tell me: do you have access to the MySQL server? Could you maybe try to change the value of the variable `sql_mode` to the value of `NO_AUTO_CREATE_USER` manually?

**Comment by LeventeNagy** [comment]
Sorry for the slow reply I was away, I did some googling around and one thing solved the problem.

In the database.php if I change strict from true to false in the MySQL setting everything is alright, no problems at all

**Comment by chriskonnertz** [comment]
Oh right, yeah that was a good idea. :+1: 

I close this issue since it has been solved.
