### ISSUE TITLE
.htaccess file for the root folder?

### ISSUE THREAD

**Issue by eodclan** [Contentify/Contentify#59]
Hello, you might be able to create a .htaccess file to provide for the root directory?

**Comment by chriskonnertz** [comment]
Hello.

Did you see there is a `.htaccess` in the `public`folder?

**Comment by eodclan** [comment]
htaccess file no exists in my publicfolder.
Wegen den rewrite kommt das und weil in den root ordner der website keine vorhanden ist läuft die seite nicht richtig.

**Comment by krysennn** [comment]
Hello,

you can see the .htaccess of public folder here: https://github.com/Contentify/Contentify/blob/master/public/.htaccess

copy/paste the code in .htaccess and put it in your public folder

**Comment by chriskonnertz** [comment]
Yep.

> Wegen den rewrite kommt das und weil in den root ordner der website keine vorhanden ist läuft die seite nicht richtig.

Ja. Der "goldene Weg" ist deine Server-Einstellungen so zu ändern, dass dein Server nur `public` nach draußen frei gibt. Oft ist ja bei Linux-Servern `var/www/html` der öffentliche Ordner. Das kann man aber ändern, sprich so das wenn bei dir alle in `html` liegt `var/www/html/public` der öffentliche Ordner wird. Es gibt andere Wege aber das ist der vorgesehene. Dazu musst du (sofern dein Webserver ein Apache ist) die Apache Konfigurationsdatei ändern. Dort änderst/fügst du dann das hier ein: `DocumentRoot /var/www/html/public`

**Comment by eodclan** [comment]
Kein Problem...der Fehler ist beseitigt. :)

Nur jetzt kommt der nächste Fehler und zwar bei den Modul Kontakt.

[2016-05-10 17:25:53] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/xxx/data/www/xxx/storage/framework/views/d4336408a31fd9be620041724f53fce2:3

**Comment by chriskonnertz** [comment]
Hm... Ist das die Website mit dem Theme von der Demo? Glaube da war so ein Fehler drin. Der eigentlich behoben sein sollte...

Erster Schritt wäre alle Order + Dateien im Ordner `storage/framework/views` zu löschen. Denn vielleicht liegt da noch was altes im Cache...

**Comment by eodclan** [comment]
Ok, danke dir. Nun ist alles Fehlerfrei. 
Es währe aber schön, wenn es ein Support Forum geben würde.
Wenn du kein Platz oder möglichkeit hast, dann melde dich ruhig bei mir, denn habe noch genug Platz auf meine Roots.

**Comment by chriskonnertz** [comment]
> Ok, danke dir. Nun ist alles Fehlerfrei. 
Super!

> Es währe aber schön, wenn es ein Support Forum geben würde.
Gute Idee, ein Forum ist auch bereits in Planung. Es wird noch ein wenig auf sich warten lassen aber definitiv mittelfristig kommen.

> Wenn du kein Platz oder möglichkeit hast, dann melde dich ruhig bei mir, denn habe noch genug Platz auf meine Roots.
Danke für das Angebot. Denke jedoch das wird kein Problem sein. Es steht zwar in der Tat nur begrenzter Webspace zuur Verfügung, aber ein Forum an sich verursacht ja keine so großen Daten. Wobei... Das klingt so nach den berühmten letzten Worten, und ein paar Jahre später ist der Speicher voll. ;) Naja dann kann man immer noch reagieren.
