### ISSUE TITLE
Fehler bei Installation

### ISSUE THREAD

**Issue by Stormez1998** [Contentify/Contentify#599]
Tips to create a new issue

- Contentify 2.6
Auf Linux Debian 9.0,
Apache, PHP 7.4.6
   
Ich habe folgendes Problem bei der Installation.
Beim Installieren ist alles grün und Ordnerrechte sind gesetzt.
bekomme aber nach der Eingabe der Datenbank folge Meldung angezeigt.

"ErrorException Trying to access array offset on value of type int"

Kann mir jemand dabei helfen?

Lieben Dank

**Comment by chriskonnertz** [comment]
Hey,

hast du Zugriff auf den Error-Log? Der befindet sich in `storage/log` (Achtung: Kann Passwörter enthalten, diese ggf. entfernen). Wäre super wenn du den hier posten könntest. Den die Fehlermeldung an sich ist zwar durchaus explizit aber es ist unklar __wo__ der Fehler aufgetreten ist.

**Comment by Stormez1998** [comment]
@chriskonnertz 

Das Problem hat sich durch eine neuinstallation vom Server beheben lassen.
Allerdings habe ich ein problem mit der mail.php. Diese lässt sich leider nicht verbinden. Könntest du mir da auch helfen? 
und 2 Wenn ich mir mit einem Admin Account ein Benutzerprofil ansehen will wird folgende Meldung angezeigt: Zugriff verweigert. Sie verfügen nicht über die benötigten Berechtigungen.

Vielen Dank

**Comment by chriskonnertz** [comment]
Hey,

klar kann ich gerne versuchen dir zu helfen, weiß aber gerade nicht genau, wie?

1. Mail: Was heißt verbinden? Zu einem externen Service? Tja schwer zu sagen was da schief läuft... Config-Daten genauestens überpürft?

2. Das klingt komisch.  Was für ein Admin.Account ist das denn? Der SUper-Admin der bei der Installation erstellt wird? Der sollte alle Rechte haben und auf alles zugreifen können.
