### ISSUE TITLE
Add french translation

### ISSUE THREAD

**Issue by krysennn** [Contentify/Contentify#60]
If some people would help me for translate Contentify in french, not problem ;)

Si vous êtes chaud pour traduire Contentify en français ce sera avec plaisir :)

**Comment by krysennn** [comment]
If some people would help me for translate Contentify in french, not problem ;)

Si vous êtes chaud pour traduire Contentify en français ce sera avec plaisir :)

**Comment by Lendarid** [comment]
Je peux t'aider, tu as besoin de quoi ?

**Comment by krysennn** [comment]
Finalement j'ai bien avancé sur la traduction, si jamais tu utilises contentify et que tu remarques des erreurs de traduction n'hésite pas à nous les remonter ;)

Merci à toi
