### ISSUE TITLE
Navigation hardcoded?

### ISSUE THREAD

**Issue by pguetschow** [Contentify/Contentify#600]
Gerade 3.0-dev gecloned, um das Projekt für meinen Clan zu evaluieren und ich wundere mich, dass die Hauptnavigation in den Blade Templates hardcoded ist. Ist das noch geplant, das Hauptmenü konfigurierbar zu machen oder habe ich diese Funktion übersehen?

**Comment by chriskonnertz** [comment]
Hi,

ja klar, dass das nicht schön ist - keine Frage!

Theoretisch kann man das schon selber lösen, da man im Backend Navigations-Objkete anlegen und verwalten kann, man könnte dann die starre Navi dadurch ersetzen (Navigation-Widget).

Ganz konkrekt plane ich aber nicht das per default zu machen, andere Dinge haben höhere Prio.
