### ISSUE TITLE
So many problem (step 4 )

### ISSUE THREAD

**Issue by PandaxCSGO** [Contentify/Contentify#601]
- 2.6
- Please mention any special environment characteristics. For example: 
    - Using Shared Hosting
    - Apache (PHP 7.4)
    - MariaDB
- I use Shared Hosting ( Hebergnity.com) 

I have so many problem ( i don't have screen all of problem )
![image](https://user-images.githubusercontent.com/31318425/77450124-239a0b80-6df3-11ea-8d41-2e03815988a2.png)

**Comment by chriskonnertz** [comment]
Hey,

have you tired this? https://github.com/Contentify/Contentify/wiki/Troubleshooting#open_basedir-restriction-in-effect

**Comment by PandaxCSGO** [comment]
> Hey,
> 
> have you tired this? https://github.com/Contentify/Contentify/wiki/Troubleshooting#open_basedir-restriction-in-effect

No i go test this

**Comment by PandaxCSGO** [comment]
i have "No input file specified."

**Comment by PandaxCSGO** [comment]
after https://github.com/Contentify/Contentify/wiki/Troubleshooting#open_basedir-restriction-in-effect

**Comment by PandaxCSGO** [comment]
@chriskonnertz ?
