### ISSUE TITLE
ReflectionException

### ISSUE THREAD

**Issue by Wirloo** [Contentify/Contentify#602]
- Contentify 2.6
- Please be careful when posting logs, they might contain passwords!
- Please mention any special environment characteristics. For example: 
    - using f Linux,
    - using Apache,
    - using  MySQL

- Virtual machine google lamp

![sdfdsf](https://user-images.githubusercontent.com/58761424/77497526-cda68180-6e4d-11ea-92b7-fdcecea270b8.png)

**Comment by chriskonnertz** [comment]
Hey,

uhm at this point... honestly... I'm not going to do much trouble shooting here, but instead I'll focus to finally get 3.0 done. Once it's realeased ( should be done in a couple of days ) pelase try 3.0 and then let me know if that exceptinon still is thrown!

Sorry but not having enough time to focus on 2.6 now :P
