### ISSUE TITLE
User Teams

### ISSUE THREAD

**Issue by jointothedarkside** [Contentify/Contentify#603]
Hi there I find a bit complicated to join a friends team or there's no option for the user that created the team to add members.

The only way I find so far with the 2.6 version is to use the search box with the name of the team and click join, a way to invite somebody to join your created team would be nice. Or perhaps to see that information in the friend's profile (That's what I'll try to implement).

Another improvement I can think of is to provide a user's guide a bit more explained, I'm not an experienced user so I still don't know how to use blade's yield o sections, I'm not sure if I have to create the @include blade file in the main views folder or inside the Modules, I'm asking because navigating through the same page over and over can be a little repetitive.

Thanks guys, besides those points I find it great. 👍

**Comment by chriskonnertz** [comment]
Hello,

> Hi there I find a bit complicated to join a friends team or there's no option for the user that created the team to add members. The only way I find so far with the 2.6 version is to use the search box with the name of the team and click join, a way to invite somebody to join your created team would be nice. Or perhaps to see that information in the friend's profile (That's what I'll try to implement).

You are  talking about the cups module, right?

**Comment by chriskonnertz** [comment]
> Another improvement I can think of is to provide a user's guide a bit more explained, 

Yeah I agree to that! However it's a lot of work! Did you gave the wiki ( https://github.com/Contentify/Contentify/wiki  ) a try?

If that' snot sufficent I recommend to read the Laravel documentation! Here, this should help you with your specific issue: https://laravel.com/docs/5.5/blade

**Comment by jointothedarkside** [comment]
> > Another improvement I can think of is to provide a user's guide a bit more explained,
> 
> Yeah I agree to that! However it's a lot of work! Did you gave the wiki ( https://github.com/Contentify/Contentify/wiki ) a try?
> 
> If that' snot sufficent I recommend to read the Laravel documentation! Here, this should help you with your specific issue: https://laravel.com/docs/5.5/blade

Oh yes I read all of it, thanks a lot, and yes I'm talking about the cup teams, I wish it was easier for the users to invite someone to join their team, about the bleads I understand but when I create a theme, does it only compile the 'layout.blade.php' at the main views folder? I mean nothing is taken from the modules/theme folder right?
Thanks a lot for your time, great job again

**Comment by chriskonnertz** [comment]
>  when I create a theme, does it only compile the 'layout.blade.php' at the main views folder? I mean nothing is taken from the modules/theme folder right?

Is that question still unanswered?
