### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#604]
Suggestion from a user (via email):

> 1- login/register using discord.
2- Fix Twitch Integration
3- Ability to add an instagram video in the videos section on the mainpage

**Comment by DrCha0z** [comment]
1- login/register using discord. **

> (Wird das jeh einer benutzen? gibt es Community die so stark in DC vertreten sind und keine andere der loggin methoden nutzen würden?!)

**
2- Fix Twitch Integration **

> (fände ich auch gut ;)   )

**
3- Ability to add an instagram video in the videos section on the mainpage **

> (Finde ich überflüssig, da wär es sinnvoller Insta als Standart im Profiel zu verwenden denke ich)

**

Aber finde gut das immer und immer noch Vorschläge rein kommen.

**Comment by chriskonnertz** [comment]
zu 1) Weiß ich nicht... aber Discord wird immer verbreiteter, insofern, wenn mal die Zeit ist, würde ich sagen: Kann man schon machen

zu 3) Kann ich ebenfalls nicht beurteilen aber wenn das nicht aufwendig ist würde ich es umsetzen um da vollständiger zu sein
