### ISSUE TITLE
Fehler bei der Installation

### ISSUE THREAD

**Issue by DrTatsu96** [Contentify/Contentify#605]
Tips to create a new issue

- Please mention the version of Contentify that you use
- Please be careful when posting logs, they might contain passwords!
- Please mention any special environment characteristics. For example: 
    - using Windows ,
    - using  Apache,
    - using  MySQL
- Please mention the type of hosting (XAMPP)

Hallo, ich habe ihnen heute schon mal eine Mail geschrieben wo ich es über Web-Hoster Anbieter versucht habe. aber mir ist aufgefallen das mir dort 2 dinge fehlen aber ich diese dort nicht installiert bekomme, deswegen wollte ich es auf dem Lokalen weg versuchen und habe auch, Composer und Laravel installiert.

so nun habe ich ihre CMS herruntergeladen und in meine htdocs gepackt! die database.php bearbeitet eine Datenbank angelegt. Und dann bin ich auf die Url localhost/public/ 

dann kam auch die install seite wo alles gecheckt wurde und ich auf Launch installer klicken konnte!
dies tat ich dann auch und dann zack kam die nächste fehlermeldung! 

(1/1) NotFoundHttpException
--
in RouteCollection.php (line 179)
at RouteCollection->match(object(Request))in Router.php (line 546)
at Router->findRoute(object(Request))in Router.php (line 525)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

Leider bin ich nicht so ein Profi um zu erkennen was ich jetzt falsch gemacht habe, 

vllt kann mir einer von euch Helfen und mir sagen wie ich was zu machen habe.

mfg

**Comment by chriskonnertz** [comment]
Hallo,

dass beim Klick auf den "Launch Installer" Button eine weiße Seite kommt bedeutet wahrscheinlich, dass es einen Fehler gibt. Der jedoch aufgrund der Servereinstellungen nicht angezeigt wird. 

Ich würde vorschlagen mal in den Error-Log zu schauen, der sich im Ordner `<contentify>/storage/logs` befindet.

**Comment by DrTatsu96** [comment]
Also ich habe auf der Online Website im Log geschaut und auf Localhost log geschaut da steht überall das gleiche drin

**Comment by chriskonnertz** [comment]
Und da steht nur die NotFoundHttpException drin? 

Hast du irgendwie sehr exotischen Webspace? 🤔

**Comment by DrTatsu96** [comment]
Ne eigentlich nicht

Chris Konnertz <notifications@github.com> schrieb am Mi., 15. Apr. 2020,
17:26:

**Comment by chriskonnertz** [comment]
Verwendest du Apache als Webserver?

Und wenn ja, siehst du bei der Übersicht unter `localhost/public/` dann das hier?

> mod_rewrite enabled: Yes
