### ISSUE TITLE
Issue Installation v. 2.6

### ISSUE THREAD

**Issue by MajorOli** [Contentify/Contentify#606]
Tips to create a new issue

- Please mention the version of Contentify that you use
- Please be careful when posting logs, they might contain passwords!
- Please mention any special environment characteristics. For example: 
    - using Windows instead of Linux,
    - using Nginx instead of Apache,
    - using MariaDB instead of MySQL
- Please mention the type of hosting (shared hosting, virtual server, etc.)

--------------------------

- Version 2.6
- [laravel.log](https://github.com/Contentify/Contentify/files/4471231/laravel.log)
- Use Windows / Apache / MySql
- Localhost

Bei der Installation nach der Eingabe der DB Connection erfolgt die Fehlermeldung:
Class ChrisKonnertz\Jobs\JobsCommand does not exist

Log hängt an

**Comment by chriskonnertz** [comment]
Hallo,

ist das eine Neuinstallation? Dann würde ich raten bis zum Release von Version 3 zu warten und die benutzen. Denn der Fehler ist mir glaube ich bekannt aber ich habe nicht vor den noch zu fixen, in v3 ist der obsolet.

Schau einfach in circa einer Woche nochmal vorbei. :)

**Comment by MajorOli** [comment]
Ja das ist eine Neuinstallation. Okay dann warte ich bis v3
