### ISSUE TITLE
Game icons are missing

### ISSUE THREAD

**Issue by renegade1337** [Contentify/Contentify#608]
In der 3.0-dev Version Fehlen bei einer Neuinstallation folgende Game Icons: Minecraft, Overwatch, PUBG, Fortnite.

In dem Zusammenhang könnte man auch noch Valorant hinzufügen ^^

**Comment by chriskonnertz** [comment]
Hallo,

danke für die Info und ja Valorant hinzuzufügen erscheint mir auch sinnvoll, done.

https://github.com/Contentify/Contentify/commit/4630a7aaa5347e83c0d21f189fca980d06d7c33c
