### ISSUE TITLE
Problem with nav, and adding pages PLEASE HELP

### ISSUE THREAD

**Issue by elektrikmoonkey** [Contentify/Contentify#626]
Hi There 
Recently i have found this CMS and it seems nice but i cant figure out how to create the simple things. 

Tried installing over and over again wtih different pHp version, etc and the result is always the same. 
I cant view a page that i create on the admin panel. 
The db gets this new entry. But the only page i can see is the one that is already there very "Impressum" kkk 
link comes visible public/pages/1 as well as 
pages/impressum and 
/impressum
The other one, Custom Page,  blogs post and Custom Content error 
2/2) NotFoundHttpException
No query results for model [App\Modules\Pages\CustomPage].

Tried fixing the problem 
and 
$customPage = CustomPage::whereSlug($slug)->published()->firstOrFail(); 
results as failled 

As i said is inside the db pages so. i dont know what to do more. 

Please any advice to fix this? Is it a bug or something i am doing wrong or not doing ?

Thanks

**Comment by elektrikmoonkey** [comment]
Changing 
  public function show(int $id , string $slug = null, $isImpressum = false)
    to 
 public function show(int $id = null, string $slug = null, $isImpressum = false)

Fixed the above error 
 NotFoundHttpException
No query results for model [App\Modules\Pages\CustomPage].

But returns with the 404 :/

**Comment by elektrikmoonkey** [comment]
ok guys i found the problem 
was missing the .env with my db details 
Cheers

**Comment by chriskonnertz** [comment]
Hi,

glad you managed to fix it! :)
