### ISSUE TITLE
public/cups/matches/confirm-left/

### ISSUE THREAD

**Issue by stanginator** [Contentify/Contentify#627]
hello i have a one problem whit confirm score  matches
,
`ErrorException (E_NOTICE)
Undefined variable: left`

`     * @param int $rightScore The score of the participant on the right side
     * @return Match|null Returns the next match or null if there is no next match
     * @throws MsgException
     */
    public function confirm(int $leftScore, int $rightScore)
    {
        if ($leftScore == $rightScore) {
            throw new MsgException(trans('app.not_possible'));
        }
 
        if ($left) {
            if (! $left->canConfirmLeft(user())) {
                throw new MsgException(trans('app.not_possible'));
            }
 
            // If the result has been changed by the left participant, the right has to confirm it again
            if ($match->left_score != $leftScore or $match->right_score != $rightScore) {
                $match->right_confirmed = false;
            }
 
            $match->left_confirmed = true; 
        } else {
            if (! $match->canConfirmRight(user())) {
                throw new MsgException(trans('app.not_possible'));
            }`

**Comment by stanginator** [comment]
please help me :(

**Comment by chriskonnertz** [comment]
Hello,

big refactoring mistakes happened there - should be fixed now in the last two commits! https://github.com/Contentify/Contentify/commits/3.0
