### ISSUE TITLE
Server Modul modified Version

### ISSUE THREAD

**Issue by eodclan** [Contentify/Contentify#63]
This server module has been modified by the Clan Elite of Darkness.
For questions, please contact the following email address: info@elite-of-darkness.de

Setup instructions

1. Create a backup of your existing WebSite.
2. Create a backup of your existing database of their website.
3. Now delete from your database table "servers".
4. Import now servers.sql file in its database.
5. Now copy the folder "app" to your webspace.

Now you can specify in each game server, the server version.

Download: https://elite-of-darkness.de/developing/Servers_Modul_modded.zip

Best regards

Elite of Darkness

**Comment by chriskonnertz** [comment]
Very cool! Thanks for sharing!

**Comment by chriskonnertz** [comment]
I'm cleaning up the issue so I close this now. However, nice job!
