### ISSUE TITLE
Starting off - Lacking files?

### ISSUE THREAD

**Issue by CptDreadbeard** [Contentify/Contentify#633]
Hello! 
Please bear with me here... I did go through a Laravel course to get an idea how this CMS works, but i feel like i am missing something. I just can't find the view responsible for the demo file. Neither the web.php, nor the views folder give me a hint as to where to start off. The Guide here on Github states that there is a "frontend" views folder, which is missing for me when cloning the repo.. My Contentify version is the newest pull. I am on Windows using XAMPP. 

> The resources/views folder contains all the "global" template files. They are either plain PHP files (*.php) or Blade templates (*.blade.php). The most important subdirectory is called frontendand it contains those templates that belong to the frontend. There you will find a file named layout_main.blade.php. This is, you guessed it, the main layout of the website.

Please open my eyes for me, so i can finally start my task >.>

Cheers
Captain

**Comment by chriskonnertz** [comment]
**Hello**

>  I just can't find the view responsible for the demo file. 

I guess you are talking about this file?
https://github.com/Contentify/Contentify/blob/3.0/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php ( `app/Modules/MorpheusTheme/Resources/Views/layout.blade.php`) 

> Neither the web.php

https://github.com/Contentify/Contentify/blob/3.0/routes/web.php (`routes/web.php`)

> the views folder 

https://github.com/Contentify/Contentify/tree/3.0/resources/views (`resources/views`)

>  The Guide here on Github states that there is a "frontend" views folder

Oh... where have you seen that? Here, right? https://github.com/Contentify/Contentify/wiki/Website-Development
Yeah I guess that's a  bit outdated.

**Comment by CptDreadbeard** [comment]
Hey, 
thanks for the fast reply! I didn't see the Morpheus Theme folder! Now after reapplying the theme in the admin Dashboard, everything is working as intended :)
