### ISSUE TITLE
An error occurs when adding an avatar to a profile or any image

### ISSUE THREAD

**Issue by chywUa** [Contentify/Contentify#639]
I just installed the latest version downloaded from the site
ERROR
Sorry, something bad happened. Our website has crashed.
Don't worry, we will handle this. In the meantime, make a cup of coffee. And stop crushing our website!
Log:
production.ERROR: Undefined class constant 'ALLOWED_IMG_EXTENSIONS' {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined class constant 'ALLOWED_IMG_EXTENSIONS' at esport.miditaur.net/contentify/Models/User.php:442)

**Comment by hardhout** [comment]
Same issue here. Anybody any clues?

**Comment by chriskonnertz** [comment]
Hello,

the const was referencing the wrong class.

Fixed in https://github.com/Contentify/Contentify/commit/c7c18e1724be43e5ac67f82c0fbefd796cde3695

Thanks!
