### ISSUE TITLE
API Module?

### ISSUE THREAD

**Issue by AdamJessop** [Contentify/Contentify#64]
Hi, 

I really like the look and feel of contentify admin interface, you have done a great job here. As a web developer myself however (Used to be predominantly PHP but now NodeJs / AngularJS) I think it would be awesome if there could be an API module that would expose the modules and their data through a simple JSON REST interface. This would then help people easily build their own UI implementations using whichever technology they see fit. 

Are there currently any plans for this? 

Adam.

**Comment by AdamJessop** [comment]
I was actually thinking of returning the data that has been handled by the controller's and is sent to the view (in most cases) I haven't looked at laravel in any great detail so I'm not sure just how granular it is in terms of specific view data that could be extracted. 
I have done something similar with other CMS systems in the past but maybe I should take a look into what is there a little more myself ;)
It's primarily just specific module data could be requested and have it hydrated as needed to drive a custom UI. 
On 9 Jun 2016 7:28 p.m., Chris Konnertz <notifications@github.com> wrote:Hi Adam,

thank you for the motivating feedback!

Well the question is, what exactly do you expect from such a (hypothetical) API?

I assume it's not a big challenge to create an API that exposes models as JSON objects to the outsider. But I am not sure if this is enough. You would not have any access to the methods of the (PHP) models and the controllers. So you would have to rewrite a lot of the PHP code in Node.js.

Regards,
Chris

**Comment by chriskonnertz** [comment]
Unfortunately I believe that a API that covers "everything" is not a realistic option at this time. I do not have enough time to start such a project.
