### ISSUE TITLE
Nightmare to install v3.0

### ISSUE THREAD

**Issue by LeventeNagy** [Contentify/Contentify#642]
So I gave it a try, trying composer install get the following error

>  [Composer\Json\JsonValidationException]
>   "./composer.json" does not match the expected JSON schema:
>    - name : Does not match the regex pattern ^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$ 

composer.json, changed name from _"name": "Contentify/Contentify",_ to _"name": "contentify/contentify",_

Before anything else would go wrong, running composer update, getting another error

> Problem 1
>     - phpunit/phpunit[6.0.0, ..., 6.5.14] require php ^7.0 -> your php version (8.0.8) does not satisfy that requirement.
>     - Root composer.json requires phpunit/phpunit ~6.0 -> satisfiable by phpunit/phpunit[6.0.0, ..., 6.5.14].

okay, running _composer update --ignore-platform-reqs_

Get lot of errors, but the main one is this **Carbon 1 is deprecated, see how to migrate to Carbon 2.** don't know how or why

So I ran: **./vendor/bin/upgrade-carbon**

Got 3 more errors

I gave up

**Comment by chriskonnertz** [comment]
Hello @LeventeNagy ,

thanks for your feedback. I'm trying to update Laravel from 5.5 (LTS) to 6 (LTS) which supports PHP 8 ( https://github.com/laravel/laravel/blob/6.x/composer.json#L11 )

I have rushed to 5.8 so far, and will try to get to 6 quickly.

https://github.com/Contentify/Contentify/tree/3.1

**Comment by LeventeNagy** [comment]
Thanks, I will fork Contentify and see what I can do to give a hand

> Hello @LeventeNagy ,
> 
> thanks for your feedback. I'm trying to update Laravel from 5.5 (LTS) to 6 (LTS) which supports PHP 8 ( https://github.com/laravel/laravel/blob/6.x/composer.json#L11 )
> 
> I have rushed to 5.8 so far, and will try to get to 6 quickly.
> 
> https://github.com/Contentify/Contentify/tree/3.1

**Comment by chriskonnertz** [comment]
@LeventeNagy Great! I have just uploaded the changes that are necessary to upgrade to Laravel 6 according to their docs.

**_This is untested though and probably has errors_**, because the dependencies are not yet updated.

**Comment by chriskonnertz** [comment]
Fixed dependencies. You still will have to use the option to ignore platform requirements when doing `composer install`, however, the dependencies *should* work with PHP 8.

**Comment by LeventeNagy** [comment]
thank you

**Comment by chriskonnertz** [comment]
No problem, I have made more changes and it runs now on PHP 8.x.

I have tagged it as 3.1-beta: https://github.com/Contentify/Contentify/releases/tag/v3.1-beta

I have not done many tests, just checked if the frontend and backend works (so login works as well) and wrote a news (so RSS works).

**Comment by chriskonnertz** [comment]
Tested more, fixed some stuff, but also found out it was running on PHP 8 only in the console but with 7.4 in the web, so I am not sure how well it runs with PHP 8.

**Comment by LeventeNagy** [comment]
I haven't tested it yet, I will give it a spin tonight
