### ISSUE TITLE
Installation error: File(/storage/app/.installed

### ISSUE THREAD

**Issue by hardhout** [Contentify/Contentify#643]
While installing v3.0 on Centos 8 with DirectAdmin I am receiving the following error. 

`file_exists(): open_basedir restriction in effect. File(/storage/app/.installed) is not within the allowed path(s)`

When I create an empty file `/storage/app/.installed` I am receiving a http500 error without any desprition.

I am following [this guide.](https://github.com/Contentify/Contentify/wiki/Installation). All items check out green before proceeding with installation. Only thing different is I have created a symlink from `/public` to `/public_html`. All file from /public were copied to /public_html.

**Comment by hardhout** [comment]
I got past this problem but I am not sure how.

I think I got past this problem by changing the to `https://domain.extension`. I have forced SSL for the domain in DirectAdmin

**Comment by chriskonnertz** [comment]
Hello,

glad to hear you managed to fix it!

> I think I got past this problem by changing the to https://domain.extension. I have forced SSL for the domain in DirectAdmin

Perhaps, I don't know... it's a weird server problem from my point of view.
