### ISSUE TITLE
install.php Launch Installer button sends to a 404 Not Found Page

### ISSUE THREAD

**Issue by azazel-xes** [Contentify/Contentify#644]
Hi,

I have setup the requirements to install Contentify 3.1 in Apache2 web server as shown in the image below

![contentify_install_page](https://user-images.githubusercontent.com/14966309/139779898-c1f560b1-e9de-4a76-8d24-ee208a49b1dd.png)

I have setup an Apache Virtual Host for my Contentify installation as shown in the image below
![Contentify_Virtual_Host](https://user-images.githubusercontent.com/14966309/139780237-d4312fd6-8e99-4b37-aecd-9bcef9ab4264.png)

I have also setup the .htaccess file in /var/html/contentify/public as shown in the image below
![Contentify_htaccess](https://user-images.githubusercontent.com/14966309/139780482-70ebb127-dd81-4781-91f2-899d5089d076.png)

But every time I click on the launch installer button I get redirected to the following webpage 

![Contentify_PageNotFound](https://user-images.githubusercontent.com/14966309/139780760-f4348273-be51-47b0-8b5e-ca27e00a6b84.png)

Is there something else I need to configure in my Contentify?

**Comment by chriskonnertz** [comment]
Hey, 
did you use 3.1 beta? Please use this version, older version are outdated.

**Comment by azazel-xes** [comment]
Hi Chris,

Thanks for replying, yeah I did use the 3.1 beta from this link 

https://github.com/Contentify/Contentify/releases
![Contentify_3 1_beta](https://user-images.githubusercontent.com/14966309/139934915-595b8d4d-d256-4900-a4a5-6c4d125a0a8b.png)

**Comment by azazel-xes** [comment]
I have solve my issue.

1-. Instead of using the /www/var directory use /home/user/yourAppName
2. Create a virtual host file with the following
`<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName contentify.com
    ServerAlias www.contentify.com
    DocumentRoot /home/user/Web/contentify/public
    <Directory /home/user/Web/contentify/public/>
       Options Indexes FollowSymLinks MultiViews
       AllowOverride All
       Order allow,deny
       Allow from all
       Require all granted
     </Directory>
    LogLevel debug
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
`
I got that config file from [Steps to configure Laravel with Virtual Host Apache 2](https://phpraxis.wordpress.com/2016/08/02/steps-for-configuring-laravel-on-apache-http-server/)

3. After this changes I followed the installation instructions and it did work this time
