### ISSUE TITLE
Bug when installing contentify v2

### ISSUE THREAD

**Issue by krysennn** [Contentify/Contentify#65]
Hi,

I think you have make mistake on commit: #38efe88143
Because file: layout.blade.php is deleted so when you install contentify v2 it's return: View [layout] not found.

https://github.com/Contentify/Contentify/commit/9de5717a92729e9e3b2afa21b2b1f6b40a86b085

**Comment by chriskonnertz** [comment]
Hi,

I think it is not a "real" bug. I commited some parts of the stuff I am working on these days, but not the whole changes. So I assume some important parts are still missing and this causes the error.

I will commit the missing part as soon as possible but I need a few more days.
