### ISSUE TITLE
reCAPTCHA v3 help

### ISSUE THREAD

**Issue by mazzorini** [Contentify/Contentify#653]
Hi,

I think the instructions in the wiki no longer match the code. Does anyone here have an example with 3.1?

Currently I get registrations, but the registration is deactivated. I don't think i can be productive without recaptcha.

**Comment by chriskonnertz** [comment]
Hello,

> I think the instructions in the wiki no longer match the code

The Contentify code or the Google code?

**Comment by mazzorini** [comment]
The Contentify code is different ;)

Captcha::check(Request::get('captcha'))

**Comment by mazzorini** [comment]
My bad, I could have found out myself


in app/Modules/Auth/Http/RegistrationController.php
` if (! Captcha::checkReCaptcha(Request::get('g-recaptcha-response'))) {
                return Redirect::to('auth/registration/create')
                    ->withInput()->withErrors(['message' => trans('app.captcha_invalid')]);
  }`
