### ISSUE TITLE
Error: Could not retrieve the theme name from the config!

### ISSUE THREAD

**Issue by d0nda** [Contentify/Contentify#656]
Hi I need help with this error , the script is installed on my website but I get this error every link I click on the live website 
![Screenshot_20220727-173858_Brave.jpg](https://user-images.githubusercontent.com/79589014/181291950-e34db000-ae18-44a0-8cf5-7b5580f4cca8.jpg)

**Comment by Matlord93** [comment]
I've managed to find a (temporary) fix by manually pointing to the theme.
You'll have to adjust the following line of code;
$theme = Config::get('app.theme');

And point to the theme manually;
$theme = Config::get('app.theme', 'MorpheusTheme');

Seems to work fine.
If anyone has a better solution I'd love to hear it though, but for now I'll close this issue.

https://github.com/Contentify/Contentify/issues/593

**Comment by mazzorini** [comment]
which version do you use?
I dont have this problem with 3.1 and php 7.4
