### ISSUE TITLE
Contentify Dead?

### ISSUE THREAD

**Issue by mazzorini** [Contentify/Contentify#657]
Hey,

is contentify dead?
If not, show your websites ;)

**Comment by exelv1** [comment]
seriously

**Comment by mazzorini** [comment]
dead

**Comment by chriskonnertz** [comment]
Hi,

no, it is not  dead. Maybe **undead** ;)

**Comment by exelv1** [comment]
[mail@chriskonnertz.de](mailto:mail@chriskonnertz.de)

**Comment by exelv1** [comment]
please help me with this

**Comment by Stormez1998** [comment]
@exelv1 Do you need help? Feel free to add me on Discord, maybe i can take a look :) Stormez#7904
