### ISSUE TITLE
Widgets Forum and Shoutbox

### ISSUE THREAD

**Issue by The-ZZ-Top** [Contentify/Contentify#66]
Hi, how can i set the Forum widget with the latest threads?
I have a question about the shoutbox which is not ready yet?
I use the demo version.

**Comment by chriskonnertz** [comment]
Hi

> how can i set the Forum widget with the latest threads?

Open the main template: `resource/views/frontend/layout_main.blade.php`. Then add the widget with this code: `@widget('Forums::LatestThreads`

> I have a question about the shoutbox which is not ready yet?

It is, even in the demo website. However it is very basic. For example it does not have much styling.
What is your question?

> I use the demo version.

The demo website uses version 1.0, the latest version is 1.2. But in the case of the shoutbox module it should not make a difference.

**Comment by The-ZZ-Top** [comment]
Hi Chris,
ich schreib mal auf Deutsch, erst einmal Danke für das geniale Script, erfüllt alles was mein Herz begerht. Das Forum-Widget hab ich hinbekommen, die Shoutbox geht bei mir nicht habe aber mittlerweile eine andere eingebaut. 

Habe diese hier verbaut: http://tutorialzine.com/2015/01/shoutbox-php-jquery/

Das ganze schaut dann so aus: http://ready2web.de/public/

Nochmal besten Dank.
Gruß, Frank

**Comment by chriskonnertz** [comment]
Hall oFrank,

ja deutsch ist ok. Schön, dass dir das CMS gefällt!

Werde die Shoutbox bei Gelegenheit mal auf Funktionstüchtigkeit untersuchen. 

Übrigens ja das Galerie-Widget zeigt standardmäßig zu viele (5) Bilder an, das habe ichj zufällig vor kurzem geändert, ist aber noch nicht veröffentlicht. Sollte aber nicht schwer nachzutragen sein, man kann ja den limit-Parameter setzen und dann muss man eben die Breite der li auf 33% oder so setzen.

Gruß
