### ISSUE TITLE
Bug with PHP7

### ISSUE THREAD

**Issue by krysennn** [Contentify/Contentify#68]
Hi,

This morning i updated my PHP version from 5.6.16 to 7.0.9 and i test with 7.0.10-1~dotdeb+8.1. 
And i get some errors with PHP 7 and not with 5.6.16.

**_Error:_**
Request: http://localhost/awards
```
ErrorException in AwardsController.php line 30:
Trying to get property of non-object
Line 30 it's: $award->game->icon
```
**_Error2:_**
Variable: $cup->game->uploadPath()
```
Call to a member function uploadPath() on null
```

Debug PHP5.6
`
dd($cup->game)
There are OK.
`

Debug PHP7
`
dd($cup->game)
Return null
`

I use Contentify with branch 2.0-dev.
`php artisan --version
Laravel Framework version 5.2.45`

No problem with local environnement:
`php -v
PHP 5.6.16 (cli) (built: Nov 25 2015 18:51:26)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies`

**Comment by chriskonnertz** [comment]
I will investigate these errors but I do not have an appropriate PHP 7 environment yet.

**Comment by krysennn** [comment]
It's not urgent, i just test with php7 but I haven't time to search so i switch to php5.6, i will search maybe later

**Comment by chriskonnertz** [comment]
I've created a PHP 7 stack so I will be able to take a look at these problems.

**Comment by krysennn** [comment]
Oh thank you ;)
I dont test php7 with your last commit it's maybe fix i dont know

**Comment by chriskonnertz** [comment]
I also get the award error.

**Comment by chriskonnertz** [comment]
I updated code of the `BaseModel`.  This code is not from me but from [Ardent](https://github.com/laravel-ardent/ardent/blob/master/src/Ardent/Ardent.php).  After I applied the changes everything worked well again. (If it does not work for you, you might have to do a composer update via `php composer.phar update`)

Commi: https://github.com/Contentify/Contentify/commit/b91abad7ac09bc3887bf913f35c88be99ee10a45

**Comment by krysennn** [comment]
Oh! I will test it ASAP, thank you very much

**Comment by krysennn** [comment]
Very good perfect 👍 
Thanks!
