### ISSUE TITLE
Error after pressing Launch Installer.

### ISSUE THREAD

**Issue by lolbob181** [Contentify/Contentify#74]
Okay this is my first installing Contentifying i've followed the wifi install guides but if you go to metricmc.tk/install.php and press launch installer it says 
Not Found

The requested URL /install was not found on this server.

How do i fix this?

**Comment by chriskonnertz** [comment]
Hi,

your server has to support URL rewirting. `/install` looks like a path of a folder but it is not, it is a route that is handled internally by the framework/CMS. But this is only possible if the server supports URL rewriting. For Apache there is a module called mod_rewrite that supports this feature. It has to be activated on your server. I guess you webspace is free of cost? Then maybe your hoster does not support this featur... well you have to ask the support of your hoster or read the documentation (FAQs for example).

**Comment by lolbob181** [comment]
its a home server running Ubuntu 14.04

**Comment by chriskonnertz** [comment]
Awesome! Because this means you can simply activate mod_rewrite.

https://wiki.ubuntuusers.de/Apache/mod_rewrite/

So most likely all you have to do is to install the module with this console command:
`sudo a2enmod rewrite 
`
