### ISSUE TITLE
How to edit contentify

### ISSUE THREAD

**Issue by lolbob181** [Contentify/Contentify#77]
How can I change the theme to be like the one on the demo site for contentify I've looked in all public folders can't see help plz

**Comment by chriskonnertz** [comment]
Hi

Did you download version 2.0 (alpha)? You can download it here: https://github.com/Contentify/Contentify/releases/download/v2.0-alpha/contentify2_alpha.zip

After installing it you can login (as admin), go to the admin dashboard, then to settings and there you can switch the theme.

**Comment by lolbob181** [comment]
Will do how to change name from contentify test page

**Comment by chriskonnertz** [comment]
Open this file with a text editor: `config/app.php`. Go to line 39 and there you can change the title of the website.

**Comment by lolbob181** [comment]
Thanks

**Comment by lolbob181** [comment]
Hey dude i did all that it worked perfectly soo i go to install it to my main domain and it installs perfectly when i go to the admin-backend and configuration and change theme to the morpheus theme it isn't like it was on the previous sub-domain i had it on it looks like this: http://prntscr.com/d1pvrq but i'd like it to be like the one on the demo site with the blue thanks!

**Comment by chriskonnertz** [comment]
Most likely this is a caching problem of your browser. I had the same problem. You may try to press F5 twice but probably it will not solve the problem. Maybe the easiest thing to do is to open the website with another browser (that does not have the stylesheet in its cache).

**Comment by lolbob181** [comment]
I'll try

**Comment by lolbob181** [comment]
Sorted that one question what is size of banner and favicon

**Comment by chriskonnertz** [comment]
Favicon: 64 x 64 pixels (`public/favicon.png`) and 180 x 180 pixels (`public/img/favicon_180.png`)
Banner:  180 x 180 pixels (`public/img/logo_180.png`)

**Comment by romcika5** [comment]
Ok so really strange. I try to edit contentify template, some css and some view files. First time then i edit everythins works fine, but second time if i edit something and it's not editing. Like that: i changed some css atributes, and they don't changed on website. Sorry for my bad english.

**Comment by lolbob181** [comment]
Also how do i make it soo when i do test.com it goes to public folder on my htaccess ?

**Comment by lolbob181** [comment]
forget my previous comment above ^^ the problem now is http://prntscr.com/d35p3s how do i get that youtube twitter and facebook to go to my socialmedia? i set it in the configuration on admin panel but my social media only works on the footer

**Comment by chriskonnertz** [comment]
> Ok so really strange. I try to edit contentify template, some css and some view files. First time then i edit everythins works fine, but second time if i edit something and it's not editing. Like that: i changed some css atributes, and they don't changed on website. Sorry for my bad english.

Are you sure that it is not something about caching?

By the way you should only edit the theme that is currently active.

**Comment by chriskonnertz** [comment]
> forget my previous comment above ^^ the problem now is http://prntscr.com/d35p3s how do i get that youtube twitter and facebook to go to my socialmedia? i set it in the configuration on admin panel but my social media only works on the footer

Yeah that was a bug. :+1: Fixed by:
https://github.com/Contentify/Contentify/commit/082acaeba8877e7664aab53d18be0731dcaeff53

**Comment by lolbob181** [comment]
How do I update

**Comment by lolbob181** [comment]
Also can u add like cache reloader and on my index page the news ain't showing

**Comment by chriskonnertz** [comment]
> How do I update

Well the easiest way is to apply the changes manually:

1. Open the template file `app/Modules/MorpheusTheme/Resources/Views/layout.blade.php`
2. Select line 67-69
3. Replace them with this code:

`<a href="https://www.facebook.com/{{ Config::get('app.facebook') }}" target="_blank">{!! HTML::fontIcon('facebook') !!}</a>
<a href="https://twitter.com/{{ Config::get('app.twitter') }}" target="_blank">{!! HTML::fontIcon('twitter') !!}</a>
<a href="https://www.youtube.com/channel/{{ Config::get('app.youtube') }}" target="_blank">{!! HTML::fontIcon('youtube') !!}</a>`

**Comment by chriskonnertz** [comment]
> Also can u add like cache reloader and on my index page the news ain't showing
Yeah I will try to find a solution but this will have to wait a little bit... We should keep this issue open as a reminder for me. :)

**Comment by romcika5** [comment]
Ok so i found a solution if i changed some files in view i need to run the artisan command: php artisan clear:view

**Comment by lolbob181** [comment]
Okay but can u make it quick?

**Comment by lolbob181** [comment]
Also my news section is not displaying on index page

**Comment by chriskonnertz** [comment]
> Ok so i found a solution if i changed some files in view i need to run the artisan command: php artisan clear:view

Or ` php artisan view:clear`? :stuck_out_tongue:

**Comment by chriskonnertz** [comment]
@lolbob181 

> Okay but can u make it quick?

Sorry but I don't think so.
However, here is a quick workaround:
Open the frontend stylesheet directly in your browser. `css/frontend.css` (example URL: `http://exampe.org/css/frontend.css`) Then double press the F5 key.

**Comment by lolbob181** [comment]
Okay will try also do u know why my news is not displaying on index page web is zealgg.com

**Comment by lolbob181** [comment]
K news module is fixed just a problem with users editing there profiles when they go to click save they get this : https://gyazo.com/823e7071279cbc779e9034d710e3377f & https://gyazo.com/8b27c717b8fffdfa11877f27559f5363

**Comment by chriskonnertz** [comment]
Hm. Maybe also a GD lib problem? Did you try this? https://github.com/Contentify/Contentify/wiki/Troubleshooting#captcha-image-not-displayed

**Comment by lolbob181** [comment]
http://prntscr.com/d4m2k5 i have it

**Comment by lolbob181** [comment]
i didn't close it :(

**Comment by chriskonnertz** [comment]
Well GitHub says you did :stuck_out_tongue: 

>  lolbob181 closed this a day ago

Well no problem we will conitnue in the other issue of yours.

https://github.com/Contentify/Contentify/issues/82
