### ISSUE TITLE
Fatal Error Exception in Migrator.php

### ISSUE THREAD

**Issue by irbisgaming** [Contentify/Contentify#78]
Hello, first of all i want to thank you for the project.

I have a problem while creating the database. The problem is this one: 

FatalErrorException in Migrator.php line 335:
Class 'MigrationCartalystSentinel' not found

what do i have to do to solve it? 

I have read that  `Installation: Error message "FatalErrorException in Migrator.php" Something is wrong with your migration table. Usually the name of this table is migrations . Truncate or delete it manually, then repeat the installation`.
But i dont really know what i have to do.

I appreciate the help.

PD: Sorry for my english level

**Comment by chriskonnertz** [comment]
Hi

Well:

> Truncate or delete it (the database table "migrations") manually, then repeat the installation.

Did you try this solution?

**Comment by krysennn** [comment]
Hello,

I test to install Contentify and i have no reproduce same error ...

How did you install Contentify ?

**Comment by chriskonnertz** [comment]
Closed. If this issue still exists, please leave a comment here or create a new issue.
