### ISSUE TITLE
blank page 

### ISSUE THREAD

**Issue by exelv1** [Contentify/Contentify#8]
blank page when i run the instaler script

**Comment by chriskonnertz** [comment]
Hello,

did you use this download?

http://contentify.org/share/releases/contentify_beta1.zip

**Comment by exelv1** [comment]
i did everything you said on a lamp stack just i run the cms and it will just give me a blank instal page if you could shoot me a email im runing or hopeing to run a million dollor league around this cms mrhdr405@gmail.com thx

**Comment by exelv1** [comment]
did you get my emails ? i can setup this i assume so on azure?

**Comment by chriskonnertz** [comment]
Hello,

yes I did get you Emails. I cannot answer them right now. I'll answer later.

**Comment by chriskonnertz** [comment]
PS: Yes, for all I know you can install Laravel (the framework) on Azure and therefore you can install the CMS on Azure as well.
