### ISSUE TITLE
Contentify only load's at "http://www.example.com/public"

### ISSUE THREAD

**Issue by sCARFACETM** [Contentify/Contentify#80]
Hello,
i hope you can help me. So i installed Contentify as the installation guide describes. Everything is fine, but i have a little problem. Contentify respectively my Page only load's when i enter my URL and /public after it. 

So in my case when i enter "http://www.german-enforcers.de" nothing shows up (except some Informations from the Provider). But when i enter "http://www.german-enforcers.de/public" everything is fine. How can I change this or is this even possible? thank's in advance 

greeting sCARFACETM

BTW: sorry for my bad english ;)

**Comment by sCARFACETM** [comment]
Habe gerade gesehen das du auch aus Deutschland kommst, das würde natürlich alles vereinfachen bzg. der Fehlerbeschreibung.

**Comment by chriskonnertz** [comment]
Hi,

ja das macht es einfacher. :)

Das CMS verwendet ein Framework (Laravel) und das gibt den öffentlichen Ordner `public` vor. Die IDee ist, nur dieser Ordner soll öffentlich, also von außerhalb des Web-Servers, zugänglich sein. Logischer Weise sind dann alle anderen Ordner von Zugriffen von außen geschützt. Das ist wichtig, denn sonst hat man Zugriff z. B. auf die Datenbank-Zugangsdaten! Du solltest daher das Passwort deiner Datenbank (später) noch mal ändern da es theoretisch schon jemand ausgelesen haben könnte.

Theoretisc gibt es verschiedene Möglichkeiten das Problem zu lösen aber der vorgesehene Weg ist der: Den Server so konfigurieren, dass er automatisch beim `public` Ordner startet. Wie das bei deinem Server bzw. Hoster geht kann ich dir leider nicht sagen da das individuell ist. Die langsamste aber wahrscheinlich einfachste Methode wäre: Frag beim Support von Strato an und bitte die dir zu erklären (oder das gleich selber zu erledigen) wie man das web root (document root) auf den `public` Ordner setzen kann. Ich kann dir natürlich auch Links zu allgemeinen Tutorials geben aber ich schätze die nützen dir wenig weil die sich auf frei konfigurierbare Server beziehen während du vermutlich managed webspace verwendest.

**Comment by sCARFACETM** [comment]
Hi,

danke, das mit dem Passwort der Datenbank werde ich direkt mal machen. 

Habe jetzt auch mit dem Strato-Support gesprochen, die können da aber leider nichts machen. Habe aber eine Funktion die es mir erlaubt Intern weiterzuleiten. Das werde ich dann erstmal so machen. 

Hab da noch eine kleine Frage die nichts mit dem aktuellen Problem zu tun hat. Und zwar hat mann bei Contentify ja oben die Topbar mit Home, Teams, Matches etc. Ich habe es bei mir so eingestellt das der Ausgewählte Punkt in einer anderen Farbe erscheint. Allerdings ist dies bei mir versetzt sprich wenn ich in meinem Fall auf Matches klicke, leuchtet Teams auf. Und das ist bei allen Punkten so. Wie kann ich das abändern?

Danke schonmal für deine Mühen ;)

**Comment by lolbob181** [comment]
There's a way to fix this in ur main root of ur website make a file and call it htaccess and inside it put


RewriteEngine on
RewriteBase /
RewriteCond %{HTTP_HOST} domain.com [NC]
RewriteRule ^(.*)$ http://www.domain.com/public/index.php [R=301,NC]

Replace domain.com with ur domain

**Comment by chriskonnertz** [comment]
> Ich habe es bei mir so eingestellt das der Ausgewählte Punkt in einer anderen Farbe erscheint. Allerdings ist dies bei mir versetzt sprich wenn ich in meinem Fall auf Matches klicke, leuchtet Teams auf. Und das ist bei allen Punkten so. Wie kann ich das abändern?

Könnte ein Bug vom Theme sein, werde ich mir anschauen.

**Comment by sCARFACETM** [comment]
@lolbob181 That doesnt work for me, did it exactly as you described :(

@chriskonnertz Alles klar dann weiß ich bescheid, danke dir.

**Comment by Moupad** [comment]
Ich bin bei All-Inkl und da gibt es die Möglichkeit die Domain so zu Routen das sie, beim Aufruf der Domain, gleich auf diesen Public Ordner zugreift. Müsste es auch bei Strato geben. Schau mal in deiner Domainverwaltung ob du da einen Punkt hast der dir erlaubt Verzeichnisse zu wählen.
![screenshot_1](https://cloud.githubusercontent.com/assets/17875305/20062097/b8a296c4-a502-11e6-98d8-abb3fdaf5920.png)

**Comment by sCARFACETM** [comment]
@Moupad bei Strato heißt das "Interne-Weiterleitung" hab ich ja oben geschrieben das ich es so machen werden. Danke trotzdem für deine Hilfe ;)

**Comment by krysennn** [comment]
Do you need some help or it's ok ??

**Comment by chriskonnertz** [comment]
I close this issue because there was no reaction for about one month. 

If there are still unanswered question please create a new issue.
