### ISSUE TITLE
How to disable login until activation

### ISSUE THREAD

**Issue by romcika5** [Contentify/Contentify#81]
Hi. I'm editing contentify v2. I'm trying to do user self activation via email. Everythings works fine, but user can still login. 

`public function postLogin()
    {
        $credentials = [
'confirmed' => 0,
            'email'     => Input::get('email'),
            'password'  => Input::get('password')
        ];
        $user = Sentinel::authenticate($credentials, false); // Login the user (if possible)

        if ($user and $user->banned) {
            Sentinel::logout();
            $user = null;
        }
        if ($user) {
            return $this->afterLoginActions();
        } else {
            $this->alertFlash(trans('app.access_denied'));
            return Redirect::to('auth/login');
        }
    }

Tried like that but still not working:

`if ($user->confirmed==1) { return $this->afterLoginActions();``

**Comment by chriskonnertz** [comment]
Hi,

did you try this?

https://github.com/Contentify/Contentify/wiki/FAQ#how-can-i-fight-spambots

**Comment by romcika5** [comment]
Hi. Thanks for reply. Yes, but i want todo to user can self activate with email :)

**Comment by romcika5** [comment]
In contentify v1.2 everythings works perfect, but on contentify 2 not really

**Comment by romcika5** [comment]
Ok i found solution, u can close it! Thanks!

**Comment by chriskonnertz** [comment]
OK.
