### ISSUE TITLE
Cup module: Missing translations

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#85]
In the cup template translations are missing:
https://github.com/Contentify/Contentify/blob/2.0-dev/app/Modules/Cups/Resources/Views/show.blade.php

TODO: Also check if other cup templates need additional translations.

**Comment by chriskonnertz** [comment]
Done: https://github.com/Contentify/Contentify/commit/2054bef541bcf2b4d883278714402c8de9d9564c

**Comment by chriskonnertz** [comment]
@krysennn I#d be very happy if your translate the French parts. :)

**Comment by krysennn** [comment]
Hi :)
No problem, tomorrow it will be done ;)
Thanks for you New translation :)
