### ISSUE TITLE
Contentify already has been installed.

### ISSUE THREAD

**Issue by jakejackyll** [Contentify/Contentify#86]
Hey guys!

I'm trying to install Contentify 1.2.0, but when i run the install.php it tells me: 

"Contentify already has been installed."

Within "storage/app" is a 0 byte file called ".install" (Permissions: 640).

Thanks in advance, stay frosty

jake

**Comment by chriskonnertz** [comment]
Hi,

please rename the file to soemthing else, for example `.install_backup`.

**Comment by jakejackyll** [comment]
Holy sh*t, thats what i call a fast response, thx ;-)
 
Status: Renaming '/html/contentify_1_2_0/storage/app/.install' to '/html/contentify_1_2_0/storage/app/.install_backup'

http://www.crea-esports.at/install.php, still prompts: "Contentify already has been installed."

**Comment by chriskonnertz** [comment]
> Holy sh*t, thats what i call a fast response, thx ;-)

Haha :D Well to be honest that was just luck. I try to respod fast but you know I have to sleep, work, drive car and so on. ;)

**Comment by chriskonnertz** [comment]
Hm this is weird because here is what the script does:

```
if (! file_exists(__DIR__.'/../storage/app/.install')) {
        die('Contentify already has been installed.');  
    }
```

So only if the file exists it says ('Contentify already has been installed.'. Please take another look, does the .install file exist or not? If it exist please delete it.

**Comment by jakejackyll** [comment]
Okey thats strange,... the whole Contentify directory does not contain a file called ".install"

![screenshot from 2016-11-11 22-05-14](https://cloud.githubusercontent.com/assets/23406113/20230237/1f8876b4-a85b-11e6-9fe4-ee0b755e172e.png)

**Comment by chriskonnertz** [comment]
Well I am not quite sure about permissions. The `storage/app`directoryhas 640 but it should have 777.

**Comment by jakejackyll** [comment]
Yep, my bad. Your installation wiki states:

> Set CHMOD 777 to these **directories** and their **sub directories**

No files mentioned. Thinking i'm smart - while actually not, i choose the following option applying the permissions:

![screenshot from 2016-11-12 00-16-59](https://cloud.githubusercontent.com/assets/23406113/20235614/dfe27cb2-a896-11e6-91dd-715b17ad54ab.png)

I also had to deactivate PHP Open Basedir.

By now it's up and running, thank you. Greets

jake

**Comment by chriskonnertz** [comment]
> Your installation wiki states:
> > Set CHMOD 777 to these directories and their sub directories

You are right, the wiki was not precise about this step. I've updated the wiki. Thanks for the feedback.

> I also had to deactivate PHP Open Basedir.

I wonder why you had to  do this?
