### ISSUE TITLE
Error: Could not determine the theme name from the config!

### ISSUE THREAD

**Issue by romcika5** [Contentify/Contentify#89]
I installed new contentify and now i'm gettint that error:

Error: Could not determine the theme name from the config!

**Comment by chriskonnertz** [comment]
Hm okay... I just added this error message and I assumed no one will ever see it... ;) Okay I will investigate tomorrow.

**Comment by romcika5** [comment]
Thanks!

**Comment by romcika5** [comment]
Verry waiting to fix

**Comment by krysennn** [comment]
I make new install of Contentify and you are right, 
Open: FrontController in Contentify\contentify\Controllers and edit line 25 "true" to "false"

It's fix soon: https://github.com/Contentify/Contentify/pull/90

**Comment by romcika5** [comment]
Thanks @krysennn !

**Comment by krysennn** [comment]
No problem ;)

**Comment by chriskonnertz** [comment]
Fixed! By https://github.com/Contentify/Contentify/pull/90 *and* by https://github.com/Contentify/Contentify/commit/abae65efc370e601783b899de3d93323bb7f0e7f ;)

**Comment by romcika5** [comment]
Ok one more thing. I installed contentify in my server. My server using SSL, then i try to login i cannot and i'm not getting any errors. How can i fix that?

**Comment by romcika5** [comment]
I changed in contentify mysql config to app.https 1 but nothing happend

**Comment by chriskonnertz** [comment]
Strange. The login form uses https: http://fs5.directupload.net/images/161115/dhybmpzl.jpg
So I wonder, what problem does Chrome have with the protocol?

**Comment by romcika5** [comment]
Ok so i unistalled SSL on my server, then logged in into contentify ant changed config HTTPS again and working fine!
