### ISSUE TITLE
Installer: The password problem

### ISSUE THREAD

**Issue by chriskonnertz** [Contentify/Contentify#99]
Problem:
- Installer should use the password from the `database.ini`
- Current implementation makes it possible to view the password by users that are not authorized

First Solution:
- Users cannot run the installer twice

New Problem:
- Users cannot run the installer twice
;)

=> When in develoment or testing or just playing around it can be very useful to re-install the CMS.

Solution:
- Add checkbox "Take password from config" to the installer?

Related to: https://github.com/Contentify/Contentify/pull/96

**Comment by ImTheLe** [comment]
Well what about this solution:
when the admin wants to reinstall the CMS he just removes the .installed file and starts the installation again

**Comment by chriskonnertz** [comment]
Yeah you are right. Why make things more complicated than necessay?

Earlier when the CMS was in pre-alpha state I reinstalled it a lot so I wanted to make it easy to reinstall it. But I guess reinstalling is not a common case so it is not worth the affort.
